### ISSUE TITLE
Maxes all available CPUs

### ISSUE THREAD

**Issue by dgrumieaux** [JohnstonCode/svn-scm#10]
Running on a vanilla VSCode on macOS Sierra 10.12.6. Looks like a large number of svn status processes are running in parallel.

**Comment by JohnstonCode** [comment]
What version of VS code are you running?

**Comment by dgrumieaux** [comment]
1.16.1 - going to update and retest

**Comment by JohnstonCode** [comment]
Okay, Let me know if you have the same issue

**Comment by dgrumieaux** [comment]
Looks good so far! Thanks. I guess reopen if there's a way to configure a minimum version, but otherwise I'm going to just close. Thanks

**Comment by dgrumieaux** [comment]
Oops, spoke too soon.

This popped up a few minutes after I closed the issue
![screen shot 2017-10-31 at 10 59 43 am](https://user-images.githubusercontent.com/547941/32234600-48182be2-be2b-11e7-93c7-4b7b2aecc598.png)

**Comment by JohnstonCode** [comment]
@dgrumieaux sorry that this is happening.

I will have a look into this. See if I can replicate it.

**Comment by dgrumieaux** [comment]
No problem. Thanks for any help. Let me know if I can test anything else

**Comment by JohnstonCode** [comment]
Hi @dgrumieaux 

I have added a throttle to the update async call. Give it a try and see if you have the same issue.

The latest version is 0.8.2

**Comment by dgrumieaux** [comment]
So far so good after running for 10 minutes. Closing until I see this again. Thanks for the quick turnaround

**Comment by JohnstonCode** [comment]
No problem
