### ISSUE TITLE
Deleted or moved files shown as missing, cannot commit refactor

### ISSUE THREAD

**Issue by Faust90** [JohnstonCode/svn-scm#100]
- VSCode Version : 1.19.2
- OS Version: Ubuntu 17.10
- Extension Version:1.5.0
- System Language: English

Steps to Reproduce:

1. Remove file from filesystem
2. Look at change list

**Comment by JohnstonCode** [comment]
Hi @Faust90 

Thanks for raising this. I have had the same issue today. Seems svn needs to be told that the files have been deleted. 

I could add a right click option to files in the source control view to "Delete Selected" and also a command to delete all missing.

**Comment by JohnstonCode** [comment]
In the meantime you could run "svn status | grep '^!' | awk '{print $2}' | xargs svn delete"
