### ISSUE TITLE
Missing dependency error on remote vscode

### ISSUE THREAD

**Issue by pn1k** [JohnstonCode/svn-scm#1024]
- VSCode Version: 1.47.3
- OS Version: OSX 10.12 remote Ubuntu 14.04
- Extension Version: 2.11.6
- System Language: english
- SVN Version: 1.8.8

## Issue ##
After update extension stop working: vscode show error about missing dependency. If I install on remove older version(2.11.5) - it works. I noticed that new version of extension does not contain "bin" and "node_modules" folders.    

## Steps to Reproduce ##

1. install on remote, restart vscode
2. get error : Missing dependency, go to ".../.vscode-server/bin/..." and run: npm install jschardet

## SVN Output ##
nothing there

## Screenshots ##
![Screen Shot 2020-08-02 at 16 56 10](https://user-images.githubusercontent.com/10667472/89124642-4515ad00-d4e1-11ea-9ccd-4387387c8134.png)

**Comment by JohnstonCode** [comment]
Hi @pn1k. Can you install this vsix manually and see if it resolves your issue. You will need to install it locally and on the server. https://github.com/JohnstonCode/svn-scm/suites/998087664/artifacts/12884399

**Comment by pn1k** [comment]
yes, this version works ok.

**Comment by JohnstonCode** [comment]
Thanks for checking for me and sorry for the break.
