### ISSUE TITLE
Styling issue with "Commit selected"

### ISSUE THREAD

**Issue by TimVevida** [JohnstonCode/svn-scm#1027]
Since the latest release (of VSCode) the screen that shows when you right click on one or more selected files to commit just a selection of your changes is not styled properly.

![afbeelding](https://user-images.githubusercontent.com/16288300/89196173-20d1d300-d5aa-11ea-8b26-c3fd7ddf1be4.png)

**Comment by JohnstonCode** [comment]
Hi @TimVevida thanks for reporting this.

Can you manually install this vsix and see if it resolves the issue.
https://github.com/JohnstonCode/svn-scm/suites/1001796443/artifacts/12970532

**Comment by TimVevida** [comment]
No time now, but I will check this next thursday.
