### ISSUE TITLE
Can't Get it to work at all.

### ISSUE THREAD

**Issue by JoeKazz** [JohnstonCode/svn-scm#104]
- VSCode Version: 1.19.2
- OS Version: Window 10.
- Extension Version: 1.5.0
- System Language: C#

Steps to Reproduce:

1. Even after installing I get "There are no active source control providers" in Source Control
2. So...how do I use it? (For instance....how do I do a simple diff?) 

I don't see any interface instructions or anything looking different.
What am I missing?
(PS...I have TortoiseSVN installed (including command line tools and the PATH variable is set correctly)).

I apologize in advance if it's something simple. I'm new VSCode but had no problems getting the C# & VIM extensions to work.

Many thanks in advance.

**Comment by JohnstonCode** [comment]
if you open the output window and select svn what do you see?

**Comment by JoeKazz** [comment]
Using svn 1.9.7 (r1800392) from C:\Program Files\TortoiseSVN\bin\svn.exe

**Comment by JoeKazz** [comment]
So that's hopeful I guess.

**Comment by JohnstonCode** [comment]
Yes means its finding svn at least

**Comment by JoeKazz** [comment]
Yes.

**Comment by JoeKazz** [comment]
I just don't know what it's supposed to be doing. What I care most about....is being able to do a diff....without jumping to explorer.

**Comment by JoeKazz** [comment]
I'll make sure of that...but I believe so.

**Comment by JoeKazz** [comment]
Ok...now I got a bunch of stuff...showing up in log.
Using svn 1.9.7 (r1800392) from C:\Program Files\TortoiseSVN\bin\svn.exe
[]$ svn info --xml
[]$ svn info --xml
[Scripts]$ svn info --xml
[]$ svn stat
[]$ svn ls file:///D:/SVN_Unity/trunk --depth empty
[]$ svn ls file:///D:/SVN_Unity/branches
[]$ svn ls file:///D:/SVN_Unity/tags
[Scripts]$ svn info --xml
svn: warning: W160013: URL 'file:///D:/SVN_Unity/trunk' non-existent in revision 27
svn: E200009: Could not list all targets because some targets don't exist

svn: warning: W160013: URL 'file:///D:/SVN_Unity/branches' non-existent in revision 27
svn: E200009: Could not list all targets because some targets don't exist

svn: warning: W160013: URL 'file:///D:/SVN_Unity/tags' non-existent in revision 27
svn: E200009: Could not list all targets because some targets don't exist

**Comment by JoeKazz** [comment]
Probably because I'm not a typical SVN user. I don't Branch.

**Comment by JoeKazz** [comment]
(I don't branch of merge).
Thanks for your help....I'll play around with this for a bit....and see what I can do with these warnings.

**Comment by JoeKazz** [comment]
Seeing Diff Lines now...(so this is hopeful) (Even with the warnings).

**Comment by JohnstonCode** [comment]
Okay, To get those warning to go away just set the root path of your repository as the path for trunk, branches and tags in the settings

**Comment by JoeKazz** [comment]
The Diff lines...(and the Errors...don't always show up)....

**Comment by JoeKazz** [comment]
I can't figure out....what makes it "kick-off"....and start working per editing session.

**Comment by JoeKazz** [comment]
Like right now...it's only got the Using svn message.

**Comment by JoeKazz** [comment]
Now it's finally doing the "info"

**Comment by JoeKazz** [comment]
But nothing else....no warnings (this time)...and no change lines.

**Comment by warnedar** [comment]
How was the issue resolved?
I'm currently able to see the prompt 
Using svn "1.7.10 (r1485443)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
after selecting Svn in the output console.  But the source control manager still says, "There are no active source control providers."
Am I missing something?

**Comment by NithinBiliya** [comment]
I am still having this issue on windows. Any steps to solve this?

![image](https://user-images.githubusercontent.com/1023975/40240639-a48fda4e-5ad6-11e8-93a1-a246cf8d4106.png)

**Comment by edgardmessias** [comment]
@NithinBiliya , please run the command `svn info <your svn folder>` and paste here
