### ISSUE TITLE
quick diff gutter no longer working

### ISSUE THREAD

**Issue by QuentinHsu** [JohnstonCode/svn-scm#1042]
- VSCode Version: 1.48.0
- OS Version: Windows_NT x64 10.0.18363
- Extension Version: 2.12.3
- System Language: Simplified Chinese
- SVN Version: 1.14.0

## Issue ##

After modifying a file, the "change" flag cannot be displayed.
This worked with VS Code v1.47.3, but not with VS Code upgrade to v1.48.
As shown in the screenshot, this is what is shown in the working state.

## Steps to Reproduce ##

1.In VS Code v1.48, Extension Version: v2.12.3, modifying a committed file does not display the change flag.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```
Can't see where this information was obtained from, so I can't provide that information.

## Screenshots ##

![image](https://user-images.githubusercontent.com/21162238/90231249-77ae9680-de4d-11ea-937e-310c3c6d0759.png)

**Comment by JohnstonCode** [comment]
Think this is a VSCode issue. Raised it with them.

**Comment by RichMcL** [comment]
The downloads to rollback to previous versions: https://code.visualstudio.com/updates/v1_47

**Comment by QuentinHsu** [comment]
> 下载以回滚到以前的版本：[https](https://code.visualstudio.com/updates/v1_47) : [//code.visualstudio.com/updates/v1_47](https://code.visualstudio.com/updates/v1_47)

Thanks, I've reinstalled VS Code v1.47.

**Comment by woowalker** [comment]
vscode latest version 1.48.2 fixed

**Comment by QuentinHsu** [comment]
> vscode最新版本1.48.2已修复

Thanks for the reminder, I upgraded VS Code to v 1.48.2 this morning and updated the SVN plugin version to v2.12.4. The quick diff gutter in VS Code's SVN is now working！😊🎉🎉🎉

**Comment by wuyingjie123** [comment]
刚刚安装v2.12.4后，可以正常显示。一旦重启VSCode就又不显示了，再重新安装一遍，又可以正常显示。

**Comment by QuentinHsu** [comment]
> 刚刚安装v2.12.4后，可以正常显示。一旦重启VSCode就又不显示了，再重新安装一遍，又可以正常显示。

那你的 VS Code 版本，有尝试升级到 1.48.2 吗？

因为 VS Code 1.48.2 在 VS Code 官方层面已修复该问题（援引自 [详情](https://github.com/JohnstonCode/svn-scm/issues/1042#issuecomment-680423694)）。我目前本地开发环境：VS Code 版本为 1.48.2，SVN for VS Code 插件版本为 2.12.4（两者均更新到了当前最新版）。

使用了一天，quick diff gutter 功能一直正常工作。

**Comment by kAlvaro** [comment]
Unless I'm missing something, Microsoft hasn't fixed the bug yet. Extension author has switched to a not broken API so you need to upgrade the extension, not Visual Studio Code.

**Comment by wuyingjie123** [comment]
VSCode:
版本: 1.48.2 (user setup)
日期: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

svn-scm:
v2.12.4

**Comment by luluwuxin** [comment]
svn-scm 和 vscode 都是最新版， 刚开始安装后能使用，重启vscode后又不能使用了，除非再次重新安装

**Comment by JohnstonCode** [comment]
Please open a new issue

**Comment by joaomoreno** [comment]
@JohnstonCode Sorry for breaking this, it was an unintended breakage.

**Comment by JohnstonCode** [comment]
@joaomoreno no problem
