### ISSUE TITLE
No file changes are shown in editor if local path does not match working copy path

### ISSUE THREAD

**Issue by dimka-rs** [JohnstonCode/svn-scm#1043]
- VSCode Version: 1.48.0
- OS Version: Linux Mint 19.3 Tricia
- Extension Version: 2.12.3
- System Language: English
- SVN Version: 1.9.7 (r1800392)

## Issue ##
I work from home, working dir is mounted over sshfs. Absolute path from svn repo does not match local path.
```
Local path: /home/<home user>/Work/repo/file.c
Working Copy Root Path: /home/<work user>/Work/repo/file.c
```
## Steps to Reproduce ##
Not sure if this is correct way to reproduce
1. checkout svn repo
2. rename repo folder

## SVN Output ##
```
svn info --xml /home/<home user>/Work/repo/file.c
<?xml version="1.0" encoding="UTF-8"?>
<info>
svn: E155007: '/home/<home user>/Work/repo/file.c' is not a working copy
```

**Comment by RandomSpaceship** [comment]
I have the same issue. I'm using SVN on a PlatformIO project, and I have this same issue, as the code is in an "src" folder. TortoiseSVN recognises that the files are different, but this extension doesn't, although it works properly if it's uninstalled/reinstalled until the next VSCode restart.
