### ISSUE TITLE
Editor sidebar comparison

### ISSUE THREAD

**Issue by alvin30595** [JohnstonCode/svn-scm#1046]
the sidebar SVN comparison is not showing after the latest update of VSC

**Comment by SHiLLySiT** [comment]
@alvin30595 Are you referring to the [gutter indicators](https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators) missing for file changes? If so, I am also having this problem!

![gutter](https://user-images.githubusercontent.com/950984/90661857-86ee6500-e1fc-11ea-9f55-0a14c82a9430.png)

**Comment by JohnstonCode** [comment]
#1042

**Comment by alvin30595** [comment]
Alright, thanks
