### ISSUE TITLE
You closed...before I was really done...

### ISSUE THREAD

**Issue by JoeKazz** [JohnstonCode/svn-scm#105]
- VSCode Version:
- OS Version:
- Extension Version:
- System Language:

Steps to Reproduce:

It's now only showing "Using svn...." and an "info" the change lines seem to be intermittent at best. (And it didn't show the warnings this time. Seems to change everytime I pop in and out of VSCode.

**Comment by JoeKazz** [comment]
I'll play around with it...and get back to you...if I figure anything else out about it.

**Comment by JoeKazz** [comment]
Are there instructions anywhere...for how do do the "Quick Diff" in cutter for instance.

**Comment by JohnstonCode** [comment]
You can re-open issues.

The quick diff will only work if vs code sees changes against whats in the file and the copy in the repository.

There isn't much documentation on them. [Here is the info VS Code has](https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators)

**Comment by JohnstonCode** [comment]
I think the extension is having issues with your Svn repository layout
