### ISSUE TITLE
delete doesn't work

### ISSUE THREAD

**Issue by Spongman** [JohnstonCode/svn-scm#1091]
- VSCode Version: 1.49.1
- OS Version: CentOS 7 (via ssh)
- Extension Version: 2.12.4
- System Language: english
- SVN Version: 1.7.4

## Steps to Reproduce ##

1. delete some files 
2. commit them
3. deletions are not committed

also, if you do 'svn rm XYZ' and refresh the source control view, it doesn't show that file as deleted.

**Comment by JohnstonCode** [comment]
Are your files local or remotely mounted? I am not able to replicate.
