### ISSUE TITLE
How to use SVN in visual studio code 

### ISSUE THREAD

**Issue by youssef6dh** [JohnstonCode/svn-scm#1100]
Hi  @JohnstonCode 
 Can I have any doc or vidéo to show me how can I use ths SVN to commit the change  in  visual studio code for python
I am using TortoiseSVN without any problem but I need to use VS code directly 
I clicking on add and giving the right repo url  taking time with error "faild to repo"
Many thanks

**Comment by youssef6dh** [comment]
Hi , 
Can some one help here please ?
thanks

**Comment by JohnstonCode** [comment]
Can you please fill out the issue template. You have given no information at all.

**Comment by youssef6dh** [comment]
Hi @johnjacobkenny 
is not issue I just need a document or video to explain me how I can configure Visual Studio Code with SVN extension
I am using TortoiseSVN to commit my change into repo via this link svn+ssh://aaa.bbb.net/
Many thanks

**Comment by johnjacobkenny** [comment]
@youssef6dh if you open the project folder in vs code you should be able to use the version control tab to make your commits. I haven't been using this for a while so I don't know if anything has changed in between

**Comment by GitMensch** [comment]
Would a set of videos be nice explaining how to use svn with vscode "from the start" (= for someone neither knowing vscode, nor svn): definitely, but so far I've not seen someone creating them...

I think this is mostly the question how to work with version control in vscode. I suggest to have a look at the common documentation for that, for example https://code.visualstudio.com/Docs/editor/versioncontrol (some parts are git specific but when familiar with svn you'll see those quick). If you are not familiar with SVN, then there are definitely a bunch of videos explaining how to use that.

**Comment by Neskazhui** [comment]
Hello, Johnston.
I have the same question. I have installed JohnstonCode extension in VS Code. But I have not "version control tab". Where is it? How it's looked?

**Comment by shivampotdar** [comment]
Thanks for the comment @Neskazhui . That was helpful.
I noticed that if I already have the repo checked out and then I use the working copy directory, it shows an error saying `.svn` exists already.
Cloning to an independent location works though.
Do you know of any ways to get the Subversion tab working without actually checking out the repo again?

**Comment by focussing** [comment]
For me it doesn't work either. When I open an SVN folder the source control tab does not show anything. Also I cannot add repository, the + sign does not open a window to fill in a repository.
The folder contains a .svn folder, and I can see all the changes when I use Versions on my mac (like TortoiseSVN for windows).

Does anyone has an idea what I could be overseeing?

**Comment by GitMensch** [comment]
@focussing Just to check: when you use the terminal within vscode and execute `svn log` do you see everything as expected? If not then one of the following is likely:

* you don't have an `svn` binary in PATH
* the `svn` binary in PATH has unmet dependencies (missing shared objects)
* the `svn` binary does not support the SVN version of the local checkout

**Comment by focussing** [comment]
@GitMensch Good suggestion! Thank you!

raymond$ svn log
svn: E155036: Please see the 'svn upgrade' command
svn: E155036: The working copy at '/Users/raymond/Documents/Appcelerator_Studio_Workspace/xxxx'
is too old (format 29) to work with client version '1.14.1 (r1886195)' (expects format 31). You need to upgrade the working copy first.

I have to make a release first, and commit that situation. Next I will svn-upgrade and report back here.

**Comment by GitMensch** [comment]
@focussing can you please create a new issue about "handle svn client differences" describing exactly what you see and requesting the extension to output this message somewhere - ideally with a question "Do you want to upgrade the working-copy format now" (if, like in your case, the client is newer; if the other way around then only an error message can be returned)?

**Comment by focussing** [comment]
@GitMensch sure I will do that.
