### ISSUE TITLE
Diff Changes Head not work on UNC path

### ISSUE THREAD

**Issue by nyan777** [JohnstonCode/svn-scm#111]
VSCode Version: 1.19.2
OS Version: Windows 10
Extension Version: 1.6.0
System Language: Japanese

Steps to Reproduce:

1. open project on unc path.
2. show svn file list.
3. right click any file, select "Diff Changes Head".

output like this:

[proj]$ svn cat \web\proj\index.html -r HEAD
svn: E155007: 'C:\web\proj\index.html' is not a working copy

path should be:

\\\\xxx.xxx.xxx.xxx\web\proj\index.html

it will work if I change script like:

svn.js:133

\+        path = path.replace(/^/g, "\\\\xxx.xxx.xxx.xxx");
        var args = ["cat", path];

But I don't know how to get root path for project.
So please fix it.

Thank you.

**Comment by edgardmessias** [comment]
Fixed in #113
