### ISSUE TITLE
Add `svn.sourceControl.ignore` option to Ignore unversioned files like .gitignore

### ISSUE THREAD

**Issue by basecell** [JohnstonCode/svn-scm#1113]
## Feature Request

Hi, I want to create a pull request to add `svn.sourceControl.ignore` option, It can ignore unversioned files like .gitignore. At the same time, configuring this option will overlook the default svn ignore rule, but if you do not configure this option, nothing will change.
The effect is as follows:
![image](https://user-images.githubusercontent.com/14192199/97101041-d78aae80-16d4-11eb-83ea-a3da04837417.png)
![image](https://user-images.githubusercontent.com/14192199/97101470-a6ac7880-16d8-11eb-9646-3740039c302f.png)
![image](https://user-images.githubusercontent.com/14192199/97101327-73b5b500-16d7-11eb-9a3d-c637622d3551.png)
![image](https://user-images.githubusercontent.com/14192199/97101440-60efb000-16d8-11eb-900c-17bb9e108c5d.png)

**Comment by JohnstonCode** [comment]
What is the benefit of this over just using `svn propset svn:ignore` or the context menu?

**Comment by basecell** [comment]
It is convenient to prevent some people who are not very familiar with svn from submitting some messy things to the warehouse. We can set the rules in text, and then share them with people in the team in text. To be honest, many people around me don't know how to use svn:ignore.

**Comment by basecell** [comment]
Moreover, if you want to add a directory, but there are files in the directory that need to be ignored, the right-click menu will be invalid at this time, you can only add it to the ignore rule with a command, which is too cumbersome.

**Comment by JohnstonCode** [comment]
Yeah it can be difficult for people who have used git before. I see your point.
