### ISSUE TITLE
Error message when selecting commit from Repositories view

### ISSUE THREAD

**Issue by jakelevi1996** [JohnstonCode/svn-scm#1146]
- VSCode Version: 1.51.0 (user setup)
- OS Version: Windows_NT x64 10.0.19041
- Extension Version: 2.13.3
- System Language: Huh?
- SVN Version: **1.6.17 (r1128011)**

## Issue ##

From the repositories view in the Subversion menu in the left side-bar, selecting a commit raises an error message in the bottom right corner of the screen which reads `Cannot read property 'replace' of undefined`.

This could be because I'm using an old version of SVN (1.6.17). This is the version of SVN used across projects in my company, and unfortunately I do not have the option to upgrade to a newer version of SVN. Assuming it is a problem with an old SVN version, it would be great if the extension could be updated to support this older version.

## Steps to Reproduce ##

1. Open an SVN repository in VSCode
2. Select the SVN icon in the left sidebar
3. Under the repositories view, click on one of the commit messages
4. Observe error message `Cannot read property 'replace' of undefined` (shown in screenshots)

## SVN Output ##

There is no SVN Output that is generated by me clicking on one of the commit messages.

## Screenshots ##

![image](https://user-images.githubusercontent.com/31698048/98803224-53dafc80-240c-11eb-814e-0a8c1ddc1c3c.png)

**Comment by JohnstonCode** [comment]
If you are not getting anything in the svn output, can you copy the contents of the dev console.

Help >> Toggle Developer Tools >> Console

**Comment by jakelevi1996** [comment]
Thank you for looking into this @JohnstonCode . Here is the output from the dev console:

```
notificationsAlerts.ts:38 TypeError: Cannot read property 'replace' of undefined
	at Function.file (c:\Users\jol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:154:279)
	at new h (c:\Users\jol\.vscode\extensions\johnstoncode.svn-scm-2.13.3\out\extension.js:2:201347)
	at b.getPathNormalizer (c:\Users\jol\.vscode\extensions\johnstoncode.svn-scm-2.13.3\out\extension.js:2:219461)
	at e.RepoLogProvider.getTreeItem (c:\Users\jol\.vscode\extensions\johnstoncode.svn-scm-2.13.3\out\extension.js:2:188389)
	at c:\Users\jol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:675:33
	at Array.map (<anonymous>)
	at m.fetchChildrenNodes (c:\Users\jol\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:674:985)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
onDidChangeNotification @ breadcrumbsModel.ts:39
(anonymous) @ breadcrumbsModel.ts:39
fire @ event.ts:584
addNotification @ notifications.ts:204
error @ breakpointWidget.ts:390
(anonymous) @ mainThreadTreeViews.ts:158
Promise.then (async)
then @ remoteExtensionManagementService.ts:25
getChildren @ mainThreadTreeViews.ts:158
getChildren @ treeView.ts:181
getChildren @ treeView.ts:662
(anonymous) @ asyncDataTree.ts:755
a @ cancellation.ts:137
doGetChildren @ asyncDataTree.ts:755
doRefreshNode @ asyncDataTree.ts:755
doRefreshSubTree @ asyncDataTree.ts:689
refreshNode @ asyncDataTree.ts:689
refreshAndRenderNode @ asyncDataTree.ts:689
_onDidChangeCollapseState @ asyncDataTree.ts:755
(anonymous) @ event.ts:753
(anonymous) @ event.ts:753
bufferEvents @ event.ts:753
setCollapsed @ indexTreeModel.ts:233
setCollapsed @ objectTreeModel.ts:228
onViewPointer @ abstractTree.ts:1104
(anonymous) @ event.ts:139
fire @ event.ts:584
(anonymous) @ linkedList.ts:127
fire @ event.ts:584
o @ browser.ts:96
```

**Comment by JohnstonCode** [comment]
If you do a `svn info` what is the `Working Copy Root Path`?

**Comment by jakelevi1996** [comment]
When I enter `svn info` at the command line, the fields I get are `Path`, `URL`, `Repository Root`, `Repository UUID`, `Revision`, `Node Kind`, `Schedule`, `Last Changed Author`, `Last Changed Rev` and `Last Changed Date` (IE no `Working Copy Root Path` exactly). Next to `Path` I just have `.` (IE the current directory that VS Code is open in).

**Comment by jakelevi1996** [comment]
I've updated the extension, tested it, and verified it's working. Thank you for the fix, @JohnstonCode !!
