### ISSUE TITLE
Diff any 2 files from any 2 commits

### ISSUE THREAD

**Issue by jakelevi1996** [JohnstonCode/svn-scm#1147]
**Is your feature request related to a problem? Please describe.**

The problem is that while it is useful to be able to open a diff between a file on 2 consecutive commits, or a diff between an old commit and the current version of a file, it would be useful if there were more diff options.

**Describe the solution you'd like**

I would like to be able to select any 2 files from any 2 different commits from the repository view in the Subversion menu from the left sidebar, and open them for diff (like the equivalent feature in Git Lens).

**Comment by jhnyang** [comment]
That's what i am exactly looking for ;_;
how can i diff 2 revisions which is not consecutive? 
is this solved?
