### ISSUE TITLE
svn commit found error.

### ISSUE THREAD

**Issue by ekopei** [JohnstonCode/svn-scm#116]
- VSCode Version: 1.19.2
- OS Version: win7 x64
- Extension Version:SVN 1.8.0 
- System Language: Chinese

error log: 
[scrm]$ svn commit -m 1
svn: E155007: 'C:\Program Files\Microsoft VS Code' is not a working copy

**Comment by s-martin** [comment]
`C:\Program Files\Microsoft VS Code` is probably not a SVN workspace.
Have you opened your SVN workspace?

**Comment by edgardmessias** [comment]
The file list is empty, you can send a print of your Source Control?

**Comment by ekopei** [comment]
Using svn 1.9.7 (r1800392) from C:\Program Files\TortoiseSVN\bin\svn.exe
[scrm]$ svn info --xml
[scrm]$ svn info --xml
[scrm]$ svn stat --xml
[scrm]$ svn ls http://tc-svn.tencent.com/xybase/mgsystem_proj/trunk --depth empty
[scrm]$ svn ls http://tc-svn.tencent.com/xybase/mgsystem_proj/branches
[scrm]$ svn ls http://tc-svn.tencent.com/xybase/mgsystem_proj/tags
[scrm]$ svn update
[scrm]$ svn stat --xml
[scrm]$ svn commit -m 1
svn: E155007: 'C:\Program Files\Microsoft VS Code' is not a working copy

It's OK when run command "svn update" , but run "svn commit" had error.

**Comment by edgardmessias** [comment]
@ekopei, you are using "Command Palette" to commit?

**Comment by JohnstonCode** [comment]
@ekopei  Please reopen this issue if you are still having problems
