### ISSUE TITLE
Ability to switch to sub SVN branches

### ISSUE THREAD

**Issue by TheDanR** [JohnstonCode/svn-scm#117]
Steps to Reproduce:

1. Have a SVN branch that is two levels down for example Root\level 1\level 2
2. on clicking the svn branch button (botton left) you can only see level 1 branches

**Comment by edgardmessias** [comment]
Unlike GIT, branches in SVN are very complex.

**Comment by pawellan13** [comment]
I change the branche using tortoises :(

**Comment by edgardmessias** [comment]
@TheDanR, @pawellan13, @Eretik, @JohnstonCode , test with this: https://ci.appveyor.com/api/buildjobs/9g08tgueatcnrfw7/artifacts/svn-scm.vsix

Instalation: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix
Disable auto-update before

**Comment by JohnstonCode** [comment]
@edgardmessias sorry for the delay I will check it out tomorrow.

**Comment by edgardmessias** [comment]
Someone?

**Comment by TheDanR** [comment]
Only seems to go down by one 
it also doesn't take into consideration as to where in the branch you checked out, so when switching it pulls from the top of the branch.

**Comment by edgardmessias** [comment]
@TheDanR, you modified the `svn.layout.( trunk, branches, tags )Regex` and `svn.layout.( trunk, branches, tags )RegexName`?

**Comment by JohnstonCode** [comment]
How do you create sub-branches? Also, Why would you need to create a sub-branch?

**Comment by edgardmessias** [comment]
Refer to #204

Some projects use `/trunk/<project>`, `/branches/<project>/<branches>` and `/tags/<project>/<tags>`

Some cases, I see `/<project>/branches/<username>/<branches>`

See https://confluence.atlassian.com/fisheye/svn-tag-and-branch-structure-298976888.html

**Comment by edgardmessias** [comment]
![image](https://user-images.githubusercontent.com/1530997/37047955-446422d4-214b-11e8-8a63-bba5ca69a114.png)

**Comment by JohnstonCode** [comment]
I use a standard layout never had any experience with custom layouts.

@edgardmessias thanks for those two links.
