### ISSUE TITLE
Error when clicking svn link: 'Unable to open ...'

### ISSUE THREAD

**Issue by jay-pee** [JohnstonCode/svn-scm#1181]
- VSCode Version: 1.15.1
- OS Version: Windows 10 1909
- Extension Version: 2.13.5
- System Language: English
- SVN Version: 1.12.2

## Issue ##

Clicking on svn links doesn't work for me. First i thought it is a VS Code problem but when I deactivate the extension the links are not clickable.

## Steps to Reproduce ##

1. create a json file in VS code:
```json
test:
  url: svn://svnrepo/Repository_X
  rev: 1
```
2. click on the link:
![image](https://user-images.githubusercontent.com/9380980/100998005-4a503a80-355b-11eb-8708-64b622d57f1a.png)

## Expected behavior

Suggesting to open the link in TortoiseSVN like Chrome does for example:
![image](https://user-images.githubusercontent.com/9380980/100998097-68b63600-355b-11eb-9f8b-4d90a23fdeb3.png)

**Comment by JohnstonCode** [comment]
This is not something the extension should support.
