### ISSUE TITLE
Click on file opens diff

### ISSUE THREAD

**Issue by s-martin** [JohnstonCode/svn-scm#12]
First of all thanks for the effort to finally implement a SVN extension!

I suggest to improve the feature from #4 and not only open the files from changes list, but open the file in diff view.

**Comment by JohnstonCode** [comment]
Hi @s-martin 

No problem using VS code without svn support was a pain for me as well!

Thanks for your suggestion. This is something that I can add.

I will copy the git version. left click open diff view and right click to open a context menu with options to open file, open diff and open HEAD

I am currently working on implementing my own svn interface so can't say when I will get around to this but should be soon.

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1
