### ISSUE TITLE
Doesn't work in VS Code 1.52.0

### ISSUE THREAD

**Issue by MocniMax** [JohnstonCode/svn-scm#1200]
- VSCode Version: 1.52.0, 1.52.1
- OS Version: MS Windows server 2019
- Extension Version: 2.13.5
- System Language: ENG
- SVN Version: TortoiseSVN 1.14.0, Build 28885 - 64 Bit 

## Issue ##
After it is installed, SVN icon is briefly displayed in VS Code Activity Bar and then disappears. In Command Palette only SVN: Checkout is accessible. The SVN box is displayed in File Explorer side bar.

## Steps to Reproduce ##
Install SVN extension and observe its behaviour.

## Screenshots ##

![image](https://user-images.githubusercontent.com/26117076/102494546-1bff4e80-4075-11eb-9a51-e5aa4e6e9fa8.png)

**Comment by sergiotendero** [comment]
I have the same problem. Installing on 1.52.1 SVN panel for configuring svn repositories, ... disapears

**Comment by MocniMax** [comment]
Actually, I figured it out that it works. Not in the way I will expect, but it works :).
What confused me is that when no svn client was installed on PC, the SVN icon was displayed in VS Code Activity Bar but when svn client (TortoiseSVN) is installed, the icon disappears.

The point is that SVN icon in VS Code Activity Bar is displayed only after checkout is done, not before (what basically make sense). After checkout is done, SVN icon shows in VS Code Activity Bar and all svn functions are available.

It would be very useful and logical to have SVN:checkout as part of Code File Explorer (as Revert with SVN is) but that is my opinion only.

Thank you for very useful Code extension!

**Comment by sergiotendero** [comment]
Yes, you're right.
I agree it would be useful to have SVN:checkout and/or add repo+checkout.

Thank you @MocniMax for your reply and @JohnstonCode for this extension!

**Comment by JohnstonCode** [comment]
https://github.com/JohnstonCode/svn-scm#checkout
