### ISSUE TITLE
Cannot detect all repos in a folder in real time

### ISSUE THREAD

**Issue by mengxianbin** [JohnstonCode/svn-scm#1204]
- VSCode Version:
```
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
```

- Extension Version: v2.13.5
- System Language: English
- SVN Version: 1.14.0 (r1876290)

## Issue ##

There are multiple repositories in a folder.
Sometimes the source control view show all repositories,
 but sometimes show only a part of them.

## Steps to Reproduce ##

1. Open the repo root folder with VSCode.
2. Reload the VSCode window.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```
```

```

**Comment by JohnstonCode** [comment]
How many repos? How big are the repos? How many folders do the repos contain?

**Comment by lask79** [comment]
We are having the same problem. We have ~200 checked out projects in one folder but this extension does not find all of those repositories. Sometimes he finds 50, next time >100 and sometimes more. 
It always seems the process of looking for the repos stopped somewhere in the middle. In the output view I cannot see any error that could explain it. 

I am running VSCode remote per SSH on a VM.

I am using SVN 1.7.14 and I put "svn.multipleFolders.enabled": true and "svn.multipleFolders.depth": 2, into the settings file.

Is there a way to debug it or to write out more information to track this down?
