### ISSUE TITLE
See commit messages command fails

### ISSUE THREAD

**Issue by andmau90** [JohnstonCode/svn-scm#1232]
- VSCode Version: 1.52.1
- OS Version: Windows 10
- Extension Version: 2.13.5
- System Language: English
- SVN Version: 1.13.0

## Issue ##
Unable to open '\c:{path}\trunk\svn.log (read-only)': Unable to resolve filesystem provider with relative file path 'svn:\c:\{path}\svn.log?{"action":"LOG","fsPath":"c:\\{path}\\trunk","extra":{}}'.

## Steps to Reproduce ##
1. execute command SVN: Show commit messages

## SVN Output ##
```
nothing
```

**Comment by stephanedr** [comment]
I get the same error.
```
Unable to open '\c:\<path>\svn.log (read-only)': Unable to resolve filesystem provider with relative file path 'svn:\c:\<path>\svn.log?{"action":"LOG","fsPath":"c:\\<path>","extra":{}}'.
```
`<path>` corresponds to the directory of the working copy (containing `.svn` subdir).
I suppose it should be the SVN server URL instead.

VSCode Version: 1.58.2
OS Version: Windows 10
Extension Version: 2.13.6
System Language: English
SVN Version: 1.14.1
