### ISSUE TITLE
Only 3 SVN repos detected

### ISSUE THREAD

**Issue by austin-bowen-iss** [JohnstonCode/svn-scm#1235]
- VSCode Version: 1.50.1
- OS Version: Windows 10
- Extension Version: 2.13.5
- System Language: en_US
- SVN Version: 1.14.0

## Issue ##
I have a project with 4 different SVN repositories checked out into four separate "src" directories, structured like so:
- MyProject\ModuleA\src
- MyProject\ModuleB\src
- MyProject\ModuleC\src
- MyProject\ModuleD\src

I have checked the setting "Allow to find subfolders using SVN".  After restarting VS Code, it successfully picks up only 3/4 of the SVN repos -- in my example above, it only picks up the SVN repos for Modules A, C, and D.

## Steps to Reproduce ##

1. Check out more than 3 SVN repositories in a project.
2. Check "Allow to find subfolders using SVN" setting and restart VS Code.
3. Only 3 of the SVN repositories are discovered.

**Comment by austin-bowen-iss** [comment]
Well this is strange -- I left VS Code running overnight, and this morning, it seems to have finally detected my 4th SVN repository.  Not sure if that means this issue should be closed, or if it should be repurposed to figure out why it took so long to find the 4th repo?

**Comment by JohnstonCode** [comment]
Unable to reproduce.
![image](https://user-images.githubusercontent.com/10222719/106382044-ab0dbf00-63b4-11eb-8c00-6fa7b9383d66.png)

If one of your modules has lots of folders within the src directory it can take a while to search through them all. Try lowering the `Svn > Multiple Folders:Depth` config option to 3.

**Comment by austin-bowen-iss** [comment]
That would make sense and explains what I am seeing, the projects are pretty massive.  Thank you!
