### ISSUE TITLE
"Offline" diff of modifications compared to original checked out state.

### ISSUE THREAD

**Issue by jamesmikesell** [JohnstonCode/svn-scm#125]
- VSCode Version: `1.19.2`
- OS Version: `Win 10` and `OSX High Sierra`
- Extension Version: `1.8.0`
- System Language: `English`

Not sure if this is a bug report, feature request, user error, or gap in documentation.

Is there a way when offline (or more likely, not VPNed into the network that hosts the SVN repository) to see a diff of modifications compared to the original checked out state of the file?  It appears that the only information available when offline is that a file has been modified, but no indication as to what lines etc have been modified within that file.

By comparison, with Tortoise SVN, when offline and a modified file is double click , a diff of the uncommitted local changes can be viewed.

This plugin only appears to show a diff against `HEAD`, and only when the remote svn repository is accessible.

**Comment by edgardmessias** [comment]
You can set `svn.diff.withHead` to false to compare with local.

**Comment by jamesmikesell** [comment]
That's it! 

Thanks!
