### ISSUE TITLE
Only access the server on explicit request

### ISSUE THREAD

**Issue by lapo-luchini** [JohnstonCode/svn-scm#126]
- VSCode Version: 1.17.2
- OS Version: FreeBSD 11.1
- Extension Version: 1.9.0
- System Language: Italian

Steps to Reproduce:
1. open VSCode
2. open directory with SVN checkout
3. wait a bit (doing nothing SVN-related)
4. an SSH agent pop-up appears to ask for password

I also tried `"svn.diff.withHead": false` but it still happens.

I'd prefer for the plugin to stick to locally available data unless instructed otherwise, i.e. of course if I ask a `svn blame` on a file the server is needed, but I don't like the random connections (and modal password requests that this produces) just to update the status of files in the GUI.

**Comment by JohnstonCode** [comment]
Do you know what command is running?

I suspect it is svn cat

**Comment by lapo-luchini** [comment]
Not yet, I'm fairly new to VSCode and I didn't learn how to debug extension yet. I shall.

**Comment by edgardmessias** [comment]
Go to `View -> Output`, select `SVN` in dropbox

**Comment by lapo-luchini** [comment]
OK, I see a bunch of `svn stat --xml`, `svn info --xml` and `svn cat`… but I tried all those from a shell with unset `SSH_AUTH_SOCK` and they don't ask for password, so that's not it.
Now I'll try and wait a bit.

OK, this is most certainly it:
```
[project]$ svn ls svn+ssh://lapo@server/path/trunk --depth empty
[project]$ svn ls svn+ssh://lapo@server/path/branches
[project]$ svn ls svn+ssh://lapo@server/path/tags
```

**Comment by JohnstonCode** [comment]
Would you like an option not to check for branch updates automatically then?

**Comment by lapo-luchini** [comment]
Would be nice. Together with `"svn.diff.withHead": false` (that I'm already using) seems like it should achieve the "no unexpected connections" I was looking for.

**Comment by edgardmessias** [comment]
The problem: when check remotes branches, svn use external request.

We need improve the auth for this cases.

**Comment by JohnstonCode** [comment]
Yeah, auth is a big pain.

Not sure how to handle it.

**Comment by lapo-luchini** [comment]
(In the meanwhile I did a local checkout and understood how to debug in VSCode.)
Seems to start from `Repository.getBranches()`'s usage of `svn.list(branchUrl)`… which seems to be called from the parsing of `svn info --xml` output… but I get a bit lost in seemingly unrelated Promises (__awaiter/step/fulfilled) and I don't understand how that's related.

**Comment by JohnstonCode** [comment]
I think you are looking at the output files, not the ts files.

**Comment by lapo-luchini** [comment]
Yeah, those intermediate stuff are in `.js` files, but following only the `.ts` files I don't understand how `svnRepository.ts` is called from `infoParser.ts`.
![image](https://user-images.githubusercontent.com/420454/35627310-d0daf800-0698-11e8-88de-dcbeb3b31c49.png)
Anyways, this puzzles me but is not so important, with the good old way of grepping for method names I guess it all originates from this:
```ts
    setInterval(() => {
      this.updateBranches();
    }, 1000 * 60 * 5); // 5 minutes
```
Would it be acceptable a PR with that number made an option?
(I would then make that very big in my workspace)
If that makes sense to you.

**Comment by JohnstonCode** [comment]
Yeah, send a PR!

**Comment by lapo-luchini** [comment]
I understand the extension's approach seems to be «you're one developer on a very active branch, so you want to know often when stuff changes, so that you can update often and follow the branch» (I guess?), while I'm more accustomed to develop mostly offline and make a single big commit for a new working feature (which makes sense on a distributed SCM like [mtn](http://www.monotone.ca/) or git, but also in my workplace's SVN, as we're just a few developers on each branch at the same time).

**Comment by edgardmessias** [comment]
I will start to fixe auth issues

**Comment by JohnstonCode** [comment]
@edgardmessias can you add what you are planning in #89 

Would like to know how you plan to tackle it.

**Comment by lapo-luchini** [comment]
I wasn't so sure about the naming, feel free to change it (of course).

**Comment by JohnstonCode** [comment]
live in v1.1.3.0
