### ISSUE TITLE
Status of files outside of current folder being shown

### ISSUE THREAD

**Issue by bkromhout** [JohnstonCode/svn-scm#13]
It seems that, if I have VS Code open to a specific folder within my overall SVN repository, the SCM provider is now showing the status of files everywhere in the SVN repository rather than just the files that are under the current folder somewhere.

For example, if VS Code is open to `C:\Dev\branches\A\1\`, and my SVN repo's root is `C:\Dev`, I'm now seeing the status of all files in `C:\Dev`, rather than just those under `C:\Dev\branches\A\1\`.

I believe this might be a recent regression, I'm fairly sure it used to only show the status of files within the currently open folder.

**Comment by JohnstonCode** [comment]
HI @bkromhout 

Yes this is a regression checking out d2f770bd4b946a39d42d1a029b151e27767c5868 does not have the same issue.

I believe this is because of how the repository root is calculated to accommodate for multi-root.

Thanks for raising this.

**Comment by JohnstonCode** [comment]
Hi @bkromhout 

Version 0.8.4 should fix this for you.
