### ISSUE TITLE
diff two DIFFERENT revisions

### ISSUE THREAD

**Issue by jhnyang** [JohnstonCode/svn-scm#1307]
Can i diff 2 different revision which are not consecutive?
Or can I save 'diff result view' as a file? so that i can share it when i need

Please!! it would be super great if they are available

**Comment by cyberpatent-mao** [comment]
Yes, exactly the same problem!
I have to use TortoiseSVN+WinMerge to achieve the action.

**Comment by cp-mao** [comment]
Yes, exactly the same problem!
I have to use TortoiseSVN+WinMerge to achieve the action.
