### ISSUE TITLE
Unversioned files shown twice

### ISSUE THREAD

**Issue by stephanedr** [JohnstonCode/svn-scm#131]
- VSCode Version: 1.19.3
- OS Version: Windows 7
- Extension Version: 1.13.0
- System Language: English

Unversioned files are shown twice (was not the case with earlier versions, but don't know which version exactly):
1. In the UNVERSIONED section, as before (but now with 2 "+" buttons),
2. In the CHANGES section.

I don't know whether showing them twice is intentional, but I prefer seeing them once below UNVERSIONED. If intentional, can we have an option to select where we want to see them?

**Comment by JohnstonCode** [comment]
Ill sort it thanks for raising it!

**Comment by edgardmessias** [comment]
In UNVERSIONED, one button is to add to svn control ("CHANGES") and one for "CHANGELIST"

In CHANGES, is for to choose "Changelist"

**Comment by stephanedr** [comment]
This is fixed. Thanks !
