### ISSUE TITLE
Deleted items not going to recycle bin

### ISSUE THREAD

**Issue by kqlehman** [JohnstonCode/svn-scm#1322]
VSCode Version: 1.54.3
OS Version: Windows 10
Extension Version: 2.13.5
SVN Version: TortoiseSVN 1.8.11
### Issue
When I delete an unversioned file, it does not go to the recycle bin.

### Steps to Reproduce
1. From VS Code, click on Explorer and create a new file. 
2. Click on Source Control. The new file appears under unversioned files. 
3. Right click on the unversioned file and choose "Delete selected files". Click Yes.
4. Look in the recycle bin and the file is not there.

**Comment by kqlehman** [comment]
<img width="270" alt="2021-03-16 11_37_17-FileToDeleteTest j" src="https://user-images.githubusercontent.com/3231482/111337052-22896c00-864c-11eb-9ff9-7e2631277c7a.png">
Here is a screen shot showing how I deleted a file.

**Comment by JohnstonCode** [comment]
Node JS fs doesn't provide a way to send deleted files to the recycle bin.
