### ISSUE TITLE
feature request - commit bar at the top of the svn module

### ISSUE THREAD

**Issue by Guema** [JohnstonCode/svn-scm#133]
Hello,

This is a feature request about the way we write the commit message.
Instead of what it is at the moment, could you eventually use the top bar of the SVN source control, like for the Microsoft's git one, allowing to write multi-line messages, making it easier to use and less missed enter key susceptible. 

I have now idea about how it is difficult or possible or anyway, just letting it here, in case of.

Thank you in any way for your awesome work, from svn user.

**Comment by JohnstonCode** [comment]
Do you mean commit messages for selected files rather than all changes?

**Comment by Guema** [comment]
I just understood that i did not exactly understood how the thing works.

Didn't know it was possible to commit all change before :/

Anyway, i think it could be more ergonomic to assemble and mix the 2 commit ways. The "commit selected" should probably be deleted and top bar behaviour should be changed.
(as having multiple way to do one thing is generally not a good idea, because it can be confusing, like i was actually)

A possible way should be to add a "Flagged for commit" category or something like this. It is just a local flag, allowing both flagging all changes, or some change(s), without any difference.
The real problem is it will be hard to manage UI depth with ChangeLists. I don't know if the vscode UI allow you to manage Categories and sub-categories.
In this case, a possible way should be to have 3 Big inclusive Categories : Flagged for commit, Changed, and Unversionned, with a second category level for Change-Lists in Flagged and Changed.

Another good way could be to add checkboxes to the left of each Versioned files, allowing to check/uncheck it and commit the whole with the top bar (that is, in my opinion, better than popup bar for the reasons i explained before). Probably more intuitive and apparent than Maj or Ctrl + click each individual changes.

As i said i don't know how it is difficult to do this, as i don't know vscode Api, just letting some suggests.
Thank you !

**Comment by edgardmessias** [comment]
VSCode has some limitations.

Could not you simply use a "to-commit" changelist, and commit only it?

**Comment by Guema** [comment]
At the moment i do something like this, so yes, it is fully possible and working well,
I just let some ideas to enhance general ergonomy (in my opinion)

But i can understand VScode is limited as you said, and things i suggest may be not possible or
too time-expensive or difficult-to-do for what it can truly bring.

As said before i let it here, feel free to do, or not do, or to see later, its just suggestions :)

**Comment by JohnstonCode** [comment]
@Guema suggestions are always welcome.

Like @edgardmessias  said the VS code API is limited and can be a pain to work with. I found it doesn't cater too well with svn as it does with GIT.

I would like to use the top commit bot for all commit messages as I to do like to write multiline commit messages.

@edgardmessias  has recently added changelists which allow you to use the top commit box.
