### ISSUE TITLE
svn.previousCommitsUser is too slow and has no restricted limit

### ISSUE THREAD

**Issue by chaitumanne** [JohnstonCode/svn-scm#1332]
The svn.previousCommitsUser command is too slow whenever we commit a message. Also, we can restrict the number of previous commits to display on commit that could improve the performance.

**Comment by JohnstonCode** [comment]
It seems that a limit is only applied if you are not using the `previousCommitsUser` configuration option. It would be nice to also limit the log by user functionality.
