### ISSUE TITLE
Feature: SVN Remote Status statusBar Icon

### ISSUE THREAD

**Issue by rwatts3** [JohnstonCode/svn-scm#135]
It would be nice to have a status bar icon display to show the user that remote updates are present. 
Running the command `svn status -u -q` would show us remote changes that are not currently updated in the project. 

Possibly adding a config setting for frequency x mins , and have the statusBar Icon display some signal showing project is updated, and show another with possibly the number of changes that are not within the project. 

[Current] | [10 Updates]

I am happy to do this, but would like some insight on what areas of the code this type pf functionality should go.

**Comment by edgardmessias** [comment]
To compare only revision number, we can use `svn info --xml -r HEAD` (<commit />)

To compare new commits, only need count log entry `svn log -r BASE:HEAD -q --xml`

**Comment by rwatts3** [comment]
Awesome.  

Could you give me some pointers on where to implement this in the code and I’ll give it a shot.

**Comment by JohnstonCode** [comment]
have a look at statusBar, svn, svnrepository

Follow the chain of stuff that gets the switch branch command to work. You wont need to deal with commands as its only going to update text.

**Comment by rwatts3** [comment]
perfect thank you

**Comment by edgardmessias** [comment]
I'll start working on it.

My idea:
* No update - `(brachicon) <brachname> (refreshicon)`
* With update - `(brachicon) <brachname> (refreshicon) <updatetext>`

On click `brachicon`, prompt switch branch, already done
On click `refreshicon`, run svn command: `svn update`

**Comment by rwatts3** [comment]
Nice work guys, this is an extremely useful feature, especially with big teams.

**Comment by johnjacobkenny** [comment]
Isn't it supposed to be `new commits` instead of `news commit`?

If so, I can send a PR once I get back home.

**Comment by JohnstonCode** [comment]
Yeah submit a PR
