### ISSUE TITLE
can i select different revisions for diff? (not with head, or base)

### ISSUE THREAD

**Issue by jhnyang** [JohnstonCode/svn-scm#1357]
Hi, first of all, thanks for useful extension
  
can i diff two different revisions which is not consecutive at subversion mode?
in explorer mode, there are 'select for compare' function so that i can choose any files for diff, but not in subversion mode.
At svn history menu, with right click, i can see some choices which are 'diff with base' and 'diff with head'
but i hope to see diff tab with the different revisions that i select.

in svn command it will like,
 "svn diff <file> -r <revision1212>:<revision1313>"

but i wanna see the diff result in edit page, not terminal 
thank you.

**Comment by jacobweber** [comment]
You could write a little script like this:
```
#!/bin/bash
code -d -w "${@: -2}" "${@: -1}"
```
and in your `~/.subversion/config` file, set `diff-cmd` to your script's path.

That way when you run `svn diff file1 file2` on the command line, it will open in a VS Code window.
