### ISSUE TITLE
Changes icons alway on

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#136]
Extension Version: 1.13.2

There are two icons appeared recently: changed with Head and changes with Base. There are two problems with them: they both have same icon, the same with git too. And they appear for files which do not belong to any svn working copy

**Comment by JohnstonCode** [comment]
Can you provide a screenshot please.

**Comment by Yanpas** [comment]
![image](https://user-images.githubusercontent.com/7345761/35701405-f6768cc8-07a6-11e8-9616-1f3904dab6ac.png)

**Comment by edgardmessias** [comment]
Que need check opened repositories, like Git.

Tomorrow I fix

**Comment by Yanpas** [comment]
Great, thanks!
