### ISSUE TITLE
New VS Code 1.56 update broke SVN Repository Icons

### ISSUE THREAD

**Issue by TMcKinley** [JohnstonCode/svn-scm#1382]
- VSCode Version: 1.56 (April 2021 Update)
- OS Version: Windows 10 Pro 20H2
- Extension Version: v2.13.5
- System Language: English
- SVN Version: v1.14.0

## Issue ##
The icons for the following quick commands are missing:
- Commit Changes
- Pick a previous commit message
- Refresh

Strangely the "Update Revision" icon is still there. Maybe related to the codicon changes they mentioned in the
[Release Notes](https://code.visualstudio.com/updates/v1_56#_extension-authoring)?
Additionally, I disabled all other extensions and restarted VS Code and confirmed it was still an issue. 
Finally, I also rolled back to VS Code v1.55.2 and confirmed that they were showing correctly in that version.

## Steps to Reproduce ##

1. Open VS Code
2. Switch to the Source Control Tab
3. Icons next to the repository name/branch are missing

## SVN Output ##
```

```

## Screenshots ##
![2021-05-07 13_51_18-Window](https://user-images.githubusercontent.com/511627/117507765-5d1cd000-af3c-11eb-98ef-26f6e1a5cd5f.jpg)

**Comment by JohnstonCode** [comment]
Unable to replicate
![image](https://user-images.githubusercontent.com/10222719/118392485-e49bca80-b631-11eb-8736-16c1ffd2f2a3.png)
