### ISSUE TITLE
Plaintext Password

### ISSUE THREAD

**Issue by mpearon** [JohnstonCode/svn-scm#1383]
- VSCode Version: `1.56.0-insider`
- OS Version: `Windows 10 `
- Extension Version: `v1909 build 18363.1500`
- System Language: `English`
- SVN Version: `1.12.2 (r1863366)`

## Issue ##
Username and password committed to Windows Event Log (Windows Logs \ Security) in plaintext
`%SystemRoot%\System32\Winevt\Logs\Security.evtx`

## Steps to Reproduce ##

1. Commit any change to any file

## SVN Output ##
```
N/A
```

## Event Log Output ##
```
"C:\Program Files\TortoiseSVN\bin\svn.exe" stat --xml --no-ignore --ignore-externals --username REDACTED --password REDACTED --config-option config:auth:password-stores= --config-option servers:global:store-auth-creds=no --non-interactive
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/7157790/117508271-ebe61880-af4d-11eb-9471-fefea6923728.png)

**Comment by JohnstonCode** [comment]
Is there a way to do the same command without the username and password without using svn ssh?

**Comment by pgit** [comment]
This happens on Linux as well, "svn stat" with username and password visible in "ps" output. This was even without doing a commit.
I think the password should never be part of the command line, at least not without a big fat red warning.

**Comment by mpearon** [comment]
@JohnstonCode - This behavior does not appear to be present in the current version.  Can you confirm that this was addressed?
