### ISSUE TITLE
Some things to do to improve the code

### ISSUE THREAD

**Issue by edgardmessias** [JohnstonCode/svn-scm#140]
Some things to do to improve the code:

- [x] Rework run commands in `repository.ts`, like in git (Better for capture events) #141 
- [x] Rework `commands.ts`, disallow usage of `this.repository.repository` #143 
- [x] Show progress in the editor for some commands (update, commit, switch branch)
- [x] Rework `svn.ts` to every accepty proccess options (Current `CpOptions`)
- [x] Fix commands palette (Add all to `package.json`)
- [x] More usage of disposables
- [x] More usage of placeholders
- [x] Optimize `getStatus`, to use cache, and update only changed file (Update all on repository change)

**Comment by edgardmessias** [comment]
@JohnstonCode, your opinion?

**Comment by JohnstonCode** [comment]
Yeah, all valid points.

The codebase has become very ugly with the rapid development. Might be useful separating into individual issues so we can assign ourselves to work on them and not be tripping over each other.

**Comment by edgardmessias** [comment]
Yes, good idea.

Let's use this as topic and discussion

**Comment by edgardmessias** [comment]
Added branch for rework: https://github.com/JohnstonCode/svn-scm/tree/rework

**Comment by johnjacobkenny** [comment]
If there's something suitable for a newbie, please let me help out. Thanks!

**Comment by edgardmessias** [comment]
@JohnstonCode, one item done.

**Comment by JohnstonCode** [comment]
@edgardmessias good work.

Need me to do any?

**Comment by edgardmessias** [comment]
At the moment, if you can perform tests, to see if something went unnoticed.

**Comment by JohnstonCode** [comment]
Okay, ill test everything tomorrow.

**Comment by edgardmessias** [comment]
@JohnstonCode, done.

**Comment by JohnstonCode** [comment]
`command 'svn.revertSelectedRanges' not found`

**Comment by JohnstonCode** [comment]
Don't think its part of this but open file head possible change the title to add "-HEAD" or something. Might be a pain to do.

**Comment by JohnstonCode** [comment]
Code looks so much better now

**Comment by edgardmessias** [comment]
@JohnstonCode, good morning, I will check the issues.

**Comment by edgardmessias** [comment]
To add "-HEAD" in title, we can use [TextDocumentContentProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametextdocumentcontentprovideraspan-classcodeitem-id465textdocumentcontentproviderspan)

**Comment by edgardmessias** [comment]
@JohnstonCode, the command `svn.revertSelectedRanges` need a proposed api, I will add alert to this case.

**Comment by JohnstonCode** [comment]
Okay, cheers. 

Let me know when the branch is ready and ill merge it

**Comment by edgardmessias** [comment]
@JohnstonCode, fixed the `svn.revertSelectedRanges`, if not has support, not show.

**Comment by JohnstonCode** [comment]
Okay ill merge it now

**Comment by edgardmessias** [comment]
OK, after merge, I will work on #145

**Comment by JohnstonCode** [comment]
Leave with that john see if he can put it together

**Comment by edgardmessias** [comment]
Merged

**Comment by JohnstonCode** [comment]
That's all merged in and also the news stuff is merged and fixed
