### ISSUE TITLE
Action buttons in vscode's workspace are very small

### ISSUE THREAD

**Issue by sameerthekhans** [JohnstonCode/svn-scm#1412]
- VSCode Version: 1.56.1
- OS Version: Linux x64 (Ubuntu)
- Extension Version: 2.13.6
- System Language: English
- SVN Version: 1.10.2

## Issue ##
Action buttons in vscode's workspace are very small
## Steps to Reproduce ##

1.Create vscode workspace and open multiple svn projects

## Screenshots ##
Single project
![image](https://user-images.githubusercontent.com/25663556/120319694-eab2cc00-c2fe-11eb-9829-75f85483fa27.png)

Multiple projects in vscode's workspace
![image](https://user-images.githubusercontent.com/25663556/120319794-07e79a80-c2ff-11eb-9873-5b00f87e7961.png)

**Comment by JohnstonCode** [comment]
Unable to replicate
![image](https://user-images.githubusercontent.com/10222719/120338003-b8e43a00-c2eb-11eb-82ff-94b6e7880445.png)


Can you paste the content of "View >> Output >> OUTPUT >> SVN"?

**Comment by sameerthekhans** [comment]
Closing this because this is not related to SVN, This is the issue of VSCode [(found here)](https://github.com/microsoft/vscode/issues/123036) and thankfully it is resolved in 1.56.2
