### ISSUE TITLE
Config options to configure status count

### ISSUE THREAD

**Issue by stephanedr** [JohnstonCode/svn-scm#144]
- VSCode Version: 1.19.3
- OS Version: Windows 7
- Extension Version: 1.15.0
- System Language: English US

The number of pending changes displayed with the source control icon should not include the number of items reported in the EXTERNAL section.

For me the same applies to UNVERSIONED, though it can be a user preference.
Maybe an option would be needed here?

**Comment by JohnstonCode** [comment]
Hi @stephanedr 

Good suggestion and yes a config option would be useful.

**Comment by edgardmessias** [comment]
@JohnstonCode, wait for rework first.
@stephanedr, good idea.

**Comment by edgardmessias** [comment]
Done with #151
