### ISSUE TITLE
Give commit log tab a proper title

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#145]
Currently, show commit message creates a new document with a title of Untitled-1

**Comment by johnjacobkenny** [comment]
I'll give this a try. Thanks!

**Comment by JohnstonCode** [comment]
@johnjacobkenny Just work in master the rework branch should affect this

**Comment by edgardmessias** [comment]
For this, use [TextDocumentContentProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametextdocumentcontentprovideraspan-classcodeitem-id465textdocumentcontentproviderspan)

Use a custom schema, like `svn-provider`, and in `query`, set a `action` to `log`

**Comment by johnjacobkenny** [comment]
I'm not making much progress. Do I create another file similar to `SvnContentProvider`?

**Comment by edgardmessias** [comment]
@johnjacobkenny, I working on this.

**Comment by johnjacobkenny** [comment]
Oh okay!

**Comment by edgardmessias** [comment]
Done with #147
