### ISSUE TITLE
SVN does not refresh on branch switch

### ISSUE THREAD

**Issue by unterwegsmitkeks** [JohnstonCode/svn-scm#146]
- VSCode Version: 1.19.3
- OS Version: Windows 10 Pro 1709
- Extension Version: 1.15.0
- System Language: german

Steps to Reproduce:

1. click branch name (bottom left corner)
2. click "+ create new branch" and finish creation
3. click branch name (bottom left corner)
4. click on created branch
5. loading indicator shows but when it stops, the branch name in the bottom left has not changed
6. use Tortoise repo browser to confirm the branch switch was successful
7. refresh SVN manually in VSCode -> the branch name in the bottom left is now correct

**Comment by edgardmessias** [comment]
@JohnstonCode, you can test o `rework`?

**Comment by edgardmessias** [comment]
@unterwegsmitkeks, please, test with version 1.16.0

**Comment by unterwegsmitkeks** [comment]
@edgardmessias It works with version 1.16.0
Thanks, you guys are awesome :)
