### ISSUE TITLE
[Bug] SCM vanishes when opening a non-repository file.

### ISSUE THREAD

**Issue by Guema** [JohnstonCode/svn-scm#149]
- VSCode Version: 1.9.3
- OS Version: Win x64
- Extension Version:  1.16.0

Steps to Reproduce:

1. open a SVN repos folder in vscode. The ext will be enabled
2. while keeping the folder open, open any file that is not in the repository, like, for exemple, User Settings. SCM vanishes.

**Comment by JohnstonCode** [comment]
@Guema not able to replicate this.

Are you getting anything strange in the output window?

**Comment by Guema** [comment]
No other strange things.
When loading User settings, "SOURCE CONTROL" things just disappear, letting the sentence "There are no active source control providers".
To be more accurate, when this bug occur, the "..." menu still offer the svn commands of the ext.
But all repo changes are gone. Until reload/relaunch.

**Comment by JohnstonCode** [comment]
@edgardmessias you able to replicate this.

Iv tried opening the User Settings and opening random files I have that aren't in my repos.

**Comment by edgardmessias** [comment]
@JohnstonCode , I could not replicate here.

@Guema, you can send printscreen after and before?

**Comment by Guema** [comment]
![pouet](https://user-images.githubusercontent.com/8943532/35929997-13f5bdee-0c31-11e8-875d-b9e6646e8666.gif)

**Comment by edgardmessias** [comment]
@Guema , same problem with another workspace? You can check the setting `"svn.enabled": true`

**Comment by Guema** [comment]
@edgardmessias tried both, same problem.

**Comment by Guema** [comment]
Hi ^^

So my problem still here after vscode 1.20 and os reboot.

I'm investigating a bit, and here is what i get at vscode launch in dev console.
It may be known or not related.

![2018-02-08 09_44_43-clipboard](https://user-images.githubusercontent.com/8943532/35963442-00655ba2-0cb5-11e8-86ac-4075625b16d3.png)

I reproduced the bug to see what it do.
The errors are not instantly thrown when the bug occur. I must wait ~5 sec to see messages appear on the console.
I see you the 2 messages it prints, note that this two messages literally spam my console for number and number of lines. and they seems to be called in a random order.

![2018-02-08 09_56_37-clipboard](https://user-images.githubusercontent.com/8943532/35963889-79b5fe7a-0cb6-11e8-9f59-fa9010ce0dd4.png)

Thanks for your time and attention.

Guema

**Comment by edgardmessias** [comment]
I did everything and I can not reproduce here.

The stranger is the line: `... switch: --enable-proposed-api undefined`
My tests show: `... switch: --enable-proposed-api johnstoncode.svn-scm`

**Comment by johnjacobkenny** [comment]
I am facing the same issue on my work computer.
- VSCode Version: 1.20.0
- OS Version: Win x64 (same)
- Extension Version: 1.16.0 (same)

**Comment by JohnstonCode** [comment]
Possible a windows issue.

I will have a look tonight when I have access to a windows machine.

**Comment by johnjacobkenny** [comment]
I am getting an svn: E155007: '<redacted>\AppData\Roaming\Code\User\settings.json' is not a working copy in the svn output window.

**Comment by edgardmessias** [comment]
I found the problem.

**Comment by edgardmessias** [comment]
The function `hasSupportToDecorationProvider` always returned true.

The coverage show usage https://codecov.io/gh/JohnstonCode/svn-scm/src/c1390f9a188c49c4dcfd314e915f643f3e16f611/src/decorationProvider.ts

Correct is not usage.

**Comment by Guema** [comment]
The problem is still here for me at 1.17.0

**Comment by edgardmessias** [comment]
Console log?

**Comment by JohnstonCode** [comment]
Confirmed this is a windows only bug.

Debugging now

**Comment by Guema** [comment]
Sorry, cannot provide more details right now as this problem occur on my job's pc. will try to replicate it on my own pc later

**Comment by edgardmessias** [comment]
How?

**Comment by JohnstonCode** [comment]
Just working on my widnwos machine it happens.

**Comment by edgardmessias** [comment]
I my windows not happens

**Comment by JohnstonCode** [comment]
[this line is the issue](https://github.com/JohnstonCode/svn-scm/blob/d262c6646ed786e2d8f4e18d8d2b572c404de2f2/src/svnContentProvider.ts#L90)

For some reson repositroy is true for documents that arnt in the repository.

**Comment by JohnstonCode** [comment]
[This check is returning true](https://github.com/JohnstonCode/svn-scm/blob/d262c6646ed786e2d8f4e18d8d2b572c404de2f2/src/model.ts#L265)

**Comment by JohnstonCode** [comment]
@Guema @johnjacobkenny 

Do you have vs code and your project on a different drive?

**Comment by JohnstonCode** [comment]
Seems that because vs code is installed on my C:/ drive and my work is on my D:/ that `path.relative` just returns the path for the files being passed my my case `c:\Users\chris\AppData\Roaming\Code\User\settings.json`

This then passed the check of `!/^\.\./.test(relativePath)`

**Comment by johnjacobkenny** [comment]
Yes, VS Code was installed normally without changing the drive. My project is in D drive. I can check again on Monday by checking out to somewhere in C drive.

**Comment by JohnstonCode** [comment]
It fine figured it out

**Comment by JohnstonCode** [comment]
Could use [this](https://nodejs.org/api/path.html#path_path_sep) to see fi the paths are on the same drive

**Comment by JohnstonCode** [comment]
@edgardmessias pro level fix

`if (liveRepository.repository.workspaceRoot.split(path.sep)[0] !==  hint.fsPath.split(path.sep)[0]) {
          return undefined;
        }`

**Comment by Guema** [comment]
Yes, im in this case too, vscode is on C:/ and projects on D:/
will try asap and see if it is solved, but should be good 👍
good job and thanks guys

**Comment by johnjacobkenny** [comment]
It works correctly for me now. Thanks!!

**Comment by Guema** [comment]
fix confirmed for me too. good job and thanks !
