### ISSUE TITLE
Not all branches are detected

### ISSUE THREAD

**Issue by mattiasthalen** [JohnstonCode/svn-scm#1507]
- VSCode Version: 1.59.1
- OS Version: Windows 10 Enterprise 1909
- Extension Version: 2.13.6
- System Language: English
- SVN Version: 1.14.1

## Issue ##
SVN structure:
`/branches/...`
`/staging`
`/trunk`

Branch detection only working for `/trunk` & the subfolders of `/branches/...` but not for `/staging`

**Comment by JohnstonCode** [comment]
Can you try setting `svn.layout.branchesRegex` to `(branches|staging)(\/.*)?`?

**Comment by mattiasthalen** [comment]
That solved it, thanks!
