### ISSUE TITLE
Cannot use svn plugin

### ISSUE THREAD

**Issue by maxiaogood** [JohnstonCode/svn-scm#1516]
Issue Type: <b>Bug</b>

When vscode is opened, the SVN plug-in disappears after being displayed on the sidebar.Did not report any errors about svn and I am sure that the path setting of svn is correct.

Extension version: 2.13.6
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (11.37GB free)|
|Process Argv|--crash-reporter-id ff93cb9a-af8e-407d-891b-1f6cb4bef270|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwtct:30364498
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedt:30364666
pythonvspyt187cf:30365362
pydsgsc2:30361791
vscus224cf:30358040
vssid140:30363603

```

</details>

**Comment by boesi** [comment]
I have the same problem. For me it started after I updated my Ubuntu WSL to version 2 and moved the workspace folder to the virtual hard drive. If I leave the workspace in the old place, the SVN plugin still works. 

I think the cause is TortoiseSVN because it also can't access the files in \\wsl$\Ubuntu\...... In Ubuntu I have svn installed, I can update and commit there, but the integration with VSCode is a big productivity boost.
