### ISSUE TITLE
Ignore specific external in project

### ISSUE THREAD

**Issue by mrvkino** [JohnstonCode/svn-scm#1524]
- VSCode Version: 1.60.2
- OS Version: 11.6 (20G165)
- Extension Version: v2.13.6
- System Language: English
- SVN Version: 1.8.13 (r1667537)

## Issue ##
I have about 60 or so externals on a remote project (using the ssh remote extension) and it is causing the extension to be slow at updating the status of all the externals. I am trying to find a way to filter the list of externals being shown in the "Source Control" side view to the one I need.

I am using the `"svn.detectExternals": false,`for the time being, but I would like to see some of them since not all are static externals.

I tried using the `"svn.ignoreRepositories"` with full path similar to `/path/to/folder/containing/externals/*` since I want ot remove more than 20 externals folders. I also tried `"svn.multipleFolders.ignore"`.

None of them where able to shorten the list of external in the "Source Control` view.

I am sure there is a way and that I am not the first one to do this. Looking through the issues helped me in my experiments, but nothing  seemed to worked.

This is the list I want to shorten and make manageable.

<img width="601" alt="source_control_view_externals jpg" src="https://user-images.githubusercontent.com/279511/134550991-6b7e0a68-46fd-4211-b5fe-f414e9cc95ef.png">

Thanks

**Comment by Zevensoft** [comment]
When listing the externals in the ignoreRepositories option in the current (2.15.2) version you need to specify both the absolute path with a trailing slash and without the trailing slash. Each path is treated as a string and must match *exactly*, but sometimes the path has a trailing slash internally.
