### ISSUE TITLE
VSCode Title bar doesn't show (BASE) or (HEAD) string since VSCode 1.61

### ISSUE THREAD

**Issue by coeyes** [JohnstonCode/svn-scm#1537]
- VSCode Version: 1.61
- OS Version: Windows 10 1909
- Extension Version: 2.14.0
- System Language: Korean
- SVN Version: 1.14.1

## Issue ##
VSCode title bar doesn't show (BASE) or (HEAD) string since VSCode Ver 1.61

## Steps to Reproduce ##

1. select any modifed file.
2. check title bar (screenshot).

## SVN Output ##
```
```

## Screenshots ##
![2021-10-08 18_50_59-vario_ahklib ahk - scripts - Visual Studio Code](https://user-images.githubusercontent.com/260646/136536691-67acf744-42b5-4f17-8ea8-8b89d2d94644.jpg)

**Comment by JohnstonCode** [comment]
That sounds like a vs code issue. I would raise it there.
