### ISSUE TITLE
Revert to the old version

### ISSUE THREAD

**Issue by Vincent0706** [JohnstonCode/svn-scm#1541]
Sometimes, I want to revert the project to the old version. But, I found this plug-in don't have this function.
This function like this:
![image](https://user-images.githubusercontent.com/82581024/141771736-0aebf56a-1cbd-466a-9b24-c1313561eeb7.png)

**Comment by Vincent0706** [comment]
I found we can use `svn update -r  + version number` command to update the project version. But I still hope this plug-in can give a interface.

**Comment by lizheng2018CC** [comment]
In 2023, they still do not solve this problem, kidding?

**Comment by Vincent0706** [comment]
Sorry, I find out that nobody reply to me at that time, and I almost forgot this issue. Now I will close the issue.

**Comment by lizheng2018CC** [comment]
现在vscode上的svn插件有这个功能了吗，我是最近才开始用的，确实也没发现这个功能。我好奇，回退版本不是一个很常用的功能吗
