### ISSUE TITLE
total of modified files does not appear on the icon

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#1551]
Just one thing is strange with the new release.
Now the total of modified files does not appear on the icon (only the clock still remain)

![image](https://user-images.githubusercontent.com/10075509/145376841-7417feb5-d71a-4552-a657-6c1ffb8d0bea.png)

_Originally posted by @slolo2000 in https://github.com/JohnstonCode/svn-scm/issues/1542#issuecomment-989707593_

**Comment by shahzebgit** [comment]
Working fine for me here
![modified](https://user-images.githubusercontent.com/51449693/145406785-3d4eaefe-508f-4f21-9871-57c02d172f15.jpg)

**Comment by yyj961010** [comment]
![image](https://user-images.githubusercontent.com/42398073/146338243-f11af41e-09ee-431c-b669-59415ecb39bb.png)
I have the same problem

**Comment by art40100** [comment]
Restarting VSCode seems to fix it temporarily, after some time the clock icon is shown only and does not go away.

**Comment by IperStan** [comment]
I have the same issue reported in the wrong thread: https://github.com/microsoft/vscode/issues/140408

Restarting VSCode seems to work sometimes, sometimes not

**Comment by slolo2000** [comment]
I have done a test by disabling SVN extension, reload extensions, enable it again and it seems to unlock the problem. 
![image](https://user-images.githubusercontent.com/10075509/148785510-abf12398-15db-4faa-b79c-ffcaa47122b1.png)

But, if I restart Visual Studio Code, the problem comes again.

**Comment by korandcom** [comment]
Having the same issue. VS Code restart temporary fix the problem but it comes again after some time.
