### ISSUE TITLE
SVN path not finded, despite setting my env var.

### ISSUE THREAD

**Issue by ChokmahBinah** [JohnstonCode/svn-scm#1555]
- VSCode Version: 1.63.2
- OS Version: Windows_NT x64 10.0.19044
- Extension Version: v2.15.2
- System Language: French
- SVN Version: 1.14.1

## Issue ##
Visual Studio Code don't find SVN excutable.

## Steps to Reproduce ##

1. Start Visual Studio Code
2. That's all.

## SVN Output ##
```
Svn installation not found.
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/33164632/146636135-7de2dcd6-0ee5-4335-8716-9f83a115039a.png)

My environment variable is good imo :
![image](https://user-images.githubusercontent.com/33164632/146636159-b463181e-775c-4129-a2ce-0ba6795944ff.png)

Thanks in advance for your help :)

**Comment by slolo2000** [comment]
It works fine for me by my path is (without any space): "D:\\Dvpt\\Apache-Subversion\\"

Otherwise you can try to add your path into Settings:
![image](https://user-images.githubusercontent.com/10075509/148790392-9beab374-e8e0-417c-a0ed-a4efeae808b8.png)

"svn.path": ""D:/Dvpt/Apache-Subversion/"
