### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by modbw** [JohnstonCode/svn-scm#1560]
- VSCode Version: 1.64.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19044
- Extension Version: 2.15.2 (2021-12-09)
- System Language: English
- SVN Version: 1.14.0

## Issue ##
Using current insiders build of vscode results in a missing dependency from svn-scm. This happens for me in a local and a SSH remote workspace.

## Steps to Reproduce ##
1. Install current vscode-insiders
2. Install svn-scm

## Screenshots ##
![image](https://user-images.githubusercontent.com/4498104/151790814-ce788165-d16e-456c-af18-04a5120d5d7c.png)

**Comment by metal571** [comment]
1.64.0 is now stable, so this is now widespread among any user running extension 2.15.2.

**Comment by waderoberts123** [comment]
Is there a workaround? This seems to make the extension unusable for anyone who updates to the latest version of VS Code.

**Comment by metal571** [comment]
> Is there a workaround? This seems to make the extension unusable for anyone who updates to the latest version of VS Code.

You can downgrade to 1.63.2 using links on this [page](https://code.visualstudio.com/updates/v1_63).

You will also need to set update.mode to "none" in settings.json to prevent automatic updates until this extension is fixed.

**Comment by slolo2000** [comment]
Hello, same problem for me.
I have just updated Visual Studio Code to the last version 1.64 and I have the same error message.

- VSCode Version: 1.64.0
- OS Version: Windows 10 Pro version 21H2
- Extension Version: 2.15.2
- System Language: French
- SVN Version: 1.14.1

**Comment by tilman22** [comment]
> Is there a workaround? This seems to make the extension unusable for anyone who updates to the latest version of VS Code.

You can also just download and run the portable version, for Linux 64bit this one: https://update.code.visualstudio.com/1.63.2/linux-x64/stable

**Comment by aswinkumar863** [comment]
Back to back dependency issue, then [jschardet](https://github.com/JohnstonCode/svn-scm/issues/1542) now `iconv-lite` :(

**Comment by slolo2000** [comment]
Thank you very much for this quick fix.
It works perfectly now.

**Comment by MarcoScaletta** [comment]
Hello,
same problem here. 
I tried to downgrade to vscode version 1.63.2.
I tried to install different version of svn-scm:
- 2.15.0: jschardet is missing
- 2.15.1: jschardet is missing
- 2.15.2: no error, the svn panel shows the right information, but the panel for the source control is empty (no content) although the counter of changes on the icon is working:
<img width="655" alt="Screenshot 2022-02-04 at 10 19 57" src="https://user-images.githubusercontent.com/17848034/152503783-d2e4c309-8217-4fc8-b549-68a2e8b0ca65.png">
- 2.15.3: same as 2.15.2.

**Comment by jvanoosterom** [comment]
problem still there with version 2.15.3

**Comment by slolo2000** [comment]
Really strange because its works well on my computer.
I even recovered the file counter

I have uninstall and reinstall the extension. Perhaps it helps.

![image](https://user-images.githubusercontent.com/10075509/152509841-8dc9f4b5-64e8-41d6-9406-273c1eb5242c.png)

**Comment by MarcoScaletta** [comment]
I tried also to uninstall and reinstall the latest version.
I tried to restart the Mac.
Still nothing

These are the information about vscode.

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z (1 mo ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

**Comment by jvanoosterom** [comment]
yes works now, 
Thank you!

**Comment by slolo2000** [comment]
@MarcoScaletta have you tried with the last version of Visual Studio Code 1.64 now that the extension has fix the "iconv-lite" problem?

**Comment by MarcoScaletta** [comment]
It works! Thanks!

I realised I started writing the first comment before the fix, but posted afterwards :)

**Comment by slolo2000** [comment]
Nice to hear it!

![image](https://user-images.githubusercontent.com/10075509/152543457-d5c1b908-0709-4d17-9d5b-3aca4b671e0c.png)

But contrary to what I thought, the files counter still doesn't work well at the moment.
See issue #1551
