### ISSUE TITLE
Appears to hang in 2.15.3

### ISSUE THREAD

**Issue by jimbobmcgee** [JohnstonCode/svn-scm#1563]
- VSCode Version: 1.64.2
- OS Version: Microsoft Windows NT 10.0.19044.0
- Extension Version: 2.15.3
- System Language: English
- SVN Version: 1.11.1-SlikSvn

## Issue ##
Appears to hang, possibly since upgrade to 2.15.3
VSCode remains responsive, but no source-control operations are shown
Source control icon shows blue clock; disappears if SVN extension disabled/reloaded
Source control panel has marquee progress bar; disappears if SVN extension disabled/reloaded
Extension panel show timer icon for SVN extension; reports a number of uncaught errors
Uncaught errors appear to all be *Cannot read property 'fire' of undefined*.
Does not appear to do so in 2.15.2

## Steps to Reproduce ##
Apologies for the noddy repro -- I haven't nailed down why it is happening, just that it *is* happening.  Will try to flesh out, as I try new things.

1. Be me
2. Open VSCode
3. Have two separate windows with various files in various repos 
4. ...
5. Profit?

(Not sure if specific to multiple repos or multiple windows -- have one window mostly working in a single repo/workspace; have another window not working with various scratch files in various repos)

## SVN Output ##
```
Using svn "1.11.1-SlikSvn" from "C:\Program Files\SlikSvn\bin\svn.exe"
[trunk]$ svn info --xml
[trunk]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[trunk]$ svn log -r1:HEAD --stop-on-copy --xml --with-all-revprops --verbose
[trunk]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[trunk]$ svn info --xml
[trunk]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[trunk]$ svn info --xml
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/12205864/154616060-d4aa730a-c48d-40b5-ad83-14d1c9a4fc4b.png)

**Comment by jimbobmcgee** [comment]
Might be duplicate of #1538

**Comment by SuporteSysrs01** [comment]
I'm facing the same issue, my extension is reporting the same error "Cannot read property 'fire' of undefined", and the blue clock appears to hang forever. It was working fine before some updates.

> Might be duplicate of #1538
I don't think it is, as I have only one working directory.
