### ISSUE TITLE
Cannot get svn diff with Base 

### ISSUE THREAD

**Issue by Boundw** [JohnstonCode/svn-scm#1568]
- VSCode Version:1.65.2
- OS Version:Windows10
- Extension Version:2.15.3
- System Language:EN
- SVN Version:2.15.3

Issue 
1) Open a file in VSCode
2) Open the SVN extension on the left
3) Right click on a history line
4) Click 'SVN Diff with Base'

Expected: Shows the differences between that revision and the latest checked in SVN code
Actual: Error 'Error running command svn.itemlog.openDiffBase: unknown path. This is likely caused by the extension that contributes svn.itemlog.openDiffBase.'

teps to Reproduce

1) Open a file in VSCode
2) Open the SVN extension on the left
3) Right click on a history line
4) Click 'SVN Diff with Base'

SVN Output

Error running comand svn.itemlog.openDiffBase: unkown path

Screenshots 
![下载](https://user-images.githubusercontent.com/43398986/161888540-dacbfeef-dfd8-41ba-ac9f-18d2f908cca4.png)

**Comment by jmatsuzawa** [comment]
I got the same error.

**Comment by JohnnyElvis** [comment]
Same here...any idea how to work around problem?

**Comment by JohnnyElvis** [comment]
Ok, problem seems to be between chair and keyboard. You must have a base first to compare against it. It would help to change the error to "BASE does not exist"
