### ISSUE TITLE
No prompt to input username/password, all commands thus fail

### ISSUE THREAD

**Issue by Zodiannok** [JohnstonCode/svn-scm#1569]
- VSCode Version: 1.66
- OS Version: macOS Monterey 12.3.1
- Extension Version: v2.15.3
- System Language: English
- SVN Version: 1.14.0 (r1876290)

## Issue ##
There is no way to input password for my SVN connection. Reading other discussions, the expected behavior seem to be that a prompt window would popup when VSCode is opened. But this didn't happen. And thus all commands that require connection to server would fail.

## Steps to Reproduce ##

1. Open VSCode
2. Run commands that require server connection, such as Open Changes with HEAD
3. SVN command fails to execute

## SVN Output ##
(URL and filenames replaced with _***_)

[client]$ svn list _***_ --xml
[client]$ svn: E170013: Unable to connect to a repository at URL 'svn+ssh://_***_'
[client]$ svn: E210002: To better debug SSH connection problems, remove the -q option from 'ssh' in the [tunnels] section of your Subversion configuration file.
[client]$ svn: E210002: Network connection closed unexpectedly
[client]$ svn info --xml _***_
[client]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[client]$ svn: E170013: Unable to connect to a repository at URL 'svn+ssh://_***_'
[client]$ svn: E210002: To better debug SSH connection problems, remove the -q option from 'ssh' in the [tunnels] section of your Subversion configuration file.
[client]$ svn: E210002: Network connection closed unexpectedly

**Comment by hsxrcn** [comment]
I had the same problem
VSCode Version: 1.71
OS Version: macOS  M1 Monterey 12.5.1  
System Language: English
SVN Version: 1.14.2 (r1899510)

**Comment by hsxrcn** [comment]
> 

My problem has been solved,My problem is with the SVN version.After replacing the SVN version, the above problem occurred. I entered the "svn ls" input in the directory terminal,It gives you the choice R (reject), T (accept temporarily), or P (accept permanently)，then I choose P, then you will be prompted to enter the computer user password and SVN account password. It good job.

**Comment by hsxrcn** [comment]
> * VSCode Version: 1.66
> * OS Version: macOS Monterey 12.3.1
> * Extension Version: v2.15.3
> * System Language: English
> * SVN Version: 1.14.0 (r1876290)
> 
> ## Issue
> There is no way to input password for my SVN connection. Reading other discussions, the expected behavior seem to be that a prompt window would popup when VSCode is opened. But this didn't happen. And thus all commands that require connection to server would fail.
> 
> ## Steps to Reproduce
> 1. Open VSCode
> 2. Run commands that require server connection, such as Open Changes with HEAD
> 3. SVN command fails to execute
> 
> ## SVN Output
> (URL and filenames replaced with _***_)
> 
> [client]$ svn list _***_ --xml [client]$ svn: E170013: Unable to connect to a repository at URL 'svn+ssh://_***_' [client]$ svn: E210002: To better debug SSH connection problems, remove the -q option from 'ssh' in the [tunnels] section of your Subversion configuration file. [client]$ svn: E210002: Network connection closed unexpectedly [client]$ svn info --xml _***_ [client]$ svn stat --xml --no-ignore --ignore-externals --show-updates [client]$ svn: E170013: Unable to connect to a repository at URL 'svn+ssh://_***_' [client]$ svn: E210002: To better debug SSH connection problems, remove the -q option from 'ssh' in the [tunnels] section of your Subversion configuration file. [client]$ svn: E210002: Network connection closed unexpectedly
> 
> ## Screenshots

I entered the "svn ls" input in the directory terminal,It gives you the choice R (reject), T (accept temporarily), or P (accept permanently)，then I choose P, then you will be prompted to enter the computer user password and SVN account password.
