### ISSUE TITLE
Feature : Patch Apply

### ISSUE THREAD

**Issue by rwatts3** [JohnstonCode/svn-scm#157]
Proposal to Apply Patch files to a project.

**Use Case**
- Dev A patches his files for review then saves them on a shared drive or forwards to Dev B
- Dev B then applies the patched file to his project to get a working copy of Dev A's patch.

**Things to Consider**
- A setting in vscode to allow a default directory to pull patches from
- A prompt to allow the user to select a patch file from the above mentioned directory
- A prompt to allow the user to choose a patch file from any directory
- Handling conflicts. When applying patches sometimes a conflict can occur, and I believe generally svn will save .rej files throughout the project on various conflicts.
- We will need to consider a stepped popup workflow for reviewing and correcting conflicts via the gui vs. just bailing and letting the .rej files flow through the project (I experienced this recently when applying a patch via the terminal). 

Please let me know your thoughts and if this type of feature would even be a high demand item.

**Comment by JohnstonCode** [comment]
Patching is not something i do in my dev workflow.

But i can see its use.

This would be good project to get started on doing GUI stuff. [This extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) has a nice gui window it uses for settings.

**Comment by edgardmessias** [comment]
I am working on patch for current or selected files.

**Comment by rwatts3** [comment]
Yes their GUI is nice, very clever way to do things. 
I can see that being useful for this use case, navigating through conflicts and the ability to resolve them.

**Comment by dfliess** [comment]
+1

**Comment by sameerthekhans** [comment]
Any update on this?
