### ISSUE TITLE
Cannot read properties of undefined (reading 'fire') on update

### ISSUE THREAD

**Issue by TobiasKrahn** [JohnstonCode/svn-scm#1583]
- VSCode Version: 1.71.2
- OS Version: Win10 21H2
- Extension Version: 2.15.5
- System Language: german
- SVN Version: 1.14.2

## Issue ##
The runtime throws "Cannot read properties of undefined (reading 'fire')" when I try to update a repository.
It seems that it's important, that the folder that is open in vscode must be a subdirectory of the trunk. Like .../trunk/frontend for example.

I debugged it quickly and it seems like there is just a .bind(this) missing while registering the watcher at
src\watchers\repositoryFilesWatcher.ts:54

## Steps to Reproduce ##

1. open a folder that is a subdirectory of the trunk
2. try to update
3. look at the runtime status of the extension

## SVN Output ##
```
[Frontend]$ svn update --ignore-externals
[Frontend]$ svn stat --xml --no-ignore --ignore-externals
[Frontend]$ svn info --xml
[Frontend]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[Frontend]$ svn stat --xml --no-ignore --ignore-externals
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/16705453/191521410-765dcd2d-a785-49e8-91cc-4fc72d766a66.png)

**Comment by wangyongxiao** [comment]
the same error

VSCode Version: 1.72.2
OS Version: Debian GNU/Linux 11  aarch64
Extension Version: 2.15.5
SVN Version: 1.14.1
