### ISSUE TITLE
Create a settings object 

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#159]
Create a config class that auto assigns all the possible config options to itself. This will remove some of the repetitive getting the config and checking values

**Comment by edgardmessias** [comment]
Maybe, we can update requeriments to VSCode 1.18.0, for use the [affectsConfiguration](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameconfigurationchangeeventaspan-classcodeitem-id1367configurationchangeeventspan) of workspace.onDidChangeConfiguration

**Comment by JohnstonCode** [comment]
Yeah ill up the version tonight.

**Comment by edgardmessias** [comment]
Base for use: https://github.com/eamodio/vscode-gitlens/blob/6c3716daf8d669fae5139c8e56713447bd55b542/src/configuration.ts
