### ISSUE TITLE
in  VsCode Commit change CheckBox Select All Not Work

### ISSUE THREAD

**Issue by AliSafa** [JohnstonCode/svn-scm#1590]
- VSCode Version: 1.74.0
- OS Version: win10
- Extension Version: 
- System Language: eng
- SVN Version:  don't know

## Issue ##
hi
when i write comment for commit
then click Ctrl+Enter
vscode show a list of changed files
but when i click Ok Button 
files not commit

## Steps to Reproduce ##

1.Change files
2.go to  Source Control Pane
3.Write Commit Comment
4.Ctrl+Enter
5.Be sure select All CheckBox Selected
6.Do not search for any phrase
7.Click OK Button
8.Don't send any Change to Server

When the number of changed files is large
It becomes very annoying
## SVN Output ##
No Thing

## Screenshots ##
![01](https://user-images.githubusercontent.com/19464475/207020723-23e71192-8363-40e0-86fa-d16eed68a992.png)

**Comment by yuusakuri** [comment]
I'm experiencing the same issue.

**Comment by rmnrdi** [comment]
I'm also experiencing the same issue. SVN shows all files checked, then I commit. 
Sometimes all files are committed, sometimes not.
Sometimes, they show as committed, then re-appear moments later.
