### ISSUE TITLE
Command 'svn...' not found.

### ISSUE THREAD

**Issue by simonebrunox** [JohnstonCode/svn-scm#1593]
VSCode Version: 1.74.3
    OS Version: macOS Ventura 13.1 
    Extension Version: v2.15.7
    System Language: it
    SVN Version: 1.14.2 

Issue

Hi,
after installed and configured the extension with my svn path (/opt/homebrew/bin/svn), i open my project, i see the svn icon on the left of visual studio code, but i can't use funcionallities.
I see errors when i click on svn-refresh, repositories, file history, can you help me?

Thank you

Screenshots
![Screenshot 2023-01-30 alle 15 00 29](https://user-images.githubusercontent.com/2202632/215498922-fe21e434-9065-49ef-8b28-e9a92648b7e0.png)
![Screenshot 2023-01-30 alle 14 59 59](https://user-images.githubusercontent.com/2202632/215498931-7efabd9e-30bf-4df8-91e7-80c14590a0fd.png)

**Comment by drticcz** [comment]
same here... when I add the svn path to the settings the extension crashes :(

**Comment by simonebrunox** [comment]
I found the solution, my working copy is too old while my svn client is 1.14.2, so i opened the project with Smart Svn (or other client) and migrated to recent version, now the plugin work.
Thank you

**Comment by jja08111** [comment]
I fixed by upgrading SVN version 1.7.* to 1.14.* Thanks!
