### ISSUE TITLE
Add repo-like path  error。 

### ISSUE THREAD

**Issue by xihumeijing** [JohnstonCode/svn-scm#1596]
- VSCode Version: 1.78.2
- OS Version: Darwin arm64 22.3.0
- Extension Version:v2.15.7
- System Language:中文Chinese
- SVN Version:1.14.2

## Issue ##
![image](https://github.com/JohnstonCode/svn-scm/assets/19543763/8fbd8e9c-e35a-44cf-a063-081bb0834a2f)
![image](https://github.com/JohnstonCode/svn-scm/assets/19543763/f984ceb5-f88c-4319-8b3a-e552a18316dc)

## Steps to Reproduce ##
tip: 运行命令 svn.repolog.addrepolike 错误: command 'svn.repolog.addrepolike' not found。这可能是由提交 svn.repolog.addrepolike 的扩展引起的。

settings.json:
 "svn.path": "/usr/local/bin/svn"

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by liquidnight2** [comment]
I have this problem, too.  
Linux Mint 21.1,   VisualStudio Code 1.80.1
    johnstoncode.svn-scm   v2.17.0  
> /usr/bin/svn  --version 
>     svn, Version 1.14.1 (r1886195)
