### ISSUE TITLE
svn.IgnoreRepositories not behaving like expected

### ISSUE THREAD

**Issue by JujuAT** [JohnstonCode/svn-scm#1597]
- VSCode Version: 1.78.2
- OS Version: Ubuntu 23.04
- Extension Version: 2.15.7
- System Language: English
- SVN Version:

## Issue ##
When adding a folder to the svn-IgnoreRepositories it is not ignored when the filepath contains **  i.e. "abc/**/def"
abc/123/def works though.

![image](https://github.com/JohnstonCode/svn-scm/assets/93029210/1fbf64d9-be6b-476e-93c0-58f5bcb3572a)

**Comment by JohnstonCode** [comment]
The `svn.IgnoreRepositories` config only accept file path it has no regex or string substitution capabilities.
