### ISSUE TITLE
Typo in SVN missing in $PATH message 

### ISSUE THREAD

**Issue by brunnerh** [JohnstonCode/svn-scm#16]
> SVN is not **avaialbe** in your $PATH

I suppose that should be *available*. Appears multiple times in the code, presumably due to copying.

**Comment by JohnstonCode** [comment]
Thanks @brunnerh 

Yes, that will be some sloppy copy paste on my part.

I will get it cleaned up

**Comment by csholmq** [comment]
Fixed in #15
