### ISSUE TITLE
Sidebar doesn't update when adding file to changelist

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#160]
I made some changes to a file, and then added that modified file to a changelist. It does not move down into the changelist in VS code UI until I press the refresh button at the top. It does get added in svn changelist though.

**Comment by johnjacobkenny** [comment]
I think this was an oversight on my part, or something which changed in recent updates, but this is working for me now. Could someone confirm?

**Comment by JohnstonCode** [comment]
Yeah, this was fixed as part of the latest release.
