### ISSUE TITLE
How to create a Tag

### ISSUE THREAD

**Issue by sampsonats** [JohnstonCode/svn-scm#1607]
I can't figure out how to create a Tag in Visual Studio Code with the SVN extension.

Can someone walk me through it?

**Comment by ssarna1** [comment]
Click "trunk" on the bottom left, then on the top a dropdown list should appear:
![obraz](https://github.com/JohnstonCode/svn-scm/assets/4578755/a7c6963b-06da-424e-bff1-fde3d353358a)
then, click on tag, and You should see "create new branch" button
![obraz](https://github.com/JohnstonCode/svn-scm/assets/4578755/60c5168d-2370-4d8b-b001-49cc4415e6f3)

That is the theory, in practice i don't see this button, either in branch nor tag:
![obraz](https://github.com/JohnstonCode/svn-scm/assets/4578755/069a33df-9b64-461d-8362-c3f832c6680f)

**Comment by sampsonats** [comment]
Works! Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ssarna1** [comment]
@JohnstonCode any chance of taking a look into this issue?
