### ISSUE TITLE
Unable to resolve conflicts on different drives

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#161]
Title says it all. Or else. we could have a right click option on the file and choose to mark as resolved manually.

**Comment by JohnstonCode** [comment]
There is a command on the ... menu that resolves conflicts. Is this what you are looking for?

**Comment by johnjacobkenny** [comment]
I think that is the one I was looking for. However that gives this as output in svn console
`svn resolve --accept working C:\d:\Projects\<redacted>`

**Comment by JohnstonCode** [comment]
Think it will be the different drive issue that was causing the extension to close when opening settings.

**Comment by JohnstonCode** [comment]
Ill have to have a look at this tonight when i have my machine with to hard drive.

**Comment by edgardmessias** [comment]
Fixed
