### ISSUE TITLE
svn.revertChange has a bug with "Cannot read properties of undefined (reading 'toString')"

### ISSUE THREAD

**Issue by LUOJI666** [JohnstonCode/svn-scm#1613]
- VSCode Version: 1.70.3/1.84.0
- OS Version: win7/win10
- Extension Version:2.17.0
- System Language: Chinese
- SVN Version: 1.14.5

## Issue ##
svn.revertChange has a bug with "Cannot read properties of undefined (reading 'toString')"

## Steps to Reproduce ##

1. use svn.revertChange of the key command to revert select range. report bug with "Cannot read properties of undefined (reading 'toString')"

## SVN Output ##

Paste here content of "View >> Output >> OUTPUT >> SVN"
```

## Screenshots ##
![bug](https://github.com/JohnstonCode/svn-scm/assets/54590697/efe8dc6d-e1f3-4e3c-980c-cf4ca5242ee0)

**Comment by MStachowicz** [comment]
Second this. Fix please :(
