### ISSUE TITLE
No diff for conflicted files

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#162]
Clicking on conflicted files in the source control sidebar does not do anything. At the least, it could open up the file normally where we could perform conflict resolution.

On a related note, the right click options for conflicted files `Open changes with BASE/HEAD` don't do anything.

**Comment by JohnstonCode** [comment]
Need to update the package.json to remove commands from conflicted files. Also need to update the Resource class to put open file as left click command

**Comment by johnjacobkenny** [comment]
If its suitable for a beginner I could look into it.

**Comment by JohnstonCode** [comment]
Yeah, nice first issue. Just need to look at the commands in the package.json and add checks for conflicts. Just reference the external check that are already there.

You will also need to edit the resource.ts and add a check for changes in the `get command()` function and return a open file command instead.

**Comment by JohnstonCode** [comment]
If you have any issue let me know.

**Comment by johnjacobkenny** [comment]
Is there any quick way to get a merge conflict in my testing repo? I'm not at all familiar with the available commands in svn.

**Comment by edgardmessias** [comment]
Checkout, edit one file and switch branch.
The file need are diff between branchs

**Comment by johnjacobkenny** [comment]
I don't know if it's something I'm doing wrong, but I chose switch branch and created a branch, but the next time I choose switch branch, I'm not able to see that created branch in the list of branches.

**Comment by johnjacobkenny** [comment]
I'm using a file:// repo on my disk. SVN console says `E200009: Could not list all targets because some targets don't exist` for repo/trunk, repo/branches, repo/tags
I tried creating those directories, still no progress.

**Comment by johnjacobkenny** [comment]
There might be some issue with the way I set up my repo. What steps did you take to initialize a local repo. I'm on linux btw.

**Comment by JohnstonCode** [comment]
I have used [this](https://www.guyrutenberg.com/2007/10/29/creating-local-svn-repository-home-repository/) guide before

**Comment by johnjacobkenny** [comment]
I'll try this again today evening.

**Comment by JohnstonCode** [comment]
Okay, let us know if you have any more issues.

**Comment by edgardmessias** [comment]
Fixed

**Comment by johnjacobkenny** [comment]
Is there any resource that can help in understanding the codebase better?

**Comment by edgardmessias** [comment]
@johnjacobkenny, Update the `README.md` with new config options

**Comment by johnjacobkenny** [comment]
Okay I'll do that in the evening!
