### ISSUE TITLE
Support for blame

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#163]
Is it possible to add a blame view?

**Comment by JohnstonCode** [comment]
Don't see why not.

**Comment by johnjacobkenny** [comment]
It would be nice to have the option to toggle the blame inline with the file, but I'm not sure how intensive that operation might be for the svn server.

**Comment by JohnstonCode** [comment]
I think the operation will be fine on the server.

My hopes are to try an put something together like [git lens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)

**Comment by edgardmessias** [comment]
Tips: To blame, we need execute two commands:
* `svn blame <file> --xml` to show revision number, author and date
* `svn log -r <revision> [-r <revision> ...] --xml` to show the last message

First need run blame, collect all revisions numbers and pass to log

**Comment by edgardmessias** [comment]
VSCode api:
* [window.createTextEditorDecorationType](https://code.visualstudio.com/docs/extensionAPI/vscode-api#window.createTextEditorDecorationType)
* [TextEditor.setDecorations](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditor.setDecorations) with [DecorationOptions[]](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DecorationOptions)

**Comment by hellboy81** [comment]
+ `infinity`

**Comment by lapo-luchini** [comment]
There seems to be a [different extension already](/BeauAgst/blamer-vs/) for that (but it fails for me currently with `svn: E170013`, while this extension is working fine on the same SVN address).
Could still be interesting to take a look / integrate / cooperate with.

**Comment by JohnstonCode** [comment]
@lapo-luchini Thanks for letting me know, wasn't aware this extension existed.

**Comment by BeauAgst** [comment]
Hey @lapo-luchini, if you have found a bug with [my extension](https://github.com/BeauAgst/blamer-vs/) could you please raise an issue explaining the problem, and I will take a look at it for you? Thanks!

**Comment by lapo-luchini** [comment]
@BeauAgst sure, I usually wait to have a proper debug before opening issues, but I can open a placeholder in the meanwhile. :)

**Comment by JohnstonCode** [comment]
Please use [blamer-vs](https://github.com/BeauAgst/blamer-vs/) for blame support

**Comment by MichaelSuen-thePointer** [comment]
> Please use [blamer-vs](https://github.com/BeauAgst/blamer-vs/) for blame support

Author of blamer-vs has stopped updating the project for years, several minor bugs remains unfixed and PRs not responded, please re-consider it.
