### ISSUE TITLE
SVN support broken after update from 0.8.0 to 0.8.3

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#17]
Directories inside svn tree are not determined as svn working trees after update anymore. So diff and eveything else doesn't work.

OS Linux Ubuntu
version 0.8.4 - same story

**Comment by JohnstonCode** [comment]
Can I have a little more information, please. I don't quite understand what you mean.

**Comment by Yanpas** [comment]
I have a folder `y`:
```
x
  .svn
  y
    file1
    file2
  ...
```
I clock "open folder" in vs code, click on big black vcs icon and it suggests me to init empty git repo, ti doesn't find svn here, but before update your extension worked: it did show diff... and I guess that's all.

**Comment by JohnstonCode** [comment]
Thanks for raising this i will look into it.

**Comment by JohnstonCode** [comment]
Just released 0.8.5 see if that fixes your issue.

**Comment by Yanpas** [comment]
It seems to work on my local machine with local repository (`file:///`), tommorow will test on real working copies

**Comment by JohnstonCode** [comment]
Okay, let me know.

**Comment by Arwalk** [comment]
Have the exact same problem here, none of my checkouts are recognized anymore. I'm on 0.8.7 . I think it started behaving that way since 0.8.5, prior versions were working fine.

**Comment by JohnstonCode** [comment]
Hi @Arwalk 

I am not sure what you mean by your checkouts are not recognized.

Can you give me a little more information?

**Comment by Arwalk** [comment]
Sure. My workspace is a SVN checkout. Before, it was instantly recognized as a SVN working copy. Now, not anymore, just like @Yanpas it doesn't seem to recognize it as a svn workspace and only suggests me to init a new git repository.

It doesn't track any changes anymore.

Is it clearer?

**Comment by Yanpas** [comment]
I've tested on real svn repo and extension works again! (version 0.8.7)

**Comment by JohnstonCode** [comment]
Glad to hear @Yanpas!

**Comment by Arwalk** [comment]
Considering it works for @Yanpas i suppose it's mostly about my configuration.

"svn info --show-item" doesn't seem to exist for my version (version 1.8.8 (r1568071)) which might explain something later. In the end, here's the output of a full svn info, stripped of personal/work related informations.

`Path: .
Working Copy Root Path: /home/[REDACTED]
URL: [REDACTED]
Relative URL: ^/[REDACTED]
Repository Root: [REDACTED]
Repository UUID: 5b4854...
Revision: 36304
Node Kind: directory
Schedule: normal
Last Changed Author: [REDACTED]
Last Changed Rev: 36289
Last Changed Date: 2017-11-07 08:06:35 +0100 (mar., 07 nov. 2017)`

That should not tell much more than it's a working copy... Do you want to know anything else?

Thanks for the help, and for the extension, of course.

**Comment by JohnstonCode** [comment]
Yeah " --show-item" was added in 1.9

I should have checked what version it was added.

I use that as it was the only language neutral way I could get the root path for the given repository.

**Comment by Arwalk** [comment]
Sadly Ubuntu 14.04 doesn't have support for svn 1.9. I'll have to wrestle around this at work then.

Thank you.

**Comment by JohnstonCode** [comment]
Sorry about that.

Blame multi-root workspaces coming in Code 1.18.

I'll also add the 1.9 requirement to the readme.

**Comment by s-martin** [comment]
Is there a possibility to add support for SVN 1.7? On CentOS we are bound to that old version

**Comment by JohnstonCode** [comment]
Yes. thanks for opening an issue.
