### ISSUE TITLE
Viewing HEAD information shows all information has changed and kills PowerShell extension

### ISSUE THREAD

**Issue by mpearon** [JohnstonCode/svn-scm#170]
- VSCode Version: 1.20.1
- OS Version: Windows 10 1607
- Extension Version: 1.19.0
- System Language: English

## Issue ##
After a versioned file is modified (in this case a .psm1) and saved, the plugin detects changes.
I then switch to Source Control in the Activity Bar.
If I just submit the file, all is well - but if I click the file to view the HEAD info, it reports back that the _entire_ file was changed, then after a moment, the PowerShell session terminates.

- If I view the HEAD in Tortoise, it correctly displays the change data.

## Steps to Reproduce ##
- Modify versioned file
- View head information for modified file by clicking on filename in Changes pane.

## Sample ##
![headcrash](https://user-images.githubusercontent.com/7157790/36324004-ee5a1898-134a-11e8-9cd9-8a6537e0a150.JPG)

**Comment by edgardmessias** [comment]
@mpearon , you can send the svn log?

**Comment by mpearon** [comment]
@edgardmessias - I hope this is what you're after:
```
Using svn 1.9.7 (r1800392) from C:\Program Files\TortoiseSVN\bin\svn.exe
[DIT]$ svn info --xml
[DIT]$ svn stat --xml --no-ignore
[DIT]$ svn log -r BASE:HEAD -q --xml
[DIT]$ svn info --xml
[DIT]$ svn stat --xml --no-ignore
[DIT]$ svn stat --xml --no-ignore
[DIT]$ svn info --xml
```

**Comment by edgardmessias** [comment]
@mpearon, I can't reproduce here
@JohnstonCode, you can reproduce?

**Comment by JohnstonCode** [comment]
@edgardmessias unable to reproduce here

**Comment by mpearon** [comment]
Is there anything more I can provide you guys for troubleshooting?  It's consistent on my end.
In the meantime, I'll verify that I can reproduce the issue on another machine with the same environment.

**Comment by JohnstonCode** [comment]
Yeah if you can try on another machine in the same environment that will help.

**Comment by edgardmessias** [comment]
@mpearon, try disable all plugins and run.
Maybe it's another plugin the problem

**Comment by mpearon** [comment]
@edgardmessias - I have switched to a new machine, synced my settings, then disabled all extensions. Unfortunately, this was all to no avail.

Here are a few screenshots
Disabled settings:
![image](https://user-images.githubusercontent.com/7157790/36678426-5776ec06-1ad6-11e8-9ab3-4f0112ebe7fc.png)

Head from vsCode:
![image](https://user-images.githubusercontent.com/7157790/36678465-79300256-1ad6-11e8-9f48-e07ed6cc7dc4.png)

Head from Tortoise:
![image](https://user-images.githubusercontent.com/7157790/36678512-9896ede4-1ad6-11e8-8624-37e2e242a8cc.png)

**Comment by JohnstonCode** [comment]
@mpearon Thanks for going through all that trouble.

I'll try again to replicate.

**Comment by JohnstonCode** [comment]
@mpearon can you screenshot the output window when you are getting HEAD from the screenshot above?

**Comment by mpearon** [comment]
@JohnstonCode - It's no problem at all!  I greatly appreciate you taking the time to troubleshoot! :)

If this is what you're after (hopefully I didn't misunderstand), there isn't much to see:
![image](https://user-images.githubusercontent.com/7157790/36680863-92532316-1adc-11e8-9c9f-b05df1005488.png)

**Comment by JohnstonCode** [comment]
Can you screenshot the debug console as well please?

**Comment by edgardmessias** [comment]
Not running the command: `svn cat ....`

**Comment by edgardmessias** [comment]
@mpearon, please, run the commands:
`svn info <filename>` and `svn status --no-ignore <filename>`

**Comment by mpearon** [comment]
@JohnstonCode and @edgardmessias - Here is the output you requested.

**svn info:**

```
PS Microsoft.PowerShell.Core\FileSystem::\\SERVERNAME\DIT> svn info \\SERVERNAME\DIT\ScriptRepository\Modules\Modules\ServiceDesk\ServiceNow\CTS-ServiceNow.psm1
Path: ScriptRepository\Modules\Modules\ServiceDesk\ServiceNow\CTS-ServiceNow.psm1
Name: CTS-ServiceNow.psm1
Working Copy Root Path: \SERVERNAME\DIT
URL: https://SERVERNAME/svn/common/DIT/ScriptRepository/Modules/Modules/ServiceDesk/ServiceNow/CTS-ServiceNow.psm1
Relative URL: ^/DIT/ScriptRepository/Modules/Modules/ServiceDesk/ServiceNow/CTS-ServiceNow.psm1
Repository Root: https://SERVERNAME/svn/common
Repository UUID: 4bc623e6-e24c-4786-a4d0-aa7ffe565fda
Revision: 104
Node Kind: file
Schedule: normal
Last Changed Author: matthew_pearon
Last Changed Rev: 104
Last Changed Date: 2018-02-26 09:24:17 -0600 (Mon, 26 Feb 2018)
Text Last Updated: 2018-02-26 09:19:18 -0600 (Mon, 26 Feb 2018)
Checksum: 5f9354d73c311275ed80465f755592f2098bb4e3
```


**svn status --no-ignore:**
`M       \\SERVERNAME\DIT\ScriptRepository\Modules\Modules\ServiceDesk\ServiceNow\CTS-ServiceNow.psm1`

**Comment by edgardmessias** [comment]
lOl, UNC path, I can now do test

**Comment by mpearon** [comment]
I'm sorry!  I didn't think to mention that it was a UNC path.
After a few years in this field, you would think that my default posture would be to offer all details - even the ones I wouldn't think to be related/important.

**Comment by edgardmessias** [comment]
@mpearon, test this: https://ci.appveyor.com/api/buildjobs/5wgi9unbr9liw22p/artifacts/svn-scm.vsix

Instalation: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by mpearon** [comment]
@edgardmessias - I was able to add the VSIX.  For whatever reason, vsCode isn't getting the hint that it is acting as an SC provider.
![image](https://user-images.githubusercontent.com/7157790/36690350-aa9affa0-1af7-11e8-9339-751a13a04a16.png)

**Comment by edgardmessias** [comment]
Sorry, I find a bug in package.

Try this:
[svn-scm.zip](https://github.com/JohnstonCode/svn-scm/files/1759989/svn-scm.zip)

**Comment by mpearon** [comment]
@edgardmessias - The installation procedure requested a couple of reloads that time, but vsCode is still not seeing the SC provider for some reason.  Any logs I can provide you?

**Comment by mpearon** [comment]
@edgardmessias - Unfortunately, it looks the same:
![image](https://user-images.githubusercontent.com/7157790/36691245-3c923868-1afa-11e8-9691-93b047742a9f.png)

**Comment by edgardmessias** [comment]
Disable the auto update and reinstall

**Comment by mpearon** [comment]
Oh, I didn't think about the auto-update getting it.
Whatever you did there fixed the issue! :)
![image](https://user-images.githubusercontent.com/7157790/36692411-9e64ca26-1afd-11e8-8dcf-230db99799dd.png)

**Comment by edgardmessias** [comment]
Good, now wait the new release.

**Comment by mpearon** [comment]
Awesome!  Thank you for all of your assistance and troubleshooting! :)
Thank you too, @JohnstonCode!
