### ISSUE TITLE
Hide buttons, menu items etc if there are no svn repositories

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#171]
- VSCode Version: 1.20.1
- OS Version: win10
- Extension Version: 1.19
- System Language: ru

Currently "Open Changes" buttons, SCM "..." menu items are shown even if there is no svn reposiry

**Comment by edgardmessias** [comment]
Note: Need add `svnOpenRepositoryCount != 0` in all commands in `package.json`

**Comment by JohnstonCode** [comment]
Easy fix. I'll update the extension with all the changes later on today.

**Comment by Yanpas** [comment]
Thanks!

**Comment by Yanpas** [comment]
The buttons are not hidden if there is no svn installed:
`Error: Svn installation not found.`

**Comment by edgardmessias** [comment]
@Yanpas, @JohnstonCode, fixed with: https://github.com/JohnstonCode/svn-scm/commit/f71b038254eb0bcc08b6c6b854ff6342e7d244b4
