### ISSUE TITLE
Get conflicts to use API

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#172]
Current conflict resolution is poor.

need to use this API: [https://github.com/Microsoft/vscode/tree/master/extensions/merge-conflict](https://github.com/Microsoft/vscode/tree/master/extensions/merge-conflict)

**Comment by edgardmessias** [comment]
Maybe, we can check document after save contains the markers: `<<<<<<<`, `|||||||`, `=======`, `>>>>>>>`

If not contains, mark file solved.

**Comment by edgardmessias** [comment]
@JohnstonCode, see the #174

**Comment by edgardmessias** [comment]
I am working to allow you to resolve the conflict by selected file

**Comment by edgardmessias** [comment]
Done for resolve conflict by selected file.

**Comment by edgardmessias** [comment]
@JohnstonCode, can close?

**Comment by JohnstonCode** [comment]
Yeah
