### ISSUE TITLE
Reset diff indicators after commit

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#178]
- VSCode Version: 1.20
- OS Version: linux
- Extension Version: 1.20
- System Language: ru

Steps to Reproduce:

1. Modify file under version control
2. Commit it
3. Diff line indicators (near line number) are still there

**Comment by edgardmessias** [comment]
@Yanpas, working fine here.
@JohnstonCode, you can reproduce?

**Comment by JohnstonCode** [comment]
@edgardmessias unable to reproduce

**Comment by Yanpas** [comment]
Was unable to reproduce on newly created dummy local C# repo, but reproduces on real repo
![image](https://user-images.githubusercontent.com/7345761/36434027-16f8b06c-166f-11e8-8286-443ad9cc8493.png)

Trying to find steps to reproduce

**Comment by edgardmessias** [comment]
@Yanpas, to test: Edit one file, wait for 10 minutes and commit. Note: not close or change tab of file.

**Comment by Yanpas** [comment]
Still cannot reproduce on dummy repo

**Comment by edgardmessias** [comment]
@Yanpas, can I close this issue?

**Comment by Yanpas** [comment]
Yes. It's not critical and there are no steps to reproduce.

**Comment by edgardmessias** [comment]
If it happens again, we will reopen
