### ISSUE TITLE
How to enable this extension on MAC?

### ISSUE THREAD

**Issue by MrSparklle** [JohnstonCode/svn-scm#181]
- VSCode Version: 1.20.1
- OS Version: Mac OS X 10.13.3
- Extension Version: 1.20.0
- System Language: EN-US
- SVN Version: svn, version 1.9.4 (r1740329)

## Issue ##
I follow the instructions provided in readme and this extension aren't listed in the SCM providers.

## Steps to Reproduce ##

1. Installed extension
2. Changed file product.json inside ˜/applications/"Visual Studio Code.app"
3. Restart VSCode.

## SVN Output ##
```
svn, version 1.9.4 (r1740329)
   compiled Nov  6 2017, 18:06:35 on x86_64-apple-darwin16.1.0

Copyright (C) 2016 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.8 (compiled with 1.3.8)
  - handles 'http' scheme
  - handles 'https' scheme

The following authentication credential caches are available:

* Plaintext cache in /Users/joeldaros/.subversion
* GPG-Agent
* Mac OS X Keychain
```

**Comment by edgardmessias** [comment]
@MrSparklle , you want enable "SVN Status in File Explorer"
You have a workspace opened with SVN?

**Comment by MrSparklle** [comment]
Yes I did was suggested:
"Open the file: <vscode path>\resources\app\product.json
Find extensionAllowedProposedApi
Append "johnstoncode.svn-scm" in the array"

So I don't have the <vscode path> on Mac OS. I need to edit this file inside "˜/applications/Visual Studio Code.app"

I have a folder opened in VSCode withe my project. This folder has a .svn dir inside. This dir has been generated by a previous SVN client outside VSCode.

Is there something that I did wrong?

**Comment by JohnstonCode** [comment]
The part you are referring to is enabling the file explorer decorations. They are not needed to get the extension to work.

The extension should just work with no configuration needed.

The extension cannot detect an svn repository. Do you have a 2nd repository to test with?

**Comment by MrSparklle** [comment]
I already tried with 2 ou 3 different repositories unsuccessful.
All of them are created by Cornerstone SVN app.

**Comment by edgardmessias** [comment]
@MrSparklle, run the command in workspacefolder: `svn info` and paste the result

**Comment by MrSparklle** [comment]
@edgardmessias 

`svn: E155036: Please see the 'svn upgrade' command
svn: E155036: The working copy at '/Users/XXXX/Repository/CEF/SWRC'
is too old (format 29) to work with client version '1.9.4 (r1740329)' (expects format 31). You need to upgrade the working copy first.`

After run `svn upgrade` the VSCode recognize the .svn and everything works fine.
I guess the .svn generated by Conerstone is a old 1.8 SVN, and the system is a new 1.9, that was causing this issue.

Thanks for helping.
