### ISSUE TITLE
Unable to commit on MacOS

### ISSUE THREAD

**Issue by shaco-6** [JohnstonCode/svn-scm#183]
- VSCode Version: 1.20.0
- OS Version: 10.13.3
- Extension Version:
- System Language: Simplified Chinese
- SVN Version: CornerStone 3.0.3 (22,983)

## Issue ##

Unable to commit

## Steps to Reproduce ##

1. commit selected
2. 

## SVN Output ##

Erorr: Unable to commit                          

## Screenshots ##

[080A0BDF-0782-446F-A3AC-4F6354509770.png.zip](https://github.com/JohnstonCode/svn-scm/files/1746502/080A0BDF-0782-446F-A3AC-4F6354509770.png.zip)

**Comment by JohnstonCode** [comment]
Can you run "svn info" and copy the results in here, please?

**Comment by shaco-6** [comment]
Here is informatin, thank you ~~


liuchangdeMBP:UnityProject liuchang$ svn info
Path: .
Working Copy Root Path: /Users/liuchang/Desktop/PitayaSVN/Hellokitty
URL: http://liuchang@119.29.21.115:10081/svn/hex4_git/Hellokitty/UnityProject
Relative URL: ^/Hellokitty/UnityProject
Repository Root: http://liuchang@119.29.21.115:10081/svn/hex4_git
Repository UUID: 7a1f3cfe-9371-4190-b379-8a5fdfb9e7dd
Revision: 16885
Node Kind: directory
Schedule: normal
Last Changed Author: fandingchao
Last Changed Rev: 16885
Last Changed Date: 2018-02-22 16:23:54 +0800 (四, 22  2 2018)

**Comment by JohnstonCode** [comment]
Thanks for that.

Do you have anything in your debug console?

**Comment by shaco-6** [comment]
I try to commit some test file by Terminal, failed too...
but can commit by CornerStone, Is this what I did wrong ? Thanks ~~

liuchangdeMBP:Configuration liuchang$ svn commit -m "test" shop_config.json
Sending        shop_config.json
Transmitting file data .done
Committing transaction...
svn: E165001: Commit failed (details follow):
svn: E165001: Commit blocked by pre-commit hook (exit code 1) with output:
\nYou must input some comment for the commit

**Comment by shaco-6** [comment]
I try to input longger comment, it work >.<

Thank for your help ~~

**Comment by JohnstonCode** [comment]
No problem
