### ISSUE TITLE
Portable test svn repository

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#185]
Make testing issues easier between contributors.

**Comment by edgardmessias** [comment]
We can create a script (.js or .js) to generate the repository and its files.

**Comment by johnjacobkenny** [comment]
What would be a good directory structure to generate for this purpose? I can give this a try.

**Comment by JohnstonCode** [comment]
Don't think the folder structure matter too much just needs a local SVN repository creating then a copy checked out.

**Comment by edgardmessias** [comment]
Create a library to build multiple repositories, to use in unit tests.

**Comment by johnjacobkenny** [comment]
Multiple repos, how would they be different? What all should be included?
