### ISSUE TITLE
Unable to perform merge conflict selection in diff view

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#189]
So I updated my work repo and observed that I had a few merge conflicts. So I clicked one of those files in the sidebar and was presented with the diff view. Here in the diff view the conflict marker decorations are visible, but the option to pick which code to keep isn't coming in this view. Opening the same file in normal view works fine.

**Comment by edgardmessias** [comment]
@johnjacobkenny, please use [issue template](https://raw.githubusercontent.com/JohnstonCode/svn-scm/master/.github/issue_template.md)
