### ISSUE TITLE
Configure source path

### ISSUE THREAD

**Issue by andresbm05** [JohnstonCode/svn-scm#19]
I have a project which includes various modules and I'm only working on one of them with VSCode, the problem using this extension is that it tries to look up for the files where the .svn folder is (in the parent directory) when it should look up on the current directory. For example my main project is en C:\project but the project I'm working on with VSCode is in C:\project\VSCproject, if I have a file on this folder it tries to compare it with the file in C:\project\file.x and not in C:\project\VSCproject\file.x
And thats why this extension should allow us to configure the path we are working on to specify where it should look up for the files.

**Comment by JohnstonCode** [comment]
Hi @andresbm05 

The extension should only lookup files in the open directory, not the full project.

Is this affecting the source control view or the diffs in the gutter?

**Comment by andresbm05** [comment]
Hi @JohnstonCode 
It is affecting the source control view because for every modified file, when I click on it, it promts a message saying that file ... could not be oppened: file not found(file:///wrong_path_to_file) 
That wrong path is the path of my main project (the one with the .svn folder) plus the path to the file from the opened directory, it is missing the in between folders to reach the opened folder on VSCode.
So I can't compare or anything.

**Comment by JohnstonCode** [comment]
I get you. Fixed that for Linux last night are you using version 0.8.7?

**Comment by andresbm05** [comment]
I have just updated and the problem was solved. Using Windows 7 x64.

Thanks!
