### ISSUE TITLE
Bug: incorrect branch names in branch switch menu

### ISSUE THREAD

**Issue by Eretik** [JohnstonCode/svn-scm#192]
- VSCode Version: 1.20.1
- OS Version: Windows 10 x64
- Extension Version: 1.21.1
- System Language: English
- SVN Version: 1.9.7

## Issue ##
In case of custom svn folders layout (branches are on second level subfolders - see the first screenshot) VSCode display only names of first level folder instead of names of second level subfolders - see the second screenshot.

## Steps to Reproduce ##
1. Create subfolder "test" in "branches" folder
2. Add some branches to `branches/test`  
3. Add `"svn.layout.branches": "branches/test"` to the VSCode settings
4. Check VSCode's branch chooser

## Screenshots ##
![image](https://user-images.githubusercontent.com/7785859/36791961-d4a2ed02-1ca1-11e8-8d2f-805ee8a04bd4.png)

![image](https://user-images.githubusercontent.com/7785859/36791361-4541389a-1ca0-11e8-89e7-18b6f154b3e3.png)

**Comment by edgardmessias** [comment]
Duplicated of #117

**Comment by Eretik** [comment]
@edgardmessias This bug is not duplication for [#117](https://github.com/JohnstonCode/svn-scm/issues/117) because branches actually switching and VSCode shows correct branch name in left bottom corner after switching (but I've found an issue with switching back to trunk in case of such folder layout). This bug about incorrect branches names in branch switcher.

**Comment by edgardmessias** [comment]
Sorry, I will fix

**Comment by edgardmessias** [comment]
@Eretik, make a test for me:

Open file `~/.vscode/extensions/johnstoncode.svn-scm-1.21.1/out/commands.js`

Replace `ref.split("/")` to `ref.split("/", 2)`

**Comment by edgardmessias** [comment]
@Eretik , no need more, I found the problem

**Comment by Eretik** [comment]
@edgardmessias :) fast one!

**Comment by edgardmessias** [comment]
@Eretik  , test with this: https://ci.appveyor.com/api/buildjobs/09v57bj5a84p63l2/artifacts/svn-scm.vsix

Instalation: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix
Disable auto-update before
