### ISSUE TITLE
Locked items showing in changes list

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#199]
- VSCode Version:1.20.1
- OS Version:F26
- Extension Version:1.21.3
- System Language:EN
- SVN Version:1.9

Items flagged as locked are showing in changes list

## Steps to Reproduce ##

1. Have locked items look in changes list

![image](https://user-images.githubusercontent.com/10222719/36837055-1dcd4248-1d33-11e8-9980-1f674ad5b05d.png)

**Comment by edgardmessias** [comment]
@JohnstonCode , run command: `svn status <locked file> --xml` and `svn status <folder of locked file> --xml`

**Comment by JohnstonCode** [comment]
@edgardmessias Cant. needed to commit so locks have gone. 

the svn stat locked like this tho

![image](https://user-images.githubusercontent.com/10222719/36843414-cbe41c18-1d46-11e8-8e3b-12ea45f8d7e6.png)

**Comment by edgardmessias** [comment]
@JohnstonCode, send me XML: `svn stat bin --xml`

**Comment by JohnstonCode** [comment]
@edgardmessias you wont get anything the dir is no longer locked.

`<?xml version="1.0" encoding="UTF-8"?>
<status>
<target
   path="bin">
</target>
</status>
`

**Comment by JohnstonCode** [comment]
Looking through the code tho. It seems that anything that doesn't match is just added to the changes.

[here](https://github.com/JohnstonCode/svn-scm/blob/master/src/repository.ts#L458)

**Comment by edgardmessias** [comment]
The problem is this: http://svnbook.red-bean.com/en/1.7/svn.tour.cleanup.html
I will work on this problem

**Comment by edgardmessias** [comment]
To reproduce: switch branch and kill `svn`

**Comment by JohnstonCode** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<status>
<target
   path="bin">
<entry
   path="bin">
<wc-status
   wc-locked="true"
   item="normal"
   revision="580"
   props="none">
<commit
   revision="577">
<author>cjohnston</author>
<date>2015-08-14T14:39:14.912123Z</date>
</commit>
</wc-status>
</entry>
<entry
   path="bin/cron">
<wc-status
   wc-locked="true"
   item="normal"
   revision="580"
   props="none">
<commit
   revision="577">
<author>cjohnston</author>
<date>2015-08-14T14:39:14.912123Z</date>
</commit>
</wc-status>
</entry>
<entry
   path="bin/utils">
<wc-status
   item="normal"
   revision="580"
   props="none"
   wc-locked="true">
<commit
   revision="477">
<author>cjohnston</author>
<date>2011-05-05T16:26:22.728438Z</date>
</commit>
</wc-status>
</entry>
</target>
</status>

```

**Comment by edgardmessias** [comment]
My result on folder:
```xml
<wc-status
   item="incomplete"
   revision="1831457"
   props="none"
   wc-locked="true">
```

**Comment by JohnstonCode** [comment]
These shouldn't be making it to the changes list. The last else on the update will just take anything as long as it's not a changelist. This will need sorting.

**Comment by JohnstonCode** [comment]
Also, we should add the `svn cleanup` command

**Comment by edgardmessias** [comment]
@JohnstonCode, finished
