### ISSUE TITLE
Feature Request: Committing

### ISSUE THREAD

**Issue by garethflowers** [JohnstonCode/svn-scm#2]
We would love to have commit support built into this extension.

Any plans to get this implemented?

**Comment by JohnstonCode** [comment]
Hi Gareth,

Yes, that will be something that I will be adding. 

Cant give you an exact timeline but I am working on it.

**Comment by JohnstonCode** [comment]
Just to give you a quick update.

I will be testing this tonight and should be released tomorrow.

**Comment by JohnstonCode** [comment]
Version 0.5.0 will allow you to commit all changes using the SCM input box.
