### ISSUE TITLE
How to turn off the update prompt?

### ISSUE THREAD

**Issue by nuintun** [JohnstonCode/svn-scm#202]
- VSCode Version: 1.20.1
- OS Version: WIN10 PRO 1709
- Extension Version: 1.22.0
- System Language: zh_CN
- SVN Version: 1.9.7

## Issue ##

How to turn off the update prompt?
This prompt is not necessary. It can be displayed on the status bar.

## Screenshots ##

![_20180302092258](https://user-images.githubusercontent.com/1730277/36878736-5559d078-1dfb-11e8-86b3-c31ecb91ba6c.png)

**Comment by JohnstonCode** [comment]
@nuintun currently there is no way to turn the information message off on commit.

Moving it to the status bar could be an option.
