### ISSUE TITLE
Option to commit all files in a changelist

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#203]
## Issue ##
Unable to quickly commit all files in a changelist

**Comment by JohnstonCode** [comment]
@johnjacobkenny would a commit changelist command solve your issue?

**Comment by edgardmessias** [comment]
@johnjacobkenny , please, use the [issue template](https://raw.githubusercontent.com/JohnstonCode/svn-scm/master/.github/issue_template.md)

**Comment by edgardmessias** [comment]
@johnjacobkenny, svn output?

**Comment by johnjacobkenny** [comment]
@JohnstonCode yes, that's exactly what I was looking for.
@edgardmessias Sorry about the mess up... Its actually a feature request, is there a format for that

**Comment by edgardmessias** [comment]
@johnjacobkenny , on commit, you can choose a changelist, and all files are included

**Comment by edgardmessias** [comment]
If you have changelist, run normal commit, without selected file, on commit, show all changelists to select.

**Comment by johnjacobkenny** [comment]
Where can I find the option you were referring to as`normal commit`? Do you mean entering a commit message and pressing enter? I was under the impression that it would commit all files

**Comment by edgardmessias** [comment]
@johnjacobkenny, for tests.

Checkout this repository: https://plugins.svn.wordpress.org/jetpack/trunk/

Change some files, and create most change lists.

Run commit.

Note: Commit fail because need valid credentials

**Comment by johnjacobkenny** [comment]
@edgardmessias Now that I've done it, it makes perfect sense. Thanks!
