### ISSUE TITLE
Inconsistent displaying of the branchs'/trunk's names/paths

### ISSUE THREAD

**Issue by Eretik** [JohnstonCode/svn-scm#204]
- VSCode Version: 1.20.1
- OS Version: Windows 10 x64
- Extension Version: 1.21.3
- System Language: English
- SVN Version: 1.9.7

## Issue ##
In case of custom folder layout for trunk and branches:
`"svn.layout.branches": "branches/test",
"svn.layout.trunk": "trunk/test"`
VSCode shows in left bottom corner trunk/test for trunk, but only branch name for branches.

I can imagine three options to make it more consistent:
1. Show full branch path in all cases
2. Show just trunk for the trunk and just branch name for the branches as far as user configured the plugin to use specific folders for the trunk and branches
3. It could be configurable. For example, `svn.layout.showFullPaths` boolean param to switch between first and second options.

Last one is the best as I think, but what are you ideas about it?

**Comment by edgardmessias** [comment]
@Eretik , test with this: https://ci.appveyor.com/api/buildjobs/nv2veohqlsim4t9i/artifacts/svn-scm.vsix

Instalation: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix
Disable auto-update before
Configure news options

**Comment by edgardmessias** [comment]
Closed by #205

**Comment by Eretik** [comment]
@edgardmessias Sorry for late response. Yes, feature about showing/hiding full paths works now. But with moving config options from paths to regexes I do not understand how to restrict possibility of switching between branches of only one sub-folder of 'branches' folder. Could you please provide me example of regex for my case?

**Comment by Eretik** [comment]
@edgardmessias unfortunately, it works just as default values. My folder structure is:
- trunk
  - MyProject
  - AnotherProject
- branches
  - MyProject
    - branch1-1
    - branch1-2
  - AnotherProject
    - branch2-1
    - branch2-2

And I would like to bind `trunk` to `trunk\MyProject` directly, without necessity of making a choice between all possible trunks. And after clicking on branch name in left bottom corner I would like to see only branches from `branches\MyProject`. Again, without full list of available branches of all sub-projects. It was possible to achieve this state with previous configuration options. But is it possible now, with regexes?

**Comment by edgardmessias** [comment]
Use it:

svn.layout.trunkRegex: `"(trunk)/MyProject(/.*)?"`
svn.layout.branchesRegex: `"branches/MyProject/([^/]+)(/.*)?"`
svn.layout.tagsRegex: `"tags/MyProject/([^/]+)(/.*)?"`

Note: every show all folders, but, you not can switch to all, limited by "MyProject"

**Comment by edgardmessias** [comment]
Question: How you do it without VSCode?
Why not use the standard layout in SVN?

Ideas are welcome!!!

**Comment by JohnstonCode** [comment]
Would this regex not work?

svn.layout.trunkRegex: "trunk\/MyProject(\/.*)?"
svn.layout.branchesRegex: "branches\/MyProject(\/.*)?"

**Comment by Eretik** [comment]
@edgardmessias Without VSCode: `TortoiseSVN -> Switch`, with same problems of finding right folder. About second question - it's corporate restrictions (one repo per project, despite amount of sub-projects) and architectural decisions :). I'm asking about it now just because it was possible with `branches/trunk/tagsPath` options.

@JohnstonCode Unfortunately no. It works in strange way - some folders are presented as folders in branch selector, some not, some of them are empty inside, some with real branches, some with sub-folders displayed as branches...

**Comment by JohnstonCode** [comment]
@Eretik 

`svn.layout.trunkRegex: "trunk\/MyProject"`
`svn.layout.branchesRegex: "branches\/MyProject\/(.*)"`

Can you see if those are any better please

**Comment by edgardmessias** [comment]
@Eretik, for sub-folders, you need update your regex to catch all.

See: https://regex101.com/r/3Xs7x4/1

You can use this site to make your regex. You can paste all URLs.

Maybe you need update the group capture in `svn.layout.branchesRegexName`

**Comment by JohnstonCode** [comment]
@Eretik 

`svn.layout.branchesRegex: "branches\/MyProject\/(.*)(?=\/)"`

Maybe this will work

**Comment by JohnstonCode** [comment]
None of the regex will work. I thought the whole sub-branch thing worked differently.

I can also see how it use to work for you before @Eretik 

I have created a new issue #231

**Comment by edgardmessias** [comment]
@JohnstonCode, I disagree, It works, just not how he'd like it
