### ISSUE TITLE
Show incoming changes files (remote changes)

### ISSUE THREAD

**Issue by grapestech** [JohnstonCode/svn-scm#207]
- VSCode Version:
- OS Version:
- Extension Version:
- System Language:
- SVN Version:

## Issue ##
Is it possible to show the list of incoming changes in the changes view ?
## Steps to Reproduce ##

1. Go to source control view
2. Only local changes appear (M, U)

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by grapestech** [comment]
Correct. 

We currently use Subversive with eclipse and this is essential for us to view the list of incoming files and compare them with the working version before updating the code. 

The files can be listed under Changes but with a different decorator to indicate that those are remote and not local changes. 

Thanks !

**Comment by JohnstonCode** [comment]
@edgardmessias what would the best command to run to get a list of all the incoming file changes.

`svn stat -u` highlights them by putting a '*' in the ninth column. The XML output doesn't seem to highlight them in any way.

**Comment by JohnstonCode** [comment]
maybe something like `svn diff -r BASE:HEAD --summarize --xml`

**Comment by grapestech** [comment]
Yes this might work

**Comment by edgardmessias** [comment]
@JohnstonCode, from `svn stat -u --xml`, we need compare the `<repos-status>`

**Comment by edgardmessias** [comment]
From source code, to show `*`:  https://github.com/apache/subversion/blob/8691483c2568ebd3d7d6ba9a3764bc1311c8df2e/subversion/svn/status.c#L363

**Comment by edgardmessias** [comment]
The question: What is the best way to display in VSCode?

VSCode has its limitations

**Comment by JohnstonCode** [comment]
yes I was thinking about using another optional ResourceGorup that just lists the files in the incoming changes and just has the ability to diff base:head

**Comment by edgardmessias** [comment]
Small inconvenience: The position is before "changelists"

**Comment by JohnstonCode** [comment]
that would be an inconvenience. I'll have a play around and see what looks best.

**Comment by edgardmessias** [comment]
Maybe we can implement the [Tree View](https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-view-sample)

**Comment by JohnstonCode** [comment]
Tree View could work

**Comment by edgardmessias** [comment]
The another sugestion is use decorationProvider, but it is a proposed-api

**Comment by JohnstonCode** [comment]
That is also a good option. It has been proposed for a while now. Wonder how long before the make it available.

**Comment by edgardmessias** [comment]
@JohnstonCode 
I will remove the "New Commits" in favor to check `svn stat -u --xml`, `<repos-status>`.
Create a ResourceGroup, dispose and re-create, to keep at last position.
Only `n` minutes update the resouce group.

**Comment by JohnstonCode** [comment]
@edgardmessias when files in the "Remote Changed" source control gorup the right click context options only work for the modified states. If they are added or deleted errors are thrown

**Comment by Nukium** [comment]
Hello, first of all thanks for this merge !

It would have been perfect if we could update a file via a right click ont it in the incoming change view instead of having to update the whole project...

**Comment by edgardmessias** [comment]
@Nukium, good idea, please open a new issue with the feature

**Comment by JohnstonCode** [comment]
@Nukium yes please open a new issue. I will do it as part of my work on [this branch ](https://github.com/JohnstonCode/svn-scm/compare/tree-view-incomming-changes)
