### ISSUE TITLE
Newly added image asset not opening from vcs sidebar

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#208]
- VSCode Version: 1.21
- OS Version: Windows 10
- Extension Version: 1.22
- System Language: English
- SVN Version: 1.9.7

## Issue ##
Nothing happens when clicking on a newly added image in the sidebar. I was expecting the image to just open as it would normally from the explorer sidebar.

## Steps to Reproduce ##

1. Add a new image asset to project
2. Open the source control sidebar
3. Click on the image file

## SVN Output ##
NO OUTPUT OBSERVED

**Comment by edgardmessias** [comment]
@johnjacobkenny  , test with this: https://ci.appveyor.com/api/buildjobs/82fxpwlvj26fuvfa/artifacts/svn-scm.vsix

Instalation: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix
Disable auto-update before

**Comment by johnjacobkenny** [comment]
Yes it works now. Opening the file is working correctly. However when I try to delete it, I'm getting 
```
svn: E195006: Use --force to override this restriction (local modifications may be lost)
svn: E195006: '<redacted>' has local modifications -- commit or revert them first
```
