### ISSUE TITLE
Support SVN lower than 1.9

### ISSUE THREAD

**Issue by s-martin** [JohnstonCode/svn-scm#21]
- VSCode Version: 1.17.2
- OS Version: CentOS 7
- Extenstion Version: 0.8.7

Please provide support for SVN 1.7. CentOS ships only with that old version.

**Comment by JohnstonCode** [comment]
I will look into this. Will need to set up some VMs for different languages to make sure I don't break anything for them as well.

**Comment by s-martin** [comment]
Happy to provide tests for CentOS 7 with SVN 1.7 and Windows 7 with TortoiseSVN

**Comment by JohnstonCode** [comment]
Does your terminal output in German?

**Comment by s-martin** [comment]
Windows German, CentOS English

**Comment by JohnstonCode** [comment]
Okay so if you do "svn info" on windows do you get something like this on the 2nd line?

"Wurzelpfad der Arbeitskopie: G:\projects\xxx\xxx"

**Comment by s-martin** [comment]
C:\_MYDATA\Projekte\projekt1>svn info
Path: .
Working Copy Root Path: C:\_MYDATA\Projekte\projekt1
URL: http://REMOVED/svn/projekt1
Relative URL: ^/
Repository Root: http://REMOVED/svn/projekt1
Repository UUID: REMOVED
Revision: 2660
Node Kind: directory
Schedule: normal
Last Changed Author: REMOVED
Last Changed Rev: 2660
Last Changed Date: 2017-11-07 09:10:30 +0100 (Di, 07 Nov 2017)

**Comment by s-martin** [comment]
I guess this depends on the language of TortoiseSVN (I have the English version installed)

**Comment by JohnstonCode** [comment]
Guessing it does.

I will just download the German version when I get home.

Only need to test to see if the XML is translated or is the same regardless of language.

**Comment by JohnstonCode** [comment]
Using XML now. see if anyone complains. Removes the 1.9 req.
