### ISSUE TITLE
Unable to install with "Couldn't find a compatible version of SVN with this version of Code." error.

### ISSUE THREAD

**Issue by GadgetMan0101** [JohnstonCode/svn-scm#212]
- VSCode Version: 1.15.1
- OS Version: Windows 10 Pro (64bit)
- Extension Version: 
- System Language: English
- SVN Version: TortoiseSVN 1.9.7

## Issue ##
Trying to install the extension and I get the error "Couldn't find a compatible version of SVN with this version of Code."

## Steps to Reproduce ##

1. Find the SVN extension in the marketplace, click install.

## SVN Output ##
```
C:\>svn --version
svn, version 1.9.7 (r1800392)
   compiled Aug  8 2017, 22:14:48 on x86-microsoft-windows
```
```
C:\>where svn
c:\program files\tortoisesvn\bin\svn.exe
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/7810014/37351356-e08c02f0-26a8-11e8-8501-40b87f7fe286.png)
![image](https://user-images.githubusercontent.com/7810014/37352807-12816b26-26ac-11e8-902a-8cc0cfd54db5.png)

**Comment by edgardmessias** [comment]
@GadgetMan0101, the problem is not subversion not found, but, your VSCode version is too old.

Upgrade your VSCode to `>1.18`` or lastest

**Comment by GadgetMan0101** [comment]
Thanks. I couldn't see anywhere that identified the minimum version of VSCode required.
