### ISSUE TITLE
Issue in diff patch for selected

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#216]
- VSCode Version: 1.21.0
- OS Version: Windows 10
- Extension Version: 1.22
- System Language: en
- SVN Version: 1.9.7

## Issue ##
Diff patch for selected only shows the patch for a single file that is currently open in the diff view.

## Steps to Reproduce ##

1. Make changes to some code
2. Open version control sidebar
3. Select multiple files (only the first file opens up in the diff view)
4. Choose `Show diff patch for selected` from top scm options menu

## SVN Output ##
```
svn cat <firstClickedFilename> -r HEAD
svn diff <firstClickedFilename>
```

**Comment by JohnstonCode** [comment]
@johnjacobkenny does it work if you use `Show diff patch for selected` from the right click menu?

**Comment by JohnstonCode** [comment]
@johnjacobkenny never mind. 

The options menu will have not reference to what has been highlighted in the SCM menu. I can either remove it completely or replace it with a `Show diff patch for open files`

**Comment by edgardmessias** [comment]
@JohnstonCode, replace in `scm/title`, from `svn.patch` to `svn.patchAll` and remove `svn.resolve`

**Comment by JohnstonCode** [comment]
@edgardmessias okay will do
