### ISSUE TITLE
Jump to next conflict

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#217]
- VSCode Version:
- OS Version:
- Extension Version:
- System Language:
- SVN Version:

## Issue ##
When trying to resolve multiple conflicts in a file, currently we need to manually scroll to the next conflicted area to be able to resolve the next conflict. It would be easier if the editor could automatically scroll to the next conflicted section in the same file. This could be the default behavior, which could optionally be disabled by a configuration.

## Steps to Reproduce ##
1. Update code.
2. Open a file with multiple conflicts.
3. Decide whether to accept current/incoming/both etc.
4. Editor does not scroll to next conflict.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by edgardmessias** [comment]
Sorry @johnjacobkenny, this feature is not part of SVN extension.

See https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts

Open issue here: https://github.com/Microsoft/vscode/tree/master/extensions/merge-conflict

**Comment by johnjacobkenny** [comment]
I've opened an issue here https://github.com/Microsoft/vscode/issues/45853
