### ISSUE TITLE
Cannot commit to a private SVN repository

### ISSUE THREAD

**Issue by flipovic** [JohnstonCode/svn-scm#219]
- VSCode Version: 1.21.1
- OS Version: Linux Mint 17.3
- Extension Version: 1.22.0
- System Language: en_US
- SVN Version: 1.8.8

## Issue ##

I have a folder opened on my VS Code which is a checkout from an external SVN repository, to which I have access via simple username/password authentication, but I cannot commit my changes and the following appears on the SVN extension console output:
```
svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL 'https://svn.myrepo.com/myproj'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
```
Should I configure the SVN client to use the **--force-interactive** option? I have tried to specify it through the setting **svn.path**, by configuring it to **/usr/bin/svn --force-interactive**, but the problem persisted.

**Comment by JohnstonCode** [comment]
@edgardmessias is this a GNOME key ring issue?

**Comment by edgardmessias** [comment]
@JohnstonCode, maybe.

@flipovic, you can run simple test?

In terminal, on svn folder, run: `svn info -r HEAD`

**Comment by flipovic** [comment]
@edgardmessias right now I'm on a different computer, at work, with the following

**Comment by flipovic** [comment]
Sorry, I clicked on the wrong button and unintentionally closed the issue.

Right now I'm on my work computer, with the same VSCode and SVN extension version, but with Mint 18.3 and SVN 1.9.3, and although the result is the same, I still cannot perform SVN operations on the remote repository, the error is different, follows an example for a failed update as it appears on the extension console ouput:
```
$ svn update
svn: E170013: Unable to connect to a repository at URL 'https://svn.myrepo.com/myproj'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
```
And if I execute the mentioned command (I have to insert my credentials as I don't have stored credentials):
```
$ svn info -r HEAD
Authentication realm: <https://svn.myrepo.com:443> Linkare SVN Repository
Password for 'myuser': ****************

Path: certificates
URL: https://svn.myrepo.com/myproj
Relative URL: ^/myproj
Repository Root: https://svn.myrepo.com
Repository UUID: 11fcbde3-9353-43fb-82e8-452551669547
Revision: 56774
Node Kind: directory
Last Changed Author: myuser
Last Changed Rev: 56649
Last Changed Date: 2018-03-15 11:13:28 +0000 (Thu, 15 Mar 2018)
```

**Comment by edgardmessias** [comment]
@flipovic, you use GNOME Keyring?

**Comment by edgardmessias** [comment]
@flipovic , test with this: https://ci.appveyor.com/api/buildjobs/k580jdfhb8eml3p9/artifacts/svn-scm.vsix

Instalation: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix
Disable auto-update before

**Comment by flipovic** [comment]
@edgardmessias I have installed the VSIX as suggested.

GNOME Keyring stores my login credentials for some resources, and I looked around and somehow it had old credentials (no longer active) for the SVN remote repository I am using, but even after deleting them and restarting VS Code the exact same error remains.

Should I have my SVN credentials stored (via my svn client on $HOME/.subversion), in order to avoid the authentication prompt, before using the extension?

**Comment by flipovic** [comment]
I have updated my SVN configuration to store my password, using the option **store-passwords = yes** on **~/.subversion/servers** and after making an SVN operation on the terminal and thus saving my password  on GNOME Keyring the errors on VS Code extension went away and I can now use it with no problems!

The only limitation is that I'm currently forced to have my credentials saved, which means that if someone uses my computer and makes changes to the source code they will commit them with my user with no problem. As this is not the common scenario, I can live with having the credentials locally stored, but it would be nice to have the option to have an authentication prompt.

**Comment by flipovic** [comment]
Just a last comment to thank you for your quick and useful assistance! Keep up the excellent work!
