### ISSUE TITLE
Committing doesn't work with specific message

### ISSUE THREAD

**Issue by macrobb-cygnusaero** [JohnstonCode/svn-scm#221]
- VSCode Version: Version 1.21.1
- OS Version: Debian Sid (4.15.0-10.1-liquorix-amd64)
- Extension Version: 1.23.1
- System Language: English
- SVN Version: 1.9.7 (r1800392)

## Issue ##
I cannot commit a change with a specific message. With no message, it commits correctly

## Steps to Reproduce ##
1. Create a folder called 'test'(or any specific string) in your SVN-controlled directory
2. Right-click on a file in your SVN Changes list and "commit selected"
3. Use a comment of "test"(or the same thing as your folder)

## SVN Output ##
[trunk]$ svn commit -m test *My file path*
svn: E205005: The log message is a pathname (was -F intended?); use '--force-log' to override

It looks like '--force-log' should be a default option for SVN.
(Note that this isn't preventing me from using the plugin now that I understand why, but it confused me a lot when I was trying it out and just getting 'commit failed' errors.

**Comment by edgardmessias** [comment]
Not is `[trunk]$ svn commit -m "My file path" test `?

**Comment by macrobb-cygnusaero** [comment]
There are no quotes.

**Comment by edgardmessias** [comment]
@macrobb-cygnusaero, invert message and path.

`svn commit test -m My file path`

**Comment by edgardmessias** [comment]
Note: Internal, vscode use quote for each argumet

**Comment by edgardmessias** [comment]
My local tests is ok for commit new folder

**Comment by macrobb-cygnusaero** [comment]
Here's a screenshot of the issue, in the VS Code debug window.
I'm glad that VS Code is using quotes(so a comment of "TestThis | echo 'test' > 'thisisafile.txt'" won't result in shell injection)

![screenshot_20180319_092442](https://user-images.githubusercontent.com/8333829/37608347-869a2124-2b57-11e8-9427-98633a021af1.png)

**Comment by macrobb-cygnusaero** [comment]
You must make a folder(say "test") and comment using the exact same message as the folder. SVN sees the comment as being a path, I believe. I've tried it directly:
![screenshot_20180319_092916](https://user-images.githubusercontent.com/8333829/37608562-1f5e6136-2b58-11e8-9a38-1fab0d56a4ce.png)
Even with the -m after it and quoted, SVN still thinks you are commenting a path

**Comment by edgardmessias** [comment]
Now I can reproduce.

**Comment by edgardmessias** [comment]
Fixed with #222

**Comment by macrobb-cygnusaero** [comment]
Thanks!

**Comment by edgardmessias** [comment]
@macrobb-cygnusaero, test with this: https://ci.appveyor.com/api/buildjobs/3n3i60kyeuen8f0b/artifacts/svn-scm.vsix

Instalation: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix
Disable auto-update before

**Comment by macrobb-cygnusaero** [comment]
Works for me. Looks like "--force-log" is added if the file exists.

**Comment by edgardmessias** [comment]
Yes, only file exists
