### ISSUE TITLE
Does not works properly when source file contains "@"

### ISSUE THREAD

**Issue by dimazev** [JohnstonCode/svn-scm#223]
- VSCode Version: latest
- OS Version: Mac
- Extension Version: latest
- System Language: TS
- SVN Version: 1.9

## Steps to Reproduce ##
create file wich contains "@"  for example file  test@any.txt

## SVN Output ##
```
svn: E205000: Try 'svn help cat' for more information
svn: E205000: Syntax error parsing peg revision 'any.txt'
```

**Comment by edgardmessias** [comment]
About: http://svnbook.red-bean.com/en/1.8/svn.advanced.pegrevs.html

**Comment by guusw** [comment]
This still happens in version 1.50.1 of the extension (svn version 1.11.0)

**Comment by edgardmessias** [comment]
@guusw can you describe the problem?

**Comment by edgardmessias** [comment]
I found the problem
