### ISSUE TITLE
Status bar bug

### ISSUE THREAD

**Issue by randyou** [JohnstonCode/svn-scm#224]
VSCode Version: 1.21.1
OS Version: Windows 7 x64
Extension Version: 1.23.2
System Language: JS
SVN Version: 1.9.7

## Issue ##
Open a folder like 'resources' of a  java project, status bar d not shows 'struct' or  'v1' .
Svn Url :" svn://[ip]:[port]/main-project/main-name/branches/v1/my-java-project/web/src/main/resources"
My folder structure is like “E:\foo\workspace\code\my-java-project\web\src\main\resources”;
## Steps to Reproduce ##

1. Open a folder which not in root of "svn project" .

## Screenshots ##
![1111](https://user-images.githubusercontent.com/8247661/37654477-2913b336-2c7d-11e8-8c84-101cb2612203.png)
![222](https://user-images.githubusercontent.com/8247661/37690354-5a620baa-2ce5-11e8-811f-a26a50608f25.png)
![333](https://user-images.githubusercontent.com/8247661/37690363-60d3c0b4-2ce5-11e8-9703-0abfd938b2cf.png)

**Comment by edgardmessias** [comment]
@randyou, svn folder structure?

Only show if found the "branch" name

**Comment by randyou** [comment]
Svn Url :" svn://[ip]:[port]/main-project/main-name/branches/v1/my-java-project/web/src/main/resources"
My folder structure is like “E:\foo\workspace\code\my-java-project\web\src\main\resources”;

At last version, open “E:\foo\workspace\code\my-java-project\web\src\main\resources” in vscode and it showed 'v1' at bottom-left.

**Comment by edgardmessias** [comment]
If show "v1", is correct.

**Comment by randyou** [comment]
It dosn't show "v1" now.
![image](https://user-images.githubusercontent.com/8247661/37708657-7b050940-2d42-11e8-82a8-c277ec152d0e.png)

**Comment by edgardmessias** [comment]
@randyou, show me your `svn.layout.branchesRegex` and `svn.layout.branchesRegexName` config please

**Comment by edgardmessias** [comment]
Try this: `"svn.layout.branchesRegex": "branches/([^/]+)(/.*)?"`

**Comment by randyou** [comment]
I haven't set svn.layout.trunkRegex and svn.layout.branchesRegex . 
And I found it works at branches now.
![image](https://user-images.githubusercontent.com/8247661/37709693-f95d3bc0-2d45-11e8-8692-c0f46d51a1a7.png)

Then I set "svn.layout.trunkRegex": "trunk/([^/]+)(/.*)?" , it works at trunk now.
![image](https://user-images.githubusercontent.com/8247661/37709751-284ea7a2-2d46-11e8-9d4e-bcd6db0ecb95.png)

It works not like before, just show 'trunk' or 'v1'.

**Comment by edgardmessias** [comment]
For `svn.layout.trunkRegex`, use `"(trunk)(/.*)?"`

See `svn.layout.showFullName` to show only branch name

**Comment by randyou** [comment]
It works like before ! Thank you !
![image](https://user-images.githubusercontent.com/8247661/37710076-81853538-2d47-11e8-8810-ad0e6aa5dc35.png)

**Comment by edgardmessias** [comment]
Good, I will update the default config with new regex

**Comment by edgardmessias** [comment]
@JohnstonCode, done
