### ISSUE TITLE
"Remove from changelist" bad behaviour

### ISSUE THREAD

**Issue by Guema** [JohnstonCode/svn-scm#229]
- VSCode Version: 1.21.1
- OS Version: Windows 7 x64
- Extension Version: 1.26.0
- System Language: FR-fr
- SVN Version: 1.9.7

## Issue ##

It seems "Remove from changelist" command vanishes from proposals after doing some things.

I use it with ignore-on-commit only at the moment.

## Steps to Reproduce ##

1. do a change
2. add change to ignore-on-commit list via "Set changelist" menu
3. open "Set changelist" menu again on this element
-> remove from changelist is proposed
4. close it
5. open "Set changelist" menu once again on the same element
-> "remove from changelist" vanished.

another way :

1. do a change
2. commit it
3. do another change
4. add it to ignore-on-commit via "Set changelist" menu
5. open "Set changelist" menu once again on the same element
-> "remove from changelist" vanished.

## SVN Output ##
```
Using svn "1.9.7 (r1800392)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[sim2b-editor]$ svn info --xml
[sim2b-editor]$ svn stat --xml --no-ignore --ignore-externals
[sim2b-editor]$ svn info --xml
[sim2b-editor]$ svn cat imports\ui\views\dialog\dialog_graph.js
[sim2b-editor]$ svn log -r BASE:HEAD -q --xml
[sim2b-editor]$ svn cat imports\api\dialogs.js -r HEAD
[sim2b-editor]$ svn changelist --remove imports\ui\views\dialog\forms\dialog_part_modal.js imports\api\dialogs.js imports\client\dialogActions.js imports\client\d3Frames\d3Frames.js imports\ui\views\dialog\dialog_graph.css imports\ui\views\dialog\dialog_graph.html imports\ui\views\dialog\forms\dialog_part_modal.html
[sim2b-editor]$ svn stat --xml --no-ignore --ignore-externals
[sim2b-editor]$ svn stat --xml --no-ignore --ignore-externals
[sim2b-editor]$ svn stat --xml --no-ignore --ignore-externals
[sim2b-editor]$ svn info --xml
[sim2b-editor]$ svn stat --xml --no-ignore --ignore-externals
```

## Screenshots ##

![image](https://user-images.githubusercontent.com/8943532/37824731-e143a2e2-2e8d-11e8-8a6e-8d1f9f98fe75.png)

**Comment by JohnstonCode** [comment]
@edgardmessias you looking at this or am i okay to have a look at this tonight?

**Comment by edgardmessias** [comment]
The problem is windows path. Need normalize to compare

**Comment by Guema** [comment]
I updated ext.

Work perfectly now, thanks you very much and good job !

Guema
