### ISSUE TITLE
Unable to add file

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#23]
- VSCode Version: 1.17.2
- OS Version: ubuntu 16.04
- Extension Version: 0.8.7
- System Language: ru_RU.UTF8

Steps to Reproduce:

1. Create unversioned files
2. Click on "+" icon

PS there is nothing interesting in devtools: no stack trace, just the same message with some callbacks.

**Comment by Yanpas** [comment]
After playing with terminal I know bug's reason: files actually were actually added, they just remained marked as unversioned in vs code. So they must be moved to Changes list and have "A" icon.

**Comment by Yanpas** [comment]
There are problems with VCS panel updates: it is not refreshed on many file operations. E.g. if you edit file, save it, undo changes and save it again it will remain in changes list

**Comment by JohnstonCode** [comment]
Not able to replicate the issue.

How many changes and not tracked items do you currently have?

**Comment by Yanpas** [comment]
Well, only one seems to be enough (in previous revision there were 8 changes. It feels like the list(`this.changes`) of changes is not replaced, but merged with newcomers.

**Comment by JohnstonCode** [comment]
I'm not able to replicate either issue.

The list (this.changes) gets wiped and replaced on every event update.

The errors that VS Code emits are less than helpful. Not sure what could be causing your issue.

**Comment by JohnstonCode** [comment]
Finally been able to replicate it!

Ill look into it ASAP

**Comment by JohnstonCode** [comment]
This should be fixed in 0.8.8
