### ISSUE TITLE
Sub branches showing all

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#231]
- VSCode Version:1.21.1
- OS Version:f27
- Extension Version:1.26.1
- System Language:EN
- SVN Version:1.9

## Issue ##
The `svn.layout.branchesRegex` is only used to filter out the names of branches. I think there is some confusion about filtering out names and only retrieving the results of the regex.

**Comment by edgardmessias** [comment]
@JohnstonCode, the real problem is: How to detect the root of repository and the branches?

**Comment by edgardmessias** [comment]
Now work like the "TortoiseSVN", but, if is a branch, show a [git-branch icon](https://octicons.github.com/icon/git-branch/), and folder show [file-directory icon](https://octicons.github.com/icon/file-directory/)

For list all branches only, we need run `svn ls --depth infinity <url>` and filter by regex, the problem is very very slow.

**Comment by JohnstonCode** [comment]
@edgardmessias maybe combine both new and old?

Have config value to point to branches and then use the regex from there?

**Comment by edgardmessias** [comment]
Each person uses SVN in a way.

The question is not only "switch branch", but how to detect root of repository and ability of create news branches and tags

Current solution solves these problems.

Running multiple `svn ls` is very slow

**Comment by JohnstonCode** [comment]
But giving the extension a path to the branches from the root is an addition that wouldn't affect anyone?

So nothing changes for anyone happy with the current setup. But allows people that liked it the old way to use it as before

**Comment by edgardmessias** [comment]
Idea:
* Create a option like `svn.layout.useRegexForBranchName: boolean`
* Create `svn.layout.trunk.folder`, `svn.layout.branches.folder` and `svn.layout.tags.folder`
* Move `svn.layout.branchesRegex` to `svn.layout.branches.regexForName`, same with tag

If `svn.layout.useRegexForBranchName` is false, use single list to detect the branches, if true, use current listing method
