### ISSUE TITLE
Svn propset commands

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#233]
@s-martin would like

1. EOL
2. Executable
3. Externals

**Comment by edgardmessias** [comment]
After a long time, I had an idea to manage properties

* Create commands to list (proplist), read (propget with/without revision), set by value (propset) and set by file content (propset --file)
* Create a property manager to store the relation of temporary with related file/property
* When user start a edit property, generate a temporary file and create a `TextEditorDecorationType ` and set to first line with label like `Property 'svn:ignore' of 'myfile.txt'`
* On save, update the related property
* Update the `svnContentProvider.ts` to accept property type (Allow to view diff)
* Some properties, create syntax file (Ex. svn:externals)

**Comment by JohnstonCode** [comment]
Good idea, What would the diff show?

**Comment by edgardmessias** [comment]
Diff between current property and last commit property (BASE revision)
