### ISSUE TITLE
Preserve failed commit message

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#235]
- VSCode Version: 1.21.1
- OS Version: Windows 10
- Extension Version: 1.26.1
- System Language: en
- SVN Version: 1.9.7

## Issue ##
When I try to commit, if there's an error the commit fails. In order to commit again, I'm asked to enter the entire commit message. It would be nice if the commit message is preserved if the commit failed so that the user does not need to enter it again.

## Steps to Reproduce ##

1. Add a new folder with some files in it
2. Select only the files and try to commit, it fails
3. Select the folder as well and try to recommit, it asks for message again

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by JohnstonCode** [comment]
This would be a nice convenience.

**Comment by johnjacobkenny** [comment]
This is an issue only when manually selecting files and committing via _right click > commit selected_. When using the commit message area and committing a changelist, the message is preserved. Is it possible to make the commit message area the only location to enter commit messages?

**Comment by edgardmessias** [comment]
Done with #245
