### ISSUE TITLE
Show reason for commit failed

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#236]
- VSCode Version: 1.21.1
- OS Version: Windows 10
- Extension Version: 1.26.1
- System Language: en
- SVN Version: 1.9.7

## Issue ##
Currently if a commit fails, it just says commit failed and does not expand on what the issue is, or how to fix it. Right now, I'm checking the svn output to determine what went wrong. It would be nice if this is included in the error notification.

## Steps to Reproduce ##
1. Try to commit a repo in a bad state

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by JohnstonCode** [comment]
This would be helpful. We now parse errors better now in other places. Should be a quick and easy change.

**Comment by johnjacobkenny** [comment]
![image](https://user-images.githubusercontent.com/19240564/38411272-573e2a78-39a4-11e8-95a2-4b5454fa2bba.png)
This could also be more informative, maybe indicate the files when expanded

**Comment by edgardmessias** [comment]
Done with #245
