### ISSUE TITLE
Respect "ignore-on-commit" for "pending changes"

### ISSUE THREAD

**Issue by bersbersbers** [JohnstonCode/svn-scm#237]
- VSCode Version: 1.21.1
- OS Version: Microsoft Windows [Version 10.0.16299.309]
- Extension Version: 1.27.1
- System Language: English
- SVN Version: 1.9.7 (r1800392)

## Issue ##

Files on changelist "ignore-on-commit" contribute to "pending changes" count - even unchanged ones.

They should not do that.

## Steps to Reproduce ##

1. Have an active repository
2. Change a file
3. Add the file to changelist "ignore-on-commit"
4. Optionally, revert the file

## SVN Output ##
```
Using svn "1.9.7 (r1800392)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[xyz]$ svn info --xml
[xyz]$ svn stat --xml --no-ignore --ignore-externals
[xyz]$ svn info --xml
[xyz]$ svn cat const.py
[xyz]$ svn log -r BASE:HEAD -q --xml
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/12128514/38307607-7e14e984-3814-11e8-9152-96a128aa3fbd.png)

**Comment by edgardmessias** [comment]
@JohnstonCode, we can create a option for it

**Comment by JohnstonCode** [comment]
@edgardmessias yeah best way

**Comment by petrmusil** [comment]
I agree, option will be great. Then I vote that default is to NOT include "ignore-on-commit" files into count.

**Comment by edgardmessias** [comment]
Done with #244

**Comment by bersbersbers** [comment]
I cannot verify this right now, but I reported two issues (files on the ignore-commit list being counted, and *unchanged* files on the ignore-commit list being counted). This surely solves the first one, does it fix the second one if someone decides to want to count files on the ignore-commit list, too?
