### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by johnjacobkenny** [JohnstonCode/svn-scm#239]
- VSCode Version: 1.21.1
- OS Version: Windows 10
- Extension Version: 1.26.1
- System Language: en
- SVN Version: 1.9.7

## Issue ##
After renaming versioned files from vs code explorer view, the old filename file shows up as missing and the new filename file as unversioned. Is it possible to hook into the explorer rename event and perform the corresponding svn command to indicate the rename?
## Steps to Reproduce ##

1. Rename a versioned file in vs code explorer view

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by edgardmessias** [comment]
Not supported by VSCode at moment

See Microsoft/vscode#24846 and Microsoft/vscode#43768

**Comment by edgardmessias** [comment]
Note:
When file are renamed, the `const fsWatcher = workspace.createFileSystemWatcher("**");` every run `fsWatcher.onDidCreate` first, with new URI, and after run `fsWatcher.onDidDelete` with old URI.

In the source of VSCode, work with create a new copy of object and delete the old.

**Comment by edgardmessias** [comment]
Maybe, we can create a class to listener files changes to detect rename, and prompt to user.

If true, we need rollback the rename and run `svn rename`

**Comment by JohnstonCode** [comment]
`vscode.workspace.on[Will|Did]RenameFile` was added in `1.41.0` https://code.visualstudio.com/updates/v1_41#_workspace-file-events

**Comment by alexdymov** [comment]
Any update on this? I also tried to set keyboard shortcut for "Rename with SVN" command but the rename command is not executing when I press the key. It only works when clicked from file explorer. Had to go back to Eclipse to perform some basic refactoring actions.

**Comment by rbyshko** [comment]
Is somebody working on this at the moment?

**Comment by JohnstonCode** [comment]
No, feel free to submit a PR

**Comment by hansWurst-creator** [comment]
@JohnstonCode This issue is bugging me a lot. I would be willing to work on it. Would you accept a pull request?
