### ISSUE TITLE
Commit action commits all changed files in tree, not only in local folder

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#24]
VSCode Version: 1.17.2
OS Version: ubuntu 16.04
Extension Version: 0.8.7
System Language: ru_RU.UTF8

Steps to Reproduce:
```
x
  .svn
  y
    file1
    file2
  file3
  ...
```

Your current folder is y, all files are versioned, file1 and file3 are modified. Commit action commits file1 and file3, but it must commit only file1

**Comment by JohnstonCode** [comment]
This is an awkward issue.

The VS Code team has decided that with their git scm that the entire project is listed in the source control view. This is to rule out cases like this when running other commands.

What is your opinion on this?

Do you think the source control view should be repository wide or scoped down the the opened folder?

**Comment by Yanpas** [comment]
I guess that svn-scm should use current directory, not root. First of all because changelist in the sidebar is displayed for current directory, secondly because eclipse plugin works the same (and I'm almost sure IDEA's too).

Git and svn has different concepts. Git treats one repository as one project, Svn doesn't have such constraint (e.g. [apache's svn](https://svn.apache.org/viewvc) contains all apache's projects).

**Comment by JohnstonCode** [comment]
Done the code for this.

Will be testing it tonight.

**Comment by JohnstonCode** [comment]
0.8.10 should fix this for you.

Using the commit box will only commit the files listed under "changes" in the source control view.

**Comment by Yanpas** [comment]
Yes, in 0.8.10 only local files are commited, but changes list is not updated after commit (create new issue?)

here are some commands for future tests:
```
svnadmin create foorepo
svn co file://$(pwd)/foorepo foo
mkdir y
touch y/f1 y/f2 f3
svn add * --depth infinity
```

**Comment by JohnstonCode** [comment]
Not able to replicate that. 

Been using the source control input box and the right click option I'm testing.

**Comment by Yanpas** [comment]
I commit using ctrl+enter. To refresh VCS sidebar i resave file as a workaround
![_2017-11-08_16-28-44](https://user-images.githubusercontent.com/7345761/32551558-0142acec-c4a2-11e7-9e2e-9411088c4645.png)

**Comment by JohnstonCode** [comment]
I'll add a manual call to update. that should sort it out.

**Comment by Yanpas** [comment]
Thanks, marking as closed
