### ISSUE TITLE
Local changes not reflected in log after commit.

### ISSUE THREAD

**Issue by cvetan** [JohnstonCode/svn-scm#241]
If you perform commit, changes are not reflected in log until you run update again. Why is that?

You commit for instance version 119, but in commit messages option you still get 117 or 118.

**Comment by JohnstonCode** [comment]
Not sure whats causing that. I will take a look

**Comment by JohnstonCode** [comment]
Seems the default revision range for log is `BASE:1` I will change this to `HEAD:1`

**Comment by cvetan** [comment]
I still think this is not as good as it should be. I would like to hear your oppinion. When you make commit from VS code, and for instance you go to terminal run `svn log` you don't see your commit. How is that?

If you used Sublime Text, and SVN plugin for it changes are reflected right away. PhpStorm the same.

It doesn't make sense that changes you commited, from the same machine are not reflected until you run update as in the picture.

This just doesn't make sense to me.
![vscode-svn-statusbar](https://user-images.githubusercontent.com/5733322/38498875-208bfd84-3c06-11e8-9dc1-a104aafcb3e3.png)

**Comment by JohnstonCode** [comment]
Yeah, I get your point. Maybe an update even should fire after a commit.

**Comment by edgardmessias** [comment]
The update command can are a problem.

Example: if you want split your commit, a deleted file are restored after update

**Comment by edgardmessias** [comment]
@JohnstonCode, I am a favor to close this issue and open another more specific

**Comment by JohnstonCode** [comment]
Yes please do
