### ISSUE TITLE
svnkit client is not recognized, even so I specify a svn.path

### ISSUE THREAD

**Issue by papanito** [JohnstonCode/svn-scm#248]
- VSCode Version: 1.23.0-insider
- OS Version: Windows 2016
- Extension Version: 1.29.0
- System Language: EN
- SVN Version: SVNKit 1.8.12

## Issue ##
I have currently svnkit on my development machine - not installed but unpacked zip.  The packages is located here: D:\development\tools\svn\svnkit\.
There is a bin directory but does not contain exe files but only bat files. 
VS tells me that "SVN not found. INstall it or configure it using the 'svn.path'"
I cannot install it via installer so I need to configure the svn.path. But whatever I provide there, somehow the svnkit is not "seen"
```
"svn.path": "D:\\development\\tools\\svn\\svnkit\\bin"
"svn.path": "D:\\development\\tools\\svn\\svnkit\\bin\\svn.bat"
"svn.path": "D:\development\tools\svn\svnkit\bin"
"svn.path": "D:\development\tools\svn\svnkit\bin\svn.bat"
"svn.path": "D:/development/tools/svn/svnkit/bin"
```

## Steps to Reproduce ##
N/A

## SVN Output ##
N/A
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

## Screenshots ##
N/A

**Comment by papanito** [comment]
`where svn` returns nothing. however simply `svn` returns
```
Type 'jsvn help' for usage
```

**Comment by JohnstonCode** [comment]
Got mine working with setting `svn path` to `"E:/Downloads/org.tmatesoft.svn_1.9.3.standalone/svnkit-1.9.3/bin/jsvn.bat"` i also had to install Java SE Development Kit 8

**Comment by JohnstonCode** [comment]
Closing this issue. If you are still having problems please comment on this issue and I will re-open it.
