### ISSUE TITLE
Create guide to use the plugin

### ISSUE THREAD

**Issue by drenda** [JohnstonCode/svn-scm#25]
I think would be useful a small guide to use the extension. I installed it but I don't see anything in the SCM section.
I had svn on my system: `Client Subversion, versione 1.6.17-SlikSvn-tag-1.6.17@1130898-X64
` 

A troubleshooting guide would be appreciated. Thanks

**Comment by JohnstonCode** [comment]
This extension does not currently work with subversion < 1.9.

Working on fixing this should be updated tomorrow.

**Comment by drenda** [comment]
Oh ok. Thanks very much. I looking forward to the update then ;-)

**Comment by JohnstonCode** [comment]
Version 0.8.8 should work for you now.

**Comment by drenda** [comment]
Thanks very much. Now I see the svn view. Sorry for the question, maybe it is silly: I don't see the context menu to commit, see differences, updates and so on. Is that normal?
See the attachment:

![svn](https://user-images.githubusercontent.com/3420646/32538213-8cab3836-c465-11e7-9af1-cb1a8c917ca6.png)

**Comment by JohnstonCode** [comment]
Not written many svn commands yet. It is on the to-do list tho.
