### ISSUE TITLE
Workspace mode with many SVN projects doesn't show project name

### ISSUE THREAD

**Issue by lapo-luchini** [JohnstonCode/svn-scm#250]
- VSCode Version: 1.22.2
- OS Version: Windows 10
- Extension Version: 1.18.1
- System Language: it
- SVN Version: 1.10.0

## Issue ##

Workspace mode with many SVN projects doesn't show project name

## Steps to Reproduce ##

Use a workspace with a few root folders, many of which are SVN projects with standard path `project/trunk`.

## SVN Output ##

Every project is shown as `trunk`, with now way (not hover) that I know of to distinguish them.

## Screenshots ##

![image](https://user-images.githubusercontent.com/420454/39516388-1116394c-4dfd-11e8-885e-140420bd59d2.png)

**Comment by lapo-luchini** [comment]
Actually, I already did, first try was on my main box, which is:

> VSCode Version: 1.17.2
> OS Version: FreeBSD
> Extension Version: 1.18.1

but before sending the bug I also tried on another computer which is:

> VSCode Version: 1.22.2
> OS Version: Windows 10
> Extension Version: 1.29.0

but then I just forgot to update the third value.
(the screenshot is actually from the FreeBSD box, but it is the same on the Win10 one)

**Comment by edgardmessias** [comment]
Whats your folder name and URL?

**Comment by lapo-luchini** [comment]
Workspace folders:
```
{
	"folders": [
		{"name":"fatturapa","path":"/home/lapo/svn/java/fatturapa/trunk"},
		{"name":"fatturapa-api","path":"/home/lapo/svn/nodejs/fatturapa-api"},
		{"name":"fatturapa.client","path":"/home/lapo/svn/java/fatturapa.client/trunk"},
		{"name":"fatturapa.ws","path":"/home/lapo/svn/java/fatturapa.ws/trunk"},
		{"name":"hsm.api","path":"/home/lapo/svn/java/hsm.api/trunk"},
		{"name":"javaver","path":"/home/lapo/svn/nodejs/javaver/trunk"},
		{"name":"mail","path":"/home/lapo/svn/java/mail/trunk"},
		…lots of others…
	]
}
```
which correspond to `svn info | fgrep "Relative URL"`s:
> ^/java/fatturapa/**trunk**
> ^/nodejs/**fatturapa-api**
> ^/java/fatturapa.client/**trunk**
> ^/java/fatturapa.ws/**trunk**
> ^/java/hsm.api/**trunk**
> ^/nodejs/javaver/**trunk**
> ^/java/mail/**trunk**

Which corresponds more or less to this part:
![image](https://user-images.githubusercontent.com/420454/39528152-9e12bb10-4e23-11e8-9c67-60697360bd43.png)

Config about that is using default values:
> // Relative path for 'trunk' in SVN URL, 'null' to disable. (Ex.: 'trunk', 'main')
> "svn.layout.trunk": "trunk",
> // Relative path for 'branches' in SVN URL, 'null' to disable. (Ex.: 'branches', 'versions')
> "svn.layout.branches": "branches",
> // Relative path for 'tags' in SVN URL, 'null' to disable. (Ex.: 'tags', 'stamps')
> "svn.layout.tags": "tags",

**Comment by lapo-luchini** [comment]
Oh, sorry, I thought that the "layout" configuration meant it was the extension's work to do.
Changing the folder name is not possible because it's a multi-project SVN checkout, not a single checkout for each single directory, which would be an hassle to update all together.
I'll try and check with VSCode if project name can be different from folder name.
(especially in the context of the workspace, where I defined the `name` fields for that exact reason already)

**Comment by edgardmessias** [comment]
The "layout" configuration is for branch name only

**Comment by lapo-luchini** [comment]
I opened a VSCode issue, but they closed saying I should open one here… 🤔

**Comment by lapo-luchini** [comment]
That "trunk"  is indeed calculated in VSCode, by: `basename(repository.provider.rootUri.fsPath)`.
