### ISSUE TITLE
Add "set changelist" to FileExplorer Context menu

### ISSUE THREAD

**Issue by Guema** [JohnstonCode/svn-scm#252]
- VSCode Version: 1.22.2
- OS Version: Win 7 x64 
- Extension Version: 1.29.0
- System Language: FR-fr
- SVN Version: 1.9.4

## Feature request ##

Allow to also "add to a changelist" to file explorer right click (context) menu.

explaination :
- It is coherent because user could want to add a file that isn't opened or not changed yet
- Right click is easy to use
- Could be a cool plus if it allow to add multiple files to changelist too.
- Would be coherent with "add to SVN:ignore list" which is available on both context menu and shortcut command menu

Thanks,
Guema

**Comment by Guema** [comment]
got this if i try to set changelist of any file or folder
![image](https://user-images.githubusercontent.com/8943532/47730031-94221480-dc61-11e8-967c-c1e384448046.png)

SVN log is irrelevant as it logs nothing when i try to do it.

Windows specific problem ?

Os : Windows 7 x64
Code : 1.28.2
SVNext : 1.45.0

**Comment by JohnstonCode** [comment]
@Guema Will have a check tonight

**Comment by edgardmessias** [comment]
@JohnstonCode , I see only one solution for VSCode limitation.
Create a single context menu, like "SVN Action".
The "SVN Action" is a command and receive the selected files (from doc: `(fisrtFile: Uri, allFile: Uri[])`)
Check avaiable commands for current selected files and show a picker to run the command.

Example: "SVN Action" >> "Set Changelist" >> "..."

**Comment by JohnstonCode** [comment]
Too many clicks for my liking. Not sure why it was working when testing but yeah it's busted now.

I can get this to work just need some time to properly think it through

**Comment by edgardmessias** [comment]
The problem:
* SCM: Context Menu use `Resource`
* Explorer: Context Menu use `Uri`

Most commands use only Resource.

**Comment by edgardmessias** [comment]
Example for compare:
[addToIgnoreSCM.ts](https://github.com/JohnstonCode/svn-scm/blob/master/src/commands/addToIgnoreSCM.ts)
[addToIgnoreExplorer.ts](https://github.com/JohnstonCode/svn-scm/blob/master/src/commands/addToIgnoreExplorer.ts)

**Comment by edgardmessias** [comment]
Last note: A non changed file not has a Resource

**Comment by JohnstonCode** [comment]
Yeah, that is the problem. We need to somehow abstract that away so it doesn't matter what is passed.

Need something that can be created from a Uri or Resource then it doesn't matter what is passed. But it has to only be able to represent files/folders svn is aware of
