### ISSUE TITLE
Changes in svn:externals not detected

### ISSUE THREAD

**Issue by michelegalante** [JohnstonCode/svn-scm#254]
- VSCode Version: 1.23.1
- OS Version: macOS Sierra 10.12.6
- Extension Version: 1.29.0
- System Language: IT
- SVN Version: 1.8.13

## Issue ##

I did a commit of my working copy from within VS Code with changes to the "svn:externals" property. After the commit I found out that the changes to the property were not committed. Also from the VS Code user interface it looks like the working copy has no modifications, but if I do "svn stat" or "svn diff" from the command line I see the changes to the "svn:externals" property.

## Steps to Reproduce ##

1. Checkout a working copy.
2. Modify some source file and the "svn:externals" property.
3. Commit using the "Commit changes" button in VS Code.
4. Do "svn stat" on the working copy. You will see that "svn:externals" is still modified.

**Comment by JohnstonCode** [comment]
SVN output?

**Comment by michelegalante** [comment]
This is the output of the commit made from VS code.

> [project]$ svn commit lib main.c -m 'Main module.'
> [project]$ svn stat --xml --no-ignore
> [project]$ svn stat --xml --no-ignore
> [project]$ svn cat main.c
> 

The modifications to the "svn:externals" property have not been committed:

> MacBook-Pro-di-Michele:project galante$ svn st
>  M      .
> X       lib/utils
> 

When I use svn from the command line I usually commit this way:

> MacBook-Pro-di-Michele:project galante$ svn commit . -m "Commit also folder properties."
> Sending        .
> 
> Committed revision 7.
>

**Comment by JohnstonCode** [comment]
Changes to the repository are missing. Svn output will show `M .` Also changes to this are not being committed.

**Comment by JohnstonCode** [comment]
Because the root changes are missing from the changes source control resource group they are not being committed.

**Comment by JohnstonCode** [comment]
Would like it to show as `.` rather than `[name of foler] [path]`
