### ISSUE TITLE
URL getting replaced when specific hostname and "trunk" named "dev"

### ISSUE THREAD

**Issue by GuillaumeBibaut** [JohnstonCode/svn-scm#255]
- VSCode Version: 1.23.1
- OS Version: Window 10 x64
- Extension Version: 1.29
- System Language: EN
- SVN Version: 1.9.7

## Issue ##
The branches names matching removes some parts of the url in a specific case when the url is in the form:
`svn+ssh://dev.example.com/svn/repo/dev`
Where:
- `repo` is the repository
- `dev` is a dev branch

## Steps to Reproduce ##

1. config
```
    "svn.layout.trunkRegex": "(dev)(/.*)?",
    "svn.layout.trunkRegexName": 1,
    "svn.layout.branchesRegex": "user/[^/]+/([^h][^/]+)(/.*)?",
    "svn.layout.branchesRegexName": 1,
    "svn.layout.tagsRegex": "prod/([^/]+)(/.*)?",
    "svn.layout.tagRegexName": 1,
    "svn.layout.showFullName": true
```
2. In this repository, the `dev` folder is our `trunk`, and our developers are always checking out directly `dev`, nothing above that hierarchy. So you have to checkout `svn+ssh://dev.example.com/svn/repo/dev`, to use that specific config, and to try to switch branch

## SVN Output ##
```
[dev]$ svn list svn+ssh://.example.com/svn/repo/dev --xml
svn: E170013: Unable to connect to a repository at URL 'svn+ssh://.example.com/svn/repo/dev'
svn: E210002: To better debug SSH connection problems, remove the -q option from 'ssh' in the [tunnels] section of your Subversion configuration file.
svn: E210002: Network connection closed unexpectedly
```

## Screenshots ##
![screenshot_051518_015602_pm](https://user-images.githubusercontent.com/423833/40055300-b61f42f4-5847-11e8-9e97-36e046149760.jpg)

**Comment by GuillaumeBibaut** [comment]
ah... ok, I first thought that was related to the regexp match (sort of...), but that makes sense now 👍

**Comment by GuillaumeBibaut** [comment]
Surely to get the repository root URL?

**Comment by GuillaumeBibaut** [comment]
I've read the code, and even though I do not know the history of the code, I'm not getting why in this method it's done that way to try to get the repository root URL. I'm trying to guess but since in the OUTPUT console there's always a `svn info --xml`, then the getInfo() should always get the repository `<root>` XML Element, so why not just use `info.repository.root`?
Are there some cases when the `info.repository.root` is not available?

**Comment by edgardmessias** [comment]
@GuillaumeBibaut, first fix your svn auth with ssh to work the command `svn list svn+ssh://.example.com/svn/repo/dev --xml`

**Comment by GuillaumeBibaut** [comment]
I'm not the one who specifically typed this command, it's the svn extension in VS Code. I know quite well the URL to my repository and I would not type such command :) It was just me copy/pasting the OUTPUT console outputs.

Anyway, I think there might be a misunderstanding about what can be put at the root URL of a repository. Of course one can organize its repository as one has decided.
In the case of this wordpress url, the root is organized with projects, where each are organized with the trunk/branches/tags hierachy to help seperate development cycles.
In my case, the repository root mimics the FreeBSD OS folder hierarchy: https://svn.freebsd.org/base , where the `head` is the trunk of the project. Historically, my company has always called `dev` the main development project, so when we created the repo, instead of `head`, we've called it `dev`.

So I do not think any of our SVN repository is wrong, there both right because you can put anything in a repository root, the company or opensource development group decides how to organize the root. So neither of these repositories structures/hierarchies should dictates where the `{trunk,branches,tags}` are named or placed.

There is surely a work around for both, I guess the regexp values we can set in this VSCode extension are here for this extension to get an understanding and whereabouts of a repository structure/hierarchy.

**Comment by GuillaumeBibaut** [comment]
@JohnstonCode I've thought about it a bit yesterday, wouldn't it be easier to have a way in your code to separate the schema + hostname from the path in the URL?
`{schema}://{hostname}{/path}`
and/(or just) to replace only the last occurrence in the path (or full url)?

**Comment by JohnstonCode** [comment]
@GuillaumeBibaut yeah there are lots of things I would like to change but I just don't have the time. The extension went through rapid changes to keep with new features being requested and has become overly complex in my opinion. Looking back at the code it's becoming harder to reason with/understand.

Once I have some extra time I will be making changing that should make things better and easier for other people to contribute to. Some Documentation would be good.

**Comment by JohnstonCode** [comment]
@GuillaumeBibaut Your issue will be an easy fix tho.

**Comment by GuillaumeBibaut** [comment]
any news about this please? :)

**Comment by JohnstonCode** [comment]
@GuillaumeBibaut sorry for the delay. I have been trying to resolve older issues. I will get this one sorted tonight.

**Comment by JohnstonCode** [comment]
Going to do some testing tonight and publish

**Comment by GuillaumeBibaut** [comment]
thank you
