### ISSUE TITLE
How to create branch?

### ISSUE THREAD

**Issue by JamesRamm** [JohnstonCode/svn-scm#256]
- VSCode Version: 1.23.1
- OS Version: Ubuntu 16.04
- Extension Version:  1.29.0
- SVN Version: 1.9.3

## Issue ##

The marketplace page states 'creating branches' as a feature. I can't find how to do this?
All I can see in the command menu is 'Switch Branch'.
Any help welcome....

## Steps to Reproduce ##

1. Open an SVN project in VSCode
2. Open the command menu and filter "SVN" -> No create branch command

## Screenshots ##
![image](https://user-images.githubusercontent.com/2784823/40106907-4688467e-58f7-11e8-82bd-a5489536181e.png)

**Comment by JohnstonCode** [comment]
click on the branch name in the bottom left corner. Then click where you would like the branch to be o the drop-down. Then there should be an option to create a branch.

**Comment by ESLHemantSangle** [comment]
@JohnstonCode  i am not able to create branch as i don't see the name in left corner other than the update revision button 
![Screenshot from 2019-07-28 15-02-11](https://user-images.githubusercontent.com/36596748/62004894-cdcc7100-b148-11e9-893c-e4df0a36f6fc.png)

**Comment by JohnstonCode** [comment]
Can you open a new issue please @ESLHemantSangle
