### ISSUE TITLE
can svn-scm be used like this ?

### ISSUE THREAD

**Issue by gtfcugb** [JohnstonCode/svn-scm#257]
like sublime svn plugin?

![](https://imgcdn-prd.pydp888.com/file/0/1/200001/20180517/158915925de5bc853c37cbcae2b5ed30.png)

https://imgcdn-prd.pydp888.com/file/0/1/200001/20180517/9c3dd41f0decb0d7a5711bc042067fce.png

**Comment by JohnstonCode** [comment]
You are only able to ignore file/directories from the file explorer. There are more options available to files in the SCM view.

**Comment by edgardmessias** [comment]
VSCode not have support to submenu in context menu
