### ISSUE TITLE
Changelist is not updated if changelist reaches zero amount

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#26]
VSCode Version: 1.17.2
OS Version: ubuntu 16.04
Extension Version: 0.8.9
System Language: ru_RU.UTF8

Steps to Reproduce:

1. open folder with no changes (svn status returns no lines)
2. edit some file, save it
3. Undo changes, save it

File is still in the change list, change list is not updated

See also #23

**Comment by JohnstonCode** [comment]
Give 0.8.10 a try.

**Comment by Yanpas** [comment]
It works with 0.8.10!

**Comment by JohnstonCode** [comment]
Cheers for catching that again. Seems I created a regression.
