### ISSUE TITLE
Does this work with svn+ssh?

### ISSUE THREAD

**Issue by speedpacer** [JohnstonCode/svn-scm#260]
- VSCode Version:  1.23.1
- OS Version: Windows 10 1607
- Extension Version: 1.29.0
- System Language:  US
- SVN Version:  1.9.7

## Issue ##
Unable to do a diff between head and local, unable to commit, etc.  I suspect it's because I'm using svn+ssh?

## Steps to Reproduce ##

1.  Make a change in a file, can't view the diff with head
2.  Right-click on file, try to commit, receive error that it could not connect

## SVN Output ##
svn from command line/terminal/Git Bash works fine

**Comment by JohnstonCode** [comment]
Yes it works with svn+ssh. It your repo password protected?

**Comment by speedpacer** [comment]
No, no passwords. I'm the DevOps Engineer and manage the repos.  I'd like to get this working for a group of roughly 30 developers. Tortoise has given us trouble with svn+ssh too, dealing with the finicky  puTTY/TortoisePlink setup.  I was thinking it was something similar.

**Comment by speedpacer** [comment]
I'm using the svn binaries from WANdisco

**Comment by speedpacer** [comment]
I managed to get it working by uncommenting and explicitly defining my ssh path in $AppData/Roaming/Subversion/config : 

`ssh = $SVN_SSH c:/Program Files/Git/usr/bin/ssh.exe -q --`

If I do a "which ssh" in Git Bash, it's defined as /usr/bin/ssh.  So I guess you extension just needs to know where ssh is located.

**Comment by JohnstonCode** [comment]
Ummm not sure what would have been causing that. Never had that issue will testing.

**Comment by JohnstonCode** [comment]
I assume so. I have only installed git bash, VS code and TortoiseSVN without any config changes.

**Comment by speedpacer** [comment]
I guess it's using the svn binaries from your Tortoise install and those are using plink/TortoisePlink, from the PuTTY config in the registry.  The weird thing is that I experienced this on both my home and work computers and I have Tortoise installed at work but not at home. Anyway, maybe someone else will find this workaround useful, although it's not very elegant. Would it be possible to allow users to define the location of the ssh/svn binaries as part of the extensions config?

**Comment by JohnstonCode** [comment]
The extension only uses the SVN binary. Not Sure why you were having issues without poking around on my windows machine. Documentation is something that needs to be put together for this extension. But who likes to document.
