### ISSUE TITLE
svn+ssh with rsa keys as login

### ISSUE THREAD

**Issue by nolkon** [JohnstonCode/svn-scm#263]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Pro
- Extension Version: 1.29.0
- System Language: English
- SVN Version: 1.9.3

## Issue ##
I can't seem to connect to my SVN repo since I require authentication via my RSA key when i attempt to commit changes. 
I have Tortoise installed and it has no issues with logging me in via my key since it prompts me whenever it needs.
From the command line on the terminal within VScode commits work fine and prompts me for my key passphrase once i enter the command.

## SVN Output ##
```
svn: E170013: Unable to connect to a repository at URL 'svn+ssh://<Repo location>/branches/<branch>'
svn: E170012: Can't create tunnel
svn: E720002: Can't create tunnel: The system cannot find the file specified.
```

**Comment by JohnstonCode** [comment]
@nolkon have a look through #260. they were having similar issues.

**Comment by nolkon** [comment]
I just looked over it again and tried what they did by referencing my ssh.exe and just fiddling with that file in general but still no luck. When i try to commit i get the same error as stated before.

**Comment by JohnstonCode** [comment]
Do you get any errors if you try and commit or update from the command line?

**Comment by nolkon** [comment]
No, there is no issue when updating or commiting from the command line I'm prompted for the password to my RSA key and then everything works fine. This was done in the terminal of VSCode.

**Comment by edgardmessias** [comment]
The VSCode run the `svn` command a non interactive environment, like `svn --non-interactive`

You need make the `svn` command work without user interaction.

**Comment by nolkon** [comment]
I just tried adding my rsa key and used ssh-agent via the terminal but it this allows me to run updates and commits without being prompted for a password in the command line only. Commits done via the plugin still fail with the same error.

**Comment by JohnstonCode** [comment]
Can't replicate closing issue.
