### ISSUE TITLE
Add config to ignore UNVERSIONED files in UI 

### ISSUE THREAD

**Issue by mbhargav294** [JohnstonCode/svn-scm#264]
- VSCode Version: Latest
- OS Version: All supporting OS
- Extension Version: Latest
- System Language: Any
- SVN Version: Any

## Feature Request
The number of UNVERSIONED files in our code base is huge and the UI is getting cluttered. I was currently making changes to the installed extension code, which gets wiped every time an update was performed.

My Request is to add a new boolean to settings.json (may be "svn.showUnversioned") should be able to hide the unversioned files from the UI.

**Comment by mbhargav294** [comment]
Thanks! I will create a pull request and update it here.

**Comment by JohnstonCode** [comment]
@mbhargav294 that’s for the SVN ignore command not to hide the changelist

**Comment by JohnstonCode** [comment]
@Fudiou
