### ISSUE TITLE
Visual Studio Code don't tell me if there any new revision from repo

### ISSUE THREAD

**Issue by luca76** [JohnstonCode/svn-scm#265]
- VSCode Version: 1.23
- OS Version: Windows 7
- Extension Version: april 2018
- System Language: Italian
- SVN Version: 1.6.7

## Issue ##

When I start VSCode, it should report if there any new change on repository. I am forced to click on "Update" to get new changes, but doing this I cannot see diffs before update.

## SVN Output ##
```
None interesting.
Refreshing SVN doesn't see. I am forced to click on "Update" to get new changes.
```

**Comment by JohnstonCode** [comment]
@luca76 Can you include the SVN output from when you open VS code, please? It should be checking for new commits and displaying the number of changes.

**Comment by JohnstonCode** [comment]
Closing this issue. Please comment back if you would like me to re-open.
