### ISSUE TITLE
 svn.decorations.enabled has no effect

### ISSUE THREAD

**Issue by julesx** [JohnstonCode/svn-scm#268]
- VSCode Version: 1.23.1
- OS Version: Win 7 SP1
- Extension Version: 1.29.1
- System Language: english
- SVN Version: 1.9.7.27907

## Issue ##

svn.decorations.enabled seems to have no effect. i do not see any colors or badges.

## Steps to Reproduce ##

1. install extension, ensure SVN hooks are functioning
2. notice no changes

**Comment by edgardmessias** [comment]
You followed the steps https://github.com/JohnstonCode/svn-scm#-svn-status-in-file-explorer-see-34 ?

**Comment by julesx** [comment]
![image](https://user-images.githubusercontent.com/3010047/40998844-f8e3e15e-68d6-11e8-915d-1982eaa73f12.png)

**Comment by JohnstonCode** [comment]
Not Able to replicate this on Linux. Will test on windows tonight.

**Comment by JohnstonCode** [comment]
Unable to replicate on windows also

**Comment by julesx** [comment]
It is working. To be honest I’m not sure if something changed or if I never noticed the tiny coloured bars on the side.

**Comment by JohnstonCode** [comment]
Yeah its very subtle.
