### ISSUE TITLE
Not working from WP root folder

### ISSUE THREAD

**Issue by levikmax** [JohnstonCode/svn-scm#269]
- VSCode Version: 1.23.1
- OS Version: Windows 10
- Extension Version: 1.29.1
- System Language: English
- SVN Version: 1-10-dev (TortoiseSVN with command line tools. SVN works via cmd.exe)

## Issue ##
I can not get it work at all. I see only two menu items: Show patch and Ignore files. After i had set svn.path i saw all menu items, but after click on any of them - it dissapear and nothing happens. After resrating the VS code it comes again and again.
Here is the config:
{
    "workbench.startupEditor": "newUntitledFile",
    "explorer.confirmDelete": false,
    "git.enabled": false,
    "svn.path": "%ProgramFiles%\\TortoiseSVN\\bin\\svn.exe" // (i also tried full path with C:\\ the result is same)
}

## Steps to Reproduce ##

1. Open it
2. Click on any SVN menu item and all other items disspaear but two items:  Ignore file and Show patch.

## SVN Output ##
```
Using svn "svn, version 1.10.0-dev (under development)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
```

## Screenshots ##
![svn-issue](https://user-images.githubusercontent.com/18486817/41025840-a9b9065e-697b-11e8-862a-e0e387d2dfe1.png)

**Comment by JohnstonCode** [comment]
Have you checked out a repository and opened it in VS Code?

**Comment by levikmax** [comment]
@JohnstonCode Yes i have checked out a few working copies from my SVN repository and added that folders to the VS Code. The strange thing is i can not even see all menu items. Something i do, but after clicking on any of them - it disappears again. Usually i see them when just open the VS code and not doing anyhting but searching for SVN in the Command Palette.

**Comment by JohnstonCode** [comment]
Can you give me the SVN output when you have a project open and have opened a few files?

**Comment by levikmax** [comment]
is this what you need?
```
Using svn "svn, version 1.10.0-dev (under development)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[ajax.php]$ svn info --xml
```

**Comment by JohnstonCode** [comment]
Are you opening an individual file or a folder?

**Comment by levikmax** [comment]
Looks like i got it work. I had all WP folder opened in the VS code but when i open only the folder that checked out from SVN it works. Is it possible to have full wp folder with nested SVN checked out folders?

**Comment by JohnstonCode** [comment]
Yes, it is possible you will need to adjust this setting ```"svn.multipleFolders.depth": 4```

This will, however, affect performance the larger the number.

**Comment by levikmax** [comment]
thank you!

**Comment by levikmax** [comment]
For other devs who might have the same problem: If you like me work with full folder of WP and checked out some plugins folders via SVN - "svn.multipleFolders.enabled": true do the trick. The default depth is fine.

It is a great extension, thank you for developing it!
