### ISSUE TITLE
changelist is not updated on "+" icon click

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#27]
VSCode Version: 1.17.2
OS Version: ubuntu 16.04
Extension Version: 0.8.10
System Language: ru_RU.UTF8

Steps to Reproduce:

1. create unversioned file
2. press "+" in vcs sidebar
3. file is actually added, but sidebar is not refreshed

**Comment by JohnstonCode** [comment]
Not able to replicate.

![svnadd](https://user-images.githubusercontent.com/10222719/32553701-82575fac-c48f-11e7-9ea1-d0b5ea533b02.gif)

**Comment by Yanpas** [comment]
¯\_(ツ)_/¯

![peek 2017-11-08 17-18](https://user-images.githubusercontent.com/7345761/32553822-f6dfbb80-c4a8-11e7-8f8c-1db690322127.gif)

**Comment by Yanpas** [comment]
Anyway I guess refresh button would be useful. Sometimes I do some svn actions from console.

**Comment by JohnstonCode** [comment]
Yeah, that sounds like a sane idea.

I will also get the update to listen to command calls as well.

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1

**Comment by johnjacobkenny** [comment]
I've come across a similar issue where adding an existing file to an svn changelist does not reflect in the sidebar until I manually press the refresh button at the top.

**Comment by JohnstonCode** [comment]
Currently looking as sorting event stuff out.
