### ISSUE TITLE
Clicking Cancel in commit dialog still attempts to commit

### ISSUE THREAD

**Issue by jacobweber** [JohnstonCode/svn-scm#275]
- VSCode Version: 1.24.1
- OS Version: Mac OS 10.13.5
- Extension Version: 1.29.2
- System Language: en_US
- SVN Version: 1.9

## Steps to Reproduce ##

1. Go to Souce Control
2. Right-click a file and select "Commit selected"
3. Click Cancel
4. Alert appears with "Do you really want to commit an empty message?".

## SVN Output ##
N/A

## Screenshots ##
N/A

**Comment by JohnstonCode** [comment]
@jacobweber Thanks for catching this. Fixed in 1.29.3
