### ISSUE TITLE
Empty commit message warning although the comment is entered in the input field

### ISSUE THREAD

**Issue by SiFreZi** [JohnstonCode/svn-scm#276]
- VSCode Version: 1.24.1
- OS Version: Microsoft Windows [Version 10.0.14393]
- Extension Version: 1.29.3
- System Language: German
- SVN Version: 1.10.0.0

## Issue ##
Although there is text in the commit comment field the empty commit message warning appears when I try to commit. I the commit is done the svn message will be empty. 

## Steps to Reproduce ##
1. open some folder under version control
2. change some file
3. enter comment in the input field
4. click commit changes

## Screenshots ##
![2018-06-19_15h05_20](https://user-images.githubusercontent.com/39189215/41599022-349cc07a-73d2-11e8-996c-4274f2258833.png)

**Comment by JohnstonCode** [comment]
@SiFreZi cheers for spotting this.
