### ISSUE TITLE
Right Click Commit Changes -> esc [to cancel] -> commits "undefined"

### ISSUE THREAD

**Issue by Blfrg** [JohnstonCode/svn-scm#28]
- VSCode Version: 1.19.0-insider 6e4cc713eeb96c7a67453c33e5954e659fcfe3c0 (today's version)
- OS Version: Ubuntu 17.04
- Extension Version: 0.9.0
- System Language: EN-US

Steps to Reproduce:

1. Right-click file to commit from 'changes' pane
2. Prompt for commit message says 'esc' to cancel, press esc
3. Successful commit message displayed
4. Check repo, file is committed with message "undefined"
---

Thanks for the great plugin, and the new feature(s)!

**Comment by JohnstonCode** [comment]
Hi @Blfrg 

Thanks for raising this. Ill have to have a look at the VS Code API docs to see if the implimentation has changed.

**Comment by JohnstonCode** [comment]
This should be fixed in version 0.10.0

**Comment by Blfrg** [comment]
Confirmed, thank you for the quick turn around!
