### ISSUE TITLE
Feature request: changelist context menu

### ISSUE THREAD

**Issue by julesx** [JohnstonCode/svn-scm#281]
**Describe the solution you'd like**
a context menu on the changelist row in the scm panel
  - open these files
  - open these files and close all other files
  - close all other files
  - close these files
  - commit changelist
  - revert changelist files

**Comment by JohnstonCode** [comment]
Not 100% sure if this can be done, will need looking into.

**Comment by edgardmessias** [comment]
@JohnstonCode, for menu, see: https://code.visualstudio.com/docs/extensionAPI/api-scm#_menus

For close all editors: `vscode.commands.executeCommand('workbench.action.closeAllEditors')`

The command `workbench.action.closeAllEditors` change active editor, we can use to scan opened texteditors

**Comment by JohnstonCode** [comment]
From that list i think it would be easy to do

- open these files
- open these files and close all other files
- commit changelist
- revert changelist files
