### ISSUE TITLE
Feature request: ability to change default behavior of double clicking a file in SCM panel

### ISSUE THREAD

**Issue by julesx** [JohnstonCode/svn-scm#282]
**Is your feature request related to a problem? Please describe.**
Currently double clicking a file in the SCM panel opens a diff.

**Describe the solution you'd like**
The ability to change the default double click functionality

**Additional context**
I'd like the default behavior to open a file, as opposed to a diff.

**Comment by Guema** [comment]
> @julesx I agree, This was the original functionality but people prefer it to be like the GIT SCM.
I Think this is something that can be done easily.

Actually, the GIT SCM open file by default, not diff (but maybe it was changed recently)
