### ISSUE TITLE
committing a changelist does not allow you to specify a commit message

### ISSUE THREAD

**Issue by julesx** [JohnstonCode/svn-scm#283]
- VSCode Version: 1.24.1
- OS Version: windows 10
- Extension Version: 1.29.5
- System Language: english
- SVN Version: 1.10

## Issue ##
there is no prompt to enter a commit message when committing a changelist

## Steps to Reproduce ##

create a changelist
click little checkmark in top right of SCM panel
select changelist from dropdown
warning pops up asking if you are sure you want to commit without a message

**Comment by julesx** [comment]
i thought that was a search bar ><

**Comment by JohnstonCode** [comment]
It did have placeholder text. Seems that they have changed it and I need to provide the placeholder now.

**Comment by bardware** [comment]
When creating a SVN changelis in Eclipse editor it's possible to provide a label and a description that is also suggested as the commit message. Maybe it's an option to provide the changelist description as a possible commit message.
How else to commit a changelist if not through the checkmark?
I created a checklist and had no idea how I would eventually commit. I'm glad I found this thread.
