### ISSUE TITLE
Chinese comment not supported

### ISSUE THREAD

**Issue by Larify** [JohnstonCode/svn-scm#286]
- VSCode Version: 1.24.1 (1.24.1)
- OS Version: macOS 10.13.4
- Extension Version: 1.29.6
- System Language: English
- SVN Version: 1.9.7 (r1800392)

## Issue ##
can't commit chinese comment。
try add quotation marks when detected chinese?

## Steps to Reproduce ##

1. change some file
2. add comment and commit

## SVN Output ##
```
[comic]$ svn stat --xml --no-ignore --ignore-externals
[comic]$ svn cat src/html/search.html -r HEAD
[comic]$ svn update --ignore-externals
[comic]$ svn stat --xml --no-ignore --ignore-externals
[comic]$ svn info --xml
[comic]$ svn commit src/html/search.html -m 搜索历史长度截断
[comic]$ svn log -r BASE:HEAD -q --xml
svn: E000022: Commit failed (details follow):
svn: E000022: Error normalizing log message to internal format
svn: E000022: Can't convert string from native encoding to 'UTF-8':
svn: E000022: {U+641C}{U+7D22}{U+5386}{U+53F2}{U+957F}{U+5EA6}{U+622A}{U+65AD}
```

**Comment by edgardmessias** [comment]
@Larify , a small test:

Open the `.vscode\extensions\johnstoncode.svn-scm-x.xx.x\out\svn.js`

Before `const process = cp.spawn(this.svnPath, args, options);`, add the line: `options.env = {"LC_CTYPE": "en_US.UTF-8"};`

Before:
```js
            const process = cp.spawn(this.svnPath, args, options);
```

After:
```js
            options.env = {"LC_CTYPE": "en_US.UTF-8"};
            const process = cp.spawn(this.svnPath, args, options);
```

**Comment by edgardmessias** [comment]
I found a solution for commit messages:

The problem is in decode characters in SVN, ignore defined environments.

To work, use a file with UTF-8 and pass the `--encoding UTF-8` argument.

```
cat 搜索历史长度截断 > /tmp/commit-message.txt
svn commit src/html/search.html -F /tmp/commit-message.txt --encoding UTF-8
```
