### ISSUE TITLE
Fix all the tslint errors

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#288]
`npm run lint`

All the errors need fixing. Some of the rules may need adjusting.

I think we should stop using console.* in favour of sending errors to the output.

**Comment by edgardmessias** [comment]
Maybe we can use the `tslint.json` from `Microsoft/vscode`: https://github.com/Microsoft/vscode/blob/master/tslint.json

**Comment by edgardmessias** [comment]
@JohnstonCode, a alternative: https://github.com/Microsoft/tslint-microsoft-contrib

Usage: https://github.com/Microsoft/vscode-python/blob/master/tslint.json

**Comment by JohnstonCode** [comment]
Sorted it kept it very basic
