### ISSUE TITLE
The "changes" view shows false-positive changes in special characters

### ISSUE THREAD

**Issue by bersbersbers** [JohnstonCode/svn-scm#289]
- VSCode Version: 1.24.1
- OS Version: Microsoft Windows [Version 10.0.17134.112]
- Extension Version: 1.29.6
- System Language: englisch
- SVN Version: svn, version 1.10.0-dev (under development)
(came with latest stable TortoiseSVN 1.10.0, Build 28176 - 64 Bit , 2018/04/14 08:00:32)

## Steps to Reproduce ##

1. Create a repo
2. Create a folder "WC", checkout repo
3. Copy attached Bug.txt to "WC" 
[Bug.txt](https://github.com/JohnstonCode/svn-scm/files/2149034/Bug.txt)
4. Commit Bug.txt to repo
5. Open folder "WC" in VS Code
6. Open Bug.txt
7. Change first line from "foo" to "fou"
8. Go to SVN tab, "Open changes with HEAD"

## SVN Output ##
```
Using svn "svn, version 1.10.0-dev (under development)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[WC]$ svn info --xml
[WC]$ svn stat --xml --no-ignore --ignore-externals
[WC]$ svn info --xml
[WC]$ svn log -r BASE:HEAD -q --xml
[WC]$ svn stat --xml --no-ignore --ignore-externals
[WC]$ svn cat Bug.txt
[WC]$ svn stat --xml --no-ignore --ignore-externals
[WC]$ svn cat Bug.txt -r HEAD
[WC]$ svn cat Bug.txt -r BASE
[WC]$ svn stat --xml --no-ignore --ignore-externals
[WC]$ svn info --xml

```

## Screenshots ##
![image](https://user-images.githubusercontent.com/12128514/42088501-f15d9ada-7b99-11e8-826f-37f0ade5c53c.png)

**Comment by rwatts3** [comment]
Agreed. 

In fact i'm not sure if it's this extension or vscode in general but often time's i'm noticing that the special characters if encoded are being replaced with the rendered version of the character.

**Comment by JohnstonCode** [comment]
Yeah i have noticed this as well. Not sure what is causing it.

**Comment by edgardmessias** [comment]
Try setting the `files.encoding` and `svn.default.encoding` same encoding

**Comment by bersbersbers** [comment]
@edgardmessias  adding `"svn.default.encoding": "utf8"` to settings has indeed fixed this, thank you. (I had `"files.encoding": "utf8"`.)
