### ISSUE TITLE
New folders do not appear in changelist and new files can not be added

### ISSUE THREAD

**Issue by kivervinicius** [JohnstonCode/svn-scm#292]
- VSCode Version: 1.24.1
- OS Version: LInux (Ubuntu 16.04)
- Extension Version: v1.29.6
- System Language: pt-BR
- SVN Version: 1.9.3 (r1718519)

## Issue ##
New folders do not appear in changelist and new files can not be added
## Steps to Reproduce ##

1. Create new folder and new file inside folder.
2. Create a new change list with folder and file.
3. Only file show in changelist
4. I can not send to svn because the folder does not exist on the server

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"

svn: E200009: Commit falhou (detalhes a seguir):
svn: E200009: '/mnt/sda4/Projeto/sistemas/OmegaApi/Avisos/routers/teste' não existe no repositório e não é parte da submissão, ainda assim o filho '/mnt/sda4/Projeto/sistemas/OmegaApi/Avisos/routers/teste/abc.txt' dele é parte da submissão
```

**Comment by edgardmessias** [comment]
I reproduced.

Changelist not working on folders, see [Changelist Limitations](http://svnbook.red-bean.com/en/1.7/svn.advanced.changelists.html#svn.advanced.changelists.limitations)

**Comment by edgardmessias** [comment]
@kivervinicius, see #299
