### ISSUE TITLE
installed extension, edited product.json now what

### ISSUE THREAD

**Issue by mitchjs** [JohnstonCode/svn-scm#293]
so, I installed the extension, edited the product.json
reloaded..

now what...
nothing is under source control
![nosource](https://user-images.githubusercontent.com/747871/42404154-e6d745dc-8154-11e8-930c-5111ef4bf615.jpg)

**Comment by JohnstonCode** [comment]
Have you checked out an svn repository and opened it in vs code?

**Comment by mitchjs** [comment]
Meaning outside of vscode?
Right now I just got a folder of source files and I want to import into repository ... sure I could do it outside if vscode via tortious 

Thanks
