### ISSUE TITLE
Always need authenticate in svn?

### ISSUE THREAD

**Issue by diegoaguiar90** [JohnstonCode/svn-scm#295]
Hi!

First, congrats to your work.
I have more projects in my workspace vscode, all in svn and always when i request the project update the plugin need select the project and svn authentication. Is that normal? Always need authenticate in svn?

- VSCode Version: 1.25.1
- OS Version:macOS High Sierra 10.13.6
- Extension Version: 1.29.6
- System Language: English
- SVN Version: 1.9.7

**Comment by edgardmessias** [comment]
Hello @diegoaguiar90, please update your issue and add:
- VSCode Version:
- OS Version:
- Extension Version:
- System Language:
- SVN Version:

**Comment by diegoaguiar90** [comment]
Updated!

**Comment by edgardmessias** [comment]
Great!

You are using KeyChain to store SVN auth?

Running in terminal: `svn info -r HEAD` you are prompted?

**Comment by edgardmessias** [comment]
Ping @diegoaguiar90
