### ISSUE TITLE
Show recent commits (SVN log)

### ISSUE THREAD

**Issue by luboslav** [JohnstonCode/svn-scm#296]
It would be handy to preview recent commit messages in SVN control panel.

List of changes could be collapsible (like Variables, Watch and Call Stack in debug view) and SVN log could be another collapsible list (maybe at bottom like Breakpoints). The list will display just few recent commits (the number may be configurable through settings). There could also be a detail view of commit with information about revision, date, author and actions.

**Comment by julesx** [comment]
author has said that ideally we would get something like gitlens, but it's a lot of work

**Comment by JohnstonCode** [comment]
Hi @luboslav,

You can already view commit messages through the extension. Click the three "..." next to the source control provider name and select "Show commit messages". This is a very basic format and the number of messages is configurable in the extension settings.
