### ISSUE TITLE
Commit selected commits only one file

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#298]
- VSCode Version: 1.25
- OS Version: kubuntu 18.04
- Extension Version: 1.29.6
- System Language: ru
- SVN Version: 1.9.7 (r1800392)

## Steps to Reproduce ##

1. Select 2 files using CTRL button
2. RIght click, commit selected, enter any message and press enter
3. only one file is commited

## SVN Output ##
```
Using svn "1.9.7 (r1800392)" from "svn"
[trunk]$ svn info --xml
[trunk]$ svn stat --xml --no-ignore --ignore-externals
[trunk]$ svn cat exe_fwctrld/src/fwctrl_dbhelper.hpp
[trunk]$ svn log -r BASE:HEAD -q --xml
[trunk]$ svn info --xml
[trunk]$ svn cat deps/lib_json11/json11.hpp -r HEAD
[trunk]$ svn stat --xml --no-ignore --ignore-externals
[trunk]$ svn commit deps/lib_json11/json11.cpp -m 'json11 update'
```

**Comment by edgardmessias** [comment]
I can't reprocuce

**Comment by Yanpas** [comment]
here is a cast:
![peek 2018-07-18 17-19](https://user-images.githubusercontent.com/7345761/42887482-b8045de0-8aae-11e8-94fd-3f306c147a20.gif)

**Comment by edgardmessias** [comment]
@Yanpas, a small test: select files and choose "Show diff path for selected"

**Comment by Yanpas** [comment]
Only one file is in the patch. Seems like some changes in vscode api?

**Comment by edgardmessias** [comment]
In my machine is working (windows 10, vscode 1.25.1)

My note: if select files and rigth click a non selected file, only file from rigth click commit/diff
but, if select files and rigth click a selected file, work fine

**Comment by Yanpas** [comment]
Even if I select several files - resourcestates array has length 1: :thinking: 
![image](https://user-images.githubusercontent.com/7345761/42890283-1ad72d98-8ab5-11e8-9a52-2e930e04201b.png)

**Comment by JohnstonCode** [comment]
I am also not able to reproduce on windows. Will try Linux tomorrow

**Comment by JohnstonCode** [comment]
Not able to replicate on Fedora 27, VS Code 1.25.1 and extension version 1.29.6

**Comment by Yanpas** [comment]
I've switched `window.titleBarStyle` to `native` and it works. With `custom` it reproduces. The issue is in vs code

**Comment by Yanpas** [comment]
Should I create a bug in vscode repo?

**Comment by JohnstonCode** [comment]
@Yanpas Yes, I would create a bug with them. Not sure what changing the `window.titleBarStyle` does under the hood.
