### ISSUE TITLE
Support for multiple .svn folders

### ISSUE THREAD

**Issue by dpanic** [JohnstonCode/svn-scm#30]
- VSCode Version: Version 1.18.0 (1.18.0)
- OS Version: MacOS High-Sierra
- Extension Version: 0.10.0
- System Language: English

Steps to Reproduce:
Extension doesn't work if you open folder with multiple projects. Only if you open certain folder with one .svn folder inside.

Is this possible to change?

**Comment by JohnstonCode** [comment]
This was a consideration that I had.

The Issue I face was how deep should it check for other repositories. I know the git extension only goes one level deep when looking for repositories.

What would your suggestion be?

**Comment by s-martin** [comment]
Configurable, with 1 level deep as default?

**Comment by dpanic** [comment]
I agree, configurable with default 1 level deep.

**Comment by JohnstonCode** [comment]
That seems like a very reasonable option.

**Comment by edgardmessias** [comment]
Can show an example?

**Comment by JohnstonCode** [comment]
Just means nested repositories. Currently it only checks one level deep. Just need to add a config vale and run a recursive function to scan folders for to the defined depth

**Comment by edgardmessias** [comment]
See my branch: https://github.com/edgardmessias/svn-scm/tree/multiple_svn_folders

**Comment by JohnstonCode** [comment]
Looks good.

I will pull that branch and have a play tomorrow

**Comment by edgardmessias** [comment]
Idea: option to skip some directories (Ex.: node_modules, vendor)

**Comment by JohnstonCode** [comment]
Yes skipping those folders would speed things up a lot.

**Comment by edgardmessias** [comment]
I'm doing some tests with the option to ignore.

**Comment by edgardmessias** [comment]
Done
