### ISSUE TITLE
Option in settings for confirm to revert command

### ISSUE THREAD

**Issue by TiliSleepStealer** [JohnstonCode/svn-scm#300]
At the moment when you revert a file you need to confirm the revert in a small window.
This window is only shown in the bottom right corner, not in direct view of your current focus (which by default is the left side of the screen) and can easily be missed.

I would like so see an option in the setting screen to either disable the popup or have a way where its more visible.

**Comment by JohnstonCode** [comment]
Yes it is a pain since VS Code change the notification position

**Comment by edgardmessias** [comment]
@JohnstonCode, maybe set `modal: true` in `MessageOptions`

**Comment by JohnstonCode** [comment]
yes
