### ISSUE TITLE
Problem by activating plugin

### ISSUE THREAD

**Issue by hellboy81** [JohnstonCode/svn-scm#304]
- VSCode Version: 1.22.2
- OS Version: windows 7
- Extension Version: 
- System Language: EN
- SVN Version:  [svn, version 1.6.17-SharpSvn-tag-1.6.17@1225782-WIN32 (SharpSvn/1.6.17) WIN32, compiled Dec 30 2011, 11:28:20](https://glot.io/snippets/f39dg0i2ae)

## Issue ##

Enabled plugin cannot be activated by VS Code 

Visual Studio 
## Steps to Reproduce ##

1. Plugin Installed using extension marketplace
2. `svn.path` user option is specified, `svn.showOutput`: true as workspace

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

Empty.

Log (Extension) log  is still available with following log lines:

```
[2018-07-26 11:15:42.383] [exthost1] [info] ExtensionService#_doActivateExtension johnstoncode.svn-scm {"startup":true,"activationEvent":"*"}
[2018-07-26 11:15:42.383] [exthost1] [info] ExtensionService#loadCommonJSModule P:\DATA\Programme\VSCodePortable\Data\code\extensions\johnstoncode.svn-scm-1.30.0\out\extension
```

## Screenshots ##

View -> SCM

Source Control
There are no active source control providers

**Comment by JohnstonCode** [comment]
@hellboy81 Try updating VS Code to the latest version then updating the extension to the latest version.

**Comment by hellboy81** [comment]
OK, it helped but:

- how long legacy svn version 1.6 should be supported?
- which advantages should bring integration with TortoiseSVN?

**Comment by JohnstonCode** [comment]
I have not plan to stop supporting 1.6. I'm not sure what you mean by your second question.

**Comment by hellboy81** [comment]
OK, thanks. It works. Issue can be closed
