### ISSUE TITLE
File / folder history support

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#305]
There is git history extension. It would be nice to have something similar for SVN.
I see it as HTML page with list of revisions with messages and dates. After clicking on list item you can see files changed and diff each file with previous revision or open it.
![image](https://user-images.githubusercontent.com/7345761/43256538-a86271b0-90d5-11e8-9ff1-2a2889ea2915.png)

Alternatively it may be implmented as a second list-view in VCS pane . Mad skillz :D 
![image](https://user-images.githubusercontent.com/7345761/43256979-1c277e6e-90d7-11e8-8181-b400f61df557.png)

**Comment by JohnstonCode** [comment]
@Yanpas I think implementing it in a list-view would get cramped. It would be a lot of work to implement it. I am currently working on the list-view stuff for incoming changes. 

It can be added the pile of features requested. Not sure when/if it will ever be done tho.

**Comment by JohnstonCode** [comment]
Yeah, time is always an issue. Think the use of React is to ease the burden of all the events it has to manage.

**Comment by Yanpas** [comment]
@JohnstonCode , I've started implementing this feature in my branch https://github.com/Yanpas/svn-scm/tree/history

Currently I'm facing this issue. All svn-functions are async and called after events occurence from the event-loop. Message-passing between webview and extension process is done by `onDidReceiveMessage` and `postMessage`. The first one receives a callback as an argument and calls it each time there is a new message.
The execution of my async-callback stops after first await. How can I deal with it? Is there a way to push my Promise to global event-loop? I've only found `dispatchEvent` function, but I'm not sure if it is available in extension's process and deals with Promises.

**Comment by JohnstonCode** [comment]
@Yanpas can you give me some idea of what you are trying to do so i can better assist you? Like an example of a problem you are trying to solve.

**Comment by Yanpas** [comment]
I'm implementing a webview similar to "Git history" one. This view and extension may be represented as a web frontend and backend. The frontend needs to obtain the history of commits to display it and to obtain details of each commit. Now I am trying to send a list of commits to the webview. I may send it all at once, but it may be too expensive, so there should be some paging.

**Comment by Yanpas** [comment]
After searching across github repositories I found only one soultion: `executeCommand`. This command should be private (not available in command palette). :thinking:

**Comment by edgardmessias** [comment]
@Yanpas , see documentation: https://code.visualstudio.com/docs/extensions/webview#_scripts-and-message-passing

**Comment by edgardmessias** [comment]
VSCode to Webview: `webview.postMessage({ command: 'xxxx' })` -> `window.addEventListener('message', event => {})`

Webview to VSCode: `acquireVsCodeApi().postMessage({command: 'yyyy'})` -> `webview.onDidReceiveMessage(message => {})`

**Comment by Yanpas** [comment]
Thanks for assistance! My question was how to pass **async** callback to `onDidReceiveMessage`. Instead of async callback , I call `executeCommand` inside callback which solved my problem.

**Comment by edgardmessias** [comment]
Two way. Like:
In VSCode:
```ts
webview.onDidReceiveMessage(message => {
  asyncTask.then(result =>  {
    webview.postMessage({ command: 'xxxx', result: result })
  })
})
```

In webview use only the `window.addEventListener`

**Comment by Yanpas** [comment]
I was using gitlens for some time and it feels much more handy than git-history extension. I think I'll start over with something similar.

**Comment by JohnstonCode** [comment]
@Yanpas can this be closed now?

**Comment by Yanpas** [comment]
Yep
