### ISSUE TITLE
Should the SCM badge count only show for current repo

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#309]
I was working on a project that has a couple of externals. When i select the repository in the SCM view it still shows the counts from the other external repositories (changes / incoming changes).

Should the badge only show the count for the currently selected repository?

**Comment by AnrDaemon** [comment]
I would vote for "current".
I do not necessarily have write access to external repos, and having them count in changelist is irrelevant in such case.

**Comment by edgardmessias** [comment]
The VSCode not has support to define badge count from only current selected repository.

Set `svn.detectExternals` to `false` disable external detection

**Comment by JohnstonCode** [comment]
You are right, Thought there was an on source control change event or something similar.
