### ISSUE TITLE
Only showing two svn repos in source control while using multi-root workspaces

### ISSUE THREAD

**Issue by rbingham** [JohnstonCode/svn-scm#31]
- VSCode Version: 1.18.0
- OS Version: ubuntu 16.04
- Extension Version: 0.10.0
- System Language: 

Steps to Reproduce:

1. Add 3 or more folders to multi-root workspace under svn control
2. Check SCM to show only two svn repos instead of all the repos.
![folders_in_workspace](https://user-images.githubusercontent.com/7032804/32738185-6d6334f4-c859-11e7-9cc0-814f6397ef43.png)
![svn_in_scm](https://user-images.githubusercontent.com/7032804/32738188-70499974-c859-11e7-80dd-9426cac8ae84.png)

**Comment by JohnstonCode** [comment]
Hi @rbingham 

Yes i am able to replicate this. Does the SCM show all three if you close and re-open Code?

**Comment by rbingham** [comment]
@JohnstonCode No, closing and re-opening Code doesn't fix the issue. Thanks for looking into it.

**Comment by JohnstonCode** [comment]
Thanks for raising this. Seems i forgot to add workspace events. Oops!

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1
