### ISSUE TITLE
can get extension to run

### ISSUE THREAD

**Issue by fknebels** [JohnstonCode/svn-scm#311]
I have the tortoisesvn client command line tools installed.  I've installed the svn extension, but when I look at installed source control, I get the message "there are no active source control providers"

When I start vs code I check the svn output tab and see 

Using svn "1.8.13 (r1667537)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[ceii-admin]$ svn info --xml
svn: warning: W155010: The node 'C:\working\ceii\ceii-admin' was not found.

svn: E200009: Could not display info for all targets because some targets don't exist

[ceii-admin]$ svn info --xml
svn: warning: W155010: The node 'C:\working\ceii\ceii-admin' was not found.

svn: E200009: Could not display info for all targets because some targets don't exist

Do I have to add the folder to svn prior to using VS code?

I thought I could add the folder to svn much the same way as the "add project to source control" function works in Visual Studio.

VSCode Version: 1.22.2
OS Version: Windows 7
Extension Version: 1.31.0
System Language: en-US
SVN Version: 1.8.13

**Comment by edgardmessias** [comment]
@fknebels, don't ignore the issue template, please, update with:

- VSCode Version:
- OS Version:
- Extension Version:
- System Language:
- SVN Version:
