### ISSUE TITLE
Ability to update one or more files simultaneously

### ISSUE THREAD

**Issue by Nukium** [JohnstonCode/svn-scm#312]
Hello,

Following the closure of #207 thread it would have been perfect if we could update one or more files simultaneously via a right click ont it in the incoming change view instead of having to update the whole project.

This would be very useful in a context of checking team SVN commits.

Thank you very much.

**Comment by JohnstonCode** [comment]
I will do it as part of my work on [this branch](https://github.com/JohnstonCode/svn-scm/compare/tree-view-incomming-changes)

**Comment by JohnstonCode** [comment]
Ability to update multiple selected items needs https://github.com/Microsoft/vscode/issues/56344

**Comment by JohnstonCode** [comment]
In v1.32.0 in the SVN view in the file explorer you can now pull individual changes.

**Comment by edgardmessias** [comment]
@JohnstonCode, can close?
