### ISSUE TITLE
on delete prompt for svn deletion

### ISSUE THREAD

**Issue by grapestech** [JohnstonCode/svn-scm#314]
- When you delete a file from the project, the resource shows as outgoing (but not with a D marker as a deleted file)
- When trying to commit this deletion, nothing happens. 

Ultimately, deleted files should be marked as deleted and it should be possible to commit those deletes. 

Thanks !

**Comment by JohnstonCode** [comment]
@grapestech If you delete a file it should show as missing in the SCM view. You will then need to right click it and select "Remove selected" for svn to do `svn rm` on the file.

This is very clunky at the moment.

Not sure why the missing decorator is not showing. I will open an issue for this.

**Comment by edgardmessias** [comment]
Idea: On delete file, prompt to user to mark file deleted on SVN

**Comment by grapestech** [comment]
ok great thanks for the clarification.

**Comment by edgardmessias** [comment]
From VSCode 1.22, the `window.showQuickPick` has option to "can many pick"

**Comment by JohnstonCode** [comment]
I think single prompt for all

**Comment by edgardmessias** [comment]
I will make a option to user define a list or expression to ignore some files on delete
