### ISSUE TITLE
Conflicts are not showing in the resource tree

### ISSUE THREAD

**Issue by grapestech** [JohnstonCode/svn-scm#315]
When a file has been modified locally and remotely, it appears both as incoming and outgoing. This should be considered as a conflict file (with a C marker) and should appear once in the tree.

**Comment by JohnstonCode** [comment]
Can you please provide a screenshot?

**Comment by edgardmessias** [comment]
@grapestech, It is not always that it will generate a conflict.

**Comment by grapestech** [comment]
I see what you mean. OK.

**Comment by sameerthekhans** [comment]
As @grapestech said, **C** marker/icon should be display if file is modified in both locally and remotely, Eclipse IDE shows red color for the file icon in this case.
