### ISSUE TITLE
Extension not detecting that folder is under source control

### ISSUE THREAD

**Issue by rbingham** [JohnstonCode/svn-scm#320]
- VSCode Version: 1.26.0
- OS Version: Ubuntu 16.04
- Extension Version: 1.31.1
- System Language: English
- SVN Version: 1.9.3

## Issue ##
After updating to the above version of the extension, it no longer detects that a folder is under source control. The first screenshot shows that there isn't any output or logging available from the extension. The second shows that the folder is under source control (note the .svn directory)
## Steps to Reproduce ##

1.
2.

## SVN Output ##
There is no output or logging

## Screenshots ##
![svn_bug](https://user-images.githubusercontent.com/7032804/44176392-e0b87380-a0a6-11e8-8863-bce3345213f2.png)

![svn_bug2](https://user-images.githubusercontent.com/7032804/44176451-16f5f300-a0a7-11e8-8338-78617975e362.png)

**Comment by Executus** [comment]
I have the same issue. Logged in this morning and Source Control tab is now empty with the message "There are no active source control providers". 

VS Code: 1.25.1
OS: CentOS 7.5.1804
Extension version: 1.31.1
SVN version: 1.7.14

**Comment by Lstoryc** [comment]
Same with me 

Is there any news?

**Comment by chenkksho** [comment]
Encountered the same problem

**Comment by yuzhongyuan93** [comment]
Same with me! Last night I just used this extension, this morning I see the information. At first I thought my vscode is in error. Is there any way?

**Comment by cv0cv0** [comment]
Same with me.

VSCode Version: 1.26.0
OS Version: macOS 10.14 Beta
Extension Version: 1.31.1
System Language: Chinese
SVN Version: 1.9.7

**Comment by fjkang** [comment]
me too

VSCode Version: 1.26.0
OS Version: Win10
Extension Version: 1.31.1
System Language: Chinese
SVN Version: 1.9.7

**Comment by sdir** [comment]
extensions\johnstoncode.svn-scm-1.31.1\package.json
"activationEvents": ["*"],

**Comment by windice007** [comment]
Same

**Comment by huguoliang** [comment]
me too

VSCode Version: 1.26.0
OS Version: Win10
Extension Version: 1.31.1
System Language: Chinese
SVN Version: 1.9.7

**Comment by JohnstonCode** [comment]
Sorry guys, Trying to use Travis to publish the extension and it somehow breaks the extension in the process.

Fixed in 1.31.3
