### ISSUE TITLE
Re-add Incoming Changes to SCM view

### ISSUE THREAD

**Issue by grapestech** [JohnstonCode/svn-scm#323]
Hi,

I think having everything SVN related (local, remote  changes, conflicts etc..)  in the SCM tab is much more useful that splitting the functionality over 2 views. 

Also the File explorer is now crowded especially with the native introduction of the outline view. 
On small screens, it is a hassle expanding / folding resources to view svn changes. 

Is there a reason it was added there? 

N.B: Double clicking on a remote change does not open the compare editor anymore.

**Comment by JohnstonCode** [comment]
The file explorer was always its intended place. It was added to the SCM view for ease.

The functionality is split as for most people use case looking at incoming changes isn't relevant and they just pull all incoming changes.

Having it in the file explorer also allows it to be minimised as there is no need to be constantly looking at incoming changes. It also allows more granular control over what commands are attributed to each state the change can be in. Where as the SCM view is just a blanket set of commands for each group.

**Comment by JohnstonCode** [comment]
I have also opened a new issue to add the left click to incoming changes #324

**Comment by grapestech** [comment]
Hello,

I will try to detail my experience with this latest release as much as I can and why I find the new svn pane in file explorer unusable (it might be for others).

When #207 was initially published it made our workflow much easier. vscode was the only editor I needed unless I had to do more complex svn operations like branching / merging etc...

- Managing code changes locally and remotely was done from 1 consolidated place, the SCM view. As a code maintainer, I constantly look at incoming changes and make decisions based on them. Switching between views is a hassle 
- Both local and incoming changes trees had the same behavior. Clicking on files would open the diff editor with HEAD by default. You could also select multiple files. The only missing part was the introduction of commands on right click (i.e: update individual or selected files)
- Conflicts were easier to detect and manage. 

I can see the added value of the new svn pane in the file explorer for developers not interested in others' changes. However, the UI doesn't feel consistent anymore. 

- A code versioning related view should naturally belong in the SCM view, same as the git experience. 
- With all the new views introduced by vscode (Layout, NPM scripts etc..) which are all welcome, there is little space left for the file explorer. On smaller screens, it can be frustrating to constantly minimize and expand panes.
- It's either 1 file update or all. No selective updates. And if you have multiple projects in your workspace, you can see changes grouped by project but the "update all" in the status bar only works on the active project. You need to go to SCM to select the other project. 
- Reviewing incoming changes now involves more clicks. i.e: changing views, expand SVN pane, expand project name, right click to pull... 
- It seems to me that after a pull, it is now taking longer to refresh the incoming changes view
- The refresh icon does nothing

I know this is a work in progress and I appreciate every bit of time invested in this. 
I hope you find my comments useful. 

Thanks !

**Comment by JohnstonCode** [comment]
Good Morning,

Thanks for putting that together, some very valid points that i had not considered. I think that is because my workflow doesn't require any in depth looking at incoming changes.

The limitation with the TreeView and multiple selects is a pain point. https://github.com/Microsoft/vscode/issues/56344

I think my main concern was the SCM view becoming too cluttered with incoming changes if like me people don't need to care about them.

But you seem to have had value from its presence. I will add it back and also add the single and multiple pull commands to that group. I will also add a config option to hide it if people wish to do so. (default will be shown)

Thanks for your polite feedback it is much appreciated.

**Comment by grapestech** [comment]
Hello, 

This is great ! thanks.

**Comment by grapestech** [comment]
Hi ! Can we expect an update soon ? :)

**Comment by JohnstonCode** [comment]
This will be done and released tonight.

**Comment by JohnstonCode** [comment]
This has been released
