### ISSUE TITLE
Left click open diff incoming changes

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#324]
Need to add the left click command to incoming changes.

**Comment by JohnstonCode** [comment]
Also worth noting. Command should be open diff head for modified, open head for added and one file for deleted

**Comment by grapestech** [comment]
Awesome !

Couple of notes : 

- When no local changes are made to a file, left click doesn't do anything (open diff with head)
- Can we enable multiple selection on incoming changes (like before)

Thanks again.
