### ISSUE TITLE
Status bar disappear

### ISSUE THREAD

**Issue by inceptiongt** [JohnstonCode/svn-scm#326]
- VSCode Version:1.27.0
- OS Version:win10 x64
- Extension Version:1.33.0
- System Language:simple chinese
- SVN Version:1.10.2

## Issue ##
Status bar show nothing,other svn function is useful like commit,revert.
## Steps to Reproduce ##

1.use vscode open a folder that checked out from a code rep. earlier。

## Screenshots ##
![image](https://user-images.githubusercontent.com/20478779/45147200-fc6eef80-b1f6-11e8-94a9-ab334c281ab5.png)

**Comment by JohnstonCode** [comment]
Hi @inceptiongt, can you copy the svn output, please?

**Comment by inceptiongt** [comment]
> Hi @inceptiongt, can you copy the svn output, please?
The svn output is empty,or,how to find the svn output,please.
![image](https://user-images.githubusercontent.com/20478779/45677144-1220d500-bb66-11e8-9632-ce7c2fcf1b6b.png)

**Comment by inceptiongt** [comment]
Using svn "1.10.2 (r1835932)" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[IPM2016111506100000]$ svn info --xml
[IPM2016111506100000]$ svn stat --xml --no-ignore --ignore-externals
[IPM2016111506100000]$ svn info --xml
[IPM2016111506100000]$ svn stat --xml --no-ignore --ignore-externals --show-updates
and I noticed a situation.when i open VScode and project,the status bar show 'Running',but 1 second after,it's dispppeared.and the status bar show nothing.

**Comment by edgardmessias** [comment]
@inceptiongt, with a git project works?

**Comment by inceptiongt** [comment]
> @inceptiongt, with a git project works?

yes
![image](https://user-images.githubusercontent.com/20478779/45987923-9adbcb80-c0a6-11e8-8c21-e6c58e9d0adc.png)

**Comment by JohnstonCode** [comment]
@edgardmessias do you think this could be caused by the name of the branch/trunk?
