### ISSUE TITLE
branches in repo subdirectory : bad behaviour

### ISSUE THREAD

**Issue by Guema** [JohnstonCode/svn-scm#330]
- VSCode Version: 1.27.1
- OS Version: Windows 7 x64
- Extension Version: 1.34.0
- System Language: FR-fr
- SVN Version: 1.9.4

## Issue ##

Switching branch from repo sub-directory will fail by checkouting root repo inside sub-directory.
(repo-seption)

## Steps to Reproduce ##

1. Checkout a repository
2. Go in VsCode > Open Folder
3. Open one of this repository sub/folder or sub/sub/(etc...)/folder.
> bottom left bar seems to understand you are in a repo subfolder, so everything is going well for now
4. Switch branch for any new or existing branch

BUG : at this moment, the extension will not swith the repository path from the root but will switch the selected branch root in current subfolder.

## Precisions and notes ##

to make it more visual, let's imagine "myproject" repo:
`http://myurl.com/svn/myproject/`
First, you checkout trunk in C:/myproject/
Then let's say you open C:/myproject/sub/directory/ in Vscode will show at bottom left :
`trunk/sub/directory`
So everything is perfect so far.
But if you try to switch branch from this sub directory with this extension,
`http://myurl.com/svn/myproject/branches/my_branch_a`
You will get C:/myproject/sub/directory containing 
`http://myurl.com/svn/myproject/branches/my_branch_a` content, and bottom left bar will incorectly display `branches/my_branch_a` (should be `branches/my_branch_a/sub/directory`)
It will so propose you to add tracking for your `sub/directory/` files inside your root. :confused: 

## SVN Output ##
```
[sim2b-editor]$ svn switch https://dev.artefacts-studio.fr/svn/sim2b/trunk
svn: E195012: Path '.' does not share common version control ancestry with the requested switch location.  Use --ignore-ancestry to disable this check.
svn: E195012: 'https://dev.artefacts-studio.fr/svn/sim2b/trunk' shares no common ancestry with 'D:\svn\sim2b\Code\sim2b-editor'

[sim2b-editor]$ svn switch https://dev.artefacts-studio.fr/svn/sim2b/trunk --ignore-ancestry
[sim2b-editor]$ svn stat --xml --no-ignore --ignore-externals
[sim2b-editor]$ svn info --xml Code\Sim2bViewer\Assets\Plugins\Ink
[sim2b-editor]$ svn info --xml Code\Sim2bViewer\Assets\Plugins\JsonDotNet
[sim2b-editor]$ svn info --xml Code\Sim2bViewer\Assets\Plugins\sim2b
```

**Comment by JohnstonCode** [comment]
@Guema thanks for raising this. I will need to do some digging.

**Comment by Guema** [comment]
@JohnstonCode Thanks

as a git guy, i'm quite a newbie in svn, but from what i understand, there is no strict difference between directories and repositories in svn (where git just doesn't track folder at all)

That means that from tortoise svn, i can switch a subdirectory from a branch to another without switching main repository.
I suppose that it will detect changes or even untracked things in main repo, but i can still commit in the switched branch "sub-repository" from my sub-directory.

I suppose the best approach here should probably be like this : search current subdirectory in the other branch root then switch & update from it if found, cancel an throw a "not found" error if missing path.

![image](https://user-images.githubusercontent.com/8943532/45299081-bbcee900-b50a-11e8-8ba9-3c8117be1cc5.png)

I hope it can help, even if im a newbie :/

**Comment by kruzyk** [comment]
Similiar problem here.

I have this structure for branches:
```
^/branches/name/JIRA_TASK1
^/branches/name/JIRA_TASK1-v2
^/branches/name/JIRA_TASK2
^/branches/other_name/JIRA_TASK3
^/branches/other_name/JIRA_TASK4
```
`^/branches/name` contains only subfolders and no files:
```
- JIRA_TASK1
- JIRA_TASK1-v2
- JIRA_TASK2
```

I can change branches only with tortoiseSVN.
In vsc statusbar I can see my full path `branches/name/JIRA_TASK1` but I can't change branch.

When I use Ctrl+Shift+P `SVN: Swich Branch` or click current branch on statusbar I see `branches` on list, then and I click it and now I see list of names:
```
- name
- other_name
```
 I can't click name because when I click on some name to go deeper I see only:
![obraz](https://user-images.githubusercontent.com/35242828/54370084-51446480-4677-11e9-8c68-e86ab242e235.png) and vscode ain't going deeper.

**Comment by JohnstonCode** [comment]
@kruzyk try changing `svn.layout.tagRegexName` to `2`

**Comment by JohnstonCode** [comment]
@Guema is this still an issue?
