### ISSUE TITLE
Can't convert string from native encoding to 'UTF-8'

### ISSUE THREAD

**Issue by paaboo2013** [JohnstonCode/svn-scm#331]
- VSCode Version:版本 1.28.0-insider (1.28.0-insider)
- OS Version:macos 10.14 Beta (18A384a)
- Extension Version:
- System Language:zh-cn
- SVN Version:1.34.0

## Steps to Reproduce ##

1.svn commit
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```
Can't convert string from native encoding to 'UTF-8': {U+8425}{U+9500}/{U+8D85}{U+7EA7}{U+4F1A}{U+5458}{U+6309}{U+5E74}{U+8D2D}{U+4E70}/c{U+7AEF}{U+8D85}{U+7EA7}{U+4F1A}{U+5458}.html
## Screenshots ##
<img width="1024" alt="20180911183900" src="https://user-images.githubusercontent.com/5139124/45355095-04ad9d00-b5f2-11e8-8feb-cd00a5aee8b0.png">

**Comment by edgardmessias** [comment]
Same problem of #286

**Comment by edgardmessias** [comment]
The problem is in decode characters in SVN, ignore defined environments.

With SVNKit (https://svnkit.com) works with files names, but not with commit message (Work with 
 this [comment](https://github.com/JohnstonCode/svn-scm/issues/286#issuecomment-420290400))

**Comment by paaboo2013** [comment]
sloved,thx
