### ISSUE TITLE
Cant disable remote changes tracking

### ISSUE THREAD

**Issue by nkbolg** [JohnstonCode/svn-scm#333]
- VSCode Version: 1.27.1
- OS Version: Ubuntu 16.04.5
- Extension Version: 1.34.0
- System Language: English
- SVN Version: 1.10.0

## Issue ##
Setting
svn.remoteChanges.checkFrequency to 0 doesn't disable remote changes tracking
## Steps to Reproduce ##

1.Set "svn.remoteChanges.checkFrequency" to 0
2.Wait for remote changes notification at the Source Control window

**Comment by JohnstonCode** [comment]
@nkbolg Thanks for raising this issue.

Currently, it needs a restart of VS code to make the changes. It needs updating so it detects changes. 

https://github.com/JohnstonCode/svn-scm/blob/8dbe08d2547297d378615f5bdbbe9e5cfa222847/src/repository.ts#L241

**Comment by JohnstonCode** [comment]
Re-opening as it probably should. Will fix.

**Comment by nkbolg** [comment]
OK, thanks.
