### ISSUE TITLE
Commit failed in using chinese as the commit log.Is it support?

### ISSUE THREAD

**Issue by jctn** [JohnstonCode/svn-scm#336]
When I use Chinese as the commit log, it will prompt a failure; the failures are as follows:Commit failed (details follow): Error normalizing log message to internal format Can't convert string from native encoding to 'UTF-8': {U+3010}{U+4F18}{U+5316}{U+3011}{U+6218}{U+6597}{U+63D0}{U+4EA4}

How to solve the problem? or will you support to use chinese as the commit log?

**Comment by edgardmessias** [comment]
Please, use issue template, update the issue with https://github.com/JohnstonCode/svn-scm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by edgardmessias** [comment]
Version 1.34.1 has Fixed commit message with chinese character (Close #286) (547d913)
