### ISSUE TITLE
Feature: SVN status in file explorer 

### ISSUE THREAD

**Issue by arppl** [JohnstonCode/svn-scm#34]
I'd love to see the SVN status indicated with colors/icons in the file explorer similar to the GIT integration in 1.18:

![GIT file explorer decorations](https://user-images.githubusercontent.com/1794099/31959388-d709c69e-b8f4-11e7-8440-e33a1e742130.png)
Image stolen from https://github.com/Microsoft/vscode/issues/178

Maybe it's possible to reuse the git code from the official extension: https://github.com/Microsoft/vscode/tree/master/extensions/git ? 

I'd be happy to help out, if you can provide me some pointers on where to start (I'm new to VSCode)

**Comment by JohnstonCode** [comment]
Hi @arppl 

This is something that I have wanted to implement. So far I have not found any docs on how to implement this.

I have also looked through the git extension source and can't see anything that stands out.

If you can find any references please let me know.

**Comment by magic-k** [comment]
It seems to be implemented only inside the git extension. From the Changelogs of 1.18:

> There is also a proposed API to allow extension authors to add color decorations to arbitrary resources. We haven't finalized on anything yet but are eager to learn how you would use decorations.

Maybe contact microsoft directly?

**Comment by edgardmessias** [comment]
See https://github.com/Microsoft/vscode/blob/master/extensions/git/src/decorationProvider.ts to implement

**Comment by JohnstonCode** [comment]
Ta, I will have a look.

**Comment by edgardmessias** [comment]
See the link: https://code.visualstudio.com/updates/v1_18#_git-status-in-file-explorer

There is also a proposed API to allow extension authors to add color decorations to arbitrary resources.

**Comment by s-martin** [comment]
In addition, I'd like to see the revision of a file at least in the SCM view

**Comment by edgardmessias** [comment]
@JohnstonCode, you can test my branch? 
https://github.com/edgardmessias/svn-scm/tree/status_file_explorer

How to enable:
* Open the file: `<vscode path>\resources\app\product.json`
* Find `extensionAllowedProposedApi`
* Append `"johnstoncode.svn-scm"` in the array

Example:
From
```json
{
	"extensionAllowedProposedApi": [
		"ms-vsliveshare.vsliveshare"
	]
}
```

To:
```json
{
	"extensionAllowedProposedApi": [
		"ms-vsliveshare.vsliveshare", "johnstoncode.svn-scm"
	]
}
```

This trick is to avoid putting `"enableProposedApi": true` in package.json, allowing to publish in marketplace

**Comment by JohnstonCode** [comment]
@edgardmessias 

Unversioned doesn't seem to work in the file explorer but does in the SCM view.

**Comment by edgardmessias** [comment]
@JohnstonCode, fixed

**Comment by JohnstonCode** [comment]
Yeah looks good and works

**Comment by edgardmessias** [comment]
More suggestion?
Should we release a version?

**Comment by JohnstonCode** [comment]
If you create a PR I will merge it and release it. Get some real-world feedback that way

**Comment by edgardmessias** [comment]
Okay, I'll do some documentation first.

**Comment by derwaldgeist** [comment]
Has this been resolved? I am using svn in combination with VS Code 1.21.1 and cannot get the color-coding work in Windows or macOS.

**Comment by JohnstonCode** [comment]
This uses the ProposedApi once VS code releases it fully it should work.

**Comment by edgardmessias** [comment]
@derwaldgeist, see this [SVN Status in File Explorer](https://github.com/JohnstonCode/svn-scm#-svn-status-in-file-explorer-see-34)

**Comment by derwaldgeist** [comment]
@edgardmessias Oh, cool, thanks. A typical variant of RTFM, I guess :-)

**Comment by teejay-87** [comment]
It only works if we open a folder which is a SVN repository (or its subfolder).
If I open a superfolder it does not work.

**Comment by Zastai** [comment]
It works only partially for me, having opened an svn-controlled folder also containing two svn externals.
Added files in the externals have an A and are colorized (green); their parent directories are also green.

However, modified files, while flagged with an M, are only briefly colorized orange, before being overwritten by a darkish grey color.

**Comment by edgardmessias** [comment]
@Zastai, please, open a new issue

**Comment by Remzi1993** [comment]
It would be nice to put this also in the documentation, where to find product.json:
`/usr/share/code/resources/app/product.json`

I was looking for a long time. I think this is the default location.

**Comment by jflambert** [comment]
Thank you @Remzi1993 !!! Fully agree with your suggestion

**Comment by allanforever** [comment]
Hey guys, I'm trying to get this feature to work, but I had not succeed.
Now the product.json file has this entry
`{
    "extensionEnabledApiProposals": {
		"ms-vsliveshare.vsliveshare": ["contribMenuBarHome", "diffCommand", "documentFiltersExclusive", "fileSearchProvider", "findTextInFiles", "notebookCellExecutionState", "notebookContentProvider", "notebookDocumentEvents", "notebookEditor", "notebookEditorEdit", "notebookLiveShare", "terminalDimensions", "terminalDataWriteEvent", "textDocumentNotebook", "textSearchProvider"]
    }
}`

I tried to add 
`
        "johnstoncode.svn-scm": [],
`
beside the "ms-vsliveshare.vsliveshare" but didn't notice any difference.

Any help is appreciated.

**Comment by allanforever** [comment]
@edgardmessias : is there any other way to (highlight/mark down/put emblem/check) changed files in the Explorer panel?
I can see the list of changed files in Source Control panel, but I would love to see something (even an *) beside the filename in the Explorer panel.
Thanks a lot!

**Comment by seanduuu** [comment]
@allanforms I'm encountering the same issue. Could you please share how you ultimately resolved it? Thanks!

**Comment by allanforms** [comment]
@seanduuu Unfortunately I couldn't find a solution for it. What I do now is to use the Source Control panel a lot more and then I got used to changelists. It helped a lot, specially with files you don't want to upload for a little while, you can put them in "ignore-on-commit" changelist (this list is pre-loaded, if I'm not wrong).

<img width="591" height="579" alt="Image" src="https://github.com/user-attachments/assets/6f94a292-e4fe-4721-a00a-c4c41433f73c" />
