### ISSUE TITLE
Not sure how to get started...

### ISSUE THREAD

**Issue by gravelld** [JohnstonCode/svn-scm#341]
- VSCode Version: 1.27.2
- OS Version: Xubuntu 16.04.1
- Extension Version: 1.34.1
- System Language: en_GB.UTF-8
- SVN Version: 1.9.3

## Issue ##
After I installed the extension it is not clear how to enable it, or whether it is even working.

If I enter the SCM view it says: `There are no active source control providers`.

## Steps to Reproduce ##

1. Install the extension

That's it really - it's not clear what the next steps are. I tried restarting VS code.

## SVN Output ##
```
Using svn "1.9.3 (r1718519)" from "svn"
```

**Comment by JohnstonCode** [comment]
Have you opened a cheked out repository in VS Code?

**Comment by gravelld** [comment]
Erm... no. I expected the extension to allow me to check out a repository.

I just tried this and the SCM view does now populate. Thanks for that... just my expectations I suppose.

**Comment by edgardmessias** [comment]
@gravelld, see the #332
