### ISSUE TITLE
Diff is not encoding aware

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#35]
- VSCode Version: 1.18.1
- OS Version: linux
- Extension Version: 0.10.0
- System Language: ru

Steps to Reproduce:

1. Create repo with file in CP1251 encoding (windows 1251)
2. Save it and commit to repo. (svn st should return 0 lines)
3. Open in vs code, lines with cyrillic symbols will have blue diff stripe. 
![image](https://user-images.githubusercontent.com/7345761/33077137-fd5e0cc8-cedf-11e7-93da-d6b651fc69ce.png)

Some cyrillic text:
```
hello world.
привет мир.
```

PS Personally I prefer UTF8, but I have to work with legacy code :(

**Comment by JohnstonCode** [comment]
#9 

Same issue. I have fixed this in the next release.

**Comment by Yanpas** [comment]
BTW I have tried to repro this issue with git and it reproduces.

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1
