### ISSUE TITLE
Incoming changes with new created files are duplicated on Changes view

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#354]
- VSCode Version: 1.27.2
- OS Version: kubuntu 18.04
- Extension Version: 1.38
- System Language: ru_RU
- SVN Version: 1.9.7

## Issue ##

I work with big svn repo, if there are remote changes which introduce new files then these files are duplicated on Changes pane without any icon. If I click refresh button they disappear.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```
Cannot due to file names are exposed
## Screenshots ##
![image](https://user-images.githubusercontent.com/7345761/46290284-156b8600-c594-11e8-84d8-7cb28c33f3ab.png)

**Comment by edgardmessias** [comment]
Wait for #355

**Comment by Yanpas** [comment]
Thanks, very promptly :smiley_cat:

**Comment by Yanpas** [comment]
Sadly, but it seems to break updates. Running `svn st --show-updates` results in:
```
        *   205673   foo.sh
        *   205673   foo.py
Status against revision: 205676
```

And there are no updates in the sidebar.

Here is xml:
![image](https://user-images.githubusercontent.com/7345761/46306167-29c37900-c5bc-11e8-86cc-70646f65be34.png)

**Comment by edgardmessias** [comment]
@Yanpas, please, open a new issue

**Comment by Yanpas** [comment]
@edgardmessias done https://github.com/JohnstonCode/svn-scm/issues/356
