### ISSUE TITLE
Modified files are not displayed in the sidebar

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#356]
- VSCode Version: 1.27.2
- OS Version: kubuntu 18.04
- Extension Version: 1.38
- System Language: ru_RU
- SVN Version: 1.9.7

## Issue ##
If there are incoming changes with modified files they are not listed in the sidebar

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

## Screenshots ##
Running `svn st --show-updates` results in:
```
        *   205673   foo.sh
        *   205673   foo.py
Status against revision: 205676
```

And there are no updates in the sidebar.

Here is xml:
![image](https://user-images.githubusercontent.com/7345761/46306167-29c37900-c5bc-11e8-86cc-70646f65be34.png)

**Comment by edgardmessias** [comment]
Working fine here.

About your XML, the files `foo.py` and `foo.sh` no have local change, only remote change.

My test show the files in "Remote change" only

**Comment by edgardmessias** [comment]
`wc-status` refer to `work copy` and `repos-status` refer to `remote repository`

**Comment by Yanpas** [comment]
I was talking about Remote Changes

Tried to reproduce it on my home win10 computer:
```
svn st --show-updates
        *        2   b
Status against revision:      3
```
![image](https://user-images.githubusercontent.com/7345761/46314507-6b135300-c5d3-11e8-9257-0ec1a6edbf3c.png)
```
svnadmin create foorepo
svn co file:///d:/foorepo foo
cd .\foo\
touch aaa
echo aa >> a
svn add a
echo bb >> b
svn add b
svn rm --keep-local b
ls
svn ci -m a1
svn add b
svn ci -m b1
svn co ^HEAD
svn up -r1
code .
# some edits to b
svn ci -m r3
svn up -r2
```

And the remote changes are displayed. (means I cannot reproduce)

I think I saw remote changes in bash cli and they were not displayed in the sidebar. Then I clicked refresh button and didn't see any changes (I should have wait for 5 minutes) and opened an issue :)

I will open it if will be able to reproduce tommorow. By the way I think refresh button should update remote changes too
