### ISSUE TITLE
Svn installation not found.

### ISSUE THREAD

**Issue by alllucky1996** [JohnstonCode/svn-scm#357]
![erorsvn](https://user-images.githubusercontent.com/25873131/46410594-95841e00-c743-11e8-91e6-41c8d6dbcba3.PNG)
- VSCode Version: 1.27.2
- OS Version: windows 10
- Extension Version: 2.0.7
- System Language: english
- SVN Version: 1.38.1

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
Svn installation not found.

## Screenshots ##
![erorsvn](https://user-images.githubusercontent.com/25873131/46410674-daa85000-c743-11e8-9540-38ba55ba7541.PNG)

**Comment by edgardmessias** [comment]
For Windows with tortoise, see https://github.com/JohnstonCode/svn-scm#windows

Check the `svn.exe` exists

**Comment by alllucky1996** [comment]
> Đối với Windows có rùa, hãy xem https://github.com/JohnstonCode/svn-scm#windows
> 
> Kiểm tra `svn.exe`tồn tại

**Comment by alllucky1996** [comment]
version 1.9.7 has no svn.exe. other applications as eclipse, visual studio, will be identified svn :(

**Comment by edgardmessias** [comment]
Reinstall the TortoiseSVN and check the option **Command Line Tools**

Alternatives: Download binaries:
* https://subversion.apache.org/packages.html#windows
* https://svnkit.com/download.php (Java Version)
