### ISSUE TITLE
Suggest recent commit messages

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#358]
**Is your feature request related to a problem? Please describe.**
I have a hooks in svn repo which check message format and ususally have to retype some details, like issue number. Having a short list of recent commit messages would be useful

**Describe the solution you'd like**
A dropdown list generated from latest 500 revisions of mine authorship limited by 10.

**Describe alternatives you've considered**

**Additional context**
Eclipse implemetation
![image](https://user-images.githubusercontent.com/7345761/46538747-71e4e300-c8bd-11e8-8c9a-ecb846e09b58.png)

**Comment by edgardmessias** [comment]
Ideas: 
* Maybe a command to select previous commit message?
* If commit message is empty, suggest previous commit message and edit?

**Comment by Yanpas** [comment]
@JohnstonCode @edgardmessias do you think expirience with copying commit message from history log is sufficient?

**Comment by Yanpas** [comment]
Same issue in vscode https://github.com/Microsoft/vscode/issues/26952
