### ISSUE TITLE
Feature request: Add more file-options e.g. Revert

### ISSUE THREAD

**Issue by cnsgithub** [JohnstonCode/svn-scm#36]
Hi, Currently , if you open the context menu for a file in the SourceControl view, there is only one option:

"Commit Selected".

![image](https://user-images.githubusercontent.com/13161711/33171895-4450f28e-d04e-11e7-8c52-32d45f34c863.png)

Consider adding more options, especially "**Revert**" would be very useful here. (Other a nice-to-have but not a must-have)

See the context-menus of an Eclipse SVN-Plugin in comparison.

![image](https://user-images.githubusercontent.com/13161711/33171780-e6f87b5c-d04d-11e7-9853-9fa19f5f7b35.png)

![image](https://user-images.githubusercontent.com/13161711/33171818-098bcc8c-d04e-11e7-8703-3357b9d7f470.png)

**Comment by JohnstonCode** [comment]
Hi @cnsgithub 

Thanks for opening an issue. I do agree the feature set is very limited at the moment.  I do plan on implementing the full set of Svn commands. 

This will be my next port of call once V1.0.0 is released.

**Comment by JohnstonCode** [comment]
Added the ability to revert in v1.1.0

I will add all the other commands in time.
