### ISSUE TITLE
Please add context menu to delete selected unversioned file

### ISSUE THREAD

**Issue by Thaina** [JohnstonCode/svn-scm#364]
Sometimes we have unversioned file in project that want to just delete. It easier to select and delete in list of files at the SCM sidebar

Like this

![image](https://user-images.githubusercontent.com/1042507/46714744-42e8bb80-cc87-11e8-81ca-41315326ac1b.png)

I just want to have another command in that context menu. A delete command that would just delete those files

**Comment by JohnstonCode** [comment]
Thanks for the suggestion, this would be a nice convenience.
