### ISSUE TITLE
Refresh remote changes

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#366]
Add a refresh button to incoming changes resource group and an option to always display it.

**Comment by JohnstonCode** [comment]
@Yanpas Just to clarify, You would like a button that refreshes all found svn repositories, local and external?

**Comment by Yanpas** [comment]
I would like refresh button to refresh local working copy and remote changes. Or alternatively introducing refresh button on remote changes listview : ![img](https://user-images.githubusercontent.com/7345761/46729269-7e868400-cc8d-11e8-9a11-6e028d65c80b.png). This listview must be configurable to be always visible.

Thanks!

**Comment by JohnstonCode** [comment]
Yeah you are edgardmessias where both right config option was best choice

**Comment by Yanpas** [comment]
Wouldn't it better to ask user what does he want? I'm afraid nobody will find this setting

**Comment by edgardmessias** [comment]
I do not like to ask the user, because every new project it will need to respond all over again.

**Comment by Yanpas** [comment]
I meant using user settings, not workspace ones.

**Comment by Yanpas** [comment]
Thanks again!
