### ISSUE TITLE
make commits easier

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#369]
@edgardmessias what do you think about using https://github.com/commitizen/cz-cli and getting semantic-release
 to add the different types in the notes or tags?

**Comment by edgardmessias** [comment]
Make the #351 first

**Comment by JohnstonCode** [comment]
Okay, will do both this evening

**Comment by edgardmessias** [comment]
We can create a script to sort in package.json the `contributes.commands`, `contributes.menus.commandPalette`, `contributes.configuration` and update the README.md
