### ISSUE TITLE
Warning SVN not found. Install it or configure it using the 'svn.path' setting.

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#386]
- VSCode Version: 1.28
- OS Version: kubuntu 18.04
- Extension Version: 1.44
- System Language:
- SVN Version: 1.9.7

## Issue ##
Sometimes after reloading vscode window (after extensions update) I see following warning:
> SVN not found. Install it or configure it using the 'svn.path' setting.

The folder which I'm opening doesn't contain svn repository, only git.

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by JohnstonCode** [comment]
I'm also getting this when debugging sometimes.

**Comment by Yanpas** [comment]
Seems like a regression, didn't notice it a couple weeks ago or earlier

**Comment by edgardmessias** [comment]
@JohnstonCode , what your OS version?
Here with Windows 10 never showed the warning

**Comment by JohnstonCode** [comment]
i get it on Fedora 27

**Comment by edgardmessias** [comment]
Need check the https://github.com/JohnstonCode/svn-scm/blob/master/src/svnFinder.ts#L123

**Comment by Yanpas** [comment]
The issues is in `checkSvnCommand`. Seems like some synchronization issues in `cp` module. If I add console.error - then buffers are calculated succesfully every time. On the screenshot the are empty

![image](https://user-images.githubusercontent.com/7345761/47083544-988a0e80-d219-11e8-88a1-ce53af4dfb57.png)

**Comment by Yanpas** [comment]
I guess "exit" handler may be called **before** "data" handler, so that leads to this behavior.

**Comment by Yanpas** [comment]
According to [docs](https://nodejs.org/api/child_process.html#child_process_event_close) signal `exit` should be replaced with `close`, since `close` is emmited when all streams are closed. Tested - it helps. I'll open a PR
