### ISSUE TITLE
Detect svn repos in subfolder

### ISSUE THREAD

**Issue by llgcode** [JohnstonCode/svn-scm#390]
- VSCode Version: 1.28.2
- OS Version: win10
- Extension Version:  1.44.1
- System Language: English
- SVN Version: svn, version 1.9.5-SlikSvn (SlikSvn/1.9.5)

## Issue ##
I have a folder with multiple svn repo in it, I can't see these repositories in Source Control when opening  the folderA.
example:
folderA/subfolderB/.svn
folderA/subfolderC/.svn
folderA/subfolderD/.git

Git repositories are found but not svn one.

regards,
Laurent

**Comment by edgardmessias** [comment]
Have you enabled the `svn.multipleFolders.enabled` option?

**Comment by llgcode** [comment]
Sorry I was not aware of this option. It works great. 
Thank you @edgardmessias

**Comment by umdstu** [comment]
I could be missing something here - but I have enabled multiple Folders (set to true in user settings.json) and depth is at default 4. Similarly to above, my folder structure is:

```
parent/
   project1/
     dir/
     dir-svn/
  project2/
     dir/
     dir-svn/
```

I open VSCode on the parent` `directory`, but it doesn't detect the .svn directory in `dir-svn`.

Same VSCode and Extension versions as above.
