### ISSUE TITLE
Ability to show changes (incoming or local) in tree view vs flat view

### ISSUE THREAD

**Issue by grapestech** [JohnstonCode/svn-scm#392]
Provide the ability to view the changes in a hierarchical tree view.
This will make it easier to update / commit certain folders only at parent level.

**Comment by carlittoer** [comment]
Hello ! 

Is this planned? It's really useful to see changes in a tree like structure

**Comment by JohnstonCode** [comment]
Closing this after looking at it. It is far too complex to impliment

**Comment by grapestech** [comment]
Hi,

Now that vscode supports trees in the scm view, it would be great to support actions on folders.

**Comment by JohnstonCode** [comment]
Create a new issue and i will have a look.

**Comment by JohnstonCode** [comment]
@grapestech actually hold that thought https://github.com/microsoft/vscode/issues/82203#issuecomment-540664631
