### ISSUE TITLE
Open file on click

### ISSUE THREAD

**Issue by carlosm1979** [JohnstonCode/svn-scm#4]
A suggestion.
Open file when you do click on filename in changes list.

**Comment by JohnstonCode** [comment]
Thank you for your suggestion.

This is something that I will be adding. 

After using GIT on vs code I find myself clicking the files as well.

**Comment by JohnstonCode** [comment]
Thanks again for this suggestion. 

This is now live in version 0.4.0

Enjoy!

**Comment by carlosm1979** [comment]
Great, just updated.

Thanks a lot.
