### ISSUE TITLE
Extension not asking for new credentials

### ISSUE THREAD

**Issue by PhanindraNath** [JohnstonCode/svn-scm#401]
VSCode Version: 1.29.0 (user setup)
OS Version: 1709
OS Build: 16299.726
Extension Version: v1.45.2
System Language: English(India)
SVN Version: TortoiseSVN 1.10.28176

**Issue**

If I use tortoise SVN in file explorer, it is prompting for the new password when the password for SVN changes remotely. But this SVN extension does not show any error or prompt for the new password in the same case. Besides that, the extension says, **Updated** as status in the Status bar. But when I try to updating manually, it just displays a message showing unable to update. After this manual update also, the status does not change. So, how can I know if there are any pending updates from the repository?

**Steps to Reproduce**
1. Open VS code (make sure there are some pending updates in the SVN repository).
2. Now change the SVN repository password remotely(Using administrator system).
3. Send the system to sleep mode. (Steps 2 & 3 are interchangeable).
4. Now wake-up your system and go to VS code (I have not closed the VS code earlier).
5. Check the SVN status in the status bar, shows: **updated.**
6. Anyway, click on Update on the status bar. You will get error notification says **Unable to update.** But the status is still **updated**.

**Solution expected:**
Display proper message which shows " there is some authentication error or Password expired."  And prompt for the new password.

If I close and re-open the VS code and SVN extension are working as expected. But I want to resume the work VScode as I use any other app.

**The alternative solution I have used**
Initially, I have no idea why it's not working, So I used Tortoise SVN in system file explorer. After many occurences of same case I undersood the issue.

**Comment by edgardmessias** [comment]
Hello, first, update the issue with template: https://github.com/JohnstonCode/svn-scm/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
