### ISSUE TITLE
Edited changes are not showing for commit

### ISSUE THREAD

**Issue by midhun-narayan** [JohnstonCode/svn-scm#402]
- VSCode Version: Version 1.28.2 (1.28.2)
- OS Version:10.13.4 (17E199)
- Extension Version:1.45.0
- System Language: English
- SVN Version:  version 1.10.2 (r1835932)

## Issue ##
in svn section not showing changed files for committing 
If i try to update the project all files are successfully updated but in change section nothing is displaying
## Steps to Reproduce ##
Edited one file then try to commit 
1.
2.

## SVN Output ##
```

file locking has been enabled on the file server
svn: E200033: sqlite[S5]: database is locked
svn: E200042: Additional errors:
svn: E200033: sqlite[S5]: database is locked

[InfiniteMLM]$ svn update --ignore-externals
[InfiniteMLM]$ svn log -r HEAD:1 --limit 50
[InfiniteMLM]$ svn diff
```

**Comment by edgardmessias** [comment]
Maybe the #413 solve this.

Your problem is another process are locking the database of SVN.

You are using another editor? I have the issue with NetBeans ()

**Comment by JohnstonCode** [comment]
If this is still an issue please re-open
