### ISSUE TITLE
Anotations support

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#411]
Gitlens has very nice feature called annotations (blame), porting it here seems not difficult. I think I'll take this task.

**Comment by JohnstonCode** [comment]
@Yanpas you looked at https://marketplace.visualstudio.com/items?itemName=beaugust.blamer-vs

**Comment by Yanpas** [comment]
Yes, I use it curently, but gitlens's implementation is much better and allows to track changes easier. It is similar to one used in jetbrains IDEs.

**Comment by JohnstonCode** [comment]
Okay, was just wondering.

**Comment by LukePeltier** [comment]
+1, having a feature like this would be great

**Comment by charltonstanley** [comment]
This would be awesome! :+1: Has any progress been made by chance?

**Comment by Yanpas** [comment]
I did some experimental commits in some branch in my fork, but since I use git at my current position I don't have much interest ¯\_(ツ)_/¯
