### ISSUE TITLE
Refresh button in explorer view doesnt work

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#420]
## Steps to Reproduce ##

Let's say we are at revision 100
1. svn up -r99
2. press refresh button at the explorer bar
3. Nothing happens ("svn.refresh.remoteChanges": true doesn't make any effect)

## Screenshots ##
![image](https://user-images.githubusercontent.com/7345761/48730172-9ec13f80-ec4a-11e8-99cd-2762bbea23ec.png)

**Comment by JohnstonCode** [comment]
Noting will happen because there are no changes as far as svn is concerned. You have just jumped back in history but it still knows what the current revision is.
