### ISSUE TITLE
Needs a user guide.

### ISSUE THREAD

**Issue by yaclnb** [JohnstonCode/svn-scm#426]
**Is your feature request related to a problem? Please describe.**
In a word, yes.

My environment:
- TortoiseSVN 1.11.0, Build 28416 - 64 Bit installed with Command Line Tools.
- SVN Subversion 1.11.0 installed as part of Tortoise. 
- SVN Extension 1.46.3 installed in VS Code 1.29.1- 

I've set up a repository in the cloud, and working directory set up on my computer.
I created a file, added it, committed it, made several changes using Notepad and TortoiseSVN.
From the repository/working directory standpoint, everything is set up and working properly.

However, in VS Code, View | SCM brings up the Source Control Panel, with the message "No source control providers registered." This appears to be a show-stopper. 

I tried going to Edit | Preferences | Extensions | Svn and set the Default Checkout Directory to my working directory, closed and re-opened VS Code, but nothing changed. 

I also tried reinstalling the SVN plug-in, but nothing changed. 

Control-Ship-P svn:Update selected changed nothing, and resulted in no output anywhere I could find.

I can neither figure out what to do next to fix the problem, nor figure out what I've done wrong. 

**Describe the solution you'd like**
A user guide, with use cases, pictures, and a troubleshooting section would be really nice. 
I would be happy to help you write one. I am a former Software Developer and a former Technical Writer.

**Comment by mjunior-fitec** [comment]
Same situation here.
I have Tortoise SVN in Windows, with command line tools. PATH is ok, extension installed on latest version of VSCode.  product.json file updated with "johnstoncode.svn-scm"
Stucked here, with  "No source control providers registered."  message and no idea about what directions I should take.

**Comment by edgardmessias** [comment]
On the project run the lines and paste the result:
```sh
svn --version --quiet
svn info --xml
```

**Comment by mjunior-fitec** [comment]
That's great. Thanks for the prompt help.
The svn info command shown me what was wrong. My bad...
Once I choose the correct folder (already submited), it shows my unversioned files on the "Source Control" tab.

Here are the results you asked:
```
svn --version
svn, version 1.10.0-dev (under development)
   compiled Apr 14 2018, 10:24:15 on x86-microsoft-windows
```

On the wrong directory:
```
svn info --xml
<?xml version="1.0" encoding="UTF-8"?>
<info>
svn: E155007: 'C:\Users\-------' is not a working copy
```

On the correct directory:
```
svn info --xml
<?xml version="1.0" encoding="UTF-8"?>
<info>
<entry
   path="."
   revision="12"
   kind="dir">
<url>http://------------/src</url>
<relative-url>^/trunk/sw/src</relative-url>
<repository>
<root>http://--------------</root>
<uuid>6da079e3-482f-eb4c--------------------</uuid>
</repository>
<wc-info>
<wcroot-abspath>C:/Users/-----------------------</wcroot-abspath>
<schedule>normal</schedule>
<depth>infinity</depth>
</wc-info>
<commit
   revision="2">
<author>*************</author>
<date>2018-05-11T14:37:27.598781Z</date>
</commit>
</entry>
</info>
```


Thanks a lot !!!

**Comment by yaclnb** [comment]
Thanks for the tip, Edgard. Running those two commands revealed that svn couldn't find my repository. 

I thought File | Preferences | Settings |  Default Checkout Directory would identify my working directory, but I was wrong.  

I had to open the folder containing the working directory in VS Code before the extension could locat the repository and things started to work properly. 

In one sense, I no longer have a problem, so I'm happy, and you can consider the problem closed. But I think you guys have better things to do than field questions that could be answered in a user guide.  My offer to help you write one still stands.

**Comment by markuskramerIgitt** [comment]
Thank you for pointing out the solution:

"Open the folder containing the working directory in VS Code"

**Comment by IntoCpp** [comment]
Similar situation, (Linux / CentOs-7, LAN repo,  constrained environment).
Installed and nothing shows up anywhere, except for an "SVN" group in the explorer Window that stays empty. I don't see anything in any menus. 
A small screen capture of the final result would go a long way revealing if the install works or not. Just show how to do a "show log" for example. 

All operations using the command line works fine.

```
>svn --version --quiet
1.8.11
```

So an older version of the client. Would this be a problem? If so an indication would be appreciated on the main page. (I'm not sure I'm permitted to upgrade on this system).
```
>svn info --xml
<?xml version="1.0" encoding="UTF-8"?>
<info>
<entry
   path="."
   revision="77777"
   kind="dir">
<url>http://bla-svn1/svnroot/bla/integ</url>
<relative-url>^/bla/integ</relative-url>
<repository>
<root>http://bla/svnroot/bla</root>
<uuid>196c5c37-bla-bla-bla-blablabla</uuid>
</repository>
<wc-info>
<wcroot-abspath>/home/bla/SVN/bla</wcroot-abspath>
<schedule>normal</schedule>
<depth>infinity</depth>
</wc-info>
<commit
   revision="77777">
<author>blabla</author>
<date>2019-03-14T18:28:55.531836Z</date>
</commit>
</entry>
</info>
```

**Comment by bauinformatiker** [comment]
Hello,

similar problem here. 

> svn --version --quiet
1.12.0

>svn info --xml
<?xml version="1.0" encoding="UTF-8"?>
<info>
svn: E155007: 'C:\Users\USERNAME' is not a working copy

Of course, because I want to checkout my first working copy with VSCode, but I can't find the option anywhere. Does anybody know what I need to do?

**Comment by edgardmessias** [comment]
@bauinformatiker : `Ctrl + Shift + P -> SVN: Checkout`

**Comment by bauinformatiker** [comment]
> 
> 
> @bauinformatiker : `Ctrl + Shift + P -> SVN: Checkout`

ok, then checkout not in vscode, but in command line or tortoiseSVN. At my Windows client PC, but at the MacBook of my collegue we are desperate with macOS not showing us real paths in Finder. This is a different problem, but shows it would be very helpful to have to checkout function within the svn plugin auf vscode.

**Comment by scotNZ** [comment]
Anyone come from other IDE's with integrated SVN capability will be pretty confused.

As @bauinformatiker indicates the extension does not work in the manner of a fully integrated svn client plugin (no criticism intended). For example it is simply not obvious that checking out needs to be executed through the command palette.

For new users my advice is to use tortoise svn to create your rep (and lodge any initial files in the rep that you may already have). Now open/create a Working Copy folder in a desired location using the tortoise svn rep browser. This will create a working copy folder with the svn meta. Now open that folder using VSCode - the folder should be recognised as an svn working copy and version control menus in VSCode will be SVN related.

Have a look at the VSCode web pages giving guidance for GIT usage from VSCode. Suggest something similar would help no end. 

I see above there are various offers to help with a user guide ....
