### ISSUE TITLE
Lock / Release lock 

### ISSUE THREAD

**Issue by d-denver** [JohnstonCode/svn-scm#427]
In our repository files need to lock. It would be nice to add the appropriate operations to the context menu of the file.

**Comment by surgien** [comment]
+1

**Comment by Bjego** [comment]
Any news on this issue?

Here is a nice locking overview: https://www.thegeekstuff.com/2014/07/svn-lock-unlock-examples/

**Comment by Olafxso** [comment]
Hi,

I would like to use the lock/unlock option too. Is there a possibility to get this option?

**Comment by JohnstonCode** [comment]
I currently have 0 time to work on the extension. Feel free to create a PR.
