### ISSUE TITLE
There are no active source code providers under the version 1.46.3

### ISSUE THREAD

**Issue by kawhi66** [JohnstonCode/svn-scm#428]
os system: macOS Majave 10.14.1
vs code: 1.29.1
svn: 1.10.0

![image](https://user-images.githubusercontent.com/15883911/49348718-fe572a80-f6e1-11e8-9f4c-49944bf0bd1b.png)

**Comment by JohnstonCode** [comment]
Sorry for the delay, Can you copy the output of the svn output here, please?

**Comment by JohnstonCode** [comment]
If you are unsure of how to get it got to `view -> Output` then use the menu and select `Svn`

**Comment by kawhi66** [comment]
it's alright, I know what to do.

the first time I select the Svn, there are multiple lines of infomation output, but when I reopen the vscode and select the Svn again, there is only "_Using svn "1.10.0" from "/usr/bin/svn"_" was output. here is the screenshot.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/15883911/50209208-287d3d80-03ae-11e9-8677-cd0f905db9af.png">

**Comment by kawhi66** [comment]
here is another screenshot when I run _svn info_ in the terminal.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/15883911/50209555-0c2dd080-03af-11e9-8349-4ac7fc34e305.png">

**Comment by JohnstonCode** [comment]
Do you have a `.svn` folder in your project root?

**Comment by kawhi66** [comment]
no, I don't have .svn in the root, do I need one, is it necessary?

**Comment by kawhi66** [comment]
sir, I still can't get it work, even when I open the root folder, and here is the screenshot of my user config.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/15883911/50212270-94af6f80-03b5-11e9-9a1c-0b3217bfd884.png">

**Comment by JohnstonCode** [comment]
Can you run these two commands and put the output in here please ```
svn --version --quiet
svn info --xml
```

**Comment by kawhi66** [comment]
`KawhideMacBook-Pro:tq_huiclient kawhi$ svn --version --quiet
1.10.0
KawhideMacBook-Pro:tq_huiclient kawhi$ svn info --xml
<?xml version="1.0" encoding="UTF-8"?>
<info>
<entry
   revision="246"
   kind="dir"
   path=".">
<url>https://192.168.57.66/AMS/dept1/OIS/trunk/Sources/webserver/tq_huiclient</url>
<relative-url>^/trunk/Sources/webserver/tq_huiclient</relative-url>
<repository>
<root>https://192.168.57.66/AMS/dept1/OIS</root>
<uuid>eed0b98b-10e3-e34e-8928-dc5cfdf6d7ca</uuid>
</repository>
<wc-info>
<wcroot-abspath>/Users/kawhi/Desktop/tq_huiclient</wcroot-abspath>
<schedule>normal</schedule>
<depth>infinity</depth>
</wc-info>
<commit
   revision="245">
<author>panjn26369</author>
<date>2018-12-19T09:34:11.905474Z</date>
</commit>
</entry>
</info>`

**Comment by kawhi66** [comment]
```
KawhideMacBook-Pro:tq_huiclient kawhi$ svn --version --quiet
1.10.0
KawhideMacBook-Pro:tq_huiclient kawhi$ svn info --xml
<?xml version="1.0" encoding="UTF-8"?>
<info>
<entry
   revision="246"
   kind="dir"
   path=".">
<url>https://192.168.57.66/AMS/dept1/OIS/trunk/Sources/webserver/tq_huiclient</url>
<relative-url>^/trunk/Sources/webserver/tq_huiclient</relative-url>
<repository>
<root>https://192.168.57.66/AMS/dept1/OIS</root>
<uuid>eed0b98b-10e3-e34e-8928-dc5cfdf6d7ca</uuid>
</repository>
<wc-info>
<wcroot-abspath>/Users/kawhi/Desktop/tq_huiclient</wcroot-abspath>
<schedule>normal</schedule>
<depth>infinity</depth>
</wc-info>
<commit
   revision="245">
<author>panjn26369</author>
<date>2018-12-19T09:34:11.905474Z</date>
</commit>
</entry>
</info>
```

**Comment by JohnstonCode** [comment]
Are you using a VPN?

**Comment by JohnstonCode** [comment]
Can you also copy in your working copy root path from the svn info you ran in the terminal?

**Comment by JohnstonCode** [comment]
Can you try checking out your project in a directory that doesn't contain any Chinese characters in its full path?

**Comment by kawhi66** [comment]
yes, sir, it does. the root folder is inside a directory named by Chinese.
and after I rename it in English, it works.

**Comment by kawhi66** [comment]
by the way, I can access to the github.com without using vpn, it's not necessary, only if trying to access google.com.

**Comment by kawhi66** [comment]
sure, my pleasure.

since I just rename the directory, I believe the original path looks like "/Users/kawhi/Desktop/Projects/场外投资管理平台/OIS/Sources/webserver/tq_huiclient". 

the root path of svn is "/Users/kawhi/Desktop/Projects/场外投资管理平台/OIS".

**Comment by JohnstonCode** [comment]
Thanks!
