### ISSUE TITLE
Source Control Providers list modified when updating unrelated folders

### ISSUE THREAD

**Issue by julesx** [JohnstonCode/svn-scm#433]
- VSCode Version: 1.29.1
- OS Version: Win 10
- Extension Version: 0.1.1
- System Language: English
- SVN Version: 1.11.0

## Issue ##

Updating svn folders that are sub folders of a workspace root updates the Source Control Providers list incorrectly.

## Steps to Reproduce ##

Given a workspace like so:

![image](https://user-images.githubusercontent.com/3010047/49601052-c571bc80-f952-11e8-912a-866dd7379ddc.png)

With a user setting like so:

    "svn.ignoreRepositories": [
			"c:\\my stuff\\COMMONDEV"
		],

Results in a Source Control Providers list like so:

![image](https://user-images.githubusercontent.com/3010047/49601120-f520c480-f952-11e8-8602-4f2de421a67b.png)

This is great so far.  However, if I then open up my workspace root directory (commondev) in windows explorer, and issue svn updates on folders that contain unrelated projects, those folders will update into the Source Control Providers list.

![image](https://user-images.githubusercontent.com/3010047/49601216-37e29c80-f953-11e8-9ba7-6575174b8d9a.png)

running svn update commands should not be modifying my vs code environment.  I have tried adding these paths to ignoreRepositories settings, it doesn't seem to have any effect.

**Comment by JohnstonCode** [comment]
Unable to replicate this. @edgardmessias can you?

**Comment by JohnstonCode** [comment]
Can replicate this now

**Comment by JohnstonCode** [comment]
Looking back at this not 100% sure what the issue is. Is `COMMONDEV` a folder or a repository with nested repositories?
