### ISSUE TITLE
onDidChangeRepository event should have threshold

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#434]
The case:
I do some operation from CLI with repo, e.g. svn update
It modifies two files inside .svn folder
After first file got modified the vent is emmited, svn status is executed and there are no changes
The the second file gets modified, but the event is suppressed since another event took place recently

I suggest adding threshold, 200ms e.g. after which event is fired.

**Comment by edgardmessias** [comment]
My suggestion:
* For external changes, add 200ms threshold
* For internal changes: wait for `this.onDidRunOperation`, like `whenIdleAndFocused` in `repository.ts`
