### ISSUE TITLE
Subfolders in ignored folder

### ISSUE THREAD

**Issue by d-denver** [JohnstonCode/svn-scm#436]
- VSCode Version: 1.30.0
- OS Version: Windows 7
- Extension Version:  1.46.4
- System Language: Russian
- SVN Version: svn, version 1.8.19 (r1800620)

## Steps to Reproduce ##

1. Repository Folders:
-Applications
--public
---company
---catalog
---...
--bitrix
---components
-----b1team

2. Project Folders:
-bitrix
--...
-company
-catalog
-...

Root folder of project extracted from Applications->public
Folder "bitrix" marked as "ignored", becouse it contains ~150Mb of files. We don't need this whole folder in the repository. But some subfolders of "bitrix" we add to repository (our code). Therefore, in the project folder we connect separately to the repository the root folder and separately some folders inside the ignored bitrix folder. 

VSCode SVN extension sees only the root folder. The connected subfolders in the bitrix folder are not perceived by the extension as folders under the repository.

**Comment by JohnstonCode** [comment]
How are you marking "bitrix" as Ignored? through the extension settings?

**Comment by d-denver** [comment]
Sceenshots:
![root](https://user-images.githubusercontent.com/22634689/50136305-6d1eb100-02a8-11e9-90a1-32377a22d7dc.png)
![subfolder](https://user-images.githubusercontent.com/22634689/50136307-70b23800-02a8-11e9-97b4-1cd364312b75.png)

**Comment by JohnstonCode** [comment]
If the 'bitrix' folder is marked as ignored by svn then the extension will have no vision of it.

**Comment by d-denver** [comment]
Can you add some setting so that the ignored folder extension checked?

**Comment by JohnstonCode** [comment]
The subfolders of an ignored folder will not return any information when queried by svn.

**Comment by d-denver** [comment]
How about of subfolders of ignored folders?
Maybe find in subfolders ".svn" and quering finded path?
/bitrix/ - igonred, svn not returned info
/bitrix/components/b1team/ - svn return info
?

**Comment by JohnstonCode** [comment]
Do you get any output if you run `svn info bitrix/components/b1team`?

**Comment by d-denver** [comment]
Yes. 
![svninfo](https://user-images.githubusercontent.com/22634689/50216996-7129fc00-0398-11e9-8508-c5da75a4062e.jpg)

**Comment by JohnstonCode** [comment]
Okay can you open a file from the b1team directory and copy the svn output please

**Comment by JohnstonCode** [comment]
So if you make any changes to that file they don't show up on the SCM view?

**Comment by d-denver** [comment]
Yes

**Comment by JohnstonCode** [comment]
Do they appear if you do `svn stat` from the root of your project?

**Comment by d-denver** [comment]
From root - no
From bitrix/components/b1team - yes

**Comment by JohnstonCode** [comment]
That's the problem then. `svn stat` is only run from the root of the project.

**Comment by d-denver** [comment]
In extension settings there is an option "Multiple Folders". Extension really finds all the folders in the project under version control, but only if root folder is not under version control. 

Perhaps in the context of the "Multiple Folders" option, simply allow the extension to search for folders inside ignored folders?

**Comment by JohnstonCode** [comment]
That could be possible but requires a large amount of work. I would recommend opening a feature request issue. I can't give any time on if/when it will be picked up. You are free to implement this if you need it enough.

**Comment by d-denver** [comment]
> I would recommend opening a feature request issue
Ok. 
> You are free to implement this if you need it enough.
I myself do not know how to program extensions, and most likely, too, it will take a long time until the hands reach it.
