### ISSUE TITLE
Extension doesent work with Chinese chars in file paths

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#439]
Follow on from #428 

Path that breaks extension is "/Users/kawhi/Desktop/Projects/场外投资管理平台/OIS/Sources/webserver/tq_huiclient"

**Comment by edgardmessias** [comment]
Tryp with svnkit (jsvn)

**Comment by edgardmessias** [comment]
Only work with svnkit (jsvn)
The command `svn add --targets <tmp_file>`, when `tmp_file` has a list of files, does not work
