### ISSUE TITLE
Unable to commit

### ISSUE THREAD

**Issue by JadynWong** [JohnstonCode/svn-scm#44]
- VSCode Version:1.18.1
- OS Version:windows 10 1709
- Extension Version:1.20
- System Language:chinese

Steps to Reproduce:

1.Only show **Unable to commit**,Can't find any error msg.Include output panel
2.I use **Command Line Tools** is normal

**Comment by JohnstonCode** [comment]
Hi @JadynWong 

Can you update to v1.2.1. This should provide a clearer error message.

**Comment by edgardmessias** [comment]
The error message: `TypeError: Cannot read property 'fsPath' of undefined`

When you do not select files for commit, show this error.

If you only commit selected files, the problem does not occur
