### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#446]
Since @edgardmessias improved test coverage, it has slowly been decreasing. Aiming for > 80%

**Comment by edgardmessias** [comment]
Yes, we can use the SinonJS for this.

**Comment by JohnstonCode** [comment]
https://www.npmjs.com/package/sinon

**Comment by edgardmessias** [comment]
A good example for usage of sinon: https://github.com/edgardmessias/vscode.clipboard-manager/blob/master/src/test/pickAndPaste.test.ts

**Comment by JohnstonCode** [comment]
Might look at using jest

**Comment by edgardmessias** [comment]
No success with `jest`?

**Comment by JohnstonCode** [comment]
Managed to get it working but coverage was incorrect. It was 50% off.

**Comment by JohnstonCode** [comment]
Going to do this gradually. Done have the time recently.
