### ISSUE TITLE
Introduce filesytem provider api

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#449]
now in tempFile module extension uses tmp folder. I think more correct will be to use custom filesystem provider, as recent gitlens update does.

assign to me if you agree.

https://github.com/Microsoft/vscode-extension-samples/tree/master/fsprovider-sample

**Comment by JohnstonCode** [comment]
Please don't start work on it until all of the issues marked 'project' are completed as things are going to change.
