### ISSUE TITLE
No source control providers registered since version 1.47.0

### ISSUE THREAD

**Issue by Coyote139** [JohnstonCode/svn-scm#451]
- VSCode Version: 1.30.1
- OS Version: Windows 10 Pro
- Extension Version: 1.47.0
- System Language: English
- SVN Version: TortoiseSVN 1.11.0

## Issue ##

No more SVN source control in VS Code since version 1.47.0, when rolling back to version 1.46.4, it works.

## Steps to Reproduce ##

1. Install version 1.47.0 of the extension

My code is located on a Linux virtual machine (running in VirtualBox on the same PC than VS Code) with a SMB share at the IP address: 192.168.56.23

## SVN Output ##
With version 1.47.0
```
Using svn "1.11.0" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[Checksum]$ svn info --xml \philippe\TBoxLinux\Addons\Checksum\Checksum.c
svn: E155007: '\\192.168.56.23\philippe\philippe\TBoxLinux\Addons\Checksum\Checksum.c' is not a working copy
```
With version 1.46.4
```
Using svn "1.11.0" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[Checksum]$ svn info --xml
[Checksum]$ svn cat \\192.168.56.23\philippe\TBoxLinux\Addons\Checksum\Checksum.c
[Checksum]$ svn stat --xml --no-ignore --ignore-externals --show-updates
```

**Comment by JohnstonCode** [comment]
I will need to have a look into this

**Comment by CFJSGeek** [comment]
I am also having this issue. New install. v1.47.1 on VS Code 1.30.2 running Windows 10. Seems this extension is unusable in its current state.

**Comment by JohnstonCode** [comment]
Should be fixed in latest release

**Comment by Coyote139** [comment]
Thank you, I confirm that it works with the latest release ;)
