### ISSUE TITLE
How to disable auto updating? (auto refresh has been set to false)

### ISSUE THREAD

**Issue by tshi206** [JohnstonCode/svn-scm#453]
Hi this is an awesome extension. I just want to use manual update instead of letting it auto run periodically.

The fact is my laptop is not of a very high specs (pretty bad tbh, but it's my office computer so I have to use it) so every time when it's updating it uses up all the CPU resources (something to do with multi threading? idk)

I am not an expert of svn so I don't know if this is the default behaviour of my svn client (VisualSVN) or the extension itself so please accept my apologies if my problem sounds dumb.

PS. I thought auto refreshing was the right option so I've set it false (both in user scope and in workspace scope) but it seems to be nothing to do with the "svn update"?

**Comment by JohnstonCode** [comment]
Hello, sorry to hear you are having issues. Try setting `svn.remoteChanges.checkFrequency` to `0`

**Comment by tshi206** [comment]
> Hello, sorry to hear you are having issues. Try setting `svn.remoteChanges.checkFrequency` to `0`

Thanks a lot! Now it won't check unless I tell it to, fantastic :)
