### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by himanilsyne** [JohnstonCode/svn-scm#455]
- Issue Type: `Performance`
- Extension Name: `svn-scm`
- Extension Version: `1.47.0`
- OS Version: `Linux x64 4.4.0-141-generic`
- VSCode version: `1.30.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/prajyot/johnstoncode.svn-scm-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JohnstonCode** [comment]
Can you please attach `/home/prajyot/johnstoncode.svn-scm-unresponsive.cpuprofile.txt`
