### ISSUE TITLE
Azure Data Studio support?

### ISSUE THREAD

**Issue by hlattanzio** [JohnstonCode/svn-scm#461]
**Is your feature request related to a problem? Please describe.**
No SVN support in Azure Data Studio (formerly SQL Operations Studio), aka.. the VSCode for SQL

**Describe the solution you'd like**
Any chance we could get an extension that would work with Azure Data Studio?  I end up using VS Code for my SQL development because I can get SVN support, but I'd like to start using Azure data Studio since it's geared more for SQL

**Describe alternatives you've considered**
Use Visual Studio Code instead of Azure Data Studio or continue to go back to Windows Explorer to do all my SVN commits / updates / etc...

**Additional context**

**Comment by JohnstonCode** [comment]
If its a case of it needing to be published to a different marketplace then sure. But if it needs any modifications then unless someone is willing to make them it would be a no.

**Comment by edgardmessias** [comment]
See https://docs.microsoft.com/sql/azure-data-studio/tutorial-create-extension

Maybe we need add `"sqlops": "*"` in `engine` key: https://github.com/kevcunnane/ssmskeymap/blob/master/package.json#L9

**Comment by edgardmessias** [comment]
Installing from "VSIX" is working fine

**Comment by edgardmessias** [comment]
To publish to marktplace: https://docs.microsoft.com/pt-br/sql/azure-data-studio/tutorial-create-extension?view=sql-server-2017#publish-your-extension-to-the-marketplace

Need a pull request to https://github.com/Microsoft/azuredatastudio/blob/release/extensions/extensionsGallery.json on each release

**Comment by hlattanzio** [comment]
Thank you @edgardmessias  Installing from VSIX does appear to be working.

**Comment by dube77** [comment]
Up until recently I've had success with 'Install from VSIX' but after one of the recent updates I get...

`Unable to install extension 'johnstoncode.svn-scm' as it is not compatible with Azure Data Studio '1.14.1'.`

I've tried reverting back to previous versions of Azure Data Studio but I'm still getting this incompatibility notification. Perhaps something in the newest build of the extension? Any help would be appreciated.

**Comment by lpvezina** [comment]
> Up until recently I've had success with 'Install from VSIX' but after one of the recent updates I get...

> Unable to install extension 'johnstoncode.svn-scm' as it is not compatible with Azure Data Studio '1.14.1'.

I'm in the exact same situation as you @dube77 .  I'd like to try to install an earlier version of the extension.  Where can I find old version of the VSIX file?

**Comment by lpvezina** [comment]
Found out that since version 2.0.0 of svn-scm, minimum VS Code is now 1.40.0 (even 1.41.0 in 2.4.0).  Azure Data Studio 1.14.1 is currently using VS Code 1.38.0.

**Comment by JohnstonCode** [comment]
All vsix files can be found at https://github.com/JohnstonCode/svn-scm/releases

**Comment by edgardmessias** [comment]
@JohnstonCode , to next releases, add in the release notes the supported version of VSCode

**Comment by lpvezina** [comment]
Version 1.15.0 of Azure Data Studio is compatible with version 2.10.0 of svn-scm.

They've upgraded to VS Code 1.42.0.  Simply download the vsix extension and install it in Azure Data Studio.

**Comment by MikeDev96** [comment]
> Version 1.15.0 of Azure Data Studio is compatible with version 2.10.0 of svn-scm.
> 
> They've upgraded to VS Code 1.42.0. Simply download the vsix extension and install it in Azure Data Studio.

Unable to install extension 'johnstoncode.svn-scm' as it is not compatible with Azure Data Studio '1.17.0'.
