### ISSUE TITLE
High cpu usage by parallel svn processes

### ISSUE THREAD

**Issue by stefangraber** [JohnstonCode/svn-scm#463]
- VSCode Version: 1.30.2
- OS Version: Windows 7 Enterprise
- Extension Version: 1.47.0
- System Language: german
- SVN Version:

## Issue ##

I have an ansible project using 18 roles as svn:externals.
VSCode periodically starts a lot of svn processes in parallel causing a high cpu usage.
Changing svn.remoteChanges.checkFrequency to 0 of course is a possible workaround. 
But it would be better to limit the number of parallel spawning svn processes.

## SVN Output ##
```
svn info --xml <external1>
svn info --xml <external2>
```

## Screenshots ##
![vscodeprocesses](https://user-images.githubusercontent.com/6479698/51528521-2a1ba480-1e37-11e9-817f-44d3633f100a.png)
[CPU-20190122T144540.cpuprofile.txt](https://github.com/JohnstonCode/svn-scm/files/2783013/CPU-20190122T144540.cpuprofile.txt)

**Comment by JohnstonCode** [comment]
Thanks for raising this and looking into the cause.
