### ISSUE TITLE
rejected promise not handled within 1 second

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#465]
- VSCode Version: 1.30.2
- OS Version: linux
- Extension Version: 1.47
- System Language: rus
- SVN Version: 1.10

## Issue ##
When I debug some extensions and update workspace settings. I see error in the debugger of rejected Promise, that confuses. I've pointed out that it is generated by svn extension.

## Steps to Reproduce ##

1. Start extension debugging
2. Change some configuration value.

## SVN Output ##
```
Using svn "1.10.0" from "svn"

```

## Screenshots ##
![image](https://user-images.githubusercontent.com/7345761/51603626-645e7200-1f1b-11e9-8e4f-52b7f41ef48f.png)

**Comment by JohnstonCode** [comment]
You still having this issue @Yanpas? I cant seem to reproduce it any more

**Comment by Yanpas** [comment]
Yes, me too
