### ISSUE TITLE
Error on file access in network path

### ISSUE THREAD

**Issue by kleinandreas2002** [JohnstonCode/svn-scm#466]
- VSCode Version: 1.30.2
- OS Version: Windows_NT x64 10.0.16299
- Extension Version: 1.47.0
- System Language: eng
- SVN Version: Using svn "1.9.7"

## Steps to Reproduce ##

1. Open folder from network path (in my case: \\\\fs07\aklein\vsCodeTestSvn
command: tree
.
├── .svn
├── example1.txt
└── example2.txt
2. SVN extension works properly and recognize the svn modification (see image1)
3. Then click on the modified file 'example1.txt'
4. Error: the svn extension stopped -> 'No source control providers registered.' (see image2)

## SVN Output ##
```
[vsCodeTestSvn]$ svn info --xml \aklein\vsCodeTestSvn\example1.txt
svn: E155007: '\\fs07\aklein\aklein\vsCodeTestSvn\example1.txt' is not a working copy
```
It seems that the network path is not correct, because
I opened the folder with menu File->Open Folder...:
```
\\fs07\aklein\vsCodeTestSvn
```
and the svn extension looks in path:
```
\\fs07\aklein\aklein\vsCodeTestSvn
```
--> the subfolder 'aklein' is listed twice
--> This approach worked perfectly in such network paths until recently.

## Screenshots ##
![image1](https://user-images.githubusercontent.com/34026772/51754555-dd48ff80-20bc-11e9-8ff6-e76a16cb432f.png)

![image2](https://user-images.githubusercontent.com/34026772/51754622-0d909e00-20bd-11e9-8f3c-fa69da4d943d.png)

**Comment by Hrnkas** [comment]
I see similar issue, however in my case, the SVN Icon is only visible for 1 second after opening the project. After that it disappears and all I can see is the same notice: "No source control providers registered."
My Project is also on a network drive (shared roaming profile on Active Directory in Windows 10).
(\\SERVER\Redir$\Bojan\Documents\Projects\myproject)

**Comment by joshsweaney** [comment]
Been trying for the last 2 hours to figure out if this was something wrong with my setup, or if this was a bug. Glad to see others have the same issue. I'm on Windows 10.

@JohnstonCode there is clearly a bug in the way this extension handles working copies stored on network drives. When running "svn info --xml '\\some\file\path' " it works fine, but the same command appears to be failing ("is not a working copy") in the Output window (with Svn filter selected) of VSCode.

**Comment by JohnstonCode** [comment]
Yeah, I only use local checked out copies so never actually thought about network drives. Will need to have a look.

**Comment by Hrnkas** [comment]
It works fine since the latest VSCode Update (1.31.0)

**Comment by Hrnkas** [comment]
> It works fine since the latest VSCode Update (1.31.0):
> 
> Version: 1.31.0 (system setup)
> Commit: 7c66f58312b48ed8ca4e387ebd9ffe9605332caa
> Date: 2019-02-05T22:35:56.624Z
> Electron: 3.1.2
> Chrome: 66.0.3359.181
> Node.js: 10.2.0
> V8: 6.6.346.32
> OS: Windows_NT x64 10.0.17134

Ok, now it does not. Conclusion - it works sometimes. :/
