### ISSUE TITLE
Allow multi-line commit messages

### ISSUE THREAD

**Issue by jackbanditdude** [JohnstonCode/svn-scm#471]
When entering commit messages, both at the top of the SVN pane and in the top bar in the middle of the Visual Studio Code window, you can only enter a single line commit message. It gives the appearance of allowing you to enter multiple lines if you hold Shift + Enter to add new lines, but the final message to SVN comes through as a single line.

For anyone working on multiple items that they commit at once, such as multiple issues in a single file that are not necessarily related, entering multiple lines for your commit can be important.

It would be preferable that pressing "Enter" from the commit message box adds new lines to the commit dialog box and they do not get stripped when committing to your repo.

I know that it is not a limitation of SVN, as TortoiseSVN allows this.

**Comment by edgardmessias** [comment]
Not supported by VSCode, need wait for Microsoft/vscode#39969
