### ISSUE TITLE
Ctrl + Enter for commit doesn't give option to choose "Selected" files

### ISSUE THREAD

**Issue by jackbanditdude** [JohnstonCode/svn-scm#472]
When pressing Ctrl + Enter to commit, if you've specifically selected files, the pop-up dialog asks if you'd like to commit Changes or Changelist "Default", it does not either automatically choose selected files or even give the option.

The ideal solution IMO would be to add "Selected" to the pop-up dialog asking which files to commit.

**Comment by edgardmessias** [comment]
At momment, you can use changelists, like example, a changelist "tocommit", on `Ctrl + Enter` prompt you to choose a changelist

**Comment by edgardmessias** [comment]
@JohnstonCode, we can use with: https://code.visualstudio.com/api/references/vscode-api#QuickPick%3CT%3E

Default all files selected.

For "Commit selected files" command, we can change to show same list, but only some files selected
