### ISSUE TITLE
Understanding Source Control Provider view

### ISSUE THREAD

**Issue by DavidA2014** [JohnstonCode/svn-scm#474]
- VSCode Version: 1.30.2
- OS Version: Windows 10
- Extension Version: 1.47.0
- System Language:
- SVN Version: 1.11.1

I don't think this is a bug but I don't understand what I am seeing, which is:

![image](https://user-images.githubusercontent.com/7724321/52115456-969c5d80-2606-11e9-938d-3580857a290d.png)

My workspace has two folders 'software' and 'Tools' on branch BR_SW_FY18, which explains the top two entries. Folder 'software' has an external 'FixedRegisterSpecification', which explains the third entry. But I don't know where the 4th entry 'Tools' comes from - I'm not aware of an external with that name.  Any idea where it is coming from please?

**Comment by JohnstonCode** [comment]
Can you copy the svn output please

**Comment by DavidA2014** [comment]
Thanks, the output revealed that the 4th entry 'Tools' is another external. So explained now.

Thanks for a great extension.
