### ISSUE TITLE
Problematic working copy path on Subversion pane files

### ISSUE THREAD

**Issue by it0243** [JohnstonCode/svn-scm#475]
Issue Type: <b>Bug</b>

When trying to open a file from the Subversion pane I get the following error:

> Not available from this working copy: file:///home/dev-mi/home/dev-mi/...

It seems that the home directory is appended to the actual path, so I have it twice.

I have opened an existing svn project in my workspace.

I have the latest VS Code, Ubuntu 18.0.4 and SVN 1.9.7.

Extension version: 1.47.0
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:49:48.319Z)
OS version: Linux x64 4.15.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-5400K APU with Radeon(tm) HD Graphics (2 x 3468)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.74GB (0.23GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by it0243** [comment]
If i modify the file extensions\johnstoncode.svn-scm-1.47.0\out\svnRI.js at line 32 as following, it works

```js
return vscode_1.Uri.file(path.join(this.checkoutRoot.path, path.relative(this.branchRoot.path, '/' + this._path)));
// return vscode_1.Uri.file(path.join(this.checkoutRoot.path, path.relative(this.fromRepoToBranch, this._path)));
```

**Comment by JohnstonCode** [comment]
@Yanpas can you have a look at this?

**Comment by Yanpas** [comment]
Which file pane did you use to get this error? And what context menu item did you click? Was revision you were choosing creating branch or renaming file?

Added test case to annotation branch (https://github.com/Yanpas/svn-scm/commit/8ee16ad5439a2a2a91c4912100d02ed86d3e56e5) which passes successfully. That branch includes fixes to SvnRI and logic improvements, but test case runs on master successfully too.

**Comment by Yanpas** [comment]
The trouble may occur with this.fromRepoToBranch (i.e. `path.relative(this.remoteRoot.path, this.branchRoot.path);`

I assume that branchRoot (URL:) is descendant to remoteRoot (Repository Root:). What does your svn info shows?

**Comment by it0243** [comment]
Debugging the properties and variables in SvnRI.js, they have the following values:

```
**this.checkoutRoot.path**: /home/dev-mi/projects/drupal/foo 
**this.remoteRoot.path**: ""
**this.branchRoot.path**: /foo/drupal-7/trunk
**this.fromRepoToBranch**: ../../foo/drupal-7/trunk 
**this._path**: foo/drupal-7/trunk/drupal/sites/all/themes/foo_theme/scss/foo-pdf.scss 
**path.relative(this.fromRepoToBranch, this._path)**: ../../../../home/dev-mi/foo/drupal-7/trunk/drupal/sites/all/themes/foo_theme/scss/foo-pdf.scss
**this.localFullPath**: file:///home/dev-mi/home/dev-mi/foo/drupal-7/trunk/drupal/sites/all/themes/foo_theme/scss/foo-pdf.scss
```
So, **this.remoteRoot.path** is empty for my project.

**Comment by Yanpas** [comment]
Thank you for your feedback, the problem is clear now. Opened a PR that fixes it and added test case
