### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Vilon** [JohnstonCode/svn-scm#482]
- Issue Type: `Performance`
- Extension Name: `svn-scm`
- Extension Version: `1.47.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/vilonfang/johnstoncode.svn-scm-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by JohnstonCode** [comment]
#448 #455
