### ISSUE TITLE
workspace File deletion prompts for SVN removal breaking normal vscode UI flow

### ISSUE THREAD

**Issue by Sleaker** [JohnstonCode/svn-scm#487]
- VSCode Version: 1.13.1
- OS Version: Windows 10
- Extension Version: 1.47.1
- System Language: English
- SVN Version: 1.11.0 (Tortoise)

## Issue ##
workspace file deletions break process flow and pops a dialog asking the user if they want to remove the file from SVN.

## Steps to Reproduce ##

1. Remove a file from the vscode workspace that's checked into the SVN repository
2. Press an interactive vscode command like ctl+p
3. attempt to type in a file or action to perform
4. SVN dialog pops up soon after breaking the flow

## Alternative Steps ##
1. Remove a file from the vscode workspace that's checked into the SVN repository
2. Click and Hold on the workspace scrollbar.
3. SVN plugin detects a workspace change and pops the SVN deletion prompt
4. Click to delete the file.
5. the scrollbar will still be moving up/down with mouse movement even though context has swapped to a pop-up prompt and then back to vscode

## Expected Interaction ##
Instead of popping an SVN dialog immediate the plugin should pop a vscode notification in the bottom right that allows the user to later click Yes/No to delete the file from SVN, or in some other way notifies the user that they have a pending removal that needs to be looked at. The current prompt is a forced flow break but it doesn't pop immediately on deletion because the file scanning happens asynchronously.

**Comment by JohnstonCode** [comment]
Yeah been using this alot recently. Massvie pain

**Comment by Sleaker** [comment]
Thanks! this appears to be working great.
