### ISSUE TITLE
Svn repo history diff of deleted files doesn't work

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#489]
- VSCode Version:
- OS Version:
- Extension Version:
- System Language:
- SVN Version:

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by JohnstonCode** [comment]
What would you want the diff to be against?

**Comment by Yanpas** [comment]
Diff should be against revision @ when file was alive

**Comment by JohnstonCode** [comment]
a diff needs to be two revisions so which other revision should it be against? it cant be base or head because it doesnt exsists there anymore.

**Comment by JohnstonCode** [comment]
Nevermind i see what the issue is

**Comment by JohnstonCode** [comment]
from poking around the issue seems to be the use of cat. Normally it uses `svn cat -r 19 /test/file/blah` where it needs to be `svn cat ^/trunk/test/file/blah@19`

**Comment by Yanpas** [comment]
Yes, that was exactly how I tried to fix in a PR, but that did cause a lot of regressions and API has become clumsy. Currently I'm working at this issue
