### ISSUE TITLE
Fails upon first file open

### ISSUE THREAD

**Issue by omegahelix77** [JohnstonCode/svn-scm#494]
- VSCode Version: 1.31.1
- OS Version: Windows 10 Pro 1809 x64
- Extension Version: 1.47.1
- System Language: English (US)
- SVN Version: Tortoise 1.9.5.27581 (64-bit)

## Issue ##
When I first open my code folder (C/C++) the extension shows information about which files are modified and which are untracked by clicking on the "source control" icon on the left of the VS Code screen. I can also select the "Subversion" icon and see a log of commits to the SVN repository. If I open up any file (which is definitely tracked by SVN), the SVN icon disappears and when clicking on the "source control" icon it has no info but a message stating "No source control providers registered". Closing the file doesn't get SVN info back. The only way I have found is to close and re-open the source folder. I have seem similar behavior whether using a "Workspace" or not.

## Steps to Reproduce ##

1. Open a source code folder in VS Code which is under SVN control.
2. Notice you can see SVN info as described above
3. Open a source file within VS Code
4. Notice SVN info is gone as described above
5. Notice the redundant "c$\" in the path in the SVN output below

## SVN Output ##
Using svn "1.9.5" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[ProductSW]$ svn info --xml
[ProductSW]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[ProductSW]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[ProductSW]$ svn info --xml
[ProductSW]$ svn log -r HEAD:1 --limit=50 --xml -v https://[URL REDACTED]/svn/genesis/CT_LINUX/branches/users/juanderson/RT1_SyncRecon_FKVDE_XOFF
[ProductSW]$ svn info --xml \c$\Users\juanderson\MyFiles\Devel\SVN\ProductSW\ProductSW\Proprietary\Modules\Recon\SR_VHPRecon\SR_VHPRecon.c
svn: E155007: '\\juanderson-lpt\c$\c$\Users\juanderson\MyFiles\Devel\SVN\ProductSW\ProductSW\Proprietary\Modules\Recon\SR_VHPRecon\SR_VHPRecon.c' is not a working copy

**Comment by omegahelix77** [comment]
Updating Tortoise to v 1.11.1 did not change the outcome.

**Comment by JohnstonCode** [comment]
This should be fixed in 1.47.2
