### ISSUE TITLE
Add a setting to ignore whitespace-only diffs, smartly.

### ISSUE THREAD

**Issue by marvingreenberg** [JohnstonCode/svn-scm#496]
Working on a bunch of older projects with lots of different (or no) coding conventions generates lots of whitespace-only changes when files get reformatted.   Add a setting to allow diffs to highlight differences that are whitespace only.

If "smart-whitespace-diffs" is enabled, for any file reporting a diff, also do a svn diff -x '-w -b' and only display THOSE lines in the diff-view.  In the source control pane, add a (W) whitespace change badge for files that only differ in whitespace.

**Comment by edgardmessias** [comment]
The extension use `svn cat` command to get the original file, the diff are generated by VSCode, try change the `diffEditor.ignoreTrimWhitespace` option

**Comment by marvingreenberg** [comment]
OK.  That's close enough.  But then, somehow that seems not to work.  I'll open a bug.

**Comment by marvingreenberg** [comment]
The problem seemed to be some side-effect of a different extension, 'Partial Diff'.  I'm uncertain how it caused this effect with subversion workspaces but not git workspaces, but uninstalling it the 'ignore trim whitespace' works as expected.  Thanks.
