### ISSUE TITLE
SCM input box not triggering commit

### ISSUE THREAD

**Issue by TheDanR** [JohnstonCode/svn-scm#5]
Hi,

When trying to commit using the SCM input box it appears to do nothing.

If the field is left empty and Ctrl + Enter the command pallet appears but again on entering a description/commit message and pressing Enter it does nothing.

Looking at the change logs it says v5 supports the SCM input box but doesnt appear to be working.

Extra info:
Im using TortoiseSVN client.

The plugin is picking up new changes and files that aren't currently tracked.

Thanks.

**Comment by JohnstonCode** [comment]
Hi @TheDanR ,

Thanks for reporting this issue. I Haven't had any issues but i'm not using the TortoiseSVN client.

I will download it and have a look.

**Comment by carlosm1979** [comment]
I did a tres. Could It be a problema with min length    in the commit message?

**Comment by JohnstonCode** [comment]
Hi @carlosm1979 ,

Don't think the commit message length should be causing an issue. You can commit blank messages.

**Comment by TheDanR** [comment]
Interesting its now working and displaying the notification that the commit has happened. I'll keep you updated if it happens again.

**Comment by JohnstonCode** [comment]
Glad to hear.

Please do, got windwos and TortoiseSVN  setup now.
