### ISSUE TITLE
Get rid of svn cat warnings

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#513]
```
[trunk]$ svn cat /home/cjohnston/dev/test/trunk/src/include/classes/base/ical_dataclass.php
svn: warning: W200005: '/home/cjohnston/dev/test/trunk/src/include/classes/base/ical_dataclass.php' is not under version control
svn: E200009: Could not cat all targets because some targets are not versioned
svn: E200009: Illegal target for the requested operation
```

**Comment by edgardmessias** [comment]
Caused by this line: https://github.com/JohnstonCode/svn-scm/blob/7129e2b5ebf240a17f3a4b74eb4d4bb36cdf0025/src/svn.ts#L203

Maybe, add a single regex check

**Comment by JohnstonCode** [comment]
Yeah found that. Decided it was just better to make it look like the rest of the output. Least if you have multiple repos you can see which one the error is with
