### ISSUE TITLE
Unable to commit

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#515]
svn extension version: 1.47.5
vscode version: 1.32.3
os: Linux x64 4.4.175-89-default

## Issue ##
since a few updates the svn extension for Visual Studio Code seems to be broken. At least I cannot commit the changes, however committing in the terminal with svn commands is working without issues.

## SVN Output ##
```
[cs_dev]$ svn cat -r HEAD http://vsvn:8088/svn/cs_dev/trunk/climateraster2/config/drawing/austria_linediagram.yaml
[cs_dev]$ svn info --xml /daten3/nobak/ZAMG/04_CS18-19/cs_dev/climateraster2/config/drawing/austria_linediagram.yaml
[cs_dev]$ svn commit climateraster2/config/drawing/austria_linediagram.yaml -m test --depth empty
[cs_dev]$ svn info --xml /daten3/nobak/ZAMG/04_CS18-19/cs_dev
[cs_dev]$ svn info --xml /daten3/nobak/ZAMG/04_CS18-19/cs_dev
[cs_dev]$ svn stat --xml --no-ignore --ignore-externals
[cs_dev]$ svn cat -r HEAD http://vsvn:8088/svn/cs_dev/trunk/climateraster2/config/drawing/austria_linediagram.yaml
```

**Comment by JohnstonCode** [comment]
@ilgatto88

**Comment by IperStan** [comment]
svn extension version: 1.47.5
vscode version: 1.32.3
os: Win 10 x64

I have a related problem. I noticed a couple of days ago I was able to commit, however, after the commit, its message remains in the input, as if the input was waiting to be "noticed" about the operation.

**Comment by JohnstonCode** [comment]
Can you copy the svn output when you try and commit please

**Comment by IperStan** [comment]
I'm sorry, I can't find how to see the svn output in vscode, could you provide me any info?

**Comment by edgardmessias** [comment]
"SHOW > OUTPUT" and select SVN dropdown

**Comment by IperStan** [comment]
[myProject]$ svn commit src\components\dashboard\x.vue src\components\dashboard\y.vue -m '~ fix last todos' --depth empty
[myProject]$ svn info --xml C:/myProject
[myProject]$ svn info --xml C:/myProject
[myProject]$ svn info --xml C:/myProject
[myProject]$ svn info --xml C:/myProject
[myProject]$ svn info --xml C:/myProject
[myProject]$ svn info --xml C:/myProject
[myProject]$ svn info --xml C:/myProject
[myProject]$ svn stat --xml --no-ignore --ignore-externals
[myProject]$ svn info --xml
[myProject]$ svn cat -r HEAD https://192.168.0.2/svn/myProject/trunk/src/components/dashboard/y.vue

**Comment by edgardmessias** [comment]
Nice @IperStan, some message are shown after commit?

@JohnstonCode, line to refer
https://github.com/JohnstonCode/svn-scm/blob/8471670e67a0ca6d12f7c8ebd050f48eddb017a2/src/commands/commit.ts#L64

**Comment by IperStan** [comment]
@edgardmessias The above-mentioned log is exactly what was shown after I clicked "Commit", nothing more.

**Comment by edgardmessias** [comment]
Sorry, I meant if it shows a popup.

Before commit, you can go to "HELP > Toggle developers tools", and make the commit, and check some error message

**Comment by IperStan** [comment]
This is what I see after hitting "CTRL+ENTER" to commit
![svn-report](https://user-images.githubusercontent.com/43338672/54813997-1b166e80-4c8f-11e9-929f-bd282faf4be6.jpg)

**Comment by edgardmessias** [comment]
Big thanks @IperStan , now I will try reproduce here

**Comment by edgardmessias** [comment]
The problem is caused by 17c5438, has removed default encoding.
