### ISSUE TITLE
Encode after version 1.47.4

### ISSUE THREAD

**Issue by GabrielBFern** [JohnstonCode/svn-scm#526]
- VSCode Version: 1.30.2
- OS Version: Windows_NT x64 10.0.17763
- Extension Version: 1.47.5
- System Language: Português (Brasil)
- SVN Version: 1.9.5-SlikSvn

## Issue ##
Show changes in non-modified files after update to extension version 1.47.4. If I use version 1.47.3 works fine.

My config in settings.json:
    "svn.default.encoding": "windows-1252",
    "svn.multipleFolders.enabled": true

## Steps to Reproduce ##
1. Open a file with encode windows 1252 
2. The gutter to the left of the editor will show changes in special characters (Example: ç, é, á, ã )

## SVN Output ##
Using svn "1.9.5-SlikSvn" from "f:\xxx\svn\svn.exe"
[fon]$ svn info --xml f:\xxx\wc\des\barbosa\fon\TSTBAR.CBL
[rwd]$ svn info --xml
[fon]$ svn cat f:\xxx\wc\des\barbosa\fon\TSTBAR.CBL
[mod]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[rwd]$ svn stat --xml --no-ignore --ignore-externals --show-updates

## Screenshots ##
![image](https://user-images.githubusercontent.com/19215068/54923343-d0902e80-4ee8-11e9-84c2-3aae638cf77c.png)

**Comment by edgardmessias** [comment]
@GabrielBFern, you can check your `files.encoding`?

Test with: `"files.encoding": "windows-1252"`

**Comment by GabrielBFern** [comment]
With "files.encoding" solve the problem, but when I use "files.enconding" per language doesn't work (I use different encoding with each language).
Example:
    "[COBOL]": {
        "files.encoding": "windows-1252",
    },  (Doens't work)
    "files.encoding": "windows-1252", (work)

And "files.encoding" say that "windows-1252" is not a valid option and "windows1252" is the correct one, but works with "windows-1252".

**Comment by mayerui** [comment]
I feel confused too .
![图片](https://user-images.githubusercontent.com/25812837/58686395-4c0ed000-83b1-11e9-89d2-1673ac3ef8f1.png)

**Comment by edgardmessias** [comment]
@GabrielBFern, @mayerui , make a test with: [svn-scm-1.50.0.vsix.zip](https://github.com/JohnstonCode/svn-scm/files/3242453/svn-scm-1.50.0.vsix.zip)

**Comment by mayerui** [comment]
> 
> 
> @GabrielBFern, @mayerui , make a test with: [svn-scm-1.50.0.vsix.zip](https://github.com/JohnstonCode/svn-scm/files/3242453/svn-scm-1.50.0.vsix.zip)

Thanks for your attention. But there is no changes. May I provide more infomation: VSCode detect my files' encoding is "GB 2312", and every trouble is about Chinese words. Hope my reply helpful.
![捕获](https://user-images.githubusercontent.com/25812837/58743585-13313280-8467-11e9-964c-907504083a7b.PNG)
![捕获2](https://user-images.githubusercontent.com/25812837/58743586-15938c80-8467-11e9-9859-0e48c8e4ebb5.PNG)

**Comment by edgardmessias** [comment]
Try set files.enconding with correct value and filés.autoGuestEncoding to false.
