### ISSUE TITLE
not working in code-server environment

### ISSUE THREAD

**Issue by WengShengyuan** [JohnstonCode/svn-scm#546]
- VSCode Version: 1.408-vsc1.32.0(that is codercom/code-server's image version)
- OS Version: ubuntu18.10 (Docker image uses FROM ubuntu:18.10, and that is where code-server is running on) 
- Extension Version: 1.47.5
- System Language: English
- SVN Version: 1.10.0

## Issue ##
not working in code-server environment. 
code-server repository see: [code-server](https://github.com/codercom/code-server)

## Steps to Reproduce ##
1. I tried download svn vsix file and install offline or install directly in vscode, and none of those work. 
2. Click "+" button, or refresh button ,shows 'svn.repolog.addrepolike' not found, or 'svn.repolog.refresh' not found.

## SVN Output ##
```
 ** there is no SVN output option. **
```

## Screenshots ##
<img width="1389" alt="屏幕快照 2019-04-04 20 12 41" src="https://user-images.githubusercontent.com/9462331/55554721-0f5a8b80-5716-11e9-8476-4c0c8c0d0dbd.png">

**Comment by JohnstonCode** [comment]
If you go `Help -> Toggle Developer Tools` do you have any svn-scm related errors?

**Comment by WengShengyuan** [comment]
sorry , there is no "Toggle Developer Tools" menu in these code-server environment. 
<img width="1393" alt="屏幕快照 2019-04-13 08 55 30" src="https://user-images.githubusercontent.com/9462331/56072494-1f373700-5dca-11e9-9fc4-4e1289dafabc.png">

**Comment by BurneyFM** [comment]
I experience the same issue - the extension does not recognize the SVN repo. I encountered the following error messages:

- command 'svn.repolog.addrepolike' not found
- command 'svn.repolog.refresh' not found
- command 'svn.itemlog.refresh' not found
- command 'svn.repolog.addrepolike' not found

I am using the codercom/code-server docker image and already installed SVN inside the image.

**Comment by JohnstonCode** [comment]
Can you try with the latest release?

**Comment by musicman3569** [comment]
I have the same problem with a freshly download copy of the code-server binary from yesterday

**Comment by JohnstonCode** [comment]
Can you copy the output from the svn output window?

**Comment by musicman3569** [comment]
I'm not sure if this is what you mean by "svn output window", but for example, this is a screen shot of the SVN extension while in a folder that has an existing SVN repo.m  The warning in the bottom-right is what appears after hitting the "+" button next to the "REPOSITORIES" section.
![image](https://user-images.githubusercontent.com/16069898/57820280-5ee69b00-7749-11e9-9740-c186c1c04fd0.png)

**Comment by musicman3569** [comment]
If it helps to see it in action here is a short screencast of the issue.

https://homecarepulse-my.sharepoint.com/:v:/p/jason/EctayLuSQ5RIrtFBIO5xsiMBsjBqJThRPb2YY1vHMJ4MSQ?e=UzVSRC

**Comment by JohnstonCode** [comment]
@edgardmessias seems the import magic is the issue

```
Activating extension 'johnstoncode.svn-scm' failed: Cannot find module 'iconv-lite'.
```

**Comment by edgardmessias** [comment]
@JohnstonCode, maybe, we need find the `node_modules` of code-server

**Comment by JohnstonCode** [comment]
Yeah I’ll have a dig around tomorrow and see if I can find it

**Comment by JohnstonCode** [comment]
The latest release of 1.48.5 should provide you with instructions of how to get this extension working with code-server.

**Comment by WengShengyuan** [comment]
thank you guys for all the hard work!

**Comment by madmalkav** [comment]
I'm having this issue with VS Code 1.38.1 downloaded from official site, tried both Collabnet and VisualSVN packages.
