### ISSUE TITLE
SVN prompts for login constantly

### ISSUE THREAD

**Issue by Zevensoft** [JohnstonCode/svn-scm#552]
- VSCode Version: 1.33.0
- OS Version: Linux x64 4.15.0-20-generic
- Extension Version: 1.48.0
- System Language: English
- SVN Version: 1.9.7

## Issue ##
vscode will ask for login credentials for every repository every few minutes, even if given correctly. Its very annoying when you're trying to do something and vscode keeps promping for information that has been given 50 times already.

## Steps to Reproduce ##

1. Open vscode on a folder that exists in the repository.
2. Wait for SVN plugin to try to do something.

## SVN Output ##
(For each repository)
[repo1]$ svn info --xml /datalocal/[redacted]
[repo1]$ svn: E170013: Unable to connect to a repository at URL 'http://[redacted]/repos/branches/[redacted]'
[repo1]$ svn: E215004: No more credentials or we tried too many times.
[repo1]$ Authentication failed

**Comment by MichaelSuen-thePointer** [comment]
Same problem here. VS Code runs on Debain 9 x64 hosted in VMWare virtual machine on Win10 1709

VSCode version: 1.33.1
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.9.0-8-amd64
SVN version: 1.9.5

It seems a `svn stat` or `svn info` in the background failed with network issue, then the extension cannot restore to the correct state and keeps asking credentials.

**Comment by Zastai** [comment]
I've had to disable the extension to avoid getting interrupted all the time.
This was on Debian 4.19.37-3, with VSCode 1.35.1 and extension 1.54.1.

(Also: it looks like the auth handling doesn't properly integrate with key stores. When I first run the command-line svn client, it will ask to unlock my Gnome keyring (I connect via SSH and that's not done automatically). The prompts in VSCode never did, suggesting they never tried to use the keyring.)

**Comment by DavidA2014** [comment]
If Gnome keyring isn't supported, the extension really isn't usable in our environment, which is a shame.

**Comment by edgardmessias** [comment]
I am working on this issue to stop prompt login contantly, I will make a vsix to test

**Comment by edgardmessias** [comment]
About GNOME Keyring, see #188

**Comment by edgardmessias** [comment]
@DavidA2014 @Zastai @Zevensoft @MichaelSuen-thePointer 

Can test with [svn-scm-1.54.1.vsix.zip](https://github.com/JohnstonCode/svn-scm/files/3334759/svn-scm-1.54.1.vsix.zip)?

**Comment by DavidA2014** [comment]
@edgardmessias I do have 1.54.1 installed but I see:

    [build]$ svn: E200009: Could not display info for all targets because some targets don't exist[<myrepo>]$ svn stat --xml --no-ignore --ignore-externals --show-updates
    [<myrepo>]$ svn: E170013: Unable to connect to a repository at URL '<myrepo>'
    [<myrepo>]$ svn: E215004: No more credentials or we tried too many times.
    [<myrepo>]$ Authentication failed

**Comment by edgardmessias** [comment]
My VSIX has a modification to test

**Comment by DavidA2014** [comment]
Thanks, the modified vsix indeed seems to have fixed the issue.  I did notice, however, that the extension doesn't seem to ignore ignored files:

    [build]$ svn: E200009: Could not display info for all targets because some targets don't exist[build]$ svn: warning: W155010: The node '<snip>/Release/CMakeFiles' was not found.

**Comment by DavidA2014** [comment]
Actually I still got:

    $ svn: E170013: Unable to connect to a repository at URL '<snip>'
    $ svn: E215004: No more credentials or we tried too many times.
    $ Authentication failed

**Comment by DavidA2014** [comment]
Thank you

**Comment by MichaelSuen-thePointer** [comment]
Thank you very much

**Comment by KennethScott** [comment]
Am I the only one this issue has reappeared for recently in 2.3.0?  VSCode 1.41.1

**Comment by MichaelSuen-thePointer** [comment]
> Am I the only one this issue has reappeared for recently in 2.3.0? VSCode 1.41.1

You are not alone, this issue still appear in my Linux virtual machine, but not on the host Windows. When the vm is unfocused for a while, this issue appears, a manual 'svn update' will resolve that, so Im not care about it any more.

**Comment by filipnis** [comment]
> Am I the only one this issue has reappeared for recently in 2.3.0? VSCode 1.41.1

Same here ! Windows 10, extension version is 2.13.6. It is good extension, it helps a lot, but this is killing me since I have more then 10 projects on SVN and I need to put credentials constantly. Is there any solution ?

**Comment by CalvinDay** [comment]
In Git, create a Personnel Access Token (PAT) with all access rights and when the Authentication screen pops up, use the PAT as password.
