### ISSUE TITLE
Add svn cleanup command

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#557]
- VSCode Version: 1.33.1
- OS Version: kubuntu 19.04
- Extension Version: 1.48.1
- System Language:
- SVN Version: 1.10

## Steps to Reproduce ##

1. `ln -s aaa bbb`
2. Delete bbb

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by Yanpas** [comment]
BTW there is useful svn command `svn cleanup --remove-unversioned`

**Comment by JohnstonCode** [comment]
What version of svn was that flag added?

**Comment by Yanpas** [comment]
According to [stackoverflow](https://stackoverflow.com/a/32102497/4355809) since 1.9

**Comment by JohnstonCode** [comment]
Yeah, support is aimed at 1.6... It is a pain but people on Centos complained

**Comment by JohnstonCode** [comment]
@Yanpas would adding a command be enough?

**Comment by Yanpas** [comment]
Absolutely
