### ISSUE TITLE
VSCode diff show changes with respect to the latest revision in the repository, not in relation to the local copy.

### ISSUE THREAD

**Issue by v4a26** [JohnstonCode/svn-scm#56]
1.18.1 - VSCode Version:
Windows 7 x64- OS Version:
v1.3.2 - Extension Version:
Russian cp1251- System Language:

Steps to Reproduce:

1. SVN checkout in one place, for example `exampleFolder1` revision 4.
2. SVN checkout in other place, for example `exampleFolder2` revision 4..
3. Do some changes in folder `exampleFolder1`, do not commit.
4. Do some changes in folder `exampleFolder2`, commit them in trunk. Thats how we get revision 5.
5. Look into Changes mark in  `exampleFolder1`, it will show to you diff between revision 4 and revision 5 plus your own changes into local copy.

So in my case SVNdiff gives one change in the file based on 50 revision.
![svndiff](https://user-images.githubusercontent.com/9762164/33363340-09351fc0-d4f1-11e7-8dce-59b4a140bec4.PNG)

But VSCode show a lot of changes made by my collegue. Actually 39 changes in gap of 50->64 revision. 
![vscode diff](https://user-images.githubusercontent.com/9762164/33363442-6ea005be-d4f1-11e7-9ad1-bbfa4ae2b380.PNG)

I think thats not proper behaviour. I expect same result as SVNdiff gives.

**Comment by JohnstonCode** [comment]
By changes mark do you mean the gutter colours? For example the green gutter decoration for new additions.

**Comment by v4a26** [comment]
Yes it is. The problem is in local copy was no changes that shown, they came from last revision.

**Comment by JohnstonCode** [comment]
Yeah it’s set to diff against HEAD. I can change this.

**Comment by v4a26** [comment]
May be some people find current situation usefull. Looks like possible new item in options. I'm not sure.

**Comment by magic-k** [comment]
When i have a local copy, i expect the diff to go against the latest version in the current branch (not necessarily HEAD). If there were 10 new revisions since my last update i expect to see a lot of diffs. Or do i misunderstand the issue?

**Comment by v4a26** [comment]
>  If there were 10 new revisions since my last update i expect to see a lot of diffs.

Well, a lot of diffs very unconfortable for me. I expect see my own changes with respect to base revision of my local copy. In that way working tortoiseMerge, which could be called in context menu of file in local copy like `TortoiseSVN -> Diff`.

**Comment by magic-k** [comment]
I see it like @v4a26. These are two use cases, diff against current revision and diff against head. How does git handle this?

**Comment by Arwalk** [comment]
Considering both behaviours appeal to different public (i enjoy seeing the diff against head, it incites me to svn up early and merge earlier anything that could conflict later in my env), it probably could be a good idea to make it a user setting?

Just throwing my two cents in the discussion.

**Comment by edgardmessias** [comment]
After merge #55, I can start working to have option

**Comment by JohnstonCode** [comment]
@edgardmessias  yeah lets config this.

**Comment by edgardmessias** [comment]
Working

**Comment by edgardmessias** [comment]
Done.

**Comment by JohnstonCode** [comment]
Looks good. Send a PR

**Comment by edgardmessias** [comment]
Ok.
