### ISSUE TITLE
Is `remove from changelist` feature removed?

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [JohnstonCode/svn-scm#569]
Cannot find `remove from changelist` feature in the right click menu anymore.

Is it removed or moved to other place? 

If it is removed, please change this issue to a feature request, I will be grateful.

![image](https://user-images.githubusercontent.com/12868093/57509170-205e7400-7336-11e9-98b8-b449c0472d17.png)
![image](https://user-images.githubusercontent.com/12868093/57509188-29e7dc00-7336-11e9-88f1-803ae1782fbe.png)

**Comment by edgardmessias** [comment]
If file has a changelist, on "Set changelist" has option to remove.

Look: https://github.com/JohnstonCode/svn-scm/blob/80743dd2cfe4f69e640f8cb71272fa880f0469f4/src/changelistItems.ts#L31

**Comment by MichaelSuen-thePointer** [comment]
> If file has a changelist, on "Set changelist" has option to remove.
> 
> Look:
> 
> https://github.com/JohnstonCode/svn-scm/blob/80743dd2cfe4f69e640f8cb71272fa880f0469f4/src/changelistItems.ts#L31

Tried, but there's no remove option.
![test](https://user-images.githubusercontent.com/12868093/57605781-04f3a300-759a-11e9-9e81-af2965dd1899.gif)

**Comment by edgardmessias** [comment]
@JohnstonCode, I can't reproduce, working fine here.
@MichaelSuen-thePointer , what you extension version? VSCode?
Go to "Help > Toggle Developers Tools" and check some message

**Comment by MichaelSuen-thePointer** [comment]
> @JohnstonCode, I can't reproduce, working fine here.
> @MichaelSuen-thePointer , what you extension version? VSCode?
> Go to "Help > Toggle Developers Tools" and check some message


VSCode:
version: 1.33.1 (user setup)
commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

Extension: 1.48.2

After a quick debugging, I found this `repository.changelist` is just an empty object, wierd.
Where is it initialized?

![image](https://user-images.githubusercontent.com/12868093/57620468-6d06b100-75bb-11e9-9044-164065110839.png)

**Comment by JohnstonCode** [comment]
Here https://github.com/JohnstonCode/svn-scm/blob/master/src/repository.ts#L575

**Comment by edgardmessias** [comment]
@MichaelSuen-thePointer, the question is: How the file is in "IGNORE-ON-COMMIT"? You can set another change list and back?

**Comment by JohnstonCode** [comment]
@edgardmessias I cant reproduce either

**Comment by MichaelSuen-thePointer** [comment]
> @edgardmessias I cant reproduce either


> @JohnstonCode, I can't reproduce, working fine here.
> @MichaelSuen-thePointer , what you extension version? VSCode?
> Go to "Help > Toggle Developers Tools" and check some message


Guys, I found a way to repro the bug:

1. checkout a folder, lets say `folder1`
2. modify `folder1`'s `externals` property: add an external entry to another folder, lets say `folder2`
![image](https://user-images.githubusercontent.com/12868093/58017051-d80f3500-7b31-11e9-8308-e34d5f3ca18a.png)
3. commit changes in `folder1` and update in `folder1` to get `folder2` downloaded
4. create a file `testfile.txt` inside `folder1/folder2`
5. commit `testfile.txt`
![image](https://user-images.githubusercontent.com/12868093/58017087-eeb58c00-7b31-11e9-93c5-88c48e383b32.png)
6. set `testfile.txt`'s change list to `ignore-on-commit`, either in VSCode or in command line is OK
7. back to `folder1`, **open with Code** here
8. see what happends
![image](https://user-images.githubusercontent.com/12868093/58017325-7dc2a400-7b32-11e9-9be6-3d440b605847.png)

**Comment by MichaelSuen-thePointer** [comment]
@JohnstonCode @edgardmessias 
Guys, I found the steps to reproduce the issue above, please have a try.

**Comment by JohnstonCode** [comment]
Thanks for finding a way to replicate this. Will have a look as soon as i have time.
