### ISSUE TITLE
Add confirm to revert command

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#57]
- VSCode Version:1.18.1
- OS Version:Fedora 25
- Extension Version:1.3.2
- System Language:English

Probably should add a confirm to the revert command to avoid accidents.

**Comment by johnjacobkenny** [comment]
Currently, after reverting a file, the diff view stays on screen without updating. I was expecting that once the revert was done the diff would automatically update to reflect the changes. The file is correctly removed from the left side bar.

**Comment by johnjacobkenny** [comment]
No wait, this happened just once, I might have done something differently to cause that. It isn't recurring.
