### ISSUE TITLE
Cannot update files

### ISSUE THREAD

**Issue by bardware** [JohnstonCode/svn-scm#576]
Hi,

I noticed a certain behaviour in eclipse editor when using subclipse plugin and observed the same in your VSCode plugin.
I look at the files that are changed on remote. I right click a file and choose Update. The file is not loaded and an error is printed in the console: `Path is not a working copy directory`. This is because the directory structure for that file is not complete o the client. In my image the directory I highlighted yellow does not exist.
The solution is to call `svn update ..` with the `--parents` switch. This checks out the parent folders of the selected file.

![grafik](https://user-images.githubusercontent.com/802702/57730483-d90b1700-7698-11e9-8cb8-f675db9ce53a.png)

**Comment by JohnstonCode** [comment]
Thanks for raising this

**Comment by JohnstonCode** [comment]
The issue with using `--parents` with update is that other files/folders are ignored. For example:
```
/test/test.js
/test/new/new.js
test/new/newest/newest.js
```
If you you do not have any of those directories checked out in your local copy and do `update --parents test/new/newest/newest.js` then it will be checked out but the other 2 files and 'new' directoy will not be and will no longer show in the external changes list. Not sure what to do.
