### ISSUE TITLE
Open Changes With Head Error

### ISSUE THREAD

**Issue by kimkee** [JohnstonCode/svn-scm#581]
- VSCode Version:
- OS Version: Windows10Pro
- Extension Version: 1.47.3 Later
- System Language: 
- SVN Version:

## Issue ##

File comparisons are normal until version 1.47.3.
Starting with version 1.47.4, file comparison is an error.
Please refer to the attached photo.

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Using svn "1.11.1" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[webapp]$ svn info --xml c:\workspace\web\SHR\src\main\webapp\static\css\common.css
[webapp]$ svn cat c:\workspace\web\SHR\src\main\webapp\static\css\common.css
[webapp]$ svn info --xml
[webapp]$ svn stat --xml --no-ignore --show-updates
[webapp]$ svn cat -r HEAD svn://0.0.0.0.0/PCOFF/mHR/trunk/server/web/SHR/src/main/webapp/static/css/common.css
[webapp]$ svn info --xml c:\workspace\web\SHR\src\main\webapp\static\css\common.css

```

## Screenshots ##
![svb_bug_1](https://user-images.githubusercontent.com/6386956/58236372-b99d7980-7d7d-11e9-9568-329a28887a67.png)

![svb_bug_2](https://user-images.githubusercontent.com/6386956/58236381-be622d80-7d7d-11e9-9033-39d0ed1f5e6d.png)

**Comment by JohnstonCode** [comment]
Paste here content of "View >> Output >> OUTPUT >> SVN"

**Comment by kimkee** [comment]
> Paste here content of "View >> Output >> OUTPUT >> SVN"
Ok. Got it

**Comment by JohnstonCode** [comment]
If you got to "Help >> Toggle developer tools >> console" Do you have any svn-scm errors?

**Comment by kimkee** [comment]
> If you got to "Help >> Toggle developer tools >> console" Do you have any svn-scm errors?
![svb_bug_3](https://user-images.githubusercontent.com/6386956/58238489-57934300-7d82-11e9-9fff-3c9c25f08a2b.PNG)

**Comment by JohnstonCode** [comment]
If you diff base does it display the diff correctly?

**Comment by kimkee** [comment]
> If you diff base does it display the diff correctly?

![svb_bug_5](https://user-images.githubusercontent.com/6386956/58293636-4fc6b380-7e01-11e9-9376-ac9e531a102a.PNG)

**Comment by JohnstonCode** [comment]
Sorry what i meant was if you click on a modified file and select "Open changes with BASE" does that display the diff properly?

**Comment by kimkee** [comment]
Like the attachment, "(HEAD)" does not show anything.

> Sorry what i meant was if you click on a modified file and select "Open changes with BASE" does that display the diff properly?

Like the attachment, "(HEAD)" does not show anything.

![58236381-be622d80-7d7d-11e9-9033-39d0ed1f5e6d](https://user-images.githubusercontent.com/6386956/58388808-2787c080-805e-11e9-8dac-a1f150face98.png)

**Comment by kimkee** [comment]
Wow! Resolved.
In "Setting"
"files.encoding": There was a problem with "utf8bom".
Fixed by setting "files.encoding": "utf8". 😂

Thank you for your help.

![9-05-27 213755](https://user-images.githubusercontent.com/6386956/58420223-b54bc600-80c7-11e9-9c6b-8f8cf02e6d5b.png)
