### ISSUE TITLE
Failed to open path

### ISSUE THREAD

**Issue by suzinicco** [JohnstonCode/svn-scm#593]
- VSCode Version: 1.34.0
- OS Version: macOS 10.14.5
- Extension Version: 1.50.1
- System Language: English
- SVN Version: 1.9.4

## Steps to Reproduce ##

1. can not open revision file 
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
Failed to open path

## Screenshots ##
![svnext_error1](https://user-images.githubusercontent.com/26999365/58781507-081d0480-8617-11e9-8219-5275b05e9a3a.png)

**Comment by SpecialYy** [comment]
So do I. When I click the commit log in VSCode, it will pop a window shows that "failed to open path" or "cannot diff last commit". Why? It was good before, until today, something went wrong.   
- VSCode Version: 1.34.0
- OS Version: Windows 10 professional
- Extension Version: 1.50.1
- SVN Version: 1.7.10

**Comment by suzinicco** [comment]
output : 
svn: E125002: URL 'svn://mysvnserverroot/../../../../../../svn:/path/to/file' contains a '..' element

**Comment by it0243** [comment]
The same for me too since a couple of days.

VSCode Version: 1.34.0
OS Version: Ubuntu 18.0.4
Extension Version: 1.52.0
SVN Version: 1.9.7

**Comment by edgardmessias** [comment]
I found the problem
