### ISSUE TITLE
Diff view does not work on modified files

### ISSUE THREAD

**Issue by michelegalante** [JohnstonCode/svn-scm#594]
- VSCode Version: 1.34.0
- OS Version: macOS 10.14.5
- Extension Version: 1.50.1
- System Language:
- SVN Version: 1.12.0

## Issue ##

When you select a modified file from the SCM sidebar, the diff view shows the file as if it was a new file, i.e. the left pane is empty and the right pane shows the whole file.

This happens with 1.50.1. I downgraded to 1.50.0 and now it works correctly.

## Steps to Reproduce ##

1. Open a working copy directory with modified files
2. Open the SCM sidebar
3. Select a modified file

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by edgardmessias** [comment]
@michelegalante @maddev0, test with: set `files.encoding` correct and set `files.autoGuessEncoding` to `false`.

**Comment by michelegalante** [comment]
My files.encoding is UTF-8 and file.autoGuessEncoding is false.

Anyway, I just updated to 1.50.2 and it works now. I double-checked with 1.50.1 and the problem reappears. So it looks like it has been solved in the upgrade from 1.50.1 to 1.50.2

Thanks.

**Comment by edgardmessias** [comment]
Fixed on 1.50.2
