### ISSUE TITLE
Feature Request: Commit selected items

### ISSUE THREAD

**Issue by TheDanR** [JohnstonCode/svn-scm#6]
Great extension so far.

Using it today I found myself only wanting to commit certain files.

Would be good if you could commit only the selected files in the list rather than all of them.

Dan

**Comment by JohnstonCode** [comment]
Hi @TheDanR ,

This feature would be helpful. I Would have to think how this would be implemented as I am not sure the SCM API allows files to be selected in the source control view. (could be wrong)

This could be done with creating a new resource group and adding the required files then committing this new group.

**Comment by magic-k** [comment]
The SCM API priovides the possibility for a context menu with multiple selections, See https://code.visualstudio.com/docs/extensionAPI/api-scm under "Menues".

**Comment by JohnstonCode** [comment]
Hi @TheDanR 

Sorry for the delay.

Changes now have a right click option to commit. You can select multiple files by pressing Ctrl and selecting the files.

This is live in version 0.9.0

**Comment by ZhiPing-S** [comment]
hi , after i apply commit, it pop up message "Unable to commit", can you give me some advices ? thanks
