### ISSUE TITLE
SVN remote operations (refresh, switch, ...) are very long.

### ISSUE THREAD

**Issue by berengergermain** [JohnstonCode/svn-scm#603]
- VSCode Version: 1.35.0
- OS Version: Windows 10
- Extension Version: 1.52.2
- System Language: FR
- SVN Version: 1.10.0

## Issue ##
On some PHP projects, svn refresh take a while to execute and all basic operations such as switch branches are very slow (> 2 minutes).  My connexion is good and I tried to clean my repositories but the problem is still here.

In the same time on some other projects, everything goes fine.

**Comment by lomash** [comment]
I'm seeing the same issue on Linux with 1.52.2, vscode 1.34.0, svn 1.9.5

**Comment by berengergermain** [comment]
One more thing : it seems that this bug affects only the last folder of the current workspace.

**Comment by JohnstonCode** [comment]
Do you have a repository or sample repository this is happening on?

**Comment by JohnstonCode** [comment]
Can you profile the extension when doing a remote operation?
https://github.com/microsoft/vscode-wiki/blob/master/Performance-Issues.md#profile-the-running-extensions
