### ISSUE TITLE
Upload Changed Files button

### ISSUE THREAD

**Issue by art40100** [JohnstonCode/svn-scm#605]
**Is your feature request related to a problem? Please describe.**
I am using SFTP extension by liximomo
This extension provides sync options but I am frustrated because there is no info about which files are about to be synchronized (local->remote). By default it should be changed files but there is no 100% knowing before.

**Describe the solution you'd like**
A button/option to upload changed files from Source Control sidepanel, so you are 100% sure about the files to be uploaded to server.
There is already an option in GIT source control:
https://github.com/liximomo/vscode-sftp/issues/545 (it works for me)
**I would like the same option from SVN source control tab.**

![vsvsvsvsvvcode](https://user-images.githubusercontent.com/33236770/59185023-1ec3de00-8b78-11e9-85f9-434add02d968.png)

**Comment by JohnstonCode** [comment]
That has to be implemented by the sftp extension.
