### ISSUE TITLE
Add setting for default revert depth

### ISSUE THREAD

**Issue by bkromhout** [JohnstonCode/svn-scm#606]
**Is your feature request related to a problem? Please describe.**
A recently fixed issue (#573) made it so that every time you try to revert something, you get asked for a revert depth. While I appreciate the ability to explicitly choose every time, it can become quite bothersome after a while, especially if you're usually just reverting single files.

**Describe the solution you'd like**
Please add a setting that lets you specify a default revert depth so that it isn't asked for each and every time something is reverted. It should be unset by default (causing it to ask each time), since that's the safest behavior.

**Describe alternatives you've considered**
There aren't really any alternatives for this sort of thing.

**Comment by edgardmessias** [comment]
I will add a check to prompt depth when has some directory

**Comment by bkromhout** [comment]
That seems like a good idea as well, though I still think there's value in having a setting too. There could even be a setting for with and without directories (though that's probably too complex).
