### ISSUE TITLE
Changes not displaying properly (folder with files)

### ISSUE THREAD

**Issue by art40100** [JohnstonCode/svn-scm#607]
- VSCode Version: 1.35.0
- OS Version: W10x64
- Extension Version: 1.53.0
- System Language: En
- SVN Version: 1.12.0

## Issue ##
I am merging changes into my branch from main repo. The changes include a newly created folder with some files in it. In VSCode Source Control Providers(SVN) I see only the folder(?), the files are not shown.
## Steps to Reproduce ##
1. Merge an added folder with files in it to your branch.
## Screenshots ##
The other changes seen are unrelated.
![commitz123](https://user-images.githubusercontent.com/33236770/59355639-03033800-8d30-11e9-9522-c15d111e2ddc.PNG)
As seen with TortoiseSVN, main repo:
![bnbn](https://user-images.githubusercontent.com/33236770/59356156-f9c69b00-8d30-11e9-80fc-ca5450729b07.PNG)

**Comment by JohnstonCode** [comment]
Not able to reproduce. Do youhave a repository or sample repository where this issue is happening?
