### ISSUE TITLE
我在使用vscode一个平行版本vscodium上用SVN出现一个问题

### ISSUE THREAD

**Issue by git10135405** [JohnstonCode/svn-scm#616]
vscodium版本1.35.1
win7旗舰版64位

在使用插件：
名称:SVN
id: johnstoncode.svn-scm
说明: Integrated Subversion source control
版本: 1.54.1
发布者: Chris Johnston
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm

在使用该插件时经常遇到如下图所示情况，vecode暂无此情况发生。就是放着一段时间 或者变更较多 或者锁屏一端时间后看到如下图，update也一直加载不出来
![image](https://user-images.githubusercontent.com/35558611/59652287-b00e0280-91bf-11e9-8aac-7fca86f159cc.png)

麻烦帮忙看看，谢谢

**Comment by JohnstonCode** [comment]
Can you put this in English please?

**Comment by git10135405** [comment]
> 你能用英语这个吗？

vscodium version 1.35.1  git link: https://github.com/VSCodium/vscodium
Win7 Ultimate 64-bit

Using the plugin:
Name: SVN
Id: johnstoncode.svn-scm
Description: Integrated Subversion source control
Version: 1.54.1
Posted by: Chris Johnston
VS Marketplace link: https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm

When using the plugin in vscodium, I often encounter the situation shown in the following figure. This is not the case with vscode. Just put it for a while or change more or lock the screen for one time and see the following picture, the update will not be loaded.
![image](https://user-images.githubusercontent.com/35558611/59663027-bbbdf100-91e0-11e9-8541-f8cb10d3d7fb.png)

 Please help me to see this question, thank you!

**Comment by JohnstonCode** [comment]
Do you have a way i can reproduce it?

**Comment by git10135405** [comment]
> Do you have a way i can reproduce it?

Yes, I have been refactoring code recently and I often come across

**Comment by JohnstonCode** [comment]
Sorry i meant do you have a way i can reproduce the issue?

**Comment by git10135405** [comment]
> Sorry i meant do you have a way i can reproduce the issue?

Sorry, I understood the meaning of your mistake last time. You can try to use a large number of items from svn to check out a project, open it with vscodium, and try best to modify as many files as you can at once, then idle for a while and then observe it. I am here to refactor the project and change a lot of places and then often Encountered, reload the window when that happens again to avoid this problem.Thank you for your response.

**Comment by tyu1996** [comment]
@git10135405 他的意思是你能够提供让他重现这个问题的步骤吗？

**Comment by git10135405** [comment]
@tyu1996 
我上面说的就是重现步骤，但我不确定他机器上能不能复现

**Comment by git10135405** [comment]
@JohnstonCode
https://github.com/JohnstonCode/svn-scm/issues/616#issuecomment-504330556
thanks!

**Comment by JohnstonCode** [comment]
Do you know of any large public svn repositories i can use to replicate the bug?

**Comment by git10135405** [comment]
@JohnstonCode  sorry i can't!

**Comment by git10135405** [comment]
@JohnstonCode 
I just changed the three files. It was normal at the beginning. I browsed a few webpages for a while and then see it again. I looked at the output log of the console as a screenshot.：
![image](https://user-images.githubusercontent.com/35558611/60476948-1579ed00-9cb0-11e9-8744-97a35869fda9.png)

**Comment by JohnstonCode** [comment]
If there isnt a way i can locally reproduce the issue i wont be able to fix it
