### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by alizfazel** [JohnstonCode/svn-scm#617]
- Issue Type: `Bug`
- Extension Name: `svn-scm`
- Extension Version: `1.54.0`
- OS Version: `Linux x64 4.15.0-51-generic`
- VSCode version: `1.35.1`
json 
{
	"messages": [],
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 11031,
		"activateCallTime": 1,
		"activateResolvedTime": 3274,
		"activationEvent": "*"
	},
	"runtimeErrors": []
}

**Comment by JohnstonCode** [comment]
Is this just a one off or a constant issue?
