### ISSUE TITLE
SVN Merge Support

### ISSUE THREAD

**Issue by adam-stamand** [JohnstonCode/svn-scm#618]
I apologize if this has already been addressed, but I can't find any information about it. Does this plugin support SVN Merge? If not, do other users just use the CLI when it comes to merging?

**Comment by JohnstonCode** [comment]
The extension does not currently support merge. I use the cli to merge

**Comment by adam-stamand** [comment]
Understood, thanks for the information. I think merging with the ability to view and resolve conflicts within vscode would be a very handy feature. 

Thanks again

**Comment by mctunes** [comment]
I second this feature request. The extension is fantastic, and merging in the terminal is no problem, but merging and resolving conflicts through the UI would be awesome!

WAWAW

**Comment by lpvezina** [comment]
+1 for this feature

**Comment by rpetrik** [comment]
+1

**Comment by liucien** [comment]
+1

**Comment by hallsamuel90** [comment]
+1

**Comment by KrestenHelstrup** [comment]
+1
Would really improve my workflow :)
