### ISSUE TITLE
svn-scm executes 'svn info' from within ignored directories

### ISSUE THREAD

**Issue by DavidA2014** [JohnstonCode/svn-scm#621]
- VSCode Version: 1.35.1
- OS Version: Centos 7.6
- Extension Version: 1.54.2
- System Language:
- SVN Version: 1.12.0

It seems that svn-scm executes 'svn info' from within ignored directories. This gives multiple warning messages in the log.

In my project, .vscode directory is versioned but directory ipch is ignored.  From the command line I see:

    $ cd .vscode
    $ svn info
    Path: .
    Working Copy Root Path: <snip>
    URL: <snip>
    Relative URL: <snip>
    Repository Root: <snip>
    Repository UUID: <snip>
    Revision: 39
    Node Kind: directory
    Schedule: normal
    Last Changed Author: <snip>
    Last Changed Rev: 37
    Last Changed Date: 2019-06-27 11:10:28 +0100 (Thu, 27 Jun 2019)
    
    $ cd ipch
    $ svn info
    svn: warning: W155010: The node '<snip>/.vscode/ipch' was not found.
    
    svn: E200009: Could not display info for all targets because some targets don't exist

Similarly in svn-scm I see:

    [ipch]$ svn: E200009: Could not display info for all targets because some targets don't exist
    [ipch]$ svn: warning: W155010: The node '<snip>/.vscode/ipch' was not found.

I see lots of similar warnings.  Could **svn info** be inhibited for ignored folders?

**Comment by dbausch** [comment]
It is a missing "await" on the result of isSvnFolder in model.ts. (Introduced in 5e3631e). I will prepare a PR later today.

**Comment by dbausch** [comment]
Created PR #625 which should remedy the situation substatially. However, I'm still confused why tryOpenRepository is called for all those files in the first place. With "multipleFolders" set to false, shouln't it try to open the root folder and nothing else?

**Comment by DavidA2014** [comment]
Thank you.
