### ISSUE TITLE
Flatten multifolder workspaces

### ISSUE THREAD

**Issue by vrokolos** [JohnstonCode/svn-scm#622]
Can we have an option to flatten multiple folder workspace hierarchy so that instead of 5 lists of svn we get 1 combined list when the project share the same repo?

**Comment by edgardmessias** [comment]
Look the `svn.sourceControl.combineExternalIfSameServer` option

**Comment by vrokolos** [comment]
Tried but it didn't work. I still see multiple projects on the svn sidebar

**Comment by edgardmessias** [comment]
Each repository has same repository UUID? `svn info` to show

**Comment by vrokolos** [comment]
FOLDER1:
Working Copy Root Path: J:\ctaf\client
URL: http://10.10.100.11:81/svn/ctaf/client/MOD_EMPOFFICE
Relative URL: ^/client/MOD_EMPOFFICE
Repository Root: http://10.10.100.11:81/svn/ctaf
Repository UUID: 45b33c56-67e6-634e-a54d-d765a1cd1f47

FOLDER2:
Working Copy Root Path: J:\ctaf\server
URL: http://10.10.100.11:81/svn/ctaf/server
Relative URL: ^/server
Repository Root: http://10.10.100.11:81/svn/ctaf
Repository UUID: 45b33c56-67e6-634e-a54d-d765a1cd1f47

**Comment by JohnstonCode** [comment]
@vrokolos do you mean if you have two folders open with the same svn repository checked out in them?
