### ISSUE TITLE
svn.path - Unknown configuration setting

### ISSUE THREAD

**Issue by DavidA2014** [JohnstonCode/svn-scm#627]
- VSCode Version: 1.35.1
- OS Version: Windows 10 with remote connection to Centos 7.6
- Extension Version: 1.54.3
- System Language:
- SVN Version:

## Issue ##

I have two versions of svn on the remote machine. I want to set svn.path to indicate which version svn-scm should use.  I tried to set svn.path in remote settings but I see:

## Screenshots ##
![image](https://user-images.githubusercontent.com/7724321/60427591-e6e80d80-9bee-11e9-8c4d-eb69c03eaa07.png)

![image](https://user-images.githubusercontent.com/7724321/60430478-506b1a80-9bf5-11e9-8597-76318bb58b87.png)

**Comment by JohnstonCode** [comment]
I need to look into this.

**Comment by edgardmessias** [comment]
@DavidA2014, your value is a folder, change to `/opt/CollabNet_Subversion/bin/svn`

**Comment by DavidA2014** [comment]
Thanks for your reply, but the configuration setting is still unknown (I have checked the path):

![image](https://user-images.githubusercontent.com/7724321/61122461-bf6c2d00-a499-11e9-805b-330e40681614.png)
