### ISSUE TITLE
Reuse svn credentials for externals

### ISSUE THREAD

**Issue by DavidA2014** [JohnstonCode/svn-scm#629]
We have a svn project that includes 6 externals. My credentials are the same for all externals but I am prompted for credentials 7 times.  Would it be possible for svn-scm to reuse the project's credentials for all externals so that I am prompted only once? Or am I missing something?

I am running svn-scm 1.54.3 over Remote-SSH.

**Comment by JohnstonCode** [comment]
What OS? both local and remote.

**Comment by DavidA2014** [comment]
My particular request is for remote (Centos 7.6). This is because the remote system is headless and does not have gnome keyring installed.

**Comment by JohnstonCode** [comment]
I will need to look into this.

**Comment by JohnstonCode** [comment]
For credential reuse i would  recommend adding a config option. but this would involve saving them in memory. Would people be comfortable with that?

**Comment by jstolte** [comment]
I see a similar issue with our code base... we have 25+ externals across a couple of different code repositories... running VSCode 1.40.2.  What I experience is being asked 3x for credentials for each external (though svn output logs shows 4 authentication failures).  The main project is in one code repository and our externals are in 2 different code repositories all on the same SVN server... my credentials are the same for all repositories.

If I view the SCN Output logs within VSCode... I see something like the following...

[hydra]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/branches/feature-xyz/source/hydra'
[hydra]$ svn: E215004: No more credentials or we tried too many times.
[hydra]$ Authentication failed[hydra]$ svn stat --xml --no-ignore --ignore-externals --show-updates

[hydra]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/branches/feature-xyz/source/hydra'
[hydra]$ svn: E215004: No more credentials or we tried too many times.
[hydra]$ Authentication failed[hydra]$ svn stat --xml --no-ignore --ignore-externals --show-updates

[hydra]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/branches/feature-xyz/source/hydra'
[hydra]$ svn: E215004: No more credentials or we tried too many times.
[hydra]$ Authentication failed[hydra]$ svn stat --xml --no-ignore --ignore-externals --show-updates

[hydra]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/branches/feature-xyz/source/hydra'
[hydra]$ svn: E215004: No more credentials or we tried too many times.
[hydra]$ Authentication failed[v8Mac]$ svn stat --xml --no-ignore --ignore-externals --show-updates

[v8Mac]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/trunk/tools/jslint/v8Mac'
[v8Mac]$ svn: E215004: No more credentials or we tried too many times.
[v8Mac]$ Authentication failed[v8Mac]$ svn stat --xml --no-ignore --ignore-externals --show-updates

[v8Mac]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/trunk/tools/jslint/v8Mac'
[v8Mac]$ svn: E215004: No more credentials or we tried too many times.
[v8Mac]$ Authentication failed[v8Mac]$ svn stat --xml --no-ignore --ignore-externals --show-updates

[v8Mac]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/trunk/tools/jslint/v8Mac'
[v8Mac]$ svn: E215004: No more credentials or we tried too many times.
[v8Mac]$ Authentication failed[v8Mac]$ svn stat --xml --no-ignore --ignore-externals --show-updates

[v8Mac]$ svn: E170013: Unable to connect to a repository at URL 'hxxp://xxxx/svn/yyyy/trunk/tools/jslint/v8Mac'
[v8Mac]$ svn: E215004: No more credentials or we tried too many times.
[v8Mac]$ Authentication failed[graphics]$ svn stat --xml --no-ignore --ignore-externals --show-updates

... etc for each external

If I load up the same project in Eclipse... I am asked once for credentials.

**Comment by edgardmessias** [comment]
Closed with #799

**Comment by daldr-ntml** [comment]
Hi, I've just returned to trying this extension after a long gap. I am running v2.17.0 on a remote Ubuntu 22.04 server. The extension still seems to be prompting me for credentials for every external, even though they are the same.

Is your understanding that this issue is fixed and I should only be prompted once?
