### ISSUE TITLE
Revert this change in inline diff

### ISSUE THREAD

**Issue by it0243** [JohnstonCode/svn-scm#638]
It would be really helpful to have a 'Revert this change' functionality when viewing a locally modified file in Diff mode.

![code-svn-diff](https://user-images.githubusercontent.com/1389205/60974479-d2b0b880-a332-11e9-925b-ac0d43bd29f6.png)

**Comment by JohnstonCode** [comment]
If you open the file and go to the line in question and click on the colored gutter you can revert the change.

**Comment by JohnstonCode** [comment]
I don't think vs code currently supports reverts in the diff view.

**Comment by it0243** [comment]
@JohnstonCode Yes, this is how I am doing it now, but for a large number of files and diffs, I think that it would be easier to revert it in diff mode. So this is a vs code issue and not an issue of the svn plugin, right?
Thank you for your help and instant reply.

**Comment by JohnstonCode** [comment]
Yes the plugin only uses the diffing provided by VS Code.
