### ISSUE TITLE
can't refresh!

### ISSUE THREAD

**Issue by zhouqiulin** [JohnstonCode/svn-scm#64]
- VSCode Version:
- OS Version:
- Extension Version:
- System Language:

Steps to Reproduce:

1.
2.

**Comment by JohnstonCode** [comment]
Can I have any more information?

**Comment by zhouqiulin** [comment]
When I run 'svn:refresh' the vscode seems do nothing and have no any messeage.

**Comment by JohnstonCode** [comment]
The refresh command doesnt you any messages.

It is just there to update the source control view.

**Comment by zhouqiulin** [comment]
But can't get changed source by my colleague
Do confirm my colleague have commitd the source

**Comment by edgardmessias** [comment]
Fixed by #63

**Comment by JohnstonCode** [comment]
I'll do a release now

**Comment by JohnstonCode** [comment]
live now v1.4.0
