### ISSUE TITLE
svn plugin can't be used in mac 

### ISSUE THREAD

**Issue by frhandlee** [JohnstonCode/svn-scm#642]
- VSCode Version:1.36.1
- OS Version:macOs 10.14.5
- System Language:CN
- SVN Version: 1.54.3

in my macbookpro , when a svn program opened in VSCode,the icon of svn plugin beside will disappear,Before that ，It's not gonna happen in my macbookair，so it could be a  system problem but
I'm not sure。
Another phenomenon，the svnplugin of old version such as 1.46.2 , which without the icon of svn plugin in the sidebar  can be used

**Comment by JohnstonCode** [comment]
Please use the bug template

**Comment by frhandlee** [comment]
> Please use the bug template
sorry, Is this the template？

VSCode Version:1.36.1
OS Version:macOs 10.14.5
System Language:CN
SVN Version: 1.54.3
in my macbookpro , when a svn program opened in VSCode,the icon of svn plugin beside will disappear,Before that ，It's not gonna happen in my macbookair，so it could be a system problem but
I'm not sure。
Another phenomenon，the svnplugin of old version such as 1.46.2 , which without the icon of svn plugin in the sidebar can be used

**Comment by JohnstonCode** [comment]
If you go `View >> Output >> Svn` can you copy what you have in there please?

**Comment by frhandlee** [comment]
> If you go `View >> Output >> Svn` can you copy what you have in there please?

![image](https://user-images.githubusercontent.com/37646076/61340456-fadd7180-a874-11e9-9ef3-b13af8e1d191.png)

**Comment by frhandlee** [comment]
> > If you go `View >> Output >> Svn` can you copy what you have in there please?
> 
> ![image](https://user-images.githubusercontent.com/37646076/61340456-fadd7180-a874-11e9-9ef3-b13af8e1d191.png)

Screenshots under version 1.46.2
![image](https://user-images.githubusercontent.com/37646076/61341400-b18f2100-a878-11e9-820f-4f345fa41cd9.png)

**Comment by JohnstonCode** [comment]
If you go to `Help >> Toggle Developer Tools >> Console` do you have any errors relating to the svn extension?

**Comment by frhandlee** [comment]
> relating

![image](https://user-images.githubusercontent.com/37646076/61355918-e5356f80-a8a7-11e9-93b0-b29102e14e59.png)

**Comment by JohnstonCode** [comment]
Any of the svn calls that use `--xml` will return UTF-8 which is what is breaking for you i think.

**Comment by frhandlee** [comment]
> Any of the svn calls that use `--xml` will return UTF-8 which is what is breaking for you i think.

Thank you for your help,I solved the problem, my computer lacks character set.

**Comment by JohnstonCode** [comment]
Good news! :)
