### ISSUE TITLE
Remove coverage reports from mac and windows builds

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#644]

**Comment by edgardmessias** [comment]
Why?

**Comment by JohnstonCode** [comment]
coverage is the same regardless of OS

**Comment by JohnstonCode** [comment]
I know that it will not show fails that are OS specific but i dont use the report for that just to see coverage

**Comment by edgardmessias** [comment]
Not for `src/svnFinder.ts`, but ok
