### ISSUE TITLE
How to create branch

### ISSUE THREAD

**Issue by ESLHemantSangle** [JohnstonCode/svn-scm#648]
- VSCode Version:1.36.1
- OS Version: Ubuntu 16.04 LTS
- Extension Version: 1.54.4
- SVN Version:1.9.3

I have referred the issue [256](https://github.com/JohnstonCode/svn-scm/issues/256) but still
I am not able to create branch as i don't see the name in left corner other than the update revision button please see the image below

![62004894-cdcc7100-b148-11e9-893c-e4df0a36f6fc](https://user-images.githubusercontent.com/36596748/62034012-d84f3f00-b20a-11e9-942b-4a1a3e0ed362.png)

**Comment by JohnstonCode** [comment]
Can you run `svn info` and show me the output?

**Comment by ESLHemantSangle** [comment]
Here is output of `svn info` running in repository folder
Working Copy Root Path: /home/hemant/HemantSangle/Workspace/VSCode/Java/StateParameterProcessing
URL: svn://192.168.0.6/SVN2/StateParameterProcessing
Relative URL: ^/StateParameterProcessing
Repository Root: svn://192.168.0.6/SVN2
Repository UUID: a1bb019b-ad4d-4fad-94e8-3b243ef4eac2
Revision: 67
Node Kind: directory
Schedule: normal
Last Changed Author: hemant.sangle
Last Changed Rev: 67
Last Changed Date: 2019-07-29 11:10:49 +0530 (Mon, 29 Jul 2019)

**Comment by JohnstonCode** [comment]
Can you run `svn ls ^/branches` for me please

**Comment by ESLHemantSangle** [comment]
Here is output of `svn ls ^/branches`

svn: warning: W160013: URL 'svn://192.168.0.6/SVN2/branches' non-existent in revision 68
svn: E200009: Could not list all targets because some targets don't exist

**Comment by JohnstonCode** [comment]
Can you explain the directory structure of your svn repository?

**Comment by ESLHemantSangle** [comment]
It's a single folder containing other project related file
StateParameterProcessing
 --logs
 --src
 --target
 --pom.xml

**Comment by JohnstonCode** [comment]
I mean like 

```
svn_repo:
    - trunk
    - branches
    - tags
```

**Comment by ESLHemantSangle** [comment]
> I mean like
> 
> ```
> svn_repo:
>     - trunk
>     - branches
>     - tags
> ```

No actually we don't have that structure because the SVN server is setup by other person.

**Comment by JohnstonCode** [comment]
If you just have a flat structure then you cant create banches

**Comment by ESLHemantSangle** [comment]
Okay now i got it i will try to update the directory structure of my repository and then will try to create branch so now i have to create structure like below
<pre>StateParameterProcessing:
        - trunk
            - V1
            - V2
        - branches
        - tags
</pre>
is it right?

**Comment by JohnstonCode** [comment]
Not sure about the V1/V2.

but my normal structure is trunk, branches and tags

**Comment by ESLHemantSangle** [comment]
Hey it worked now i am able to see the name of repository in the left corner and can create the branch also by clicking it. Thanks for this wonderful plugin.

**Comment by JohnstonCode** [comment]
No problem. glad it's work for you now.

**Comment by ahmednrana** [comment]
I still cannot create branches. The option is not visible. 
My project Structure is 
```
-trunk
-lib
-branches
```

the command 
`svn ls ^/branches`
gives the following output 
`sccd/`
