### ISSUE TITLE
Encoding problems with gutter 

### ISSUE THREAD

**Issue by nihlet** [JohnstonCode/svn-scm#649]
- VSCode Version: 1.36.1
- OS Version: Microsoft Windows 7  [Version 6.1.7601]
- Extension Version: 1.54.4
- System Language: Russian, windows-1251 
- SVN Version: TotroiseSvn 1.12

## Issue ##
Gutter shows, that there is some unsaved editions on characters specific to windows-1251 encoding. 

I've tryed to use different variants of settings `"files.autoGuessEncoding"` and `"svn.default.encoding"` with `true/false` and `none/windows1251/windows-1251/cp1251` respectfully.

There is some similar issues back in time: #594, #526, #483, #9.

## Steps to Reproduce ##

1. Commit to repo file with windows-1251 encoding (and specific characters)
2. Open VScode 

## SVN Output ##
```
[tempRepoWorkingCopy]$ svn info --xml e:\Projects\tempRepoWorkingCopy\iddqd.cpp
[tempRepoWorkingCopy]$ svn cat iddqd.cpp
```

## Screenshots ##
![Gutter](https://user-images.githubusercontent.com/9762164/62353524-87459080-b513-11e9-8546-e87bf7b11099.PNG)
![extentions](https://user-images.githubusercontent.com/9762164/62353529-8a408100-b513-11e9-9ab8-7778a822aa44.PNG)

## User settings ##
```
{
    "editor.fontSize": 12,
    "editor.minimap.enabled": false,
    "editor.fontLigatures": true,
    "editor.rulers": [
        120
    ],
    "window.zoomLevel": 0,
    "terminal.integrated.shell.windows": "C:\\Windows\\system32\\cmd.exe",
    "window.restoreWindows": "none",
    "files.associations": {
        "*.cu": "cpp"
    },
    
    "C_Cpp.default.cppStandard": "c++14",
    "C_Cpp.default.intelliSenseMode": "clang-x64",
    "diffEditor.ignoreTrimWhitespace": true,
    "editor.fontFamily": "'Fira Code', Consolas, 'Courier New', monospace",
    "editor.renderWhitespace": "none",
    "files.autoGuessEncoding": false,
    "git.autofetch": true,
    "http.proxy": "http://user:password@server.domain:port",
    "svn.default.encoding": "windows-1251",
    "svn.diff.withHead": false,
    "svn.enableProposedApi": "none",
    "workbench.colorTheme": "Solarized Dark",
    "workbench.editor.tabSizing": "shrink",
    "C_Cpp.default.cStandard": "c99"
}
```

Repo and workspace example:
[example.zip](https://github.com/JohnstonCode/svn-scm/files/3460226/example.zip)

**Comment by JohnstonCode** [comment]
Can you try
```
"files.encoding": "windows1251",
"files.autoGuessEncoding": false
```

and delete `"svn.default.encoding"`

**Comment by nihlet** [comment]
With your tweaks it work good.

**Comment by JohnstonCode** [comment]
Glad its working for you now. Can i close the issue?

**Comment by nihlet** [comment]
It could be good to have sync between `"files.autoGuessEncoding": true` and SVN stuff,
but I'm fine with this workaround.

**Comment by JohnstonCode** [comment]
Yeah it would be nice but encoding is an absolute mine field.
