### ISSUE TITLE
On MacOS, it will ask for username/password every time after VSCode restart

### ISSUE THREAD

**Issue by netsesame2** [JohnstonCode/svn-scm#652]
- VSCode Version: 1.37.0
- OS Version: Darwin x64 18.7.0
- Extension Version:1.54.4
- System Language:English
- SVN Version:1.8.13

## Issue ##
Recently, every time when I restart VSCode, SVN will ask for username and password. However, when I offer the username and password, it works, but when I restart VSCode, it ask again. I'm nearly crazy.

## Screenshots ##
<img width="633" alt="QQ20190812-233357@2x" src="https://user-images.githubusercontent.com/22102518/62877458-ae912e80-bd59-11e9-901c-055233918e04.png">

**Comment by JohnstonCode** [comment]
Do you have the issue on an older version fo the extension?

**Comment by netsesame2** [comment]
@JohnstonCode The older version works well

**Comment by JohnstonCode** [comment]
Which version?

**Comment by netsesame2** [comment]
@JohnstonCode I forgot to get the old version...

**Comment by netsesame2** [comment]
@JohnstonCode To my strange, two different project, the same SVN server, one is OK, and the other need uname/password every time.

**Comment by JohnstonCode** [comment]
Can you copy the output of `"View >> Output >> OUTPUT >> SVN"` from each of the projects please

**Comment by netsesame2** [comment]
OK, I'll send you later.




------------------ 原始邮件 ------------------
发件人: "Christopher"<notifications@github.com>; 
发送时间: 2019年8月27日(星期二) 下午4:02
收件人: "JohnstonCode/svn-scm"<svn-scm@noreply.github.com>; 
抄送: "Netsesame"<netsesame@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [JohnstonCode/svn-scm] On MacOS, it will ask forusername/password every time after VSCode restart (#652)




Can you copy the output of "View >> Output >> OUTPUT >> SVN" from each of the projects please

**Comment by netsesame2** [comment]
The following output both copied after restart vscode.
The svn output which works well:
```
Using svn "1.8.13" from "/usr/local/bin/svn"
[ErrorbookWeb]$ svn info --xml /Users/netsesame/Projects/ErrorbookWeb/caches/configs/product.php
[ErrorbookWeb]$ svn info --xml
[ErrorbookWeb]$ svn cat caches/configs/product.php
[ErrorbookWeb]$ svn stat --xml --no-ignore --ignore-externals --show-updates
```

Another which works always ask username:
```
Using svn "1.8.13" from "/usr/local/bin/svn"
[ErrorbookApp3]$ svn info --xml /Users/netsesame/Projects/ErrorbookApp3/src/global.scss
[ErrorbookApp3]$ svn cat src/global.scss
[ErrorbookApp3]$ svn info --xml
[ErrorbookApp3]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[ErrorbookApp3]$ svn: E170001: Unable to connect to a repository at URL 'svn://www.shikongzi.com/mysa_app3'
[ErrorbookApp3]$ svn: E170001: Can't get username or password
```

**Comment by Constantiner** [comment]
I have the same issue on MacOS X and it was the same all the time I used extension. I suppose extension has some problems with Keychain access but very possibly I've mistaken.

Vote for fixing that!

**Comment by Constantiner** [comment]
Yesterday I've solved it on MacOS. It is definitely related to Keychain. SVN extension asks username/password on VS Code start up on MacOS when password is storing in Keychain.

You can go to `~/.subversion/auth/svn.simple` and find there a file with your SVN domain and username.  It will contain something like:

```
K 8
passtype
V 8
keychain
```

and it tells us it stores password in Keychain. To solve it (I mean to make it work with current version of SVN extension) just delete this file, then add the following to the `[auth]` section of `~/.subversion/config` file:

```
password-stores=
```

Then run the following in Terminal in your project's catalog:

```bash
svn up
```

and enter your login/password there. After that find newly created file for your SVN domain in `~/.subversion/auth/svn.simple` and make sure it contains something like the following:

```
K 8
passtype
V 6
simple
```

Unfortunately it will contain your SVN password in plain text and it is not great for security reasons but we need to wait for fix of SVN extension Macos Keychain access issue to return back to secure stroing of Subversion passwords.

Now you can restart your VS Code and it should not request for SVN username/password.

**Comment by netsesame2** [comment]
Thanks for @Constantiner. I followed your advise, and found another simple way to resolve it.
1. Goto ~/.subversion/auth/svn.simple
2. Find and delete the config file which contains my svn site.
3. Open the Keychain Tool in control center, remove the related key.
4. Goto my project folder, run 'svn up --username xxxx --password xxxx'
5. Reopen VSCode. it will be OK.

**Comment by fattoliu** [comment]
Thanks for @Constantiner . I've solved it on macOS Catalina. Cool!!
