### ISSUE TITLE
SVN VSCode plugin not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by SamoPP** [JohnstonCode/svn-scm#654]
- VSCode Version: 1.37.1
- OS Version: Ubuntu 18.04
- Extension Version: 1.54.4
- System Language: English US
- SVN Version: 1.9.7

## Issue ##
I have installed your plugin via VSCode marketplace. Icon briefly appears at the stratup of VSCode app. But then disappeares. Please see screenshots.

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

## Screenshots ##
![SVN Icon Briefly Appears At Startup](https://user-images.githubusercontent.com/4817398/63636961-a2a04900-c644-11e9-9ee2-3eb21ea7881e.png)

![SVN Icon Diassapears After Startup](https://user-images.githubusercontent.com/4817398/63636965-aaf88400-c644-11e9-8e81-868da027bbab.png)

**Comment by JohnstonCode** [comment]
`Paste here content of "View >> Output >> OUTPUT >> SVN"`

**Comment by HarveyJay** [comment]
I try to run vs code in command line with parameter: code --enable-proposed-api johnstoncode.svn-scm.
And it work! But I need to run like this every time. It's terrible.
