### ISSUE TITLE
Unable to update - Can't convert string from native encoding to 'UTF-8'

### ISSUE THREAD

**Issue by theophane-girard** [JohnstonCode/svn-scm#656]
Hello,

- VSCode Version: 1.37.1
- OS Version: Windows_NT x64 10.0.16299
- Extension Version: 1.54.4
- System Language: french
- SVN Version: 1.11.1
## Issue ##
Can't update
## Steps to Reproduce ##

1. Click on "Update Revision"

## SVN Output ##
```
$ svn: E000022: Error converting entry in directory '/path/to/folder/which/contains/pdf/files' to UTF-8
$ svn: E000022: Can't convert string from native encoding to 'UTF-8':
$ svn: E000022: file.1.pdf
```

## Screenshots ##
<img width="506" alt="svn" src="https://user-images.githubusercontent.com/11314829/63929630-0ca85c00-ca52-11e9-835b-3d0aba2c57ef.png">

**Comment by JohnstonCode** [comment]
#331 have a look at the solution suggested here.

**Comment by theophane-girard** [comment]
Well, after many searches, I just ran 
```
SET LC_CTYPE=fr_FR.UTF-8
```
reopened vscode and it's OK

Thanks

**Comment by edgardmessias** [comment]
@JohnstonCode, maybe we can change to like this: https://github.com/microsoft/vscode/blob/e77b008fb04222192a608906ff603bd72943d779/extensions/git/src/git.ts#L452

**Comment by JohnstonCode** [comment]
@edgardmessias Yeah would stop theses issues from happening. Think this is the 4th one now

**Comment by edgardmessias** [comment]
And add a documentation for svnkit (jsvn) for some cases

**Comment by theophane-girard** [comment]
would be great :)

I close the issue
