### ISSUE TITLE
Search the svn log? eg. author, date, etc.

### ISSUE THREAD

**Issue by huiEric** [JohnstonCode/svn-scm#657]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by it0243** [comment]
Indeed it would be very useful if we could have a search/filtering functionality in log history.

**Comment by pspletinckx** [comment]
+1 This is the only thing still missing from my workflow. 
_I find myself looking most for for PROJ-1234 or Rev._
