### ISSUE TITLE
Wrong revision diff file with files with the same name

### ISSUE THREAD

**Issue by davidmartos96** [JohnstonCode/svn-scm#658]
- VSCode Version: 1.37.1
- OS Version: Windows 10
- Extension Version: 1.54.4

## Issue ##
When looking at the diffs in the "Repositores" block, in the SVN tab, files with the same name use the same diff file in the temporary directory. This can happen quite often in multi module Maven projects, which have the file pom.xml in different subfolders.

I was wondering if it would fix it if the whole path of the file was used instead of the basename.
https://github.com/JohnstonCode/svn-scm/blob/b26602f2237938106ebaaba52bf7dc54aecf00cc/src/tempFiles.ts#L16

## Screenshots ##
![image](https://user-images.githubusercontent.com/22084723/64172167-a443eb00-ce54-11e9-9137-64931186cc9e.png)

Those 2 pom.xml are in different directories in the source code, but the diff viewer makes both link to the same diff file.
![image](https://user-images.githubusercontent.com/22084723/64172268-d9503d80-ce54-11e9-96fe-f2784d0e109e.png)

**Comment by djbrown** [comment]
Same here! This bug lead to great confusion in out code reviews.
A workaround is to close the diff-view and open the other same-named file in a fresh view.

**Comment by JohnstonCode** [comment]
Sorry completly missed this one. Using the whole path wont work because of the slashes. Maybe a hash of the full path will work.

**Comment by davidmartos96** [comment]
Many thanks for the update!

**Comment by JohnstonCode** [comment]
Release has failed. VS marketplace issue. Will try again tomorrow
