### ISSUE TITLE
How to add an SVN repository

### ISSUE THREAD

**Issue by deepfriedbrain** [JohnstonCode/svn-scm#662]
I installed this extension to Visual Studio Code on Mac. I have SVN installed.

I have been using Eclipse to work with SVN-based projects. In Eclipse I can go to the SVN Explorer and add a repo to explore it, or I can create a new SVN project by selecting a folder in a repo.

I can't figure out how to add a repo or create a SVN project in VSC similar to the way I can do in Eclipse.

Any help would be appreciated. Thanks.

**Comment by JohnstonCode** [comment]
You cannot create a SVN repository using this extension. You can check out a project using the command pallet and typing `svn checkout`
