### ISSUE TITLE
SVN not found. Install it or configure it using the 'svn.path' setting.

### ISSUE THREAD

**Issue by raghumedia21** [JohnstonCode/svn-scm#669]
- VSCode Version: 1.38.1
- OS Version: Windows 10 
- Extension Version: 
- System Language: English
- SVN Version: 1.12.2

## Issue ##
 Installed Tortoise SVN 1.12.1, Still getting "SVN not found. Install it or configure it using the 'svn.path' setting."
## Steps to Reproduce ##

1. Install Tortoise SVN 1.12.1
2. One VS code 
3. Install SVN extension.

## SVN Output ##
```SVN not found. Install it or configure it using the 'svn.path' setting. 
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/39167752/66096326-7d5dff00-e54f-11e9-994e-47e6cc4dd70a.png)

**Comment by JohnstonCode** [comment]
Can you go to the directory of your svn.exe and run `svn.exe --version --quiet`
