### ISSUE TITLE
Error: "Unable to update", if nothing to update

### ISSUE THREAD

**Issue by s-martin** [JohnstonCode/svn-scm#67]
- VSCode Version: 1.18.1
- OS Version: CentOS 7.4
- Extension Version: 1.4.0
- System Language: DE

Steps to Reproduce:

1. Open directory with clean workspace and unchanged repo
2. Select "Svn update"
3. Error message "Unable to update" occurs

I think this message is a little bit misleading.

**Comment by JohnstonCode** [comment]
Yeah that does sounds misleading. I'm trying to replace all the generic error messages with something a bit more accurate.

**Comment by JohnstonCode** [comment]
can you copy and paste the console error message you get when you try to update please.

**Comment by s-martin** [comment]
It's just "Error: Unable to update" in the top message box (no idea how this is called in VSCode).

In the output window I just see `svn update`

**Comment by JohnstonCode** [comment]
if you view the command pallet and search and click on "toggle developer tools" and go to the console what do you get?

**Comment by s-martin** [comment]
Hope this helps:

```
﻿console.ts:123 [Extension Host] TypeError: Cannot read property '0' of null
	at Repository.<anonymous> (/home/mts/.vscode/extensions/johnstoncode.svn-scm-1.4.0/out/svnRepository.js:192:71)
	at Generator.next (<anonymous>)
	at fulfilled (/home/mts/.vscode/extensions/johnstoncode.svn-scm-1.4.0/out/svnRepository.js:4:58)
	at <anonymous>
messageService.ts:126 Unable to update
e.doShow	@	messageService.ts:126
e.show	@	messageService.ts:105
e._showMessage	@	mainThreadMessageService.ts:72
n.Class.derive._oncancel	@	winjs.base.raw.js:1641
e._showMessage	@	mainThreadMessageService.ts:42
e.$showMessage	@	mainThreadMessageService.ts:36
e.invoke	@	abstractThreadService.ts:41
e._invokeHandler	@	rpcProtocol.ts:109
e._receiveOneMessage	@	rpcProtocol.ts:96
(anonymous)	@	rpcProtocol.ts:32
(anonymous)	@	rpcProtocol.ts:157
e.invoke	@	callbackList.ts:36
e.fire	@	event.ts:123
(anonymous)	@	ipc.net.ts:82
emitOne	@	events.js:96
emit	@	events.js:191
readableAddChunk	@	_stream_readable.js:178
Readable.push	@	_stream_readable.js:136
onread	@	net.js:560
```

**Comment by JohnstonCode** [comment]
Yeah that's what i'm after. Thank you.

**Comment by JohnstonCode** [comment]
@s-martin im guessing if you run "svn update" in the command line the result comes back in German?

**Comment by s-martin** [comment]
Negative.

```
[user@machine mycurrdir]$ svn update
Updating '.':
At revision 2803.

```

**Comment by JohnstonCode** [comment]
Just updated to v1.4.1 have a try with that and see if you get the same problem

**Comment by s-martin** [comment]
1.4.3:
Now I get Info with the revision. Works for me, thanks!

**Comment by rolkey** [comment]
我的乖乖，这个现象又出现了，这是什么回事呀，万恶的高人呀，还有高版本可以升级吗？
