### ISSUE TITLE
Locked files show as remote changes

### ISSUE THREAD

**Issue by likid** [JohnstonCode/svn-scm#670]
- VSCode Version: 1.38.1
- OS Version: Windows 10 1903
- Extension Version: 1.54.5
- System Language: pt-br
- SVN Version: 1.12

## Issue ##
When another user lock files in the svn server, the extension shows this files as remote changes.

## Steps to Reproduce ##

1. Lock file as a user
2. Check the svn project as another user.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
[Cristal]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[Cristal]$ svn info --xml
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/10984007/66122983-6ce16f00-e5b7-11e9-9c48-58c19bb33b15.png)

**Comment by JohnstonCode** [comment]
If a file is locked it will show up in `svn stat`
