### ISSUE TITLE
Removal of proposed API

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#675]
I suggest that anything using the proposed API is removed. My reasoning is that it is `Proposed API is a set of unstable API ` and `They are subject to change`. Having to hack them to work is also problematic for less knowledgeable people.

**Comment by JohnstonCode** [comment]
#632

**Comment by JohnstonCode** [comment]
@edgardmessias thoughts?

**Comment by JohnstonCode** [comment]
This would be a breaking change and would mean a major version bump

**Comment by edgardmessias** [comment]
I agree, we can make a special plugin to use only proposed api like: https://github.com/microsoft/vscode/tree/master/extensions/git/src/api
Example: this plugin keep only "stable api" and "svn-scm-proposed" with proposed APIs, but it is a dependent plugin

**Comment by JohnstonCode** [comment]
@edgardmessias is the revert in the diff gutter a proposed api?

![image](https://user-images.githubusercontent.com/10222719/67316974-ea363a80-f4f8-11e9-9a5d-2e9a55121221.png)

**Comment by edgardmessias** [comment]
I not remember, but you can check this: https://github.com/microsoft/vscode/blob/313a14265237bc59420bc98c73fbc446b2bf38d1/src/vs/vscode.proposed.d.ts#L581

**Comment by JohnstonCode** [comment]
Yeah it will be requires `LineChange`
