### ISSUE TITLE
Feature Request: Add files/directories to svn:ignore

### ISSUE THREAD

**Issue by s-martin** [JohnstonCode/svn-scm#68]
It would be helpful, if files/directories could be ignored.
Low prio, but still.

This could be part of a bigger feature "Support svn:properties".

**Comment by JohnstonCode** [comment]
@s-martin 

What other svn:properties would be useful?

**Comment by s-martin** [comment]
For me relevant would be (priority from high to low):

1. EOL
2. Executable
3. Externals

I don't use other properties, so i have no preferences.

**Comment by JohnstonCode** [comment]
Thanks for that.

**Comment by edgardmessias** [comment]
@JohnstonCode , my sugestion:

Create a unique command (like "SVN Properties") for
* Command Palette (Current File View)
* Explorer Context (One File or Folder)

From command, run the "proplist" and generate a pick list with avaiable properties (Add common properties if not exsists to create)

After select pick, read value of property and create a temporary file, on file save, update the property

**Comment by JohnstonCode** [comment]
@edgardmessias 

Yea that sounds like a good idea.

**Comment by JohnstonCode** [comment]
Working on this.

**Comment by edgardmessias** [comment]
What your Idea?

**Comment by JohnstonCode** [comment]
Pretty much same as you suggested. But rather than temp file just add a prompt then run `svn propset` if they accept

**Comment by JohnstonCode** [comment]
@edgardmessias how would you suggest i deal with ignoring unversioned files as they arnt in a repository so you cant find a repository to run the command against?

**Comment by edgardmessias** [comment]
Tell me a example

**Comment by edgardmessias** [comment]
We cant use "Resource Group", because contain many files.

We can use [Explorer context menu (`explorer/context`)](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus)

**Comment by JohnstonCode** [comment]
What I mean is that all our commands require the file in question to be in the repository. so we use `getRepository` to find the repository and then use that to run the command

**Comment by JohnstonCode** [comment]
I could just loop through all open repositories and see if the unversioned file is in the directory structure of the repository

**Comment by edgardmessias** [comment]
Show a example of structure
In `svn status` show the unversioned file.

**Comment by JohnstonCode** [comment]
I need to get all open repositories and then check if the file is in the unversioned resource group of each

**Comment by edgardmessias** [comment]
I still can not understand its logic

**Comment by JohnstonCode** [comment]
how do you find out what repository an unversioned file is in?

**Comment by edgardmessias** [comment]
`getRepository` of `model.ts`

**Comment by JohnstonCode** [comment]
Sorry, me being stupid. distracted at work.

**Comment by edgardmessias** [comment]
😆

**Comment by JohnstonCode** [comment]
Everything is working. Having one issue tho. im currently using `svn propset svn:ignore file.php .` it seem to only overwrite whats there already. Any suggestions? 

FYI i use .svnignore and set it via `svn propset svn:ignore -F .svnignore .`

**Comment by JohnstonCode** [comment]
I could do `svn propget svn:ignore .` and then just append it as a new line

**Comment by edgardmessias** [comment]
Yes, use `svn propget svn:ignore .`, append new ignore, remove duplicated items, and `svn propset svn:ignore <new value> .`

**Comment by edgardmessias** [comment]
The question: set ignore on root workspace or first parent folder of file?

**Comment by JohnstonCode** [comment]
parent folder of file

**Comment by JohnstonCode** [comment]
Changes are on [this branch](https://github.com/JohnstonCode/svn-scm/tree/properties)

The changes arnt currently finished some more changes are needed to clean up.

**Comment by edgardmessias** [comment]
For `mime-type`, you can get current defined value

**Comment by edgardmessias** [comment]
Suggestion:
```patch
diff --git a/src/svnRepository.ts b/src/svnRepository.ts
index 7c01743..490744c 100644
--- a/src/svnRepository.ts
+++ b/src/svnRepository.ts
@@ -370,10 +370,11 @@ export class Repository {
   }

   async ignore(directory: string, filename: string) {
+    directory = this.removeAbsolutePath(directory);
     let result;
-    let ignore
+    let ignore;
     try {
-       result = await this.svn.exec(directory, ['propget', 'svn:ignore', directory]);
+       result = await this.exec(['propget', 'svn:ignore', directory]);
        ignore = result.stdout;
        ignore = ignore + filename + "\n";
        ignore = ignore.trim();
@@ -381,6 +382,6 @@ export class Repository {
       return;
     }

-    return await this.svn.exec(directory, ['propset', 'svn:ignore', ignore, '.']);
+    return await this.exec(['propset', 'svn:ignore', ignore, directory]);
   }
 }
```

**Comment by edgardmessias** [comment]
To allow custom properties:
`svn:${propName}` => `propName` in `svnRepository.ts`

Example of custom: `tsvn:logtemplate`

**Comment by JohnstonCode** [comment]
Didn't know custom properties were a thing.

Regarding your above changes I have done [this](https://github.com/JohnstonCode/svn-scm/commit/405b4c38ca6dc889d05ca1acb3505001dec79527). `this.removeAbsolutePath(directory);` was not resolving to the correct path so just left `directory` as is.

**Comment by JohnstonCode** [comment]
Not sure what to do about mime-type.

**Comment by JohnstonCode** [comment]
#232

**Comment by JohnstonCode** [comment]
#233
