### ISSUE TITLE
SCM view empty on latest vscode version

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#681]
- VSCode Version: 1.39.0
- OS Version: Fedora 20
- Extension Version: 1.54.6
- System Language: EN_GB
- SVN Version: 1.12.2

## Steps to Reproduce ##

1. Create nested folders
2. Add file in last nested folder
3. Click add in SCM view
4. Only Folder is shown as changes

## Screenshots ##
![image](https://user-images.githubusercontent.com/10222719/66549923-e4714a00-eb33-11e9-9634-5f13d92fdafe.png)

![image](https://user-images.githubusercontent.com/10222719/66549939-ef2bdf00-eb33-11e9-99e3-920d217d2031.png)

![image](https://user-images.githubusercontent.com/10222719/66549981-fd79fb00-eb33-11e9-94be-58a0b4edafde.png)

![image](https://user-images.githubusercontent.com/10222719/66550031-108ccb00-eb34-11e9-877d-0fceab7c53ec.png)

![image](https://user-images.githubusercontent.com/10222719/66550070-1f737d80-eb34-11e9-822f-95afcf1a2356.png)

![image](https://user-images.githubusercontent.com/10222719/66550113-32864d80-eb34-11e9-8127-2879f0f165d5.png)

**Comment by Yanpas** [comment]
I observe all changes to disappear after first svn refresh

**Comment by sgreiner** [comment]
My changelist is also empty. Reinstalled the extension, also reinstalled it in the WSL - still empty

**Comment by JohnstonCode** [comment]
@sgreiner vscode issue

**Comment by sgreiner** [comment]
Yeah they said that they can reproduce it https://github.com/microsoft/vscode/issues/82203
Thanks @JohnstonCode

**Comment by JohnstonCode** [comment]
https://github.com/microsoft/vscode/issues/82203#issuecomment-540664631
