### ISSUE TITLE
I can't see any files in 'source control' view

### ISSUE THREAD

**Issue by ROMYIM** [JohnstonCode/svn-scm#684]
- VSCode Version:1.39.1 (user setup)
- OS Version:Windows_NT x64 6.1.7601
- Extension Version:1.54.6
- System Language:Chinese
- SVN Version:1.12.0

## Steps to Reproduce ##

1.I updated to the latest version of vscode
2.But I can't see any files in 'source control' view

## SVN Output ##
```

```

## Screenshots ##
![图片](https://user-images.githubusercontent.com/26106153/66698528-62d71300-ed11-11e9-984e-a2dccb801cb4.png)

**Comment by JohnstonCode** [comment]
https://github.com/microsoft/vscode/issues/82203
