### ISSUE TITLE
Even files up to date, the "BASE" row appears in the revision list and stuck at the wrong row

### ISSUE THREAD

**Issue by moonflame** [JohnstonCode/svn-scm#685]
- VSCode Version: 1.39.1
- OS Version: Windows 10 1903
- Extension Version: 1.54.6
- System Language: Chinese (Simplified)
- SVN Version: 1.12.0

## Issue ##
Working in VSCode workspace in the subfolder of the existing SVN folder, the "BASE" row  in the revision list displays at the wrong row, and it remains even the whole local SVN folder is up to date.
Unless I update the whole SVN folder manually and restart VSCode, the BASE is always stuck at the certain row.

## Steps to Reproduce ##
1. Create and work in VSCode workspace in the subfolder of the existing SVN folder.
2. All other functions of the extension work fine, and the extension can update the workspace folder rather then the whole SVN folder (No problem).
3. After submitting or updating within the extension, the revivion list displays correctly, but the "BASE" row is stuck at the certain row when the VSCode program loaded.
4. After updating the whole SVN folder and restarting VSCode program, the "BASE" row disapperd correctly, which means the workspace is up to date.
5. After other submitting or updating whin the extension, if there are revisions newer than when the program loaded, the problem reproduced. The "BASE" row appears at the revision when the program loaded.

6. If I start VSCode with remote revision newer than the local revision, the "BASE" row appears at start of VSCode, and can not be removed without updating the whole SVN folder and restart the program.

## SVN Output ##
Using svn "1.12.0" from "C:\Program Files\TortoiseSVN\bin\svn.exe"
[BDCDJ_Client]$ svn info --xml d:\projects\xx\xx\xx\xx\xx\common.js
[BDCDJ_Client]$ svn cat xx\xx\xx\common.js
[BDCDJ_Client]$ svn log -r HEAD:1 --limit=50 --xml -v svn://subversion.coding.net/xx/xx/xx/xx/xx/xx/common.js
[BDCDJ_Client]$ svn log -r HEAD:1 --limit=50 --xml -v svn://subversion.coding.net/xx/xx
[BDCDJ_Client]$ svn info --xml
[BDCDJ_Client]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[BDCDJ_Client]$ svn update --ignore-externals
[BDCDJ_Client]$ svn stat --xml --no-ignore --ignore-externals
[BDCDJ_Client]$ svn info --xml
[BDCDJ_Client]$ svn stat --xml --no-ignore --ignore-externals --show-updates

## Screenshots ##
Wrong BASE position
![Wrong BASE position](https://user-images.githubusercontent.com/26050430/66792713-8aee8e00-ef2c-11e9-9107-f49736250ee2.png)
SVN folder
![SVN folder](https://user-images.githubusercontent.com/26050430/66792802-f59fc980-ef2c-11e9-8af5-f9dd045df599.png)
VSCode workspace folder
![VSCode workspace folder](https://user-images.githubusercontent.com/26050430/66792811-fc2e4100-ef2c-11e9-844a-11e7eeedcb48.png)

**Comment by JohnstonCode** [comment]
The information from `svn info` is taken directly from the .svn/entries file, and not from the server. This stems from Subversion's basic design of not requesting information from the repository server whenever possible.
