### ISSUE TITLE
Keeping up with the latest vscode version

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#688]
Should we keep up with the latest vscode version? Again just thinking about easer maintinance rather than having to think about our version, current version and insiders.

**Comment by JohnstonCode** [comment]
@edgardmessias @Yanpas

**Comment by Yanpas** [comment]
I vote for bumping minimal vscode version to 1.39. Currently there are no reasons for users to use older vscode and update process is pretty simple

**Comment by edgardmessias** [comment]
After vscode 1.31, we can use `target: es2017` to build, it improve the speed.

**Comment by edgardmessias** [comment]
VSCode 1.31 - Node 10.2.0

https://node.green/#ES2018

https://code.visualstudio.com/updates/v1_31#_nodejs-update

**Comment by JohnstonCode** [comment]
Tests break because of `istanbul`

**Comment by JohnstonCode** [comment]
Options are:

1. Just up vscode enginer version and leave the tsconfig alone and coverage will continue to work
2. Remove coverage and update engine and tsconfig
3. Remove coverage and update engine and tsconfig + Use Jest
