### ISSUE TITLE
Source control doesn't display anything when working in a svn rep subfolder.

### ISSUE THREAD

**Issue by Guema** [JohnstonCode/svn-scm#69]
- VSCode Version: 1.18.1
- OS Version: Win7 x86
- Extension Version: 1.4.1
- System Language: 

Don't know exactly if it is intended or not, but since last version (1.4.1), i'm unable to see source control :

Im working on a multi-languages project, and used to only open the folder where i work, which is a actually a subfolder belonging to a large SVN repository that contains everything.

Worked until 1.4, doesn't work anymore now.
Only work when opening root folder.

Was practical.

Thanks for you precious work
Guema

**Comment by JohnstonCode** [comment]
Thanks for raising this.

I'll look into it.

**Comment by edgardmessias** [comment]
@JohnstonCode, I will fix it.

**Comment by edgardmessias** [comment]
We need to create a lock, for when it is not the root of the trunk, branch or tag, to not allow switch branch

**Comment by JohnstonCode** [comment]
Yes we do. This current issue is caused by the check on [this line](https://github.com/JohnstonCode/svn-scm/blob/master/src/model.ts#L187)

**Comment by edgardmessias** [comment]
I'm updating for it to check the top folders

**Comment by JohnstonCode** [comment]
Opening in a subfolder does also stop the switch branch from working. Doesn't throw any errors as well.

**Comment by edgardmessias** [comment]
Fixed.

**Comment by Guema** [comment]
Thanks and good job for this really fast fix !
