### ISSUE TITLE
Source Control menu empty...

### ISSUE THREAD

**Issue by Davonter** [JohnstonCode/svn-scm#703]
- VSCode Version:1.39.2
- OS Version: Windows10  remote-ssh to Ubuntu16.04
- Extension Version: 1.54.8
- System Language: Windows10(Chinese), Ubuntu16.04(English)
- SVN Version:1.9.3

## Issue ##
The extension upgrade to version 1.54.8 automatically, when I opened my project, the source control menu is empty.

But I downloaded a version 1.54.6, it's work well!

## Steps to Reproduce ##

1. as above.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

nothing output

## Screenshots ##
![image](https://user-images.githubusercontent.com/19240391/67736783-cff1e480-fa43-11e9-8213-b4b900581bcf.png)

**Comment by azenapow** [comment]
Same problem under Remote-Development.

**Comment by lhz960904** [comment]
same problem, please fix as soon as possible!

**Comment by yckim120** [comment]
same problem, OS is macOS Catalina(10.15)

**Comment by JohnstonCode** [comment]
Sorry about that. I tried to release last night but it failed and said it did not publish. I appears it just published an empty package. Fixing now

**Comment by wswongat** [comment]
> Sorry about that. I tried to release last night but it failed and said it did not publish. I appears it just published an empty package. Fixing now

Thank you!

**Comment by JohnstonCode** [comment]
1.54.9 should be rleased in a few minutes.

**Comment by oddbytes** [comment]
Hi,

Sorry, I'm having the same issue with 1.54.9
![imagen](https://user-images.githubusercontent.com/16150346/67748188-9f518100-fa2a-11e9-94c1-2936c7448449.png)

regards

**Comment by carlittoer** [comment]
Hello,

Still no repos found with 1.54.9

Thanks.

**Comment by JohnstonCode** [comment]
Looking at it now

**Comment by bodydisplaynone** [comment]
Just wanted to post this as I'm experiencing the same issue.

1. No repos found in version control.
2. Using the actual plugin (add, refresh) throws errors like: command 'svn.repolog.something' not found

**Comment by bodydisplaynone** [comment]
Any extra steps I have to make to make sure I'm running the fixed version?

I just updated the plugin to the latest release (1.54.10) but I'm still having this issue.

Disable/enable, uninstall/reinstall does not help either.

**Comment by JohnstonCode** [comment]
Probs isnt working. The auto deployment is broken. Sorry

**Comment by bodydisplaynone** [comment]
Oh okay, no worries. :) I'll keep watching and report back as soon as it starts working.

**Comment by JohnstonCode** [comment]
Sorry build process is broken. Manually released 1.54.11

**Comment by dogzhang** [comment]
It works, thanks

**Comment by bodydisplaynone** [comment]
Works perfectly. Thank you.
