### ISSUE TITLE
command 'svn.repolog.addrepolike' not found

### ISSUE THREAD

**Issue by licornduan** [JohnstonCode/svn-scm#704]
Issue Type: <b>Bug</b>

command 'svn.repolog.addrepolike' not found

Extension version: 1.54.9
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Nelson-Ning** [comment]
So am I

**Comment by azenapow** [comment]
#703 is not resolved.

**Comment by Nelson-Ning** [comment]
![image](https://user-images.githubusercontent.com/22850291/67749346-f0339a80-fa67-11e9-9658-607b032f706f.png)
I try to refresh the plug-in or it doesn't work

**Comment by pranayrauthu** [comment]
extension stopped working suddenly. 

`command 'svn.repolog.refresh' not found`

**Comment by oh-jy** [comment]
Still no repos found with 1.54.9，
the same.

**Comment by licornduan** [comment]
![image](https://user-images.githubusercontent.com/19664671/67749990-42c18680-fa69-11e9-848c-86cff19b39d3.png)

**Comment by Nelson-Ning** [comment]
I tried to install version 1.54.6 and the problem was solved

**Comment by oh-jy** [comment]
rollback to 1.54.6 and the problem was solved

**Comment by JohnstonCode** [comment]
Looking at it now

**Comment by JohnstonCode** [comment]
Sorry build process is broken. Manually released 1.54.11
