### ISSUE TITLE
1.54.10版本 mac 升级之后无法使用 

### ISSUE THREAD

**Issue by benmo1602** [JohnstonCode/svn-scm#708]
- VSCode Version: 1.39
- OS Version:
- Extension Version: 
- System Language: js
- SVN Version:1.54.10

## Steps to Reproduce ##

1.   1.54.10版本 mac 升级之后无法使用 ，退回 
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by JohnstonCode** [comment]
Sorry build process is broken. Manually released 1.54.11
