### ISSUE TITLE
branch switchnig doesnt work if not in root of repo

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#71]
- VSCode Version:1.18.1
- OS Version:Fedora 26
- Extension Version:1.4.1
- System Language:EN

Steps to Reproduce:

1.Open folder within svn repo
2. switch branch does nothing but causes conflicts

**Comment by JohnstonCode** [comment]
@edgardmessias any suggestions?

**Comment by edgardmessias** [comment]
Two suggestions:
* Display alert if not root
* Make switch within subfolder (Ex.: trunk/my/folder -> branches/test/my/folder)

**Comment by JohnstonCode** [comment]
what about a check to see if the folder exists in the branch we are switching to. If not show an error message?

**Comment by edgardmessias** [comment]
Yes, like this: https://github.com/JohnstonCode/svn-scm/blob/9c2b975802ece12e6b463db5b9139f03d27b4f7e/src/svnRepository.ts#L113

**Comment by JohnstonCode** [comment]
yes. Ill quickly do this.

**Comment by JohnstonCode** [comment]
Think this was a simpler solution what do you think?

[Link](https://github.com/JohnstonCode/svn-scm/commit/12879e5692eb906a354a9381ccac759548178930)

**Comment by edgardmessias** [comment]
Nice
