### ISSUE TITLE
There is no production.json 

### ISSUE THREAD

**Issue by HoffmannP** [JohnstonCode/svn-scm#715]
- VSCode Version: 1.39.2
- OS Version: Linux arbeit 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Extension Version: 1.54.11
- System Language: LANG=de_DE.UTF-8
- SVN Version: 1.9.7

I don't have a `production.json`

```
Using svn "1.9.7" from "svn"
```
![SVNError](https://user-images.githubusercontent.com/432592/68220260-b9b9ca80-ffe7-11e9-9e28-0be275d54409.png)

**Comment by JohnstonCode** [comment]
You can ignore it. It will be removed shortly #690
