### ISSUE TITLE
Simplify remote changes settings

### ISSUE THREAD

**Issue by SimplySayHi** [JohnstonCode/svn-scm#720]
- VSCode Version: 1.40
- OS Version: MacOS Mojave 10.14.6 (18G103)
- Extension Version: 1.54.11
- System Language: English
- SVN Version: 1.10.4 (r1850624)

## Issue ##
With setting "svn.remoteChanges.checkFrequency" set to 0:
In the "source control" panel the list of remote updates is no longer visible even if "svn.refresh.remoteChanges" is set to true.

**Comment by JohnstonCode** [comment]
`Set the interval in seconds to check changed files on remote repository and show in statusbar. 0 to disable`

**Comment by SimplySayHi** [comment]
Sure, but I'd expect to get the updated list if I click on the refresh button.
This doesn't happen now.

**Comment by JohnstonCode** [comment]
Yeah i get your point. This needs changing
