### ISSUE TITLE
Not available from this working copy

### ISSUE THREAD

**Issue by skyyouare** [JohnstonCode/svn-scm#735]
- VSCode Version: 1.40.0
- OS Version: os x 10.14.6
- Extension Version:2.02
- System Language:
- SVN Version: 1.10.3

## Steps to Reproduce ##

1. open subversion->repositories
2. click file open diff

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```
## Screenshots ##
<img width="1236" alt="屏幕快照 2019-11-13 上午10 29 21" src="https://user-images.githubusercontent.com/8912113/68727839-7f13eb80-0600-11ea-83a7-9f0b698d9336.png">

**Comment by skyyouare** [comment]
Not available from this working copy: file:///Users/doujinya/dashbord/st_pms_dashboard/common/tools/Lib.php

svn info

Working Copy Root Path: /Users/doujinya/dashbord/st_pms_dashboard
URL: svn://doujinya@192.168.0.129/svn/st_it_project/st_pms_dashboard/branchs/v4_20190904_forbug
Relative URL: ^/st_it_project/st_pms_dashboard/branchs/v4_20190904_forbug
Repository Root: svn://doujinya@192.168.0.129/svn
Repository UUID: 5e209b29-4666-47e1-8dfc-d676ec2cbe28
Revision: 377387
Node Kind: directory
Schedule: normal
Last Changed Author: doujinya
Last Changed Rev: 377385
Last Changed Date: 2019-11-11 19:22:05 +0800 (一, 11 11 2019)

**Comment by JohnstonCode** [comment]
If you rever to using verison `2.0.0` does the issue still occur?

**Comment by skyyouare** [comment]
2.0.0 is ok

**Comment by skyyouare** [comment]
> If you revert to using verison `2.0.0` does the issue still occur?

2.0.0 is ok

**Comment by JohnstonCode** [comment]
Can you give `2.1.1` a try please

**Comment by JohnstonCode** [comment]
Able to replicate

**Comment by JohnstonCode** [comment]
Note to self. Paths seem to be relative to their brnaches. Example make changes in trunk. switch branch, trunk changes show `../../trunk/index.js`

**Comment by skyyouare** [comment]
> Can you give `2.1.1` a try please

<img width="1255" alt="屏幕快照 2019-11-15 上午10 18 13" src="https://user-images.githubusercontent.com/8912113/68911861-4fe0b400-0791-11ea-87e8-75ab27508c0a.png">

**Comment by skyyouare** [comment]
> > Can you give `2.1.1` a try please
> 
> <img alt="屏幕快照 2019-11-15 上午10 18 13" width="1255" src="https://user-images.githubusercontent.com/8912113/68911861-4fe0b400-0791-11ea-87e8-75ab27508c0a.png">

Using svn "1.10.3" from "/usr/bin/svn"
[v1_20190903_for_issue6307]$ svn info --xml
[v1_20190903_for_issue6307]$ svn stat --xml --no-ignore --ignore-externals --show-updates
[v1_20190903_for_issue6307]$ svn log -r1:HEAD --stop-on-copy --xml --with-all-revprops --verbose
[v1_20190903_for_issue6307]$ svn mergeinfo --show-revs=merged svn://doujinya@103.37.141.57/svn/st_it_project/st_o2c/trunk/v1 svn://doujinya@103.37.141.57/svn/st_it_project/st_o2c/branchs/v1_20190903_for_issue6307
[v1_20190903_for_issue6307]$ svn info --xml svn://doujinya@103.37.141.57/svn/st_it_project/st_o2c/branchs/v1_20190903_for_issue6307
[v1_20190903_for_issue6307]$ svn diff svn://doujinya@103.37.141.57/svn/st_it_project/st_o2c/trunk/v1@370147 svn://doujinya@103.37.141.57/svn/st_it_project/st_o2c/branchs/v1_20190903_for_issue6307 --ignore-properties --xml --summarize
[v1_20190903_for_issue6307]$ svn log -r HEAD:1 --limit=50 --xml -v svn://doujinya@103.37.141.57/svn/st_it_project/st_o2c/branchs/v1_20190903_for_issue6307@


Path: .
Working Copy Root Path: /Users/doujinya/o2c/st_o2c
URL: svn://doujinya@103.37.141.57/svn/st_it_project/st_o2c/branchs/v1_20190903_for_issue6307
Relative URL: ^/st_it_project/st_o2c/branchs/v1_20190903_for_issue6307
Repository Root: svn://doujinya@103.37.141.57/svn
Repository UUID: 5e209b29-4666-47e1-8dfc-d676ec2cbe28
Revision: 377715
Node Kind: directory
Schedule: normal
Last Changed Author: doujinya
Last Changed Rev: 377678
Last Changed Date: 2019-11-14 19:40:03 +0800 (四, 14 11 2019)

**Comment by cxy930123** [comment]
I got this too.
![图片](https://user-images.githubusercontent.com/7006257/70033432-69378c00-15ea-11ea-8954-9b98dd9cb405.png)
```bash
$ svn info
path: .
Working copy root directory: /home/chen/Documents/CODE
URL: https://61.143.61.20:8456/svn/CRM_APP/trunk/CODE/H5
Relative URL: ^/trunk/CODE/H5
Svn root: https://61.143.61.20:8456/svn/CRM_APP
#...
```

My vscode working directory: /home/chen/Documents/CODE/H5
File path: /home/chen/Documents/CODE/H5/src/components/TitleBar.vue

I found that the real file path is a little different from the one in the error message.

**Comment by wuxfheb** [comment]
if open subfolder of svn(without .svn dir) it occur , find .svn won't

**Comment by ShiLiGo** [comment]
Have any plan to solve this bug?
