### ISSUE TITLE
Updating via command line breaks the refresh sidebar

### ISSUE THREAD

**Issue by AngeloMateus** [JohnstonCode/svn-scm#736]
- VSCode Version: 1.37.1
- OS Version: 18362.418
- Extension Version: Latest
- System Language: 
- SVN Version: 1.12.2

## Issue ##
Updating via commandline breaks the refresh via VSCode, repo is updated but changes aren't reflected in the sidebar.

## Steps to Reproduce ##

1.Make changes in repo on remote machine
2.Update via command line

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by JohnstonCode** [comment]
Which sidebar are you refering to?

**Comment by AngeloMateus** [comment]
The VSCode source control tab

**Comment by JohnstonCode** [comment]
Thanks for raising this.

**Comment by JohnstonCode** [comment]
What do you mean by breaks it? If you click the refresh icon on remote changes the state is updated.

**Comment by marsfan** [comment]
@JohnstonCode I know this issue is over 2 years old at this point, but I have found that running `svn update` in the command line and then clocking on the *Refresh* icon in the SVN Sidebar does not updated the *Remote Changes* list in the sidebar.
