### ISSUE TITLE
Insiders build broken

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#737]
`TypeError: Cannot set property 'MINIMUM_THRESHOLD' of undefined`

jschardet has been updated `"jschardet": "2.1.1"` from `"jschardet": "^1.6.0"`

**Comment by JohnstonCode** [comment]
@edgardmessias

**Comment by edgardmessias** [comment]
Change:

```ts
// from
jschardet.Constants.MINIMUM_THRESHOLD = 0.2;

// to
if (jschardet.Constants) {
    jschardet.Constants.MINIMUM_THRESHOLD = 0.2;
}
```

**Comment by JohnstonCode** [comment]
This will affect detection won’t it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edgardmessias** [comment]
Yes, but only for insiders build, maybe the new jschardet can improved the detection and solve some problems.
Tha hack is for old versions

**Comment by JohnstonCode** [comment]
```
This breaks backwards compatibility (hence the major version bump) for the Constants but new methods were added to serve the same purpose: enableDebug and .detect(, {minimumThreshold: 0.2}).
```

**Comment by edgardmessias** [comment]
Look: https://github.com/aadsm/jschardet/blob/master/dist/jschardet.js#L7481
The default value is `0.20`

**Comment by JohnstonCode** [comment]
That’s perfect then. I will create a PR tomorrow
