### ISSUE TITLE
TASK: Create tests

### ISSUE THREAD

**Issue by edgardmessias** [JohnstonCode/svn-scm#74]
Create unit tests, this will help us avoid problems.

See the link: https://code.visualstudio.com/docs/extensions/testing-extensions

- [x] Create init tests
- [x] Add to Travis-CI
- [x] Add to AppVeyor-CI
- [x] Add style check
- [x] Add Code Analysis
- [x] Write unit tests

**Comment by JohnstonCode** [comment]
Yes, testing would help a lot.

**Comment by JohnstonCode** [comment]
Tests will also make CI possible

**Comment by JohnstonCode** [comment]
@edgardmessias  Travis CI is setup and the first build passed.

**Comment by edgardmessias** [comment]
Nice!

**Comment by JohnstonCode** [comment]
Iv added a prettier style guide check to Travis CI

**Comment by edgardmessias** [comment]
Maybe, we can use a https://coveralls.io/, https://codeclimate.com/, https://scrutinizer-ci.com/, ....

**Comment by JohnstonCode** [comment]
[codacy](https://www.codacy.com/)?

**Comment by edgardmessias** [comment]
Also good

**Comment by edgardmessias** [comment]
https://codecov.io/ - Example: https://github.com/codecov/example-typescript-vscode-extension

**Comment by JohnstonCode** [comment]
Added the codecov stuff not sure how it works

**Comment by edgardmessias** [comment]
Let's use codacy for now

Can you reverse those changes?

**Comment by JohnstonCode** [comment]
reverted

**Comment by JohnstonCode** [comment]
Added a tslint file for code style. This may need tweaking.

**Comment by edgardmessias** [comment]
See the project: https://github.com/vscode-icons/vscode-icons, We can use it as a base

**Comment by JohnstonCode** [comment]
copied that. You can tweak as needed. I'm not fussed by style guides as long as we all stick to one.

**Comment by edgardmessias** [comment]
We can use the codecov and bithound from vscode-icons

**Comment by JohnstonCode** [comment]
Okay ill have a look tomorrow

**Comment by edgardmessias** [comment]
CodeCov Working

**Comment by JohnstonCode** [comment]
Thanks for that. You adding appvoyer or should i?

**Comment by edgardmessias** [comment]
You can add AppVoyer

**Comment by JohnstonCode** [comment]
AppVoyer added and working

**Comment by edgardmessias** [comment]
@JohnstonCode, We now need to break the code into smaller parts so we can test

**Comment by JohnstonCode** [comment]
@edgardmessias what would you suggest we break apart?

I'm still not 100% on how we can test the extension fully. We might need to make some scripts that create a test Svn repository. I know the Mg SCM uses Powershell scripts to test.

**Comment by JohnstonCode** [comment]
Yes nice and simple.

We will need to script the creation of local repositories so they can run on Travis and AppVoyer.

I can write a PowerShell and bash script for that.

**Comment by edgardmessias** [comment]
First: create an XML parser
Second: Status Parser
Third: Command builder for cp.spawn

**Comment by JohnstonCode** [comment]
The command builder is just [this function](https://github.com/JohnstonCode/svn-scm/blob/master/src/svn.ts#L114)

Status parser is [this function](https://github.com/JohnstonCode/svn-scm/blob/master/src/svnRepository.ts#L11)

XML stuff does need grouping

**Comment by edgardmessias** [comment]
Add in Status parser: https://github.com/JohnstonCode/svn-scm/blob/6d9f1f337f1023d57671127f84eedad64d6d06b1/src/repository.ts#L137

**Comment by JohnstonCode** [comment]
Think that should be left separate but also separating. StatusAssigner maybe?

**Comment by edgardmessias** [comment]
Good

**Comment by JohnstonCode** [comment]
Also, think anything we are working on making an issue so no work is duplicated

**Comment by edgardmessias** [comment]
To add new tests, open new issue.
