### ISSUE TITLE
In project tree view files are not colored into green/yellow after removing ProposedApi 

### ISSUE THREAD

**Issue by Zhiganoff** [JohnstonCode/svn-scm#740]
Before removing ProposedApi after each update I changed `product.json` "extensionAllowedProposedApi" for coloring files in tree view into green for new and yellow for . edited files
Now explanation what should be added to "extensionAllowedProposedApi" was removed

I've set ` "svn.enableProposedApi": "product"` in settings but that didn't help

**Comment by JohnstonCode** [comment]
The functionality has been complelty removed from the extension #675
