### ISSUE TITLE
SVN status colors and icons in File Explorer

### ISSUE THREAD

**Issue by andreadam82** [JohnstonCode/svn-scm#741]
- VSCode Version: 1.40.1
- OS Version: Windows 10 (1909)
- Extension Version: 2.1.1
- System Language: Italian
- SVN Version: 1.12.2

## Issue ##

The SVN status color and icons (eg. 'A', 'M', 'U') are stop to working in the File Explorer. 

I checked  product.json and i have "johnstoncode.svn-scm" in the extensionAllowedProposedApi list.

Anyone have this issue too?

**Comment by JohnstonCode** [comment]
The proposed api has been removed #675
