### ISSUE TITLE
Decoration provider API

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#743]
Waiting on https://github.com/microsoft/vscode/issues/54938

**Comment by spmeesseman** [comment]
in the meantime does this mean decorations in the explorer don't work?  Because I update my VSCode to the latest 1.41.1, and decorations no longer work.  The extension name is in the proposed api list of package.json, not sure what could be wrong, I made a pretty big jump 1.37 to 1.41

**Comment by JohnstonCode** [comment]
All proposed API's were removed. Awaiting Vscode to add them to stable.

**Comment by spmeesseman** [comment]
aaaahhhh.  thanks for the update

**Comment by jacobweber** [comment]
It's ready!
