### ISSUE TITLE
Extension suddenly stopped working

### ISSUE THREAD

**Issue by howling0** [JohnstonCode/svn-scm#744]
- VSCode Version:1.40.1
- OS Version: Windows 8
- Extension Version:2.1.2
- System Language:Chinese
- SVN Version: tortoiseSVN 1.9.0

## Issue ##
The SVN panel suddenly stopped working, and kept showing command 'svn:xxxxxxxxx' not found when I tried to use related features.
Have tried to reinstall svn, reboot, and rollback to previous versions of the extension, still not working.

## SVN Output ##
command 'svn.repolog.refresh' not found
command 'svn.treeview.refreshProvider' not found

**Comment by JohnstonCode** [comment]
try using `1.54.11`

**Comment by howling0** [comment]
I've tried it, and it's still showing the same message

**Comment by JohnstonCode** [comment]
Paste here content of "View >> Output >> OUTPUT >> SVN"

**Comment by howling0** [comment]
There's nothing in the output, only the popup messages saying command 'svn.treeview.refreshProvider' not found.

**Comment by JohnstonCode** [comment]
Can you run svn commands from the cli without issue?

**Comment by JohnstonCode** [comment]
Also do any recent commits have Chinese characters in the commit message or in the path of commited files?

**Comment by howling0** [comment]
the client can work properly. I didn't commit anything in the afternoon, but pulled some updates from SVN, and there are some Chinese characters in the path of the files.

**Comment by JohnstonCode** [comment]
Can you have a look at https://github.com/JohnstonCode/svn-scm/issues/248

**Comment by howling0** [comment]
Added 'C:\\program files\\tortoisesvn\\bin\\TortoiseProc.exe' to the svn.path and solved the problem, still don't know why this problem suddenly popped up, thanks for helping.

**Comment by JohnstonCode** [comment]
No problem
