### ISSUE TITLE
'Revert Selected Ranges' allways report an error: 'Cannot read property 'filter' of undefined'

### ISSUE THREAD

**Issue by wush007** [JohnstonCode/svn-scm#746]
- VSCode Version:   1.39.2   (on all other VSCode versions, is the same problem)
- OS Version: Windows 7 ultimate Service Pack 1
- Extension Version: 1.54.11  (all other Extension versions, is the same problem)
- System Language: Chinese
- SVN Version: 1.95.1210

## Issue ##
**Revert Selected Ranges' allways report an error: 'Cannot read property 'filter' of undefined'**
## Steps to Reproduce ##
 , always report the same error.
1. Select the chaned ranges,
2. call the command "revert selected ranges"

## SVN Output ##
```
Cannot read property 'filter' of undefined
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/8723146/69426864-362f0600-0d69-11ea-822f-d147578726de.png)

![image](https://user-images.githubusercontent.com/8723146/69235448-668d6d80-0bcc-11ea-8f79-610b21aa884a.png)

![image](https://user-images.githubusercontent.com/8723146/69235360-30e88480-0bcc-11ea-842c-cfef572b55bf.png)

**Comment by JohnstonCode** [comment]
Can you please fill out the bug issue template

**Comment by JohnstonCode** [comment]
That command no longer exsists
