### ISSUE TITLE
Bad encoding of "Show commit messages" output

### ISSUE THREAD

**Issue by michelegalante** [JohnstonCode/svn-scm#752]
Versione: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Data: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Nome: SVN
ID: johnstoncode.svn-scm
Descrizione: Integrated Subversion source control
Versione: 2.1.3
Editore: Chris Johnston
Collegamento di Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=johnstoncode.svn-scm

The output of the "Show commit messages" command does not render non-ASCII characters correctly. For example, this is the output I get on the command line with "svn log":

------------------------------------------------------------------------
r46962 | galante | 2019-12-02 10:19:44 +0100(Lun, 02 Dic 2019) | 1 line

Eliminato il file "configurations.py" perché è definito nei progetti delle singole applicazioni.
------------------------------------------------------------------------

This is how it appears in the "svn.log" window opened by "Show commit messages":

------------------------------------------------------------------------
r46962 | galante | 2019-12-02 10:19:44 +0100 (Mon, 02 Dec 2019) | 1 line

Eliminato il file "configurations.py" perchÃ© Ã¨ definito nei progetti delle singole applicazioni.
------------------------------------------------------------------------

I have tried changing the "svn.default.encoding" and "files.encoding" settings, but the output does no change (normally I set both settings to "utf8").

**Comment by JohnstonCode** [comment]
encoding is detected as `windows1252` https://github.com/JohnstonCode/svn-scm/blob/master/src/svn.ts#L178

I think that configuration should override detection. Thoughts @edgardmessias ?
