### ISSUE TITLE
conflict with luaide

### ISSUE THREAD

**Issue by le888** [JohnstonCode/svn-scm#753]
- VSCode Version:1.40.2
- OS Version:windows10
- Extension Version:2.1.3
- System Language:Chinese
- SVN Version:

## Issue ##
conflict with luaide，There will be no conflicts when using version （svn）1.54

TypeError: Cannot read property 'fire' of undefined

	at FSWatcher.repoWatch (c:\Users\liule\.vscode\extensions\johnstoncode.svn-scm-2.1.3\out\watchers\repositoryFilesWatcher.js:63:32)

	at Timeout._onTimeout (c:\Users\liule\.vscode\extensions\johnstoncode.svn-scm-2.1.3\out\decorators.js:78:50)

	at listOnTimeout (internal/timers.js:531:17)

	at processTimers (internal/timers.js:475:7)

![image](https://user-images.githubusercontent.com/11625590/70139649-e2f47600-16cd-11ea-9fb0-3f9d106f9e64.png)

## Steps to Reproduce ##

1.
2.

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by luluwuxin** [comment]
+1

**Comment by JohnstonCode** [comment]
How can i reproduce this issue?

**Comment by luluwuxin** [comment]
> How can i reproduce this issue?
commit or update

**Comment by le888** [comment]
View source control 
![image](https://user-images.githubusercontent.com/11625590/72034800-ff895c80-32d0-11ea-80c8-73a3bf8fe7d5.png)

**Comment by JohnstonCode** [comment]
![image](https://user-images.githubusercontent.com/10222719/72052306-d65ed100-32bc-11ea-892e-d1b02d962502.png)
![image](https://user-images.githubusercontent.com/10222719/72052331-e1b1fc80-32bc-11ea-9471-5ea87a2cfdf9.png)
cant replicate

**Comment by le888** [comment]
![test](https://user-images.githubusercontent.com/11625590/72053544-39268b80-3302-11ea-8879-983e92144359.gif)

**Comment by JohnstonCode** [comment]
Still unable to reproduce

**Comment by le888** [comment]
让我找一下重现方法在来报告，多谢
Let me find a way to reproduce it and report it. Thank you
