### ISSUE TITLE
File history display is stale (does not clear) when editor is deleted or selection is changed

### ISSUE THREAD

**Issue by marvingreenberg** [JohnstonCode/svn-scm#756]
- VSCode Version: 1.40.2
- OS Version: OSX
- Extension Version: 2.1.3
- System Language: English
- SVN Version: 1.9.7

## Issue ##
When A file is displayed in an editor and the editor is selected its history is shown.   If the editor is closed and no file editor is displayed, or the selected editor is a file or buffer without svn properties, the File History of the original file is still displayed.  
## Steps to Reproduce ##

1. Close all editors.
2. Create a file in a subversion controlled directory, e.g. echo "hello" > foo
3. Open editors for a couple subversion controlled files, and for 'foo'.
4. Switch to (very cool) Subversion extension sidebar.
5. Select one subversion controlled edit:
    File history is correctly displayed
5. Select another subversion controlled edit:
    File history is correctly displayed
6. Select 'foo' editor pane
     * Error * stale File History is displayed
7. Close all editors
      * Error * stale File History is displayed

RELATED, but possibly a feature request
Double click on a particular file either in the "BRANCH CHANGES" section or the REPOSITORIES section for a particular file.  Now a "Delta" editor is displayed, e.g.,
```package.json (8338:8888)```

Again the file history is stale, not displaying the file history for ```package.json```  At least this should clear the File History.  But it would be even nicer if it displayed the file history that for the file that the diff is being displayed for.

## Screenshots ##

![Non SVN selected](https://user-images.githubusercontent.com/216707/70352008-2e2a9800-1838-11ea-9400-afbc21760a92.png)

![Diff Editor selected](https://user-images.githubusercontent.com/216707/70352039-3be01d80-1838-11ea-9052-0540c9a6c942.png)

**Comment by Yanpas** [comment]
The idea behind this behaviour was: when you view older revisions of some file under version control, which are actually files inside `/tmp`, file history view isn't get reset.
