### ISSUE TITLE
svn:externals fixed revision is not handled

### ISSUE THREAD

**Issue by cptpatrick** [JohnstonCode/svn-scm#763]
We have projects that include a library from another repository via svn:external. Usually this library is used from trunk and nailed down at a certain (tested) revision. Unfortunately svn-scm seems to ignore or not handle that revision marker and always shows me the number of incoming modifications for this library to update to the HEAD revision...

**Comment by JohnstonCode** [comment]
that is because the command that is run behind the scenes is just `svn stat --show-updates`

**Comment by cptpatrick** [comment]
What does "need feedback" mean? Is there anything I can do / check / test?

**Comment by JohnstonCode** [comment]
I was just relaying what the command was and seeing if you had any insight to alternatives. But i have been looking into this more to see if there is a better way i can model externals. `svn propget -R svn:externals` does this show the revision marker?

**Comment by JohnstonCode** [comment]
Also if you are fixing to revisions cant you just disable externals `svn.detectExternals`?

**Comment by cptpatrick** [comment]
> I was just relaying what the command was and seeing if you had any insight to alternatives. But i have been looking into this more to see if there is a better way i can model externals. `svn propget -R svn:externals` does this show the revision marker?

Yes, on the terminal I see the revision marker, like "external - 'url_of_repository/branches/name_of_branch@MY_DESIRED_REVISION name_of_project'

> Also if you are fixing to revisions cant you just disable externals `svn.detectExternals`?what are you expecting it to show?

Well, I wasn't aware of that, so thanks for pointing out! This definitely helps to not update the external repository all the time by mistake. We update the fixed revision from time to time, so doing an 'svn up' via terminal would be necessary then as a workaround.

**Comment by JohnstonCode** [comment]
aaah i see. Also `svn.update.ignoreExternals` should be true
