### ISSUE TITLE
Cannot run on latest code-server 2.1692-vsc1.39.2

### ISSUE THREAD

**Issue by ophbalance** [JohnstonCode/svn-scm#770]
When trying to install the extension from the VSCode extension lookup I'm getting the following:

![2020-01-05_11-20-17](https://user-images.githubusercontent.com/7144366/71782929-bf169f80-2fad-11ea-84b6-3d01465a9761.jpg)

**Comment by JohnstonCode** [comment]
The latest version on the extension only support the latest version of vscode
