### ISSUE TITLE
date-fns increased vsix size by 2MB

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#773]

**Comment by JohnstonCode** [comment]
vsix is 1.1MB using moment js

**Comment by edgardmessias** [comment]
Try with day.js

**Comment by JohnstonCode** [comment]
day,js does not have the `formatDistanceToNow` functionality

**Comment by Yanpas** [comment]
RelativeTimeFormat (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RelativeTimeFormat) for some reason is unavailable, despite vscode uses node 12.4
Seems it will be soon available in typescript https://github.com/microsoft/TypeScript/pull/36084

Tried rewrite import statement (according to https://github.com/date-fns/date-fns/issues/771), but that didn't help:
```diff
diff --git a/src/historyView/common.ts b/src/historyView/common.ts
index 3c862023..3e07ad15 100644
--- a/src/historyView/common.ts
+++ b/src/historyView/common.ts
@@ -1,5 +1,5 @@
 import { createHash } from "crypto";
-import { formatDistanceToNow } from "date-fns";
+import formatDistanceToNow from "date-fns/formatDistanceToNow";
 import * as path from "path";
 import {
```

**Comment by JohnstonCode** [comment]
Yeah i tried different variations of imports and it did not seem to make a difference.
