### ISSUE TITLE
Code-server 2.1698-vsc1.41.1 and SVN-SCM 2.0.2 command 'svn.repolog.addrepolike' not found

### ISSUE THREAD

**Issue by ophbalance** [JohnstonCode/svn-scm#777]
- VSCode Version: 1.41.1
- OS Version: Ubuntu 16
- Extension Version: 2.0.2
- System Language: English
- SVN Version: 1.9

## Issue ##

Attempting to run latest code-server with latest version of extension results in all SVN actions coming back as not found.

## Steps to Reproduce ##

1.  Run latest code-server binary on Ubuntu 
2.  Install SVN extension
3.  Attempt SVN commands

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
Not available.  There is no option to select SVN anywhere in the output section.
```

## Screenshots ##

![image](https://user-images.githubusercontent.com/7144366/72683286-01f36f80-3aa4-11ea-87a2-af8b0bedc57e.png)

**Comment by hvalot** [comment]
Hi, still having the issue with 2.7.1 and VSC 1.42.1
i removed VSC and SVN (tortoiseSVN) and reinstalled both, the issue is still there

**Comment by JohnstonCode** [comment]
The issue is that the extensions marketplace is not updated on code server. You will have to manually install it via the vsix. use the 2.7.0 vsix as i have confirmed that this is working.
