### ISSUE TITLE
asyncronous log search

### ISSUE THREAD

**Issue by Yanpas** [JohnstonCode/svn-scm#783]
- VSCode Version: 
- OS Version: all
- Extension Version:2.6.0
- System Language:
- SVN Version:

## Issue ##
From https://github.com/JohnstonCode/svn-scm/pull/782 

In my case (repo with about 250k revisions) searching is too long. There is no output until server scans all revisions. Line by line reading and outputing would be much useful. And maybe stop command or something.

**Comment by JohnstonCode** [comment]
Not possible to do using virtual files

**Comment by JohnstonCode** [comment]
Also dont currently have a way to kill commands

**Comment by JohnstonCode** [comment]
Also repo with 1873207 revisions takes like 1 minute for me.

**Comment by Yanpas** [comment]
Technically it's possible with redirecting to file in temp directory.

Not sure whether it's that useful, as for me searching in terminal is more convenient, and you always can redirect it to vscode (`| code -`).

**Comment by JohnstonCode** [comment]
Yeah using a tmp file would work. Does vs code continously update files once they have been rendered? i.e. the command opens the file. vs code renders the empty file. Then does it check if the file has changed and add the new text or does it wiat for user interaction like clikicng on the file or swtiching tabs?

**Comment by JohnstonCode** [comment]
I stand corrected it will render it as it streams

**Comment by Yanpas** [comment]
Vscode updates file's content even if the user doesn't do anything. Tested with:
` ( for i in {1..10}; do echo -n "$i "; date; sleep 2; done ) | code -`

**Comment by JohnstonCode** [comment]
`proc.kill('SIGINT');` will kill the child process.

**Comment by JohnstonCode** [comment]
ignore
```
    fs.truncateSync(`${repository.workspaceRoot}/svn.log`);

    await commands.executeCommand<void>("vscode.open", Uri.file(`${repository.workspaceRoot}/svn.log`));

    const proc = cp.spawn('svn', ['log', '--search', input], {cwd: repository.workspaceRoot});

    window.withProgress({cancellable: true, location: ProgressLocation.Notification, title: 'Searching Log'}, (_progress, token) => {
      token.onCancellationRequested(() => {
        proc.kill('SIGINT');
      });

      proc.stdout.on('data', data => {
        fs.appendFile(`${repository.workspaceRoot}/svn.log`, data.toString(), err => {
          if (err) {
            console.error(err);
            return;
          }

          console.log('written');
        });
      });
    });
```
