### ISSUE TITLE
Tortoise SVN diff/merge tool in VSCode

### ISSUE THREAD

**Issue by TheThirdRace** [JohnstonCode/svn-scm#79]
- VSCode Version: 1.18.1
- OS Version: Window 10 64bit (fall creator update)
- Extension Version: 1.4.5
- System Language: English

Hi,

I can't make the SVN plugin to use the Tortoise SVN diff/merge tools instead of the default ones from the SVN plugin.

I have both **_Visual Studio 2017_** and **_VSCode_** installed, so I reference both to make sure there's no confusion.

I have the VisualSVN extension installed for **_Visual Studio 2017_** and configured to use Tortoise SVN diff/merge tools. This works flawlessly.

When configuring **_VSCode_**, I can't find the similar setting anywhere.

I read the Readme and checked in **_VSCode_** that $env:Path (in the powershell output) has Tortoise SVN path (which it does). I also installed the Commande Line Tools correctly.

Yet, no matter what I do in **_VSCode_**, I get the SVN diff/merge tools, not the Tortoise SVN ones.

Could help me a bit please, I'm totally new to **_VSCode_**. What am I missing?

**Comment by s-martin** [comment]
Using custom diff tools is currently not supported.

**Comment by edgardmessias** [comment]
You can try this: https://marketplace.visualstudio.com/items?itemName=fantasytyx.tortoise-svn

**Comment by TheThirdRace** [comment]
I'm a bit confused... the 2nd paragraph in the Readme says this:

> Windows
>
>If you use TortoiseSVN, make sure the option Command Line Tools is checked during installation and C:\Program Files\TortoiseSVN\bin is available in PATH.

**Comment by s-martin** [comment]
TortoiseSVN *Command Line Tools* (not the GUI) provide the SVN executable, which is used by the extension.
You could use any other svn executable, but TortoiseSVN is the most popular under Windows.

At the moment there's no support for custom diff tools.

**Comment by TheThirdRace** [comment]
A million thanks for the explanation!
