### ISSUE TITLE
SVN extension asked for username repeatedly

### ISSUE THREAD

**Issue by Shmoluc** [JohnstonCode/svn-scm#792]
When using visual studio code, I have a window opening at the top of the studio code that ask to enter a svn unsername (see the screenshot below), whenever I put my username then my password, the window still arrive and so the focus of my edition is made in this window so I can't write my code, that's make me really nervous :) 

For info, I am using SVN version 1.13.1.28686 and studio code version 1.41.1

If you can say to me how to solve it, I will be the happiest coder on earth.

Thanks

![window svn extension](https://user-images.githubusercontent.com/60425822/73343909-b00bd000-4281-11ea-8e92-870717342d32.png)

**Comment by JohnstonCode** [comment]
Can you copy the contets of the svn output please

**Comment by Shmoluc** [comment]
Thanks for your help @JohnstonCode !

Thanks to you I found in the output console that it was a problem of access to a specific svn URL.

Maybe an improvement of this plugin could be to write in which svn URL the username is used for and write the error of access also in the popup window. In my case I work with multi svn URL so I was thinking of the principal url and not one of the others.

You made a programmer happy @JohnstonCode :)
Have a good day.
