### ISSUE TITLE
Change History

### ISSUE THREAD

**Issue by spmeesseman** [JohnstonCode/svn-scm#794]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to view the file's change history, i.e. commit date, author, and comment.  Both from Explorer (via context menu) and from the SCM view, in the list of changed files via context menu and/or toolbar icon button.

**Describe alternatives you've considered**
Using Tortoise for this externally

**Additional context**
I may be able to offer my time to work on this if interested, but then again, maybe not.  I would lovvvvve this feature as I manage several under-25's and check commits often, so wanted to at least stick it in there in case someone got bored one day

**Comment by JohnstonCode** [comment]
You can currently do this in the Svn view
![image](https://user-images.githubusercontent.com/10222719/73764632-40a74c00-476b-11ea-8982-2b9297072074.png)

**Comment by spmeesseman** [comment]
jeez i never even noticed that, and i use the file history below that all the time for my selected file in the editor. it would still be super handy to be able to right click a file in Explorer and get this info, so thanks for not closing! lol.  i can let you know soon if I think i might have some time to contribute with this at some point

**Comment by spmeesseman** [comment]
hmmm, for the particular functionality that exists, when i select a file in 'Repositories', it doesnt load in the 'File History'.   The file that I currently have open in my editor reamin as the one open in 'File History'.  Should it be loaded into that little view when selecting a file in the Repositories file tree?

**Comment by JohnstonCode** [comment]
Currently it only supports showing the file history of the active editor window.

**Comment by JohnstonCode** [comment]
This might change when the [timeline feature](https://code.visualstudio.com/updates/v1_42#_timeline-providers) is released.

**Comment by spmeesseman** [comment]
Thanks, and thanks for all the work on this extension, much appreciated.

i actually whipped up something real quick in that dumb little 'svn-scm-ext' extension i did when I first started using Code, you can check it out and use it if you'd like.

![svnhistory](https://user-images.githubusercontent.com/48744816/74907278-0b147c80-5381-11ea-8666-da3aa9379925.png)

**Comment by spmeesseman** [comment]
hey can i get off subject and ask real quick too... why do you use 'original-fs' over 'fs' ?

**Comment by JohnstonCode** [comment]
It is because electron providers [origional-fs](https://www.electronjs.org/docs/tutorial/application-packaging#treating-an-asar-archive-as-a-normal-file) without `asar` support. But in VS Code remote it only runs in node so we use the `origional-fs` package with reverts to using the normal node `fs`

**Comment by edgardmessias** [comment]
About `original-fs`: https://www.electronjs.org/docs/tutorial/application-packaging#treating-an-asar-archive-as-a-normal-file.
The `original-fs` npm package it is a single command:
```ts
export default require('fs');
```

**Comment by spmeesseman** [comment]
aaaaahhhhhh, thanks!  i always wondered
