### ISSUE TITLE
Setting svn.multipleFolders.ignore does not change behaviour

### ISSUE THREAD

**Issue by gkoulin** [JohnstonCode/svn-scm#795]
- VSCode Version: 1.41.1
- OS Version: Mac 10.14.6
- Extension Version: 2.6.1
- System Language: English
- SVN Version: 1.10.4

## Issue ##
Setting svn.multipleFolders.ignore does not change behaviour

## Steps to Reproduce ##

1. add 
"svn.multipleFolders.ignore": [
    "**/test",
  ]
to settings.json
2. test folder is still visible in the source control tab

## SVN Output ##
```
Paste here content of "View >> Output >> OUTPUT >> SVN"
```

**Comment by JohnstonCode** [comment]
`svn.multipleFolders.ignore` is to not try and open any svn repositories in the given folders
