### ISSUE TITLE
Feature Request: Create Branch and switching to new Branch

### ISSUE THREAD

**Issue by babujan** [JohnstonCode/svn-scm#8]
Thank you very much for this svn extension, and the integration to scm is great been using it for about a week. 

Are you planning to add feature to create a branch and switching to a branch?

**Comment by JohnstonCode** [comment]
Hi @babujan 

Yes i am planning on implementing all of the commands into the extension. This is currently delayed as i will need to write my own command line interface for SVN as the one i currently use is not flexible enough.

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1
