### ISSUE TITLE
Diff in UTF-8 nonenglish text

### ISSUE THREAD

**Issue by magic-k** [JohnstonCode/svn-scm#82]
- VSCode Version: 1.18.1
- OS Version: Ubuntu 16.4
- Extension Version: 1.4.5
- System Language:german

Steps to Reproduce:

1. Open an unchanged UTF-8 file with Umlauts
2. See the decoration for a diff
3. Open diff or diff to head

![image](https://user-images.githubusercontent.com/12908034/33761782-8a5d0016-dc0a-11e7-84ba-a3c078c24b16.png)

The file above is unchanged, local and remote file are both in UTF-8. See the diff regarding the Umlauts. 
This is also in the side by side diff. VSCode is set to UTF-8. svn diff schows no difference.

**Comment by JohnstonCode** [comment]
Can you send me that line of code please?

**Comment by magic-k** [comment]
[test.zip](https://github.com/JohnstonCode/svn-scm/files/1543177/test.zip)
Hope it works. charsets are a tricky thing.

**Comment by JohnstonCode** [comment]
Yeah they are a pain

**Comment by magic-k** [comment]
Just for completeness i did a change in the file (added öäü) and this is what svn cmdline says:
-         nachricht = nachricht +"FAIL,<Keine Datensätze> \r\n";
+         nachricht = nachricht +"FAIL,<Keine Datensätzeöäü> \r\n";

**Comment by JohnstonCode** [comment]
Bases on the sample you sent 1.4.6 fixes the issue.

Let me know if you have any further issues like this

**Comment by edgardmessias** [comment]
@JohnstonCode , you can test my branch: https://github.com/edgardmessias/svn-scm/tree/fix_diff_utf8 ?

**Comment by JohnstonCode** [comment]
Yeah sure give me 5 minutes.
