### ISSUE TITLE
Problems with multi-project workspace

### ISSUE THREAD

**Issue by yuval-gilboa** [JohnstonCode/svn-scm#83]
- VSCode Version: 1.18.1
- OS Version: Windows 7
- Extension Version: 1.4.5
- System Language: English

Steps to Reproduce:

1. Open a multi-project workspace
2. Make changes to the first project - changes are recognized correctly
3. Make changes to the second project - changes are ignored

Seems like the extension only recognizes the first project in a multi-project workspace.

**Comment by edgardmessias** [comment]
Structure of the folders?

**Comment by yuval-gilboa** [comment]
The structure is a pair of sibling projects under common root folder. Both projects are pure typescript projects with separate tsconfig.json, etc. The workspace file is under the .vscode folder of the first project:

```
root
  |---- project1
  |          |---- .vscode
  |          |        |---- myapp.code-workspace
  |          |---- out
  |          |---- src
  |          tsconfig.json
  |
  |---- project2
             |---- .vscode
             |---- out
             |---- src
             tsconfig.json

```

This is how the myapp.code-workspace looks like:

```
{
   "folders": [
      {
         "path": "../../project1"
      },
      {
         "path": "../../project2"
      }
   ]
}
```

**Comment by magic-k** [comment]
I have this issue with two sub directories of one svn repo. 

svn.xxx.de/root/Project/project1
                                      project2

I put project1 and project2 into a workspace (the path is deeper  and contains more subprojects so i didn't want to use Project directly)
Only one of the projects is shown in SVN-Explorer.

**Comment by edgardmessias** [comment]
@magic-k, can show example? You use ignored folder?

**Comment by magic-k** [comment]
I don't use svn ignore if that's what you mean.
It's a production system so examples are difficult, but i try:
This is the base
omp@Reperso:/mnt/devel/omp/project/Reperso$ svn info
Pfad: .
Wurzelpfad der Arbeitskopie: /mnt/devel/company/project/XXXX
URL: http://svn.company.de/svn/XXXX
Relative URL: ^/
Basis des Projektarchivs: http://svn.company.de/svn/XXXX
UUID des Projektarchivs: be9021b7-ebdc-4067-8375-8d21ea205b0b
Revision: 193
Knotentyp: Verzeichnis
Plan: normal
Letzter Autor: me
Letzte geänderte Rev: 193
Letztes Änderungsdatum: 2017-12-19 09:06:31 +0100 (Tue, 19. Dec 2017)

There are 4 directories:
project1 
project2 
unused1
unused2

project1 and project2 are dopped into my workspace.

omp@Reperso:/mnt/devel/company/project/XXXX/project1$ svn info
Pfad: .
Wurzelpfad der Arbeitskopie: /mnt/devel/omp/project/XXXX
URL: http://svn.company.de/svn/XXXX
Relative URL: ^/
Basis des Projektarchivs: http://svn.pb.omp.de/svn/XXXX
UUID des Projektarchivs: be9021b7-ebdc-4067-8375-8d21ea205b0b
Revision: 193
Knotentyp: Verzeichnis
Plan: normal
Letzter Autor: magick
Letzte geänderte Rev: 193
Letztes Änderungsdatum: 2017-12-19 09:06:31 +0100 (Tue, 19. Dec 2017)

Same for project2

Tell me if you need more info

**Comment by JohnstonCode** [comment]
@yuval-gilboa @magic-k 

I am having issues replicating your issue completely.

I have two separate SVN project open and when I make changes to one of them is doesn't update the SCM view. But if I click the refresh arrow it detects the changes.

Is this what you are seeing?

**Comment by magic-k** [comment]
I have one svn project open and i see changes in SCM-view. Then i add a second project, thus creating a workspace. I do changes in the second but i never see them in the SCM-pane no matter how often i refresh. When i remove the first project from the workspace, i immediately see the changes from the second project.

**Comment by JohnstonCode** [comment]
What version of the extension are you currently running on?

Also, do you get anything in the svn output channel?

**Comment by magic-k** [comment]
I'm running 1.5.0. I see normal output in the first project and none when i add the second. I guess the main problem seems to be that these are two subdirs from one svn repo.

svn repo is e.g. project1, folders in the workspace are project1/subproject1 and project1/subproject2. With two completely unrelated repos i see both in the SCM view.

**Comment by edgardmessias** [comment]
Which folders contains the ".svn" folder

**Comment by JohnstonCode** [comment]
@magic-k 

I Have been able to replicate this now.

@edgardmessias  neither. If you have an svn repo and 2 folders in the root. Opening them both separately breaks SCM view

**Comment by JohnstonCode** [comment]
@edgardmessias 

 [This line is causing the issue](https://github.com/JohnstonCode/svn-scm/blob/master/src/model.ts#L155)

The repository is already open so it never sets up the second folder.

**Comment by edgardmessias** [comment]
The problem is root of ".svn".

With SVN 1.6, works, because each folder has a ".svn" folder

**Comment by edgardmessias** [comment]
If checkout two folder, and, each folder has ".svn" folder, works perfect.

**Comment by JohnstonCode** [comment]
With two svn projects with their own .svn folders in the root it works.

But if you have an svn project and open two nested folders it doesn't work.

**Comment by JohnstonCode** [comment]
Currently, only one instance of a repository can be used. 

This is because before workspaces everything was just modeled on repositories. Everything could now be modeled on workspaces but what do we do with nested repositories within these workspaces?

How are they cleaned up with the removal of a workspace?

Is the work actually worth it for the sake of opening multiple folders in the same repository?

**Comment by edgardmessias** [comment]
I working for solution

**Comment by edgardmessias** [comment]
Done, make tests;
