### ISSUE TITLE
can't checkout new project from svn

### ISSUE THREAD

**Issue by cleohuggins** [JohnstonCode/svn-scm#839]
- VSCode Version: 1.42.1
- OS Version: Mac OS Catalina - 10.15.3
- Extension Version:
- System Language: 
- SVN Version: v2.10.3

## Issue ##
I did a clean install of Catalina on my iMac. Installed Subversion (v 1.13.0). Using Visual Studio Code (v 1.42.1) I installed SVN (v 2.10.3). My mac was empty - no svn checkouts.

When I started VSCode I saw the svn icon flash briefly in the activity bar, but then disappeared.
After a workaround (below) only directories with manually checked out repositories showed the SVN extension icon. With the svn icon available I was able to commit files. However, the icon still disappears when I opened a new directory that doesn't have any checked-out files. As it stands, I appear to be unable to check out a repository via this extension. 

## Steps to Reproduce ## 
1. Do a clean install of Catalina
2. Install Visual Studio Code
3. Install homebrew 
4. Install subversion
5. In VS Code, install SVN Chris Johnson extension. 
6. Restart VSCode the SVN icon will appear briefly then disappear.
---
6a. Open any directory that doesn't have a pre-existing repository and the icon doesn't stay.

## Workaround ##
Outside VSCode, I checked out a project from a repository using the svn command line. 
I then opened the directory that contained the checked-out project with VSCode and the SVN icon was solidly on in the Activity bar.

**Comment by JohnstonCode** [comment]
Thanks for reporting this. I will need some time to think about the best way to handle this.

**Comment by qwertycody** [comment]
+1 on this, I am having this same issue in VSCode installed on OEL/Red Hat based linux. Thought I was going crazy and not reading instructions after going through it 20 times but looks like someone is also having this same issue on MacOS based Unix.

**Comment by gatiba** [comment]
Similar problem here: if i open in VSCode a subfolder of a larger svn working copy, the icon appear briefly then disappear. 
It stays only if i open the root folder, while it was working with no problems some times/versions ago...

**Comment by HDBISG** [comment]
same issue
VSCode Version: 1.69.2
OS Version:  Monterey- 12.3
Extension Version:v2.15.5
