### ISSUE TITLE
commit message list

### ISSUE THREAD

**Issue by agluck3** [JohnstonCode/svn-scm#84]
I would love to see either a commit message list or have it save the most recent commit message. :D

**Comment by JohnstonCode** [comment]
@agluck3 

Would you be looking for something like the results of "svn log"?

**Comment by edgardmessias** [comment]
For readonly data, we can implement the [TextDocumentContentProvider](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nametextdocumentcontentprovideraspan-classcodeitem-id465textdocumentcontentproviderspan)

**Comment by JohnstonCode** [comment]
Yeah, i was thinking about using that and having a config option to limit the output as a big project could crash the editor.

**Comment by edgardmessias** [comment]
Create a config option.

The command example `svn log --limit 10`

**Comment by JohnstonCode** [comment]
yeah then pull the limit from a config value

**Comment by JohnstonCode** [comment]
set it to default of 100 or something
