### ISSUE TITLE
Custom gravitar doamin hash

### ISSUE THREAD

**Issue by JohnstonCode** [JohnstonCode/svn-scm#843]
@spmeesseman would like the option to add a domain to a username before it is md5 hashed.

https://github.com/JohnstonCode/svn-scm/issues/754#issuecomment-592043303

**Comment by JohnstonCode** [comment]
Would having a another config option of `svn.gravatar.custom_domain` and a new tag of `<AUTHOR_CUSTOM_DOMAIN_MD5>` work?

**Comment by edgardmessias** [comment]
I thought the same thing
