### ISSUE TITLE
No ask for username and password - just message can't update

### ISSUE THREAD

**Issue by jiramares** [JohnstonCode/svn-scm#849]
- VSCode Version: 1.42.1
- OS Version: openSUSE LEAP 15.1
- Extension Version: 2.10.4
- System Language: EN
- SVN Version: 1.10.6

## Issue ##

Until I login into subversion server from command line all actions in visual studio code returns error.

## Steps to Reproduce ##

1. Run VS Code
2. Try to update from server

## SVN Output ##
$ svn update --ignore-externals
$ svn: E170013: Unable to connect to a repository at URL 'https://ids/svn/repos/CARDS/CardsExchange-scripts'
$ svn: E215004: No more credentials or we tried too many times.
$ Authentication failed[CardsExchange-scripts]$ svn info --xml /home/jmares/workspaces/svt/CardsExchange-scripts
$ svn info --xml /home/jmares/workspaces/svt/CardsExchange-scripts
$ svn stat --xml --no-ignore --ignore-externals```

**Comment by edgardmessias** [comment]
Related with https://github.com/atom/node-keytar/issues/74

**Comment by jiramares** [comment]
Thanks a lot, it is working now...

**Comment by jiramares** [comment]
But after installing the new version ... when I log into svn (using visual studio code) I can't open or save any file and even can't close the vscode :(
How can I downgradu the extension to previous version?

**Comment by JohnstonCode** [comment]
Go to the extensions find svn. Click on the cog and select 'Install another version'

**Comment by jiramares** [comment]
So it looks like both version of the plugin behave the same way. After logging into subversion using vscode (instead of command line subversion - e.g. using svn info -r HEAD) the editor can't read or save any file :(

**Comment by JohnstonCode** [comment]
try an older version
