### ISSUE TITLE
Open diff view after clicking on modified file

### ISSUE THREAD

**Issue by luboslav** [JohnstonCode/svn-scm#86]
- VSCode Version: 1.18.1
- OS Version: Windows 10
- Extension Version: 1.4.5
- System Language:

If you click on file (with Modified flag) in changes list it should open diff view.

**Comment by JohnstonCode** [comment]
If you right-click on it you will get the option to diff against the head.

**Comment by luboslav** [comment]
I know about that option. I was referring to git default behavior.

**Comment by jamesmikesell** [comment]
Agreed, i prefer the default behavior that GIT does in VS Code, where if you're viewing the source control panel, clicking a file automatically opens up the diff viewer.

Obviously, GIT doesnt' show you the diff when you open a file from the "Explorer" panel, just the source control panel.

**Comment by JohnstonCode** [comment]
Think this more of a personal preference issue.

I will add it as a setting.

**Comment by edgardmessias** [comment]
I can work on it.

**Comment by jamesmikesell** [comment]
Looks awesome, thanks for the enhancement
