### ISSUE TITLE
Feature request: key command to revert current diff

### ISSUE THREAD

**Issue by RichardPflaum** [JohnstonCode/svn-scm#863]
Hi, I  would like to be able to revert the currently selected diff with a key command. 
I already described the feature here: 
https://github.com/microsoft/vscode/issues/91679#event-3135424773
I'll copy the relevant parts here.

In WinMerge, you can open two files and scroll through the diffs using alt down/up. You can then use alt left/right to copy code from one file to the other, which makes the workflow very fast.

Something similar would be nice for the diff editor in VSCode. I could not find any way of doing this. I found the actions workbench.action.compareEditor.nextChange and workbench.action.compareEditor.previousChange, which seem to be the only ones for the compareEditor so far. Git has the "Revert selected ranges" feature already.

Since the key commands for scrolling through diffs are alt+F5 and alt+shift+F5, maybe alt+F6 would be a good choice to revert the change. This would accelerate the pre-commit checks a lot. Thanks in advance!

**Comment by edgardmessias** [comment]
Related to https://github.com/microsoft/vscode/issues/84899

**Comment by FrankBlabu** [comment]
Additionally (unsure if this is closely related to this request or would be worth a separate one):

When switching from VSCode 1.38 to VSCode 1.49, the "Revert selected ranges" menu entry in the "More Actions..." triple dot menu in the diff view seems to be lost. So in VSCode 1.49 the only way to revert changes is via copy/paste from left to right.

![dotmenu](https://user-images.githubusercontent.com/27698648/95427223-7f6b5280-0947-11eb-8e9f-07be9d11c156.png)
