### ISSUE TITLE
Subversion Extension Disappears

### ISSUE THREAD

**Issue by amielalcala** [JohnstonCode/svn-scm#892]
- VSCode Version: 1.44.1
- OS Version: Windows 10* 64-bit
- Extension Version: v2.10.6
- System Language: English
- SVN Version: 1.10.6

## Issue ##
Whenever I open VS Code, the extension on the Activity Bar disappears.

## Steps to Reproduce ##

1. Install SVN Extension.
2. Open Visual Studio Code.

## SVN Output ##
```
N/A
```

## Screenshots ##
![image](https://user-images.githubusercontent.com/22849716/79406087-b2e8a800-7fc8-11ea-91b2-889aa7c5036f.png)

**Comment by JohnstonCode** [comment]
Do you have an open svn project?

**Comment by JohnstonCode** [comment]
if you need the extension to checkout a repo then it wont work. #839

**Comment by amielalcala** [comment]
Hi,

It's all good now. It seems that I need to checkout first a repo before the extensions appears.

Thanks.

**Comment by JohnstonCode** [comment]
Glad to hear it is working.
