### ISSUE TITLE
Changes mark shows on nonenglish comments. 

### ISSUE THREAD

**Issue by v4a26** [JohnstonCode/svn-scm#9]
In this codeblock was no changes, but comments marked like they have been changed. It appears all over the file only when russian comment posted. Using Windows1251 encoding.
![iddqd](https://user-images.githubusercontent.com/9762164/32228595-b74717ec-be5f-11e7-8ee1-710f4283495b.PNG)

**Comment by JohnstonCode** [comment]
Hi @v4a26 ,

I will have a look into this for you.

**Comment by JohnstonCode** [comment]
Hi @v4a26 

Looks like i dont do any checks on character encoding. Think i just assumed that everyone was going to be using utf8.

I will add encdoing checks when i roll out my own svn implimentation. Currently i rely on svn-spawn which limits the config i can currently do.

**Comment by v4a26** [comment]
Thx.

**Comment by magic-k** [comment]
I don't know if it falls into this issue. Despite seing the decoration for changes for every line that contains an Umlaut (german setting, using iso8859-15 as char set) which is related to this issue, i also see a change indicator in every file at the last line. It always shows that the last  empty line was added in the local copy.
None of the files were actually changed. Clean from the repository.

**Comment by JohnstonCode** [comment]
Yeah, i have noticed that today on 1.18. Looks like the editor is adding a new line.

**Comment by JohnstonCode** [comment]
This has been done and will be available as part of v1.0.0.

**Comment by JohnstonCode** [comment]
Hi @magic-k @v4a26 

Can you send me a sample of the comments you are having issues with so i can test them out please?

**Comment by v4a26** [comment]
Try this one. Codepage: windows 1251.
[Untitled-1.zip](https://github.com/JohnstonCode/svn-scm/files/1469754/Untitled-1.zip)

**Comment by JohnstonCode** [comment]
Thanks!

**Comment by JohnstonCode** [comment]
Should be working in v1.0.1

**Comment by v4a26** [comment]
@JohnstonCode For a while everything was fine, but right now I have a similar problem.

1.19.1 - VSCode Version:
Windows 7 - OS Version:
1.5.0 - Extension Version:
Russian; CP1251 - System Language:

The problem is similar to the topic. Gutter show that there are some changes in lines with Russian letters.

In my working repository, only a few characters cause problems. They marked bold in an example below.
![data](https://user-images.githubusercontent.com/9762164/34409603-d36e8b18-ebdb-11e7-8e23-6645d7111582.PNG)

абвгдеёжзийклмнопрстуфхцчшщъыьэю __я
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ__

Seems like used wrong offset in [Windows-1251](https://en.wikipedia.org/wiki/Windows-1251).

I tried to reproduce the problem but got the different result. All characters are corrupted.

![test](https://user-images.githubusercontent.com/9762164/34409420-caa676d6-ebda-11e7-8663-d137a466c562.PNG)

Here the test file.
[myTest.zip](https://github.com/JohnstonCode/svn-scm/files/1591106/myTest.zip)

I have no idea why results are different, but anyway something gone wrong.

**Comment by JohnstonCode** [comment]
@v4a26 encoding seems to be a reoccurring pain point.

I will have to think of another way to get it work check/work
