### ISSUE TITLE
svn folder settings

### ISSUE THREAD

**Issue by babujan** [JohnstonCode/svn-scm#90]
In the Output log of svn, I see that it is trying to automatically scan(svn ls) /branches, /tags, /trunk however the folder structure of the repo that I am working on does not follow that pattern, is there a way to configure the svn url for these? ie for the project I am currently working on the trunk folder is the project name, branches folder is call feature and tags folder is name Release.

**Comment by JohnstonCode** [comment]
Hi @babujan 

You can edit the setting in VS Code to set the svn.layout.branches, svn.layout.tags and svn.layout.trunk to what you need them to be. Just search for "svn" in the settings menu
