### ISSUE TITLE
"Do you really want to commit an empty message?"  YES!!! A thousand times yes, stop asking me!

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [JohnstonCode/svn-scm#913]
Please add a setting to turn this incessant nagging off.
I work alone and commit every few minutes all day.
When I want to add a message I will add one.

**Comment by JohnstonCode** [comment]
"Can you add an option to remove the empty commit prompt" would have sufficed

**Comment by WhatFreshHellIsThis** [comment]
Sorry, frustrating day.  Really appreciate this tool!
