### ISSUE TITLE
FR: please co-publish on Open VSX Registry

### ISSUE THREAD

**Issue by GitMensch** [JohnstonCode/svn-scm#914]
The [Open VSX Registry](https://open-vsx.org/?search=subversion) does not include anything for subversion yet. It would be helpful to co-publish the extension there, also for easier access in Theia and VSCodium.

Details on the publishing can be found at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by JohnstonCode** [comment]
Not sure if this is possible as the extension uses some of the vscode dependencies like iconv-lite and jschardet.

**Comment by edgardmessias** [comment]
As an alternative, can run the sequence:
```shell
# Add dependency
npm install --save iconv-lite jschardet

# Package again
npx vsce package -o svn-scm.vsix

# Publish
npx ovsx publish clipboard-manager.vsix -p $OVSX_TOKEN
```

**Comment by GitMensch** [comment]
@edgardmessias that looks nice - would it be bad if the dependencies are always bundled?

**Comment by edgardmessias** [comment]
Yes, because it realy big depencencies

**Comment by edgardmessias** [comment]
@GitMensch 
Current vsix size: 772KB, with dependencies: 1446:KB

**Comment by GitMensch** [comment]
OK, then maybe publish two extensions "svn-scm.vsix" and "svn-scm-bundled.vsix" (with the later either being bundled or having a dependency on a "meta" extension that includes the two dependencies)?

Note: The dependency is only an issue for theia, vscode based editors like VSCodium - which comes with the Open VSX Registry as its default "market" - would be fine with the "normal" extension, it just isn't published yet. So maybe a note that it only works on vscode based editors in the README and then publishing it as-is?

**Comment by GitMensch** [comment]
> Note: The dependency is only an issue for theia, vscode based editors like VSCodium - which comes with the Open VSX Registry as its default "market" - would be fine with the "normal" extension, it just isn't published yet. So maybe a note that it only works on vscode based editors in the README and then publishing it as-is?

Ping, I've recently installed vscodium and had to manually install this extension as it (and also the gutter extension) are not available in the open vsx registry yet. I still suggest to add a note about the compatibility/dependencies and publish as is for now.

**Comment by GitMensch** [comment]
@JohnstonCode as I'm just doing the setup for another vscodium installation and needed to do the manual vsix extension I kindly request to co-publish the extension as-is to the open vsx registry.
Support of this extension in Theia, which _may_ need a different vsix (if this is done I suggest to put these into another one and create a "svn theia bundle" that contains both), is a completely separate thing, the extension works as-is in vscodium, it just isn't found via the default extension provider, which uses open-vsx (because of the restrictive/unclear license of the vs-marketplace).

**Comment by JohnstonCode** [comment]
I think @edgardmessias approach will work. I need to add some keytar checks. If it is not available then don't try to use it. I also also need to update the readme with this information. Also think the generated bundle should be named `svn-scm-ovsx.vsix` to better differentiate it. I will get this all done this weekend

**Comment by NemanjaJovanovic98** [comment]
Try going to 'directory where is your vc code installed'/resources/app and doing npm install jschardet

**Comment by shanto** [comment]
Please take a minute to update the Open-VSX release to current version. 2.15.2 → 2.17.0
