### ISSUE TITLE
jump to next diff occurance

### ISSUE THREAD

**Issue by yoram-s** [JohnstonCode/svn-scm#92]
- VSCode Version: 
Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
- OS Version: Win10
- Extension Version: 1.4.6
- System Language: 

When opening a diff view, how can we jump to the next diff occurance when multiple ones exist in the file

**Comment by JohnstonCode** [comment]
There isn't a way to navigate through on the diff view that I am aware of. This is all handled by VS code.

You can navigate through diffs in the file directly by clicking on the diff colour in the gutter.
