### ISSUE TITLE
Commit selected should be default behaviour

### ISSUE THREAD

**Issue by IndrekHaav** [JohnstonCode/svn-scm#94]
Perhaps it's just me, but committing all changed files by default seems somewhat inadvisable. If any files are selected, the default behaviour should be to commit only those files.

**Comment by JohnstonCode** [comment]
Hi @IndrekHaav 

Thanks for raising an issue.

Unfortionalty the SCM input box has no way to track which changes are selected. As it originally was designed for GIT use.

There is a right click option to commit selected.
