### ISSUE TITLE
Can't execute any SVN commands (commands not found)

### ISSUE THREAD

**Issue by fdrijver** [JohnstonCode/svn-scm#943]
- VSCode Version: 1.45.1
- OS Version: macOS 10.15.4
- Extension Version: 2.11.1
- System Language: en_UK
- SVN Version: 1.13.0

## Issue ##

I can't execute any SVN commands. Anything I try gives me the error "command 'svn.update/commit/add/etc' not found.

## Steps to Reproduce ##

1. Install VSCode
2. Install the extension
3. Installed svn 1.13.0 from Homebrew
4. Restart VSCode (just in case)
5. Did a manual checkout of a SVN folder
6. Drag that folder in VSCode
7. Change a file, save
8. File is ready at the Source Control pane
9. Enter commit message, press commit
10. Error: "command 'svn.commitWithMessage' not found"

## SVN Output ##
```
This is empty
```

**Comment by JohnstonCode** [comment]
Is there anything in the console?
Help >> Toggle Developer Tools >> Console

**Comment by fdrijver** [comment]
After running through the steps above, it specifically says:

> Error: command 'svn.commitWithMessage' not found
>     at e._tryExecuteCommand (commandService.ts:80)
>     at commandService.ts:73
>     at async s.run (actions.ts:190)

A little bit up in the log however, I see more of these types of errors though:

![Screenshot 2020-05-22 at 14 15 35](https://user-images.githubusercontent.com/242073/82666736-c970c780-9c36-11ea-83d5-aed6bc8fa273.png)

**Comment by JohnstonCode** [comment]
Unable to reproduce

**Comment by fdrijver** [comment]
Created a new Workspace and everything works like a charm.
So weird, thanks though!
