### ISSUE TITLE
Feature request multiple change lists

### ISSUE THREAD

**Issue by shaman-apprentice** [JohnstonCode/svn-scm#95]
Support for multiple change lists would be nice.

Concrete I have the following "issue". Sometimes I change some config files like server-address or so for developing / debugging. For preventing me of accidentally committing these file, I have a change list "dont commit", where I put those changes in, which I like a lot...

**Comment by JohnstonCode** [comment]
Hi @shaman-apprentice 

This is a good suggestion. However, this will require quite a bit of work to implement.

This is something I can look at after I have cleaned up the other issues or another contributor can look at.

**Comment by edgardmessias** [comment]
See http://svnbook.red-bean.com/nightly/en/svn.advanced.changelists.html

**Comment by edgardmessias** [comment]
@JohnstonCode, using changelists, we can implement the "stage change like git"

**Comment by JohnstonCode** [comment]
Yeah thats what tortuise SVN does

**Comment by edgardmessias** [comment]
@JohnstonCode, we have two options:
* Create some changelists (stage, ignore-on-commit, etc..) and commit only "stage"
* Add ability to user create new changelist (or choose a existent) and on commit choose the changelist

Maybe can close the #99

**Comment by JohnstonCode** [comment]
@edgardmessias 

Yeah it will close #99 

I think the second option will be the best as it adds more flexibility. We could check for changelists when the extension loads and just add them with the current two. A commit changelist command could also be added. This is so the current commit input box will always commit the changes resource group
