### ISSUE TITLE
stage/unstage partial changes

### ISSUE THREAD

**Issue by Spongman** [JohnstonCode/svn-scm#960]
in vscode git you can right-click a selection in a diff view and stage/unstage those particular changes. this is invaluable when you want to commit only a subset of changes to a file:

![image](https://user-images.githubusercontent.com/1088194/83916324-d955d480-a729-11ea-83f7-b52044203fe4.png)

it would be great if you could add this to SVN. currently my workflow is this:

for each file:
- make a backup of the file
- diff the file
- manually revert changes i don't want to commit in the file
- commit
- revert file backup

with many changes in many files this becomes extremely tedious. the requested feature would make this trivial.

**Comment by JohnstonCode** [comment]
How would that work with Svn? Svn doesn't have a Stage changes state like Git.

**Comment by Spongman** [comment]
yeah, i guess that would be rather difficult. oh well...
