### ISSUE TITLE
External folders shown as unversioned

### ISSUE THREAD

**Issue by flavior121** [JohnstonCode/svn-scm#97]
- VSCode Version: 1.19
- OS Version: Windows 10
- Extension Version: 1.5.0
- System Language: PT

My working copy is made out of different subdirectories using Externals. The problem is that all external folders are shown as unversioned.

**Comment by JohnstonCode** [comment]
Hi @flavior121,

Thanks for raising this. Externals are something that I didn't think about when creating the extension. I will have a look and fix this for you soon.

**Comment by flavior121** [comment]
@JohnstonCode Thanks
This is off-topic but can you add an option to ignore a list of files too?

**Comment by JohnstonCode** [comment]
@flavior121 

You mean something separate from svn itself? Like a .gitignore file?

**Comment by flavior121** [comment]
@JohnstonCode 
I mean something like TortoiseSVN "ignore-on-commit" feature.

**Comment by JohnstonCode** [comment]
Thanks for that. TortoiseSVN uses a changelist for the functionality. Changelist is a feature request but I have not had time to look into.

Once it is implemented I will look into adding that feature.

I will open a new issue to keep track of this. #99

**Comment by JohnstonCode** [comment]
@flavior121 

Can you show the output of svn stat in the root of your project? Please replace any private information with 0's

**Comment by edgardmessias** [comment]
@flavior121 @JohnstonCode 
What do you prefer:
* Hide from the list everything that is external
* View in a separate list (Like "Externals")

**Comment by JohnstonCode** [comment]
My suggestion would be to hide

**Comment by edgardmessias** [comment]
I'll create an option and leave the default hidden

**Comment by edgardmessias** [comment]
Fixed with #114
