### ISSUE TITLE
Right click incoming change, update -> closes working copy 

### ISSUE THREAD

**Issue by carlittoer** [JohnstonCode/svn-scm#972]
- VSCode Version: 1.46.1
- OS Version: Mac OS Catalina 10.15.5
- Extension Version: 2.11.3
- System Language:
- SVN Version:

## Steps to Reproduce ##

1. Go to SVN view
2. Right click incoming change
3. Press update
4. SVN view closes

**Comment by JohnstonCode** [comment]
Unable to reproduce.
