### ISSUE TITLE
Missing dependency, go to   and run: npm install iconv-lite

### ISSUE THREAD

**Issue by nrbray** [JohnstonCode/svn-scm#973]
- VSCode Version: 1.47.0-insider 8cd3fe080bee38d28ba01d0d71713d6ec22b254e x64
- OS Version: Version 10.0.18363 Build 18363
- Extension Version:v2.11.3
- System Language:English
- SVN Version:svn, version 1.13.0 (r1867053)

## Issue ##
Missing dependency, go to   and run: npm install iconv-lite

## Steps to Reproduce ##

1. Vscode insiders auto update today 19-Jun-20  
2. Previous 'working' svn repos no longer connect and error as above

## SVN Output ##
content of "View >> Output >> OUTPUT >> SVN"
```
-none-
```

**Comment by JohnstonCode** [comment]
Unable to reproduce in:
```
Version: 1.47.0-insider
Commit: b9d7ec9ff367a8e59fe4cc2abee605a55be180e8
Date: 2020-06-19T22:34:47.305Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-7634-generic
```

**Comment by solomchuk** [comment]
Had the same issue for the last week or so. Today's Insiders update did not fix it.

Version: 1.47.0-insider (user setup)
Commit: 269f0fdd83f1e6611dd0c6d225a1685719eafedb
Date: 2020-06-22T05:53:42.894Z (2 hrs ago)
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.17763

SVN version: 1.14.0 (r1876290)

If it's any help, the output from DevTools panel is below:
`notificationsAlerts.ts:40 Missing dependency, go to "C:\Users\solomcukm\AppData\Local\Programs\Microsoft VS Code Insiders" and run: npm install iconv-lite
onDidChangeNotification @ notificationsAlerts.ts:40
log.ts:191  WARN UNRESPONSIVE extension host, 'johnstoncode.svn-scm' took 96% of 982.457ms, saved PROFILE here: 'C:\Users\SOLOMC~1\AppData\Local\Temp\exthost-6c71a1.cpuprofile' Array(3)
console.ts:137 [Extension Host] TypeError: Cannot read property 'encodingExists' of undefined	at Svn.exec (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\svn.js:136:36)	at processTicksAndRejections (internal/process/task_queues.js:93:5)	at async Svn.getRepositoryRoot (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\svn.js:167:28)	at async SourceControlManager.tryOpenRepository (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\source_control_manager.js:159:40)	at async SourceControlManager.scanWorkspaceFolders (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\source_control_manager.js:143:13)	at async SourceControlManager.enable (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\source_control_manager.js:91:9)	at async c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\source_control_manager.js:50:17	at async init (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\extension.js:29:34)	at async tryInit (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\extension.js:48:13)	at async _activate (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\extension.js:95:5)	at async activate (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\extension.js:100:5)	at async Promise.all (index 8)	at async Promise.all (index 0) (at Svn.getRepositoryRoot (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\svn.js:179:21))
t.log @ console.ts:137
console.ts:137 [Extension Host] Error: Unable to find repository root path	at Svn.getRepositoryRoot (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\svn.js:180:19)	at processTicksAndRejections (internal/process/task_queues.js:93:5) (at SourceControlManager.tryOpenRepository (c:\Users\solomcukm\.vscode-insiders\extensions\johnstoncode.svn-scm-2.11.3\out\source_control_manager.js:170:25))`

**Comment by JohnstonCode** [comment]
You are correct, i am stupid. Will fix.

**Comment by JohnstonCode** [comment]
Can you try manually installing this version of the SVN vsix please. https://github.com/JohnstonCode/svn-scm/suites/825350369/artifacts/9152841

**Comment by znck** [comment]
@JohnstonCode the issue seems to be fixed in the above mentioned VSIX file.

**Comment by solomchuk** [comment]
Indeed, the fix in vsix did the trick. Thanks!

**Comment by nrbray** [comment]
Much appreciated, am sure many many others do too.

**Comment by klren0312** [comment]
**recurrent**
![1642477041(1)](https://user-images.githubusercontent.com/10903843/149866763-4c63ca1f-8772-4494-8e32-d300e3e776a7.png)


```
Version: 1.64.0-insider (user setup)
Commit: 6612ae0f8b5d9c0d86518ebbd153c724a7cbcf73
Date: 2022-01-17T05:16:09.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```
