### ISSUE TITLE
(command 'svn.checkout' not found)

### ISSUE THREAD

**Issue by wscardua** [JohnstonCode/svn-scm#989]
- VSCode Version: 1.46.1
- OS Version: win'10
- Extension Version: v2.11.4
- System Language: Portugues
- SVN Version: 

## Issue ##

When I try to configure SVN, I received that menssage

'Command 'SVN: Checkout' resulted in an error (command 'svn.checkout' not found)'

{
    "editor.fontSize": 19,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "svn.default.encoding": "",
    "svn.path": "V:\\bin",
    "svn.defaultCheckoutDirectory": "G:\\svn_checkout"
}

![svn](https://user-images.githubusercontent.com/47982596/86139813-8c65e380-bac6-11ea-92a1-43aa2204ceb1.PNG)

**Comment by edgardmessias** [comment]
Wrong "svn.path", change to `"svn.path": "V:\bin\svn.exe"`

**Comment by wscardua** [comment]
> Wrong "svn.path", change to `"svn.path": "V:\\bin\\svn.exe"`

look @edgardmessias,
I changed, but the error remains

'V:' it's a shortcut to the server '\\\10.x.x.x\VisualSVNServer'

![svn1](https://user-images.githubusercontent.com/47982596/86144866-9b4f9480-bacc-11ea-882f-753b8ca8cc1a.PNG)

**Comment by edgardmessias** [comment]
Where is the svn binary?
