### ISSUE TITLE
Design the comparison code in vscode. UTF-8 is used by default on the left and any encoding can be set on the right?

### ISSUE THREAD

**Issue by linnjoy** [JohnstonCode/svn-scm#993]
**Is your feature request related to a problem? Please describe.**
YES, when I use code comparison, my local text encoding is GB2312, but the encoding used in the left window of the comparison is inconsistent with the right, resulting in garbled characters.
![image](https://user-images.githubusercontent.com/39291627/86443286-a2330d00-bd41-11ea-989b-afd4badff4d8.png)

**Describe the solution you'd like**&&**Describe alternatives you've considered**
1. Add options to open the left window with what code to open
2. The left and right windows are opened with the same encoding

> THANKS

**Comment by JohnstonCode** [comment]
If you could send me that snippet, that would be helpful.

**Comment by linnjoy** [comment]
Sorry, I can't share files.
However, you can use any repo to test this problem. 
1.Use vscode to create a text coded as GB2312
2.Then input Chinese characters, submit and enter the comparison to reproduce
